### ISSUE TITLE
Returns last metric value (check-keys) if key is deleted from redis

### ISSUE THREAD

**Issue by sashgorokhov** [oliver006/redis_exporter#100]
I have started redis exporter with option to watch several keys (check-keys option). These keys are present  and deleted from time to time. I have found that redis exporter continue to return last registered metric value, if that key is not found in redis. 

For example, curling on /metrics endpoint 
`curl 127.0.0.1:9121/metrics | grep redis_key`
```
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.TargetsProcessingHash"} 1
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.UrlsList"} 5
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.UrlsProcessingHash"} 11
```
And watching these keys in redis:
```
127.0.0.1:6379> KEYS pikaspy.redis_utils.proxies.*
1) "pikaspy.redis_utils.proxies.TargetsProcessingHash"
```
The keys `pikaspy.redis_utils.proxies.UrlsList` and `pikaspy.redis_utils.proxies.UrlsProcessingHash` are absent but still returned by redis exporter.

P.S. Congrats on 100th issue!

UPD: Restarting exporter cleares its memory and it reports actual keys and data. until they deleted, of course.

**Comment by oliver006** [comment]
Hmm, interesting issue. 

There might be a way to clear all "check-keys" metrics before each scrape attempt to clear out stale ones, let me look into that.

**Comment by oliver006** [comment]
Note to self: 

Calling `e.keyValues.Reset()` might fix this: https://godoc.org/github.com/prometheus/client_golang/prometheus#GaugeVec.Reset
