### ISSUE TITLE
Add an option to resolve redis host to multiple IPs before scraping Redis instances

### ISSUE THREAD

**Issue by zuzzas** [oliver006/redis_exporter#114]
Hi,

would it be possible to implement a flag that causes redis_exporter to resolve hosts, that were passed to the `-redis.addr` flag, dynamically, and to expand the list of addresses to scrape from?

That way, we can just pass a Kuberentes Service name to the `-redis.addr` flag, and redis_exporter will take care of the rest.

You see, most Redis Kubernetes installations are available through an abstraction called the [Endpoint](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#endpoints-v1-core), which are created by the [Service](https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/#service-v1-core). It works transparently to a container in which you run redis_exporter instance. Basically, you resolve a host and it resolves to one or more DNS A records.

Perhaps, this logic could be implemented as a goroutine, that re-resolves the host repeatedly with an interval?

If this proposal can be implemented, it can remove a lot of headcache that comes with dynamic nature of Kubernetes.

**Comment by zuzzas** [comment]
The proposal is wrong. It's wrong to group different Redis instances behind a single Kubernetes Service.

Everything that I need is already [here](https://github.com/oliver006/redis_exporter/pull/111).

**Comment by oliver006** [comment]
👍
