### ISSUE TITLE
Dashboard "Memory Usage" and "Total Memory Usage" are broken

### ISSUE THREAD

**Issue by StephaneBunel** [oliver006/redis_exporter#117]
The metric key "redis_config_maxmemory" seems dropped from reported metrics ?

**Comment by oliver006** [comment]
see issue #3 and #82
The metrics is exported as `redis_memory_max_bytes` when available but I'm working on a PR to bring back the config metric(s) as well.

**Comment by oliver006** [comment]
This should be fixed by https://github.com/oliver006/redis_exporter/releases/tag/v0.14

The `redis_config_maxmemory` metric should be back.

**Comment by StephaneBunel** [comment]
Great! It works for me now. Prometheus rules & Grafana dashboards are happy :-)

Thank you!

**Comment by oliver006** [comment]
👍

**Comment by tinder-ubhatnagar** [comment]
Thanks guys for fixing this! Amazing!
