### ISSUE TITLE
Make RedisHost.Aliases Optional while Creating exporter.NewRedisExporter

### ISSUE THREAD

**Issue by the-redback** [oliver006/redis_exporter#120]
Hi,
Would it be possible to make `RedisHost.Aliases` Optional while creating `NewRedisExporter`?

In Existing code, while creating a new  Redis Exporter following this procedure, it requires atleast a 'blank array of string' argument as RedisHost.Aliases.
```go
rr := RedisHost{Addrs: []string{"unix:///tmp/doesnt.exist"}, Aliases: []string{""}}
e, _ := NewRedisExporter(rr, "test", "")
```
This Example of argumet can be referred here: https://github.com/oliver006/redis_exporter/blob/master/exporter/redis_test.go#L602

But if we send no aliases, it **panics**.
In my sense, there is no point of sending a blank array as an argument.
It would be great if the code handles itself a nill/no Aliases.

**Comment by the-redback** [comment]
cc: @tamalsaha

**Comment by oliver006** [comment]
I'd be fine with making that change. 
Could probably check near here: https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L189 if Aliases is set and if not, init it to `[]string{""}`

**Comment by lukmdo** [comment]
I believe this can be closed as outdated as now 

```go
       addrs, passwords, aliases = exporter.LoadRedisArgs("IP:PORT", *redisPassword, *redisAlias, *separator)
	exp, err := exporter.NewRedisExporter(
		exporter.RedisHost{Addrs: addrs, Passwords: passwords, Aliases: aliases},
		*namespace,
		*checkSingleKeys,
		*checkKeys,
	)
```

**Comment by oliver006** [comment]
Thanks, closing.
