### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by SuperQ** [oliver006/redis_exporter#122]
When making releases, it would be nice if they consistently used [Semantic Versioning](https://semver.org/).

**Comment by oliver006** [comment]
Thanks, that's a good suggestion!

While I'm generally familiar with the concept of semantic versioning, I could use help with the specifics when it comes to redis_exporter.
The `max_memory` stuff comes to mind but do you have other pointers where in the past that could have been handled better?

**Comment by SuperQ** [comment]
This is mostly about when making releases, change `v.0.14` to `v0.14.0` so that we have a consistent version string to match against.

**Comment by oliver006** [comment]
👍

**Comment by oliver006** [comment]
Cut release https://github.com/oliver006/redis_exporter/releases/tag/v0.15.0 and will keep version strings consistent in the future.
