### ISSUE TITLE
CONFIG command

### ISSUE THREAD

**Issue by ccs018** [oliver006/redis_exporter#124]
In the latest version (0.14), redis exporter appears to be issuing CONFIG commands to Redis.  In my environment, I have renamed the CONFIG command to '' to prevent clients from changing the configuration.

It appears that every 15 seconds, redis exporter is trying to modify the configuration.  This appears to be done in redis_test.go where it is trying to configure the latency-monitor-threshold.  The Redis server is logging the following error every 15 seconds:

Dec 06 20:07:35 worker1-3-1 docker[19346]: time="2017-12-06T20:07:35Z" level=error msg="redis err: ERR unknown command 'CONFIG'"

How important is it that the redis exporter configure the latency-monitor-threshold?  Can it give up after N attempts rather than retry forever?  I'd rather not open up the CONFIG command for security / stability reasons.

**Comment by oliver006** [comment]
The `CONFIG` command is actually called here: 
https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L582 
to retrieve the current config setting for the `max_memory` metric.

I can remove the logging in the else statement, or at least reduce the log level to `debug` so it won't show up in a production environment.

**Comment by ccs018** [comment]
Don't know why I didn't see that in redis.go.  Thought it was odd that an apparent test was being run.

I thought maxmemory was available with the INFO command:

127.0.0.1:6381> info memory
# Memory
used_memory:1877976
used_memory_human:1.79M
used_memory_rss:11665408
used_memory_rss_human:11.12M
used_memory_peak:1992624
used_memory_peak_human:1.90M
used_memory_peak_perc:94.25%
used_memory_overhead:1569384
used_memory_startup:288968
used_memory_dataset:308592
used_memory_dataset_perc:19.42%
total_system_memory:16830894080
total_system_memory_human:15.67G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:14000000000
maxmemory_human:13.04G
maxmemory_policy:noeviction
mem_fragmentation_ratio:6.21
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

**Comment by oliver006** [comment]
Unfortunately, it wasn't always available via `INFO` but only added around Redis version 3.0.6 or so.

I'll see that I can get this fixed in the next couple of hours.

**Comment by ccs018** [comment]
Sounds great!  Perhaps to maintain backward compatibility, if you know if is Redis v3.0.5 or earlier than use CONFIG.  Or always try INFO and fall back to CONFIG if that fails.  And move the log level to debug.

**Comment by oliver006** [comment]
I changed the log level to Debug for now, that should address your issue.

**Comment by daquinoaldo** [comment]
Hi @oliver006, I have a similar problem with the `LATENCY` metric.
```
level=error msg="cmd LATENCY LATEST, err: ERR unknown command 'LATENCY'"
```
Is that a false error, as for `CONFIG`, or is it a real error I should care for? 😅

**Comment by oliver006** [comment]
Not all versions of Redis and all Redis-like platforms support `LATENCY` - did you try connecting to your Redis instance and running `LATENCY LATEST` ?

**Comment by daquinoaldo** [comment]
Yes, the LATENCY command is not available on the Redis instance.

**Comment by oliver006** [comment]
Ok, that would explain the error. It's not a fatal issue, you just won't get the latency metrics.

**Comment by daquinoaldo** [comment]
Perfect, it is what I supposed. Any way to suppress the log?
