### ISSUE TITLE
how to set aliases

### ISSUE THREAD

**Issue by omilun** [oliver006/redis_exporter#128]
i want to have aliases to my hosts that they lists of them are in a file and i set it for REDIS_FILE .
this is information of my container log.
INFO[0000] Connecting to redis hosts: []string{"redis://172.20.4.75:7101", "redis://172.20.4.75:7102"}
INFO[0000] Using alias: []string{"", ""}

**Comment by oliver006** [comment]
What dos your REDIS_FILE and command line look like?

**Comment by omilun** [comment]
this is my file text:

redis://172.20.4.66:7000
redis://172.20.4.66:7001
redis://172.20.4.66:7002
redis://172.20.4.66:7003
redis://172.20.4.66:7004
redis://172.20.4.66:7008

**Comment by oliver006** [comment]
The alias would need to be passed in the file itself, see this part of the code here where the file is parsed: https://github.com/oliver006/redis_exporter/pull/75/files#diff-7ddfb3e035b42cd70649cc33393fe32cR149

So in your case, the file would need to look something like this:

```
redis://172.20.4.66:7000,,alias1
redis://172.20.4.66:7001,,alias2

```
