### ISSUE TITLE
Memory Usage is N/A

### ISSUE THREAD

**Issue by fvn4edal** [oliver006/redis_exporter#129]
I‘m new to config prometheus and use redis_exporter. When i config prometheus and redis_exporter,i found the graph of memory usage is N/A. Other graphs and tables are avaliable. Could you help me?

**Comment by oliver006** [comment]
What's the output of the `/metrics` endpoint of the exporter? 
And is Prometheus correctly scraping the exporter?

**Comment by slhu91** [comment]
When you execute “CONFIG GET MAXMEMORY” in redis-cli，the result is not zero（0）？

**Comment by yongsr** [comment]
is your issue solved? I am having the same issue.

**Comment by shqear93** [comment]
Does this fixed or maybe it needs some kind of configurations??
I use docker redis exporter and still having this issue

**Comment by oliver006** [comment]
The max memory metric is normally N/A if no max memory limit is set for your Redis instance.

Run `CONFIG GET MAXMEMORY` to find out what your limit is.
