### ISSUE TITLE
Collect metrics for config options

### ISSUE THREAD

**Issue by oliver006** [oliver006/redis_exporter#13]
Collecting metrics for config options like `max_memory` could be useful and should be easy to implement by parsing the output of `CONFIG GET *`.

**Comment by jkemp101** [comment]
`CONFIG` isn't available in AWS ElasticCache Redis.  A flag would useful to disable this check.  Right now it errors and then doesn't do the check-keys because of the `continue`.

**Comment by oliver006** [comment]
Ah, interesting.
Let me fix that so it continues even if it can't get the `CONFIG` output.

**Comment by jkemp101** [comment]
Thanks for the fix, just deployed latest version and it works great.  Passing 1025 queues on the command line for `-check-keys` is also surprisingly working.

**Comment by oliver006** [comment]
Wow, over 1k for check-keys is a lot, would regex or wildcard matching help in your case?

**Comment by jkemp101** [comment]
A wildcard would definitely be cleaner but the command line list is working for now. I don't expect the list to expand for now.

**Comment by oliver006** [comment]
👍

**Comment by mrwacky42** [comment]
For the record, in AWS ElastiCache Redis, a `maxmemory` value is returned in the results of the `INFO memory` command. Perhaps it would be nice to add an option to look there instead?

**Comment by cbarratt** [comment]
^ The above would be great, I'm using Redis on Heroku and the CONFIG option is also disabled there! Retrieving the data from INFO would be a good option to have.

**Comment by oliver006** [comment]
@cbarratt - this should be fixed via #64 and released as https://github.com/oliver006/redis_exporter/releases/tag/v0.11

**Comment by plynte** [comment]
maxmemory --> "redis_memory_max_bytes" after v0.11
