### ISSUE TITLE
redis_net_input_bytes_total is not found in prometheus

### ISSUE THREAD

**Issue by slhu91** [oliver006/redis_exporter#130]
![image](https://user-images.githubusercontent.com/14175152/34975868-d23c2c8a-face-11e7-956c-cf62fe775ec2.png)

**Comment by oliver006** [comment]
What version of Redis are are you running?

**Comment by slhu91** [comment]
redis version 2.8.15

**Comment by oliver006** [comment]
What version of the exporter do you run and what's the output of `INFO` when connecting to Redis with redis-cli ? 
Do you see `total_net_input_bytes` ?

**Comment by slhu91** [comment]
The is no total_net_input_bytes for output of INFO
