### ISSUE TITLE
name of redis host inside grafana

### ISSUE THREAD

**Issue by roberteventival** [oliver006/redis_exporter#131]
Is there wa to influence the name of the monitored host in the grafana view? for example "Production/Staging". I've tried to run with `~/go/bin/redis_exporter -redis.password somepass -redis.addr 127.0.0.1:6379 -redis.alias production` but in grafana I still see `127.0.01:6379`.

**Comment by oliver006** [comment]
The preferred way to get a "proper" name would be to rename your labels, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/ for more information.

But if you already use the `-redis.alias` parameter and don't want to deal with relabeling then you'd need to change the dashboard to use the alias label in all the graphs.
