### ISSUE TITLE
I can't  install 

### ISSUE THREAD

**Issue by long904** [oliver006/redis_exporter#132]
in go1.4
main.go:11:2: cannot find package "github.com/cloudfoundry-community/go-cfenv" in any of:
        /usr/local/go/src/github.com/cloudfoundry-community/go-cfenv (from $GOROOT)
        /usr/local/go/src/src/github.com/cloudfoundry-community/go-cfenv (from $GOPATH)
exporter/redis.go:12:2: cannot find package "github.com/garyburd/redigo/redis" in any of:
        /usr/local/go/src/github.com/garyburd/redigo/redis (from $GOROOT)
        /usr/local/go/src/src/github.com/garyburd/redigo/redis (from $GOPATH)
exporter/redis.go:13:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /usr/local/go/src/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
main.go:14:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
        /usr/local/go/src/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
exporter/redis.go:14:2: cannot find package "github.com/prometheus/prometheus/util/strutil" in any of:
        /usr/local/go/src/github.com/prometheus/prometheus/util/strutil (from $GOROOT)
        /usr/local/go/src/src/github.com/prometheus/prometheus/util/strutil (from $GOPATH)
exporter/redis.go:15:2: cannot find package "github.com/sirupsen/logrus" in any of:
        /usr/local/go/src/github.com/sirupsen/logrus (from $GOROOT)
        /usr/local/go/src/src/github.com/sirupsen/logrus (from $GOPATH)

and  go1.9
package github.com/oliver006/redis_exporter
        imports runtime: C source files not allowed when not using cgo or SWIG: atomic_amd64x.c defs.c float.c heapdump.c lfstack.c malloc.c mcache.c mcentral.c mem_linux.c mfixalloc.c mgc0.c mheap.c msize.c os_linux.c panic.c parfor.c proc.c runtime.c signal.c signal_amd64x.c signal_unix.c stack.c string.c sys_x86.c vdso_linux_amd64.c

**Comment by oliver006** [comment]
What command(s) did you run?

**Comment by long904** [comment]
export GOROOT=/usr/local/go
export GOBIN=$GOROOT/bin
export GOPATH=$GOROOT/src
export GOROOT_BOOTSTRAP=$GOROOT
export PATH=$PATH:$GOBIN

/usr/local/go/src;mkdir -p github.com/oliver006/
git clone https://github.com/oliver006/redis_exporter.git
cd redis_exporter/
go build

**Comment by oliver006** [comment]
For Go 1.4 it seems like it's not finding the packages inside the vendor folder. I'm not sure to what extend Go 1.4 supports the vendor folder but you could try running ifnoring the vendor folder. Delete it, then run `go get` before `go build` and see if that works.

As for the error you get when you build with Go 1.9, not sure what's going on.
A quick google search yielded this issue here: https://github.com/prometheus/node_exporter/issues/182
So you could try what's suggested in there (set `CGO_ENABLED=1` and/or try deleting old Golang installations).

**Comment by long904** [comment]
thanks.reinstall go it's ok

**Comment by oliver006** [comment]
👍
