### ISSUE TITLE
Metrics "command_call_duration_*" should be counter

### ISSUE THREAD

**Issue by njam** [oliver006/redis_exporter#135]
The metrics `redis_command_call_duration_seconds_count` and `redis_command_call_duration_seconds_sum` should be of type *counter* instead of *gauge* I belive.
Their value seems to reflect the full count/duration since redis was started.

**Comment by njam** [comment]
Same for `redis_commands_processed_total`

**Comment by oliver006** [comment]
Yes and no.
You're right, thee should be counters but they reflect the value coming directly from redis so they're gauges as we set them directly to whatever comes from `INFO`.

**Comment by njam** [comment]
The ["INFO" documentation](https://redis.io/commands/info) doesn't say anything about gauge/counter, so I think it's up to the exporter to make that decision.

I see what you mean, but I don't see any upside of defining these metrics as *gauge*. Having them as *counter* would be much more useful when plotting and alerting etc.

Prometheus documentation:
> A *counter* is a cumulative metric that represents a single numerical value that only ever goes up. A counter is typically used to count requests served, tasks completed, errors occurred, etc. Counters should not be used to expose current counts of items whose number can also go down, e.g. the number of currently running goroutines. Use gauges for this use case.
https://prometheus.io/docs/concepts/metric_types/#counter

Up to you, it's your program :)

**Comment by oliver006** [comment]
`redis_exporter` can't use a counter as we're not counting, it simply mirrors what the redis instance is counting and to do that we need a Gauge as it allows *setting* a value, not just _counting_.

You can use the resulting metrics in Grafana just like a counter and display rates, etc - the only time it'll cause an issue is when your redis instance restarts and resets the (redis instance) counter .

**Comment by filippog** [comment]
FWIW as a redis_exporter user I find the current behaviour to be what I'm expecting: namely to be getting the same information that redis provides as @oliver006 mentioned.

**Comment by njam** [comment]
You're right, it's not even supported by the Golang library, so probably not a good idea.

Thanks anyway!
