### ISSUE TITLE
Not getting any metrics

### ISSUE THREAD

**Issue by gillesbroes2016** [oliver006/redis_exporter#136]
Hi,

I'm using your plugin:

![image](https://user-images.githubusercontent.com/22746754/36420280-c9836be0-1634-11e8-9929-8260fe98401b.png)

The exporter is online and found by prometheus.

However I only have these metrics: 

![image](https://user-images.githubusercontent.com/22746754/36420322-ee4d9540-1634-11e8-8efb-b7a9e5b45237.png)

The exporter logs are:

![image](https://user-images.githubusercontent.com/22746754/36420486-8c2a8b42-1635-11e8-84af-85ac50ac92b6.png)

Any idea on what I did wrong?

I'm using promswarm and Docker Swarm.

Thanks for any help you could offer.

**Comment by oliver006** [comment]
Looks like the exporter is running but fails to connect to the redis instance?
Without the configs it's hard to say what's going on exactly but you can check if the connection string is correct and that redis is running at the address the exporter is trying to scrape.
