### ISSUE TITLE
[Feature request] Make redis_db_keys metric available by default with "0" value 

### ISSUE THREAD

**Issue by Blasterdick** [oliver006/redis_exporter#138]
I have a kubernetes GKE v1.9.2 cluster with HPA scaling by the custom metrics via [Kubernetes Custom Metrics Adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter). 

HPA with target Pod metric as `redis_db_keys` won't be initialized on creation if any pod would have no `redis_db_keys` metric attached. You'll get an error like: 

`failed to get pods metric value: unable to get metric redis_db_keys: unable to fetch metrics from API: the server could not find the metric redis_db_keys for pods`

So it would be awesome to have that metric be present by default with 0 value till it wouldn't be replaced by a real value. Hope, it can be done and won't break some internal logic.

**Comment by brancz** [comment]
I think the crooks of the issue is here:

https://github.com/oliver006/redis_exporter/blob/fa5545286a5b4cc1849965e3193d4579aa0151f5/exporter/redis.go#L490-L492

Basically I think what's going wrong is that `ok` is false when the result is `0`, which is why the metric is not generated at all, but it should. Zeroing metrics is a best practice.

**Comment by oliver006** [comment]
I think the reason `ok` is false in line 490 is not that the result is zero, the line with metrics is absent from the `CONFIG` call. Redis allows configuring the number of DBs available and doesn't show metrics for DBs that are empty.

`Zeroing metrics is a best practice.` - it depends, yes and no.
 
Not recording metrics for DBs that don't have keys and no metrics in Redis CONFIG seems OK to me.

But if this behavior is really desired then it can be done by first getting the max number of DBs (should be available via `CONFIG` ?), then collect metrics for each DB as provided by Redis and, last but not least, fill in all the blanks with zeros.
I currently don't have time to change that but happy to review and merge a PR.

**Comment by brancz** [comment]
> Not recording metrics for DBs that don't have keys and no metrics in Redis CONFIG seems OK to me.

For all possible known time-series this is indeed best practice: https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics

I don't have time either, but I'm happy to advice someone who wants to take a stab at it.

**Comment by oliver006** [comment]
Thanks to @s-saveljev this has been taken care of via #142
