### ISSUE TITLE
Question: is it possible to monitor redis via a unix domain socket ?

### ISSUE THREAD

**Issue by zerthimon** [oliver006/redis_exporter#14]
subj

**Comment by oliver006** [comment]
I haven't tried it but right now I don't think so:

https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L292

--> `redis.Dial("tcp", addr)`

However, this should be possible with a bit of refactoring.

**Comment by oliver006** [comment]
For future reference: https://github.com/garyburd/redigo/issues/133
