### ISSUE TITLE
Allow command renaming

### ISSUE THREAD

**Issue by dgrothaus-ku** [oliver006/redis_exporter#146]
It would be nice if the exporter supported renamed dangerous commands.

Some cloud Redis installations (AWS) or password protected instances use renamed CONFIG, FLUSHDB and FLUSHALL commands.

A flag to provide the name of renamed commands would make otherwise unavailable config values available.

**Comment by oliver006** [comment]
Agreed, that'd be useful to have (and this has come up before as a request).
I personally don't have a need for renaming commands but would be happy to review and merge a PR.

**Comment by oliver006** [comment]
You can now rename the `CONFIG` command using the `--config-command` flag, closing this.
