### ISSUE TITLE
Question: is it possible to monitor multiple redis instances running on the same server ? 

### ISSUE THREAD

**Issue by zerthimon** [oliver006/redis_exporter#15]
subj

**Comment by oliver006** [comment]
Yes, as long as the redis instances are available via TCP (see #14)

The command line config would look something like this:

`redis_exporter -redis.addr=localhost:6379,localhost:6380`

**Comment by zerthimon** [comment]
Ah, nice!
Thanks.

**Comment by oliver006** [comment]
np!

**Comment by castocolina** [comment]
> Yes, as long as the redis instances are available via TCP (see #14)
> 
> The command line config would look something like this:
> 
> `redis_exporter -redis.addr=localhost:6379,localhost:6380`

Using latest version (v1.0.3). When try this the metric show `redis_up 0`

**Comment by oliver006** [comment]
@castocolina 
Have a look here: [how to configure the exporter when scraping multiple instances.](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)
