### ISSUE TITLE
Is this project needs a example?

### ISSUE THREAD

**Issue by fengzixu** [oliver006/redis_exporter#153]
The redis_exporter is used to monitor redis-server with prometheus. If a user want to add the feature of visualization, grafana is the critical. But i detect that no example of using grafana, prometheus and redis_exporter, so can i add this example for redis_exporter? what do you think? @oliver006

**Comment by ccs018** [comment]
You mean like the example shown at
https://github.com/oliver006/redis_exporter#what-does-it-look-like?

**Comment by fengzixu** [comment]
Yep. This project only reply a screenshot about grafana. However if a freshman who can't utilize the grafana and prometheus and he want to start quickly a redis_exporter demo, the tutorial of redis_exporter in readme is not enough to freshmen.
So, i want to add a example for this project that lead many freshmen to use redis_exporter quickly.

**Comment by ccs018** [comment]
There's not only a screenshot, but links to actual dashboard definitions:

Grafana dashboard is available on grafana.net
<https://grafana.net/dashboards/763> and/or github.com
<https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json>
.

Grafana dashboard with host & alias selector is available on github.com
<https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard_alias.json>
.
Surely the documentation available at prometheus.io and grafana.org is
sufficient for someone to quickly set up those services and then loading in
the example Redis dashboard is quite simple.  I'm not sure that a how-to
for using Prometheus and Grafana needs to be included here.

**Comment by fengzixu** [comment]
Yeah. I found this according your comment. But it seems like to hard to find.

**Comment by oliver006** [comment]
Thanks for jumping in here @ccs018 !

@fengzixu - as Chris pointed out, there are a lot of examples in the README as well as on [prometheus.io](prometheus.io) how to configure and setup a fully working system.
If you think they could be arranged better I'm happy to hear suggestions and/or review and merge a PR.
