### ISSUE TITLE
Redis 2.4.20 not support `info all` command

### ISSUE THREAD

**Issue by nmred** [oliver006/redis_exporter#154]
Redis 2.4.20 not support `info all` command, 

log
```
INFO[0000] Redis Metrics Exporter v0.17.2    build date: 2018-04-08-15:05:53    sha1: 182dd9a5f9506ca59d5acd8b19274300e0e44e23    Go: go1.9.4
DEBU[0000] Enabling debug output
INFO[0000] Providing metrics at :9121/metrics
INFO[0000] Connecting to redis hosts: []string{"redis://host:7359"}
INFO[0000] Using alias: []string{""}
DEBU[0004] Trying DialURL(): redis://host:7359
DEBU[0004] connected to: redis://host:7359
DEBU[0004] c.Do() - running command: INFO [ALL]
DEBU[0004] c.Do() - err: ERR wrong number of arguments for 'info' command
DEBU[0004] c.Do() - done
ERRO[0004] Redis INFO err: ERR wrong number of arguments for 'info' command

```

**Comment by oliver006** [comment]
2.x is rather old, I guess back then they didn't have the `ALL` parameter for `INFO`? 

This could be fixed by falling back to using just `INFO` when `INFO ALL` fails.

I don't have a need for this but if enough people are interested or a PR is submitted I'm happy to help and review.

**Comment by fengnex** [comment]
We have hundreds of redis v2.* servers and our development teams do not want to upgrade them to redis v3.*.

So could you please better support redis v2.*?
Or please give us some tips on where and how to modify the source code? We may want to try to enhance it sometime in the future, thanks a lot.@oliver006

**Comment by oliver006** [comment]
What version(s) of Redis are you running?

**Comment by fengnex** [comment]
The redis version we are using is v2.8, thx

**Comment by fengnex** [comment]
redis-2.8.0.tar.gz
--

**Comment by fengnex** [comment]
It's been confirmed that redis_exporter has already well supported redis-2.8.0, sorry for the inconvenience if there is any!

**Comment by oliver006** [comment]
No worries, glad you figured it out.
