### ISSUE TITLE
Put the release file in a folder inside the .tar.gz

### ISSUE THREAD

**Issue by grantstephens** [oliver006/redis_exporter#173]
So this might be a weird one, but essentially all the other exporters that I've come across and use put the binary inside another folder in the release .tar.gz- this might be annoying or whatever, but at least it was consistent, except for this exporter.
Would it be possible to adjust the release process to make this possible?

**Comment by oliver006** [comment]
Hey there,

my instinct is to not change it at this point because probably people rely on it to not be in a folder and their puppet, ansible, whatever scripts would break if out of a sudden future releases are in a folder.

Is this currently causing serious issues for you or is it more of a convenience thing?

**Comment by grantstephens** [comment]
Thanks for the reply and sorry for my delayed reply.
So we currently have a generic exporter deploy script which covers all the exporters we have encountered so far (around 8 off the top of my head) where the binary is another folder deep. 
So I guess it is a convenience thing, but it is also a conformity thing. 
Don't know if it is worth leaving the issue open to see if anybody else comes across it and can give a thumbs up if they agree?

**Comment by dkanchev** [comment]
@oliver006 @grantstephens Can't we use a symlink and this way work around this problem?

**Comment by zoonage** [comment]
+1 for this, I would like to add it to https://github.com/lest/prometheus-rpm without having to add customisations to the build process for this exporter.

**Comment by grantstephens** [comment]
@dkanchev it looks like that would be possible. Something like `ln -s ../redis_exporter redis_exporter-vxxxx.linux-arch/redis_exporter` should do it.

**Comment by oliver006** [comment]
Heads up, PR #256 will fix this and put the binary in a folder. I'm expecting to merge it some time next week.

**Comment by oliver006** [comment]
As of v1.0.0 the binary is now in a folder named e.g. `redis_exporter-v1.0.0.linux-amd64`.
