### ISSUE TITLE
"-web.listen-address" not work?

### ISSUE THREAD

**Issue by eyjian** [oliver006/redis_exporter#176]
Start two instances on a machine to monitor two redis instance:
/usr/local/redis_exporter/redis_exporter redis//127.0.0.1:6379 -web.listen-address 9121
/usr/local/redis_exporter/redis_exporter redis//127.0.0.1:6381 -web.listen-address 9122

INFO[0000] Redis Metrics Exporter v0.20.1    build date: 2018-06-26-04:39:15    sha1: 3150962765f8eaa9315121d4e8e07808953a3f1b    Go: go1.9.4 
INFO[0000] Providing metrics at :9121/metrics           
INFO[0000] Connecting to redis hosts: []string{"redis://localhost:6379"} 
INFO[0000] Using alias: []string{""}                    
FATA[0000] listen tcp :9121: bind: address already in use

**Comment by oliver006** [comment]
@eyjian your command line parameters are a bit off, try:

`redis_exporter -redis.addr="redis://127.0.0.1:6379" -web.listen-address=":9121"`
and
`redis_exporter -redis.addr="redis://127.0.0.1:6381" -web.listen-address=":9122"`
