### ISSUE TITLE
Export counters as counters

### ISSUE THREAD

**Issue by jkohen** [oliver006/redis_exporter#178]
I work on the [Stackdriver integration with Prometheus](https://github.com/Stackdriver/stackdriver-prometheus) and a user filed [an issue](https://github.com/Stackdriver/stackdriver-prometheus/issues/14#issue-343468080) because this redis exporter exports counters as gauges, and Stackdriver doesn't allow rate computations over gauge. I know this isn't a major problem for Prometheus (it can mostly cause glitches on process restart), but would you consider fixing the [setMetrics method](https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L782) to set the right metric type? Any workaround on our side will be hard to maintain. Thanks!

**Comment by oliver006** [comment]
Thanks for raising the issue.
From looking at the [Prometheus Golang library docs here](https://github.com/prometheus/client_golang/blob/master/prometheus/doc.go#L107-L143) (and #31 ) it looks like using a ConstMetric is way to go.
Alas, I currently don't have bandwidth to implement that change and it's not a priority for me as I don't use Stackdriver but I'd be happy to review & merge a PR if you (or anyone else ) submits one.

**Comment by oliver006** [comment]
Actually, it might be a lot more easy change than I initially thought.

Replacing this part: https://github.com/oliver006/redis_exporter/blob/8d260bff3036a714ecdd01a40fcc87fe07fd3610/exporter/redis.go#L905-L916
with something that uses [NewCounterFunc](https://github.com/prometheus/client_golang/blob/b49b54cdb5f9850eb4c0090e5f9a8b3fc5113d5d/prometheus/counter.go#L262-L277) might do the trick.

**Comment by lukmdo** [comment]
IMO Gauges is more appointee in common case (redis values can go up and down) 

only ones that get pass making are included
https://github.com/oliver006/redis_exporter/blob/56bddc236d9d0b548ba1265ed73675f2c1de1332/exporter/redis.go#L335-L341

**Comment by oliver006** [comment]
`a)` could be a quick hack to make it work but I was thinking about going with option `b)` and store what type metric to use with each entry in the map.

**Comment by jkohen** [comment]
@mtanda FYI, this has been closed. In reference to https://github.com/Stackdriver/stackdriver-prometheus/issues/14 you filed.

**Comment by mtanda** [comment]
@jkohen That's fantastic!
Thank you for notifying me.

Dear Oliver,
Thank you for your work. I appreciate so much!
