### ISSUE TITLE
can't get dashboard to work/ can't get all desired metrics

### ISSUE THREAD

**Issue by naseemkullah** [oliver006/redis_exporter#182]
No matter what I do I seem to only be able to get the following metrics

I am running redis on kubernetes, and prometheus is able to scrape the redis_exporter service on 9121 but i only get limited information:

redis_up
redis_exporter_scrapes_total
redis_exporter_last_scrape_error
redis_exporter_build_info

is all i get

**Comment by oliver006** [comment]
Looks like the exporter had trouble scraping the redis instance?
Can you provide a bit ore information?
What's the value of `redis_up`? 
How did you set up & configure the redis_exporter? Is there anything in the exporter logs that hints at what the issue is? Can you run the exporter with the `--debug` flag and see if any additional output can help you nail down the problem?

**Comment by naseemkullah** [comment]
Hi Oliver,
I've tried setting it up a few ways:
First, was installing the `redis` helm chart, with metrics enabled, which creates a seperate pod (not a sidecar). Then I installed the `kube-prometheus` chart and created a `servicemonitor` to monitor the `redis-metrics` service created by the redis helm chart.

value of redis_up for that one is:
```
redis_up{addr="redis-master:6379",alias="redis",endpoint="metrics",instance="10.60.2.105:9121",job="redis-metrics",namespace="default",pod="redis-metrics-586c5e5f34-xv2zw",service="redis-metrics"} | 0
-- | --
redis_up{addr="redis-slave:6379",alias="redis",endpoint="metrics",instance="10.60.2.105:9121",job="redis-metrics",namespace="default",pod="redis-metrics-586c5e5f34-fv2xw",service="redis-metrics"}
```

As you can see there are two kubernetes services to monitor, which route traffic to their respective pod(s) (redis-master-0, or redis-slave-<pod id>) ....


So when I could not get the metrics I tried to simplify things. I had another non helm deployed redis slave (of an on prem redis) running in the cluster, so i added the exporter as a sidecar to it, and deployed the `prometheus` helm chart and added the scrape in `pometheus.yml`

Here is the result of redis_up:

```
redis_up{addr="redis://localhost:6379",instance="another-redis-slave.default.svc:9121",job="api_redis_exporter"}
--
```

I will try running in debug mode now.

The logs for the exporters say:

```
time="2018-08-07T01:25:58Z" level=info msg="Redis Metrics Exporter v0.20.2    build date: 2018-07-03-14:18:56    sha1: 2e15af37aac37e114b33a07f5e9dc0410f4cbfc4    Go: go1.9.4"
time="2018-08-07T01:25:58Z" level=info msg="Providing metrics at :9121/metrics"
time="2018-08-07T01:25:58Z" level=info msg="Connecting to redis hosts: []string{\"redis-master:6379\", \"redis-slave:6379\"}"
time="2018-08-07T01:25:58Z" level=info msg="Using alias: []string{\"redis\", \"redis\"}"
```

**Comment by oliver006** [comment]
Does everything live in the same namespace? Is `redis-master` the correct host name of your redis instance? Do you maybe have to include a namespace ? 
If you open a shell in the exporter pod/container - can you resolve `redis-master` and see if you can connect to port 6379? 
The result of `redis_up` seems to be `0` so it fails to connect to the host and scrape it, hence no metrics.

**Comment by naseemkullah** [comment]
the redises and exporters live in the `default` namespace however the prometheus lives in the `monitoring` namespace (though that probably does not matter)

The exporter can indeed resolve the names, but cannot connect on port 6379! I hope to be able to take it from there. 

Thank you!

**Comment by naseemkullah** [comment]
Sorry, telnet would hang, but upon installing redis-cli on the exporter, i could connect to redis-master

**Comment by oliver006** [comment]
Ah, too bad, I was hoping you found the root cause.

Can you try running the exporter with the `--debug` flag and see if there's useful output in the logs?

**Comment by naseemkullah** [comment]
ha!

```
redis err: ERR invalid password
```

This is weird..
because when I exec into the exporter pod,
```
# echo $REDIS_PASSWORD
```
returns the correct password

**Comment by naseemkullah** [comment]
I'm sorry there is another important msg from debug:

invalid redis URL scheme: redis-master

**Comment by oliver006** [comment]
Ah yes, can you also try `redis://redis-master:6379` for the address.

As for your password, does it have any special/weird characters in it or just a-zA-Z0-9 ?

**Comment by oliver006** [comment]
Ok, keep me posted.
I asked about the characters cause #160 also had issues with odd characters in the password, maybe there's a bigger problem here.

**Comment by naseemkullah** [comment]
hmm comma here as well...

**Comment by naseemkullah** [comment]
sorry back to url thing, it actually did not work:

`"aborting for addr: redis://redis-slave.default.svc:6379 - redis err: dial redis: unknown network redis"`

**Comment by naseemkullah** [comment]
Is there anyway to have the comma be taken as part of the password string? I notice that commas are separators as well. In the meantime I will try overriding the separator

**Comment by naseemkullah** [comment]
Good news!
This has been solved by overriding the separator using the undocumented separator flag (I've created a PR to add it to docs), I over-rid it with a character not in the password, and used it to separate the hosts, and everything went well.

Thanks for your help on this and for creating such an awesome exporter and dashboard!!

**Comment by oliver006** [comment]
Ahhhh, good work figuring out the issue. And thanks for the PR!
