### ISSUE TITLE
All configs with env variables

### ISSUE THREAD

**Issue by Nighthawk22** [oliver006/redis_exporter#19]
Hi!

Nice work, we are using it every day! 
For our docker setup I would like to know if it is possible to overwrite all flags with env variables. I could provide a pull request if you like.

With kind regards,
Nighthawk

**Comment by oliver006** [comment]
Ha, thanks, glad to hear you like it.

I'm always open full pull requests to add functionality so please go ahead. I've used this package for related work in the past, it's pretty neat: https://github.com/kelseyhightower/envconfig
but I'm fine with whatever you come up with as long as it does the trick.

**Comment by rdtr** [comment]
@Nighthawk22 I just sent a PR to make what you asked possible.
Sorry I didn't notice this ticket at that time, so I only applied the change to `redis.addr`😣

But I'm sure you can do this in the exact same manner. 
https://github.com/oliver006/redis_exporter/pull/45/files
Please just use `getEnv` helper function to specify an env key and a default value.

**Comment by dkanchev** [comment]
It looks like even more config options are now using the getEnv helper function which @rdtr mentioned. Looking at the code right now the following use getEnv:

https://github.com/oliver006/redis_exporter/blob/8d260bff3036a714ecdd01a40fcc87fe07fd3610/main.go#L17-L20

Do we want to make it so that all config options use the `getEnv`?

**Comment by oliver006** [comment]
Yeah, I think that'd be useful.

**Comment by dkanchev** [comment]
@oliver006 I hope this helps:

https://github.com/oliver006/redis_exporter/pull/179

**Comment by oliver006** [comment]
Closed by #179 - thanks @dkanchev !
