### ISSUE TITLE
Metrics endpoint timing out/taking long time to return data

### ISSUE THREAD

**Issue by NikolaeVarius** [oliver006/redis_exporter#191]
I'm having a strange issue with scraping the metrics endpoint.  My prometheus instance is configured to scrape every 15 seconds.

I have redis_exporter hooked up to a redis elasticache instance. For some reason, when I hit the /metrics endpoint, it takes a very long time to return anything, Looking at debug logs, it seems that the scrapes are happening fine, but /metrics doens't return any data for 15+ seconds

What's strange is that sometimes it will return data in a timely manner with the requisite data, but on subsequent refresh attempts, it will hang.

I can hit the base / endpoint immediately just fine.

**Comment by oliver006** [comment]
That's odd.

What if you connect to the exporter pod and curl localhost:9121/metrics - does it still take 15s ?
And when you turn on verbose debug output, can you tell if the `/metrics` endpoint takes 15s or if it's a network problem?

**Comment by oliver006** [comment]
Are that all the logs? There should be a lot more for a full scrape.

**Comment by oliver006** [comment]
Yeah, I don't think there's a log for the individual requests to `/metrics` but there is a prometheus metric called `redis_exporter_last_scrape_duration_seconds` which should help with figuring out how long the scrape actually took.

**Comment by oliver006** [comment]
And did you try `curl` from the exporters pod and the prometheus pod? does it take 15+ seconds for both of them?

**Comment by NikolaeVarius** [comment]
> redis_exporter_last_scrape_duration_seconds 2.625517784

I did try the curl. It looks like the scrape itself takes less than 3 seconds. I actually ended up throwing alot more CPU at the job (750mgz) and then /metrics came back in about 10 seconds. Still seems very long for a 3 seconds scrape.

**Comment by NikolaeVarius** [comment]
Some other stuff I noticed. Task was being oom killed due to steadily increasing memory usage.
![screen shot 2018-10-05 at 1 33 26 pm](https://user-images.githubusercontent.com/8305363/46550664-b6638500-c8a3-11e8-86b6-68819bdbccd2.png)

I  don't see any explicit errors in the  logs that I would normally worry about maybe some of these internal stats might hold some clues?

`time="2018-10-05T17:33:17Z" level=debug msg="info: # Commandstats"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_get:calls=10826757,usec=20269830,usec_per_call=1.87"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_set:calls=10178173,usec=66427770,usec_per_call=6.53"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_del:calls=251408,usec=1019966,usec_per_call=4.06"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_exists:calls=51171,usec=124022,usec_per_call=2.42"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_mget:calls=218508,usec=1280595,usec_per_call=5.86"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_lpush:calls=209,usec=2052,usec_per_call=9.82"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_lrange:calls=2,usec=39,usec_per_call=19.50"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_smembers:calls=476243,usec=9260922,usec_per_call=19.45"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_zadd:calls=5569,usec=65317,usec_per_call=11.73"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_zrem:calls=14666,usec=74834,usec_per_call=5.10"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_hmset:calls=893560,usec=21072977,usec_per_call=23.58"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_hlen:calls=3500355,usec=6094867,usec_per_call=1.74"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_hgetall:calls=2042318,usec=23029725,usec_per_call=11.28"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_incrby:calls=461176,usec=2403328,usec_per_call=5.21"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_select:calls=3594336,usec=5027353,usec_per_call=1.40"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_expire:calls=20711,usec=31039,usec_per_call=1.50"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_expireat:calls=4832883,usec=14243789,usec_per_call=2.95"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_keys:calls=12004,usec=131147753,usec_per_call=10925.34"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_scan:calls=894549692,usec=6912248651,usec_per_call=7.73"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_ping:calls=6295019,usec=19665818,usec_per_call=3.12"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_bgsave:calls=70,usec=90847,usec_per_call=1297.81"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_type:calls=3500361,usec=8568706,usec_per_call=2.45"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_multi:calls=14714,usec=13218,usec_per_call=0.90"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_exec:calls=14714,usec=248835,usec_per_call=16.91"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_psync:calls=1,usec=159,usec_per_call=159.00"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_replconf:calls=3650585,usec=8757678,usec_per_call=2.40"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_info:calls=2745446,usec=245884627,usec_per_call=89.56"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_slaveof:calls=2,usec=191,usec_per_call=95.50"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_config:calls=10,usec=98,usec_per_call=9.80"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_slowlog:calls=93932,usec=135880,usec_per_call=1.45"
time="2018-10-05T17:33:17Z" level=debug msg="info: cmdstat_latency:calls=93975,usec=235716,usec_per_call=2.51"
time="2018-10-05T17:33:17Z" level=debug msg="info: "
time="2018-10-05T17:33:17Z" level=debug msg="info: # Keyspace"
time="2018-10-05T17:33:17Z" level=debug msg="info: db0:keys=100010,expires=99431,avg_ttl=55009385"`

**Comment by oliver006** [comment]
The log output above is mostly just what comes from the `INFO` command.
What would be useful would be a full log of one scrape, start to finish (from [`Trying DialURL`](https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L753) to [`scrapeRedisHost() done`](https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L884)).

The increasing memory usage is interesting. And worrisome. I'm currently looking at one of my own deployments of redis_exporter and don't see the increase in memory usage.

You could try adding pprof instrumenting to the exporter and hope that a dump of memory or goroutines would give more insight into what's going on.

Oh, speaking of which, what does the metric for `go_goroutines` for the exporter look like?

**Comment by NikolaeVarius** [comment]
`time="2018-10-09T13:01:03Z" level=debug msg="Trying DialURL(): redis://
time="2018-10-09T13:01:03Z" level=debug msg="connected to: redis://
time="2018-10-09T13:01:03Z" level=debug msg="Redis CONFIG err: ERR unknown command 'CONFIG'"
time="2018-10-09T13:01:03Z" level=debug msg="c.Do() - running command: INFO [ALL]"
time="2018-10-09T13:01:03Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:03Z" level=debug msg="info: # Server"
time="2018-10-09T13:01:03Z" level=debug msg="info: redis_version:2.8.23"
time="2018-10-09T13:01:03Z" level=debug msg="info: redis_git_sha1:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: redis_git_dirty:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: redis_build_id:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: redis_mode:standalone"
time="2018-10-09T13:01:03Z" level=debug msg="info: os:Amazon ElastiCache"
time="2018-10-09T13:01:03Z" level=debug msg="info: arch_bits:64"
time="2018-10-09T13:01:03Z" level=debug msg="info: multiplexing_api:epoll"
time="2018-10-09T13:01:03Z" level=debug msg="info: gcc_version:0.0.0"
time="2018-10-09T13:01:03Z" level=debug msg="info: process_id:1"
time="2018-10-09T13:01:03Z" level=debug msg="info: run_id:4ce62c26a287adf329ed44c4f9100260d8907aea"
time="2018-10-09T13:01:03Z" level=debug msg="info: tcp_port:6379"
time="2018-10-09T13:01:03Z" level=debug msg="info: uptime_in_seconds:6420113"
time="2018-10-09T13:01:03Z" level=debug msg="info: uptime_in_days:74"
time="2018-10-09T13:01:03Z" level=debug msg="info: hz:10"
time="2018-10-09T13:01:03Z" level=debug msg="info: lru_clock:12363407"
time="2018-10-09T13:01:03Z" level=debug msg="info: config_file:/etc/redis.conf"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Clients"
time="2018-10-09T13:01:03Z" level=debug msg="info: connected_clients:9"
time="2018-10-09T13:01:03Z" level=debug msg="info: client_longest_output_list:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: client_biggest_input_buf:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: blocked_clients:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Memory"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory:8200576"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory_human:7.82M"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory_rss:15728640"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory_peak:32147864"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory_peak_human:30.66M"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_memory_lua:36864"
time="2018-10-09T13:01:03Z" level=debug msg="info: mem_fragmentation_ratio:1.92"
time="2018-10-09T13:01:03Z" level=debug msg="info: mem_allocator:jemalloc-3.6.0"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Persistence"
time="2018-10-09T13:01:03Z" level=debug msg="info: loading:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_changes_since_last_save:91859"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_bgsave_in_progress:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_last_save_time:1539055852"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_last_bgsave_status:ok"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_last_bgsave_time_sec:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: rdb_current_bgsave_time_sec:-1"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_enabled:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_rewrite_in_progress:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_rewrite_scheduled:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_last_rewrite_time_sec:-1"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_current_rewrite_time_sec:-1"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_last_bgrewrite_status:ok"
time="2018-10-09T13:01:03Z" level=debug msg="info: aof_last_write_status:ok"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Stats"
time="2018-10-09T13:01:03Z" level=debug msg="info: total_connections_received:305322"
time="2018-10-09T13:01:03Z" level=debug msg="info: total_commands_processed:1139001966"
time="2018-10-09T13:01:03Z" level=debug msg="info: instantaneous_ops_per_sec:3"
time="2018-10-09T13:01:03Z" level=debug msg="info: total_net_input_bytes:79108207317"
time="2018-10-09T13:01:03Z" level=debug msg="info: total_net_output_bytes:37697159038"
time="2018-10-09T13:01:03Z" level=debug msg="info: instantaneous_input_kbps:0.17"
time="2018-10-09T13:01:03Z" level=debug msg="info: instantaneous_output_kbps:4.23"
time="2018-10-09T13:01:03Z" level=debug msg="info: rejected_connections:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: sync_full:1"
time="2018-10-09T13:01:03Z" level=debug msg="info: sync_partial_ok:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: sync_partial_err:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: expired_keys:226026"
time="2018-10-09T13:01:03Z" level=debug msg="info: evicted_keys:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: keyspace_hits:37481745"
time="2018-10-09T13:01:03Z" level=debug msg="info: keyspace_misses:7232026"
time="2018-10-09T13:01:03Z" level=debug msg="info: pubsub_channels:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: pubsub_patterns:0"
time="2018-10-09T13:01:03Z" level=debug msg="info: latest_fork_usec:242"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Replication"
time="2018-10-09T13:01:03Z" level=debug msg="info: role:master"
time="2018-10-09T13:01:03Z" level=debug msg="info: connected_slaves:1"
time="2018-10-09T13:01:03Z" level=debug msg="info: slave0:ip=172.16.0.5,port=6379,state=online,offset=24601227947,lag=0"
time="2018-10-09T13:01:03Z" level=debug msg="info: master_repl_offset:24601227947"
time="2018-10-09T13:01:03Z" level=debug msg="info: repl_backlog_active:1"
time="2018-10-09T13:01:03Z" level=debug msg="info: repl_backlog_size:1048576"
time="2018-10-09T13:01:03Z" level=debug msg="info: repl_backlog_first_byte_offset:24600179372"
time="2018-10-09T13:01:03Z" level=debug msg="info: repl_backlog_histlen:1048576"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # CPU"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_cpu_sys:21636.99"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_cpu_user:17821.96"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_cpu_sys_children:1.54"
time="2018-10-09T13:01:03Z" level=debug msg="info: used_cpu_user_children:15.96"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Commandstats"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_get:calls=17265202,usec=29841290,usec_per_call=1.73"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_set:calls=10780325,usec=69399784,usec_per_call=6.44"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_del:calls=262942,usec=1053714,usec_per_call=4.01"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_exists:calls=55289,usec=132227,usec_per_call=2.39"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_mget:calls=230305,usec=1429985,usec_per_call=6.21"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_lpush:calls=209,usec=2052,usec_per_call=9.82"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_lrange:calls=2,usec=39,usec_per_call=19.50"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_smembers:calls=520079,usec=10085964,usec_per_call=19.39"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_zadd:calls=5811,usec=67914,usec_per_call=11.69"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_zrem:calls=15415,usec=78397,usec_per_call=5.09"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_hmset:calls=916340,usec=21961629,usec_per_call=23.97"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_hlen:calls=9327191,usec=16106695,usec_per_call=1.73"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_hgetall:calls=2229792,usec=24762867,usec_per_call=11.11"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_incrby:calls=476488,usec=2469195,usec_per_call=5.18"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_select:calls=9563291,usec=13367286,usec_per_call=1.40"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_expire:calls=21448,usec=31989,usec_per_call=1.49"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_expireat:calls=5120243,usec=14923138,usec_per_call=2.91"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_keys:calls=13358,usec=132756831,usec_per_call=9938.38"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_scan:calls=1058583746,usec=8016963638,usec_per_call=7.57"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_ping:calls=6775340,usec=20665594,usec_per_call=3.05"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_bgsave:calls=74,usec=93838,usec_per_call=1268.08"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_type:calls=9327198,usec=22348707,usec_per_call=2.40"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_multi:calls=15209,usec=13707,usec_per_call=0.90"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_exec:calls=15209,usec=257908,usec_per_call=16.96"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_psync:calls=1,usec=159,usec_per_call=159.00"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_replconf:calls=3977969,usec=9481975,usec_per_call=2.38"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_info:calls=3031335,usec=268197371,usec_per_call=88.48"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_slaveof:calls=2,usec=191,usec_per_call=95.50"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_config:calls=10,usec=98,usec_per_call=9.80"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_slowlog:calls=236050,usec=339243,usec_per_call=1.44"
time="2018-10-09T13:01:03Z" level=debug msg="info: cmdstat_latency:calls=236093,usec=617185,usec_per_call=2.61"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="info: # Keyspace"
time="2018-10-09T13:01:03Z" level=debug msg="info: db0:keys=10574,expires=9995,avg_ttl=1066547611"
time="2018-10-09T13:01:03Z" level=debug msg="info: "
time="2018-10-09T13:01:03Z" level=debug msg="c.Do() - running command: LATENCY [LATEST]"
time="2018-10-09T13:01:03Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:03Z" level=debug msg="e.singleKeys: []exporter.dbKeyPair(nil)"
time="2018-10-09T13:01:03Z" level=debug msg="e.keys: []exporter.dbKeyPair{e"}}"
time="2018-10-09T13:01:04Z" level=debug msg="allKeys: <LOTS OF KEYS>
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:04Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-10-09T13:01:05Z" level=debug msg="c.Do() - done"
time="2018-10-09T13:01:05Z" level=debug msg="scrapeRedisHost() done"`

**Comment by NikolaeVarius** [comment]
For some reason SOME processes will work while others hang. Specifically the "/metrics" path fails, even when running on localhost.

`curl localhost:20338

<html>
<head><title>Redis Exporter vv0.22.0</title></head>
<body>
<h1>Redis Exporter v0.22.0</h1>
<p><a href='/metrics'>Metrics</a></p>
</body>
</html>`

`curl localhost:20338/metrics
`

**Comment by oliver006** [comment]
Thanks, that's odd.
A couple more questions: is the one that fails consistently the same one? Are they all set up the same way? Run in the same type of data center / cloud environment? Do they scrape a (AWS, GCP, etc) hosted redis instance or something you run yourself? Can you try running with verbose log output and try to collect logs from a complete run? (make sre you remove anything sensitive from the logs before posting here)

**Comment by NikolaeVarius** [comment]
No it is not consistently the same, as the moment it only affects one of the environments. They are set up the same way at the process level. Different at AWS but that shouldn't really matter because its just a URL end point. I can see the scraper actually processing the scrape inverbose mode. Literally the only thing that fails is the "/metrics" return.

**Comment by oliver006** [comment]
That's interesting. So after  there's nothing in the logs after`scrapeRedisHost() done` and the response doen't finish?

**Comment by NikolaeVarius** [comment]
I just see this. Looks like it just goes to the next scrape attempt

`time="2018-11-21T19:55:22Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2018-11-21T19:55:22Z" level=debug msg="c.Do() - done"
time="2018-11-21T19:55:22Z" level=debug msg="scrapeRedisHost() done"
time="2018-11-21T19:55:22Z" level=debug msg="Trying DialURL(): redi`

**Comment by mkorolyov** [comment]
Observe same behavior.
Scrape takes about 20s, while http /metrics endpoint takes 2-5 mins.

**Comment by oliver006** [comment]
Thanks @mkorolyov - do you have more information (e.g logs with exporter running in verbose mode) that can shed some more lights on where the time is spent?

**Comment by oliver006** [comment]
Old issue., closing. Please re-open and add new information if you observe the problem again.
