### ISSUE TITLE
Docker container does not exit when it gets signal to close

### ISSUE THREAD

**Issue by mardicas** [oliver006/redis_exporter#193]
Hi,
I am running the oliver006/redis_exporter:latest image in a kubernetes pod togeather with redis.
It appears that this image does not exit when the default signal is sent. (SIGTERM)

Redis has already exited but the pod remains running(for longer than needed), since this container does not seem to understand it.

The program should understand SIGTERM or change the STOPSIGNAL in the dockerfile to something that it understands.

I already checked that the /bin/redis_exporter is the go binary and PID 1. So it is not a case of shell forking(that the process never gets the signal).

https://stackoverflow.com/questions/50898134/what-does-docker-stopsignal-do

This should also make stoping of the container in any docker enviroment faster.

**Comment by mardicas** [comment]
I am not at home with GO language, but here seems to be a how-to about it:
https://medium.com/@kpbird/golang-gracefully-stop-application-23c2390bb212

**Comment by mardicas** [comment]
https://github.com/braintree/manners should be possible to drop in. "Manners allows you to shut your Go webserver down gracefully, without dropping any requests. It can act as a drop-in replacement for the standard library's http.ListenAndServe function:" As far as I can tell it is using ListenAndServe.

**Comment by oliver006** [comment]
The redis_exporter process exists just fine when sending the `SIGTERM` signal, you can try via `kill -TERM <<pid of hte process>>`, it exists right away so it's not a problem with how the process reacts to the signal.

However, I did not test this in a k8s setup.

Do you see anything in the logs between sending the termination signal and when the exporter exists?

**Comment by mardicas** [comment]
Hi, seems you are right. It works just fine! Must be something in kubernetes side.

To test it was to use only docker:
`docker run -d  oliver006/redis_exporter
time docker stop de68ac77ce5f
de68ac77ce5f

real    0m0,429s
`
It would be nice to have some sort of message in log/stdout about stopping/shutting down "nicely".
