### ISSUE TITLE
how to use -redis.file

### ISSUE THREAD

**Issue by zzxzhan** [oliver006/redis_exporter#198]
(1)when in run following command:./redis_exporter -redis.file redis.yml;
there is some errors:
INFO[0000] Redis Metrics Exporter v0.22.0    build date: 2018-11-08-15:43:26    sha1: d870a53c5e9c8a2b798d29e670ca6b43468edddc    Go: go1.11.2 
FATA[0000] parse error on line 4, column 16: bare " in non-quoted-field 

(2)so I want to know how to use -redis.file

(3)
my redis.file is like following 
redis_hosts: 
  - 
    description: test1
    redis.addr: "192.168.1.1:6379"
    redis.password: redis123456
  - 
    description: test2
    redis.addr: "192.168.1.2:6379"
    redis.password: redis123456

**Comment by oliver006** [comment]
The parameter `-redis.file` points to a CSV file with one host per  line.
See this file here for an example: https://github.com/oliver006/redis_exporter/blob/master/contrib/sample_redis_hosts_file.txt

Note to self: should link to the sample file in the README so it's more obvious what format the file is in.

**Comment by oliver006** [comment]
Closed by #224
