### ISSUE TITLE
Improve redis addr validation and handling

### ISSUE THREAD

**Issue by deepthawtz** [oliver006/redis_exporter#20]
Maybe I'm missing something but I don't see any Redis metrics around databases/keys/hit/miss

testing on various Redis versions from 2.4.x to 3.0.x and the only `redis_` prefixed metrics I see are:

```
# HELP redis_exporter_last_scrape_duration_seconds The last scrape duration.
# TYPE redis_exporter_last_scrape_duration_seconds gauge
redis_exporter_last_scrape_duration_seconds 0.001755366
# HELP redis_exporter_last_scrape_error The last scrape error status.
# TYPE redis_exporter_last_scrape_error gauge
redis_exporter_last_scrape_error 1
# HELP redis_exporter_scrapes_total Current total redis scrapes.
# TYPE redis_exporter_scrapes_total counter
redis_exporter_scrapes_total 1
```

**Comment by deepthawtz** [comment]
I've tested both with `21zoo/redis_exporter` latest Docker image and with HEAD of this repo and same results

**Comment by oliver006** [comment]
It says: `redis_exporter_last_scrape_error 1`

Anything in the console output that tells you what went wrong?

**Comment by deepthawtz** [comment]
😊 my bad, `-redis.addr` requires a port

**Comment by deepthawtz** [comment]
might be nice to raise an error if `-redis.addr` does not include a port if port number is required too

**Comment by oliver006** [comment]
Good idea, that could be handled better.

**Comment by deepthawtz** [comment]
I wouldn't mind taking a crack and we could discuss from there

**Comment by oliver006** [comment]
👍
