### ISSUE TITLE
how to moniotr redis with cipher

### ISSUE THREAD

**Issue by shiyapeng** [oliver006/redis_exporter#200]
for example  
./redis-cli -h 11.11.11.11 -p 33333 -cipherdir /opt/oss/manager/etc/cipher/ -a db@user@pwd

how should I configure，thanks

**Comment by oliver006** [comment]
I'm not familiar with the `-cipherdir` command line option and it doesn't seem to be supported by the official client - do you have more information as to what it does?

**Comment by shiyapeng** [comment]
> I'm not familiar with the `-cipherdir` command line option and it doesn't seem to be supported by the official client - do you have more information as to what it does?

the cipherdir has the  key  redis_shared.key and  and the key root.key .they  are userd  to conncet redis for security。

**Comment by oliver006** [comment]
That's currently not supported (and I don't see any information about it on the redis.io website so not sure if this is an official thing)

**Comment by shiyapeng** [comment]
> That's currently not supported (and I don't see any information about it on the redis.io website so not sure if this is an official thing)

ok，Thanks for your reply。
