### ISSUE TITLE
command calls / sec no pic

### ISSUE THREAD

**Issue by liu-yfeng** [oliver006/redis_exporter#201]
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/api/v1/query_range?query=topk(5%2C%20irate(redis_command_call_duration_seconds_count%7Baddr%3D~%22172.18.223.21%3A6379%22%7D%20%5B1m%5D))&start=1543283268&end=1543369668&step=240"
response:Object
status:"success"
data:Object
resultType:"matrix"
result:Array[0]
[]    **------------------> no values**

**but, in system has values,why?**
curl http://172.18.223.21:9121/metrics | grep "redis_command_call_duration_seconds_count"
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="auth"} 1.6291997e+07
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="client"} 9674
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="cluster"} 4837
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="config"} 15250
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="del"} 1.8815701e+07
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="echo"} 9674
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="exists"} 26
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="expire"} 1.842296e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="get"} 1.7890539e+08
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="getset"} 43
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hdel"} 1.257828e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hexists"} 5.62446e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hget"} 2.104236e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hgetall"} 26
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hlen"} 8
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hscan"} 8
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="hset"} 1.258442e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="info"} 2.152755e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="keys"} 10
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="latency"} 731
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="ping"} 78952
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="scan"} 212
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="select"} 7.5741385e+07
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="set"} 2.811651e+06
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="setex"} 3.1898545e+07
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="slowlog"} 1464
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="subscribe"} 4841
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="ttl"} 108
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="type"} 109
redis_command_call_duration_seconds_count{addr="172.18.223.21:6379",alias="",cmd="unsubscribe"} 2.143337e+06

**Comment by oliver006** [comment]
Not sure why it fails. Is Prometheus scraping the redis_exporter target correctly?

What's the output for 

`irate(redis_command_call_duration_seconds_count{addr=~"172.18.223.21:6379"} [1m])`

and

`redis_command_call_duration_seconds_count`?

**Comment by liu-yfeng** [comment]
**sorry,I don't know how to operate it.
and 
Total Items per DB**
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db0"} 66679
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db1"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db10"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db11"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db12"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db13"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db14"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db15"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db2"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db3"} 0  **---------> actually has key**
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db4"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db5"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db6"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db7"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db8"} 0
redis_db_keys_expiring{addr="172.18.223.21:6379",alias="",db="db9"} 0

**Comment by oliver006** [comment]
The queries I posted in my last comment are promql that you can query via e.g. the prometheus server console web page. That page has lots more good information for troubleshooting like discovered/scraped targets, etc so it's worth taking a look.
Address is normally something like `http://the-address-of-your-prometheus-server/graph`

**Comment by liu-yfeng** [comment]
ok,thanks

**Comment by oliver006** [comment]
Closing, please re-open if the problem occurs again.

**Comment by yongsr** [comment]
Hi I also having same issue

**Comment by liu-yfeng** [comment]
> Hi I also having same issue

i change prometheus version,is working

**Comment by yongsr** [comment]
Mine is latest version 2.8, still no clue what happened lol

**Comment by oliver006** [comment]
The metrics names for commands stats have changed a while ago (#203). If you recently updated the exporter than make sure you also updated the dashboard to pull in the correct metrics.

I did just update the version on https://grafana.com/dashboards/763 as that was still using the old metrics so if you pulled in the dashboard from there, please do again and update what you have installed.

**Comment by yongsr** [comment]
> The metrics names for commands stats have changed a while ago (#203). If you recently updated the exporter than make sure you also updated the dashboard to pull in the correct metrics.
> 
> I did just update the version on https://grafana.com/dashboards/763 as that was still using the old metrics so if you pulled in the dashboard from there, please do again and update what you have installed.

Got it, thanks!

**Comment by kcoderk** [comment]
I Change the metric "redis_commands_total" to "redis_commands_processed_total",It Works,Hope it helps
