### ISSUE TITLE
Redis Exporter is not able to expose the metrics from Master Node

### ISSUE THREAD

**Issue by grvpahuja** [oliver006/redis_exporter#202]
Hello @oliver006,

I am using the exporter on linux - amd64 architecture and installed the exporter instance on master and slave nodes but the port 9121 for master is not exposing the complete metrics.

I could see the following difference 
For master : redis_exporter_last_scrape_error 1; redis_up{addr="redis://localhost:6379",alias=""} 0
For slave: redis_exporter_last_scrape_error 0;redis_up{addr="redis://localhost:6379",alias=""} 1

I think this could be the reason because of which in master, I don't have any of the relavnt redis_* metrics. Master and slave are both up and running, and serving the application.

Could you please help me on this?

Thanks and Best Regards!

**Comment by oliver006** [comment]
That looks like `redis_exporter` is not able to scrape the master node (redis_exporter_last_scrape_error is `1`, redis_up is `0`) - can you check the logs and see if there's anything useful in there?

**Comment by grvpahuja** [comment]
Logs for Slave:
DEBU[0000] Enabling debug output                        
DEBU[0000] keys: []exporter.dbKeyPair(nil)              
DEBU[0000] singleKeys: []exporter.dbKeyPair(nil)        
INFO[0000] Providing metrics at :9121/metrics           
INFO[0000] Connecting to redis hosts: []string{"redis://localhost:6379"} 
INFO[0000] Using alias: []string{""}                    
DEBU[0014] Trying DialURL(): redis://localhost:6379     
DEBU[0014] connected to: redis://localhost:6379         

Logs for master:
INFO[0000] Redis Metrics Exporter v0.22.1    build date: 2018-11-18-05:20:28    sha1: 77c2c783e074db2b1cc0e3531a55444d5d97a889    Go: go1.11.2 
DEBU[0000] Enabling debug output                        
DEBU[0000] keys: []exporter.dbKeyPair(nil)              
DEBU[0000] singleKeys: []exporter.dbKeyPair(nil)        
INFO[0000] Providing metrics at :9121/metrics           
INFO[0000] Connecting to redis hosts: []string{"redis://localhost:6379"} 
INFO[0000] Using alias: []string{""}                    
DEBU[0011] Trying DialURL(): redis://localhost:6379     
DEBU[0011] DialURL() failed, err: dial tcp [::1]:6379: connect: connection refused 
DEBU[0011] Trying: Dial(): redis localhost:6379         
DEBU[0011] aborting for addr: redis://localhost:6379 - redis err: dial redis: unknown network redis

**Comment by oliver006** [comment]
From your master logs:

` DEBU[0011] DialURL() failed, err: dial tcp [::1]:6379: connect: connection refused`

Looks like the exporter fails to connect to the master instance.

**Comment by grvpahuja** [comment]
Thanks for your reply. Any idea, what could be the possible reason for this?
I have checked the configs for both master and slave, everything is same for both master and slave nodes but still could not connect to the master node.

**Comment by oliver006** [comment]
That's odd. What kind of environment are you running this in? VMs? Kubernetes pods? 
From the host/pod that runs the exporter for the master instance, can you connect to localhost:6379 using telnet, nc or curl or whatever?

**Comment by grvpahuja** [comment]
@oliver006 
Hey, the different behavior for master and slave node was because of different security groups defined for them. Problem is resolved now :)
Thanks for your support!

**Comment by oliver006** [comment]
Good to hear you figured it out!
