### ISSUE TITLE
promtool check metrics issues

### ISSUE THREAD

**Issue by mjtrangoni** [oliver006/redis_exporter#204]
Hi @oliver006 ,

Checking the redis_exporter `v0.23.0 output with promtool, I have the following result,

```
# curl -s http://fqdn:9121/metrics | promtool check metrics
redis_commands_duration_seconds_total non-counter metrics should not have "_total" suffix
redis_commands_processed_total non-counter metrics should not have "_total" suffix
redis_commands_total non-counter metrics should not have "_total" suffix
redis_connections_received_total non-counter metrics should not have "_total" suffix
redis_evicted_keys_total non-counter metrics should not have "_total" suffix
redis_expired_keys_total non-counter metrics should not have "_total" suffix
redis_keyspace_hits_total non-counter metrics should not have "_total" suffix
redis_keyspace_misses_total non-counter metrics should not have "_total" suffix
redis_net_input_bytes_total non-counter metrics should not have "_total" suffix
redis_net_output_bytes_total non-counter metrics should not have "_total" suffix
redis_rejected_connections_total non-counter metrics should not have "_total" suffix
```

If you agree, I could send a PR for fixing this, and also adding this check to CircleCI.

**Comment by oliver006** [comment]
@mjtrangoni - thanks for raising the issue, I think that's related to #178 - a lot or the `_total` metrics are gauges and just pass through counter data from redis so they really could/should be counters in prometheus.

Go ahead and open a PR if you want to fix the issue, that'd be great!

**Comment by mjtrangoni** [comment]
@oliver006 ok, perfect. I will be sending a PR creating Counters instead of Gauges at weekend. Thanks!

**Comment by oliver006** [comment]
Thanks @mjtrangoni 
fyi, it might not be as easy as creating Counters instead of Gauges (see #178 for a bit of background) but I'm looking forward to seeing what you come up with.

**Comment by mjtrangoni** [comment]
@oliver006 I took a look today, and saw that I can create from Exporter struct element `metrics`, two variables, one `metricsGauge`, and the other `metricsCounter`.

Do you agree doing that? This will be fixing only the following two metrics,

```
redis_commands_duration_seconds_total non-counter metrics should not have "_total" suffix
redis_commands_total non-counter metrics should not have "_total" suffix
```

After fixing them, I would be adding, like it is said in #178, a metric type field to the metricMap. Do you agree doing that too? This would be a separated PR.
