### ISSUE TITLE
（redis_command_call_duration_seconds_count）no data

### ISSUE THREAD

**Issue by yangjie1993** [oliver006/redis_exporter#206]
![image](https://user-images.githubusercontent.com/18029405/49716181-e5c0b480-fc8d-11e8-86cc-a5a696e1437f.png)
hi @oliver006 
Is that because i just start up this demo，so i can not get any data？

**Comment by oliver006** [comment]
What's the result for `redis_up`? Is the exporter able to connect to the redis instance? And is Prometheus able to scrape the exporter?

**Comment by yangjie1993** [comment]
> What's the result for `redis_up`? Is the exporter able to connect to the redis instance? And is Prometheus able to scrape the exporter?

Firstly,thanks for answering

The exporter is able to connect to the redis instance,and also can scrape the exporter,at least i think so.
Here is the picture
![image](https://user-images.githubusercontent.com/18029405/49780697-a4420f00-fd4a-11e8-9ea1-75de7f36cbfa.png)

![image](https://user-images.githubusercontent.com/18029405/49780862-698ca680-fd4b-11e8-87c3-f20f62327f65.png)

And the grafana can also get most Redis metrics like this:

![image](https://user-images.githubusercontent.com/18029405/49780963-ba040400-fd4b-11e8-85db-8132fb46fa00.png)

![image](https://user-images.githubusercontent.com/18029405/49780967-bff9e500-fd4b-11e8-9fcf-0e9d597ecd4e.png)

except ‘Command Calls / sec’

I didn't actually use redis for now，i just start up a demo.

**Comment by oliver006** [comment]
Ok great, so at least the exporter is up and can scrape redis.

Hmm, but looking at this more, I think the dashboard needs updating, the metric name has changed to `redis_commands_call_duration_seconds_count` (note the extra `s`, it's commands now).

Can you try changing the query for that panel and see if the chart populates? If yes then I'l get the dashboard query fixed.

**Comment by yangjie1993** [comment]
> Ok great, so at least the exporter is up and can scrape redis.
> 
> Hmm, but looking at this more, I think the dashboard needs updating, the metric name has changed to `redis_commands_call_duration_seconds_count` (note the extra `s`, it's commands now).
> 
> Can you try changing the query for that panel and see if the chart populates? If yes then I'l get the dashboard query fixed.

....Hmm..i think the metric name is still wrong

i think it should be “redis_commands_duration_seconds_total”。。（ the extra ’s‘，and no ’count‘）

![image](https://user-images.githubusercontent.com/18029405/49841956-a2348a80-fdf4-11e8-9e5b-c3bf263d73a2.png)

![image](https://user-images.githubusercontent.com/18029405/49841962-a791d500-fdf4-11e8-9d06-178cc0414e35.png)

Is that right？

**Comment by acaligiuri** [comment]
Hi @oliver006,
I'm having trouble understanding how to calculate the average duration of a command from this thread, and the dashboard i just imported does not have it.

Are you saying i should be using this promQL:
irate(redis_commands_duration_seconds_total[1m])/irate(redis_commands_total[1m]) ?

**Comment by oliver006** [comment]
`redis_commands_duration_seconds_total / redis_commands_total` would be the number of seconds per command per command invocation.

**Comment by acaligiuri** [comment]
Sounds like what I’m looking for, but i was perplexed by the extremely low numbers I get (5us per get commands and 20us per set commands)
Those numbers are lower than what redis-benchmark —intrisic-latency is finding... up to 1000x lower

**Comment by oliver006** [comment]
Yeah, the numbers are quite small, even when you look at the output of `INFO ALL` in redis-cli:

```
# Commandstats
cmdstat_slowlog:calls=2,usec=16,usec_per_call=8.00
cmdstat_command:calls=4,usec=4526,usec_per_call=1131.50
cmdstat_latency:calls=1,usec=14,usec_per_call=14.00
cmdstat_config:calls=1,usec=252,usec_per_call=252.00
cmdstat_info:calls=3,usec=303,usec_per_call=101.00
cmdstat_get:calls=3,usec=39,usec_per_call=13.00
```

**Comment by SuperQ** [comment]
Use `rate()` not `irate()`, it will give you skewed numbers because it only takes the last two samples into account within your range.

Looking at my production data:
```
cmdstat_get:calls=9726083553,usec=36516132041,usec_per_call=3.75
cmdstat_set:calls=136144,usec=723030,usec_per_call=5.31
```

Looking at the graph query, everything looks correct:
![redis-latency-2019-07-09](https://user-images.githubusercontent.com/1320667/60877673-8edc8700-a23e-11e9-9c9c-946e77d47da3.png)
