### ISSUE TITLE
monitor remote redis，redis_up  is down

### ISSUE THREAD

**Issue by muzili1** [oliver006/redis_exporter#207]
I want to monitor remote redis(172.16.3.117:6379),the redis is up,but monitor redis_up is down.I don't kown   why?  
The Start command：
./redis_exporter -redis.addr 172.16.3.117:6379 &
The monitor data：
redis_exporter_build_info{build_date="2018-06-13-17:32:14",commit_sha="ce489e333b3a3d83422e48fb0988c2469441b966",golang_version="go1.9.4",version="v0.19.1"} 1
# HELP redis_exporter_last_scrape_duration_seconds The last scrape duration.
# TYPE redis_exporter_last_scrape_duration_seconds gauge
redis_exporter_last_scrape_duration_seconds 7.4062e-05
# HELP redis_exporter_last_scrape_error The last scrape error status.
# TYPE redis_exporter_last_scrape_error gauge
redis_exporter_last_scrape_error 1
# HELP redis_exporter_scrapes_total Current total redis scrapes.
# TYPE redis_exporter_scrapes_total counter
redis_exporter_scrapes_total 1735
# HELP redis_up 
# TYPE redis_up gauge
redis_up{addr="redis//172.16.3.117:6379",alias=""} 0

**Comment by oliver006** [comment]
Can you connect to the redis instance at `172.16.3.117:6379` from the host/pod that runs the exporter using telnet or redis-cli? 
Is there any more console output from the exporter?

**Comment by muzili1** [comment]
Hi,I tried to connect remotely to redis at 172.16.3.117:6379,I failed,and then I modified redis.conf,I can connect to the redis at 172.16.3.117:6379.The monitor is normal.Thank you very much.

**Comment by oliver006** [comment]
Good to hear you figured it out!
