### ISSUE TITLE
Memory Usage grafana dashboard shows N/A

### ISSUE THREAD

**Issue by shinebayar-g** [oliver006/redis_exporter#212]
Hi, thanks for exporter. In my grafana, only 1 dashboard is not working as expected.
I've installed redis through stable [helm chart](https://github.com/helm/charts/tree/master/stable/redis) and currently using exporter version v0.20.2 (it was default on helm chart).
![image](https://user-images.githubusercontent.com/3091558/50050999-1b5d1600-0144-11e9-8fd6-ee081eb915ef.png)

As you see on the picture, my **Memory Usage** shows **N/A**

How can I fix it? Used metrics:
`redis_memory_used_bytes` , `redis_config_maxmemory` is available. I think its formula is not correct.

Used formula:
```
100 * (redis_memory_used_bytes{addr=~"$addr"}  / redis_config_maxmemory{addr=~"$addr"} )
```

**Comment by oliver006** [comment]
Hey there. Can you check that both metrics `redis_memory_used_bytes` and `redis_config_maxmemory` return data as expected? In particular, `redis_config_maxmemory` might be zero if no maximum was configured.

**Comment by shinebayar-g** [comment]
`redis_memory_used_bytes` in prometheus returns:
![image](https://user-images.githubusercontent.com/3091558/50091377-2c8e4b80-0246-11e9-81aa-b12df86bdb42.png)

`redis_config_maxmemory` in prometheus returns:
![image](https://user-images.githubusercontent.com/3091558/50091385-3617b380-0246-11e9-906e-97bb18a008dc.png)

**Comment by oliver006** [comment]
Looks like you found the culprit. `redis_config_maxmemory` is zero so you can't calculate the percentage of used memory --> the panel ends up being N/A

**Comment by BurningDog** [comment]
I also had this problem, using the https://grafana.com/grafana/dashboards/11835-redis-dashboard-for-prometheus-redis-exporter-helm-stable-redis-ha/ dashboard.

In this dashboard's case, the memory calculation is:

```
100 * (redis_memory_used_bytes{instance=~"$instance"}  / redis_memory_max_bytes{instance=~"$instance"} )
```

Looking the `redis_memory_max_bytes` they were all 0. 

Running `INFO` via the redis cli shows this:

```
maxmemory:0
maxmemory_human:0B
```

This means that Redis has been configured (by default, in my case, using the `redis:alpine` docker image) to have no maximum memory set - meaning that the Grafana graph can never show a percentage of memory use.

If you want to set a maximum memory value for redis, edit `redis.conf` and find the line `# maxmemory <bytes>` then set your value.
