### ISSUE TITLE
rdb_last_bgsave_status disappears when there's an error

### ISSUE THREAD

**Issue by Supermathie** [oliver006/redis_exporter#213]
I just tested out v0.21.2 and discovered that `rdb_last_bgsave_status` doesn't actually work as (I) expected… when a problem occurs the metric **disappears** instead of changing to `0`:

\*triggers the problem*

```text
127.0.0.1:6379> info persistence
…
rdb_last_bgsave_status:err

supermathie@redis-replica: ~ $ curl -s 172.17.0.5:9121/metrics | grep bgsave_status
(no output)
```

\*fixes problem*

```text
127.0.0.1:6379> info persistence
…
rdb_last_bgsave_status:ok

supermathie@redis-replica: ~ $ curl -s 172.17.0.5:9121/metrics | grep bgsave_status
# HELP redis_rdb_last_bgsave_status rdb_last_bgsave_statusmetric
# TYPE redis_rdb_last_bgsave_status gauge
redis_rdb_last_bgsave_status{addr="127.0.0.1:6379",alias=""} 1
```

_Originally posted by @Supermathie in https://github.com/oliver006/redis_exporter/pull/188#issuecomment-447893461_

**Comment by oliver006** [comment]
Thanks for reporting this, I think the problem is due to this line here:

https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L600

it should include a check for `"err"` and set `val` to zero instead of falling back to the default case and try to parse the string as a float.

**Comment by oliver006** [comment]
@Supermathie - can you give https://github.com/oliver006/redis_exporter/releases/tag/v0.24.0 a shot and see if that fixes the issue?

**Comment by Supermathie** [comment]
Worked for me! Thanks.
