### ISSUE TITLE
Command Calls / sec no data points

### ISSUE THREAD

**Issue by liu-yfeng** [oliver006/redis_exporter#215]
environment：
docker Redis Exporter v0.24.0
https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json use this dashboard json file
![image](https://user-images.githubusercontent.com/8706840/50269691-0f39c700-046a-11e9-8440-acfca4771738.png)
![image](https://user-images.githubusercontent.com/8706840/50269808-7ce5f300-046a-11e9-92f3-a0d27aa8b67e.png)
![image](https://user-images.githubusercontent.com/8706840/50269823-88d1b500-046a-11e9-8f1b-2e64b3faf9a1.png)
![image](https://user-images.githubusercontent.com/8706840/50269863-a9017400-046a-11e9-9add-524daceb9657.png)
![image](https://user-images.githubusercontent.com/8706840/50273348-61341a00-0475-11e9-871a-d1ede1affdec.png)

![image](https://user-images.githubusercontent.com/8706840/50269843-9850fe00-046a-11e9-9535-8570ab03b3a4.png)

hope you help,thanks

**Comment by oliver006** [comment]
Looks like you have data for `redis_commands_total` but no graph.
I just verified, the dashboard works for me.

What's `$addr` when the data is requested? Is it 192,168.2.71:9121 ? Grafana has a query inspector, that gives you more insights as to what exactly is requested.

Is this the same issue you raised in #201 ? Can we close that ticket and continue the conversation here?

**Comment by liu-yfeng** [comment]
I changed the prometheus version and it is now working.

I used to use percona's pmm-server, but I don't know why it doesn't work properly on this.

**Comment by oliver006** [comment]
Ah ok. I'm not familiar with the Percona pmm-server so not sure what's different.

Please re-open the issue if the problem comes back.

**Comment by kcoderk** [comment]
I Change the metric "redis_commands_total" to "redis_commands_processed_total",It Works
