### ISSUE TITLE
help:please add support /bin/sh -c /bin/redis_exporter -redis.addr=redis://localhost:6379 on  the oliver006/redis_exporter lastest version

### ISSUE THREAD

**Issue by dw130** [oliver006/redis_exporter#216]
help:
          please add support /bin/sh -c /bin/redis_exporter -redis.addr=redis://localhost:6379 on  the oliver006/redis_exporter lastest version

'''
the lastest oliver006/redis_exporter on dockerhub does not support /bin/sh -c /bin/redis_exporter -redis.addr=redis://localhost:6379
 
Tags (43)
latest 3 MB
Last update: 2 days ago
'''

as I have use the lastest  exporter version in my k8s statefulset
'''
      - args:
        - /bin/redis_exporter -redis.addr=redis://localhost:6379
        command:
        - /bin/sh
        - -c
        image: oliver006/redis_exporter
        imagePullPolicy: Always
''' 
once erea /bin/sh -c from my redis-statefulset will cause a redis restart, but restarting redis is not allowed

please help and support  /bin/sh -c in the lastest version of oliver006/redis_exporter

**Comment by dw130** [comment]
@oliver006

**Comment by oliver006** [comment]
Hey there,

why do you need `/bin/sh` and don't just run `/bin/redis_exporter -redis.addr=redis://localhost:6379` directly?

**Comment by mdawar** [comment]
Is there any possibility that you provide another image based on Alpine just like the older one, that would great and users can choose which version to use, me too I use the shell inside the container for environment variable interpolation, for example I set the container environment variables and use them as `redis_exporter` flags, also I use `$(cat /run/secrets/redis_auth)` to get the Redis password from a [secret](https://docs.docker.com/engine/swarm/secrets/), another use case is using `exec` with an interactive shell which is not possible in the latest version.

**Comment by oliver006** [comment]
Thanks to @mdawar there's no also a alpine image and you should be able to try `oliver006/redis_exporter:v0.26.0-alpine` (or simply `:alpine`) and that docker image should have the `/bin/sh` in it.
@dw130 - let me know if that fixes the issue for you.

**Comment by oliver006** [comment]
Closing this, please re-open if this is still an issue.
