### ISSUE TITLE
script metric support custom attribute

### ISSUE THREAD

**Issue by redzippo1** [oliver006/redis_exporter#223]
Now script metric only support one custom attribute named "key", I think coustom attribute maybe butter.

**now:**
`redis_script_value{addr="192.168.1.1:8382",alias="GupF7nVK",key="some value"} 1`

**hope**
`redis_script_value{addr="192.168.1.1:8382",alias="GupF7nVK",key_prefix="man_",key_end="_age",rule="max"} 18`

**Comment by oliver006** [comment]
Circling back here and I'm not sure I understand what you mean by `custom attribute` - can you explain a bit more?
