### ISSUE TITLE
Chinese characters garbled

### ISSUE THREAD

**Issue by Mrzhangxd** [oliver006/redis_exporter#226]
when I use Chinese characters in aliases，Web page garbled
![image](https://user-images.githubusercontent.com/16274179/51302529-9ed49480-1a6d-11e9-92f9-e1e77522cb3f.png)
![1.png](https://i.loli.net/2019/01/17/5c40308c03a75.png)

**Comment by oliver006** [comment]
`Web page garbled` - what web page is garbled?
