### ISSUE TITLE
check key

### ISSUE THREAD

**Issue by azagirov** [oliver006/redis_exporter#227]
Hello.

My redis exporter run command:
/usr/local/bin/redis_exporter --check-single-keys="mail_queue,mail-sec" --web.listen-address=127.0.0.1:9112
For mail_queue key I look only redis_key_size metric. 
Can I get the queue length from redis_exporter? I can't find this metric.
127.0.0.1:6379> LLEN mail_queue
(integer) 25

**Comment by oliver006** [comment]
Hey there,

what type is `mail_queue`? Is it type `list`? 

And what's the output of `curl -s "127.0.0.1:9112/metrics" | grep redis_key_size` and `curl -s "127.0.0.1:9112/metrics" | grep redis_up` ?

**Comment by azagirov** [comment]
I understand.
if ```mail_queue``` is empty type ```none```, if not empty type ```list```.
And if not empty, ```redis_key_size``` write correct key length.
I close issue, thanks.
