### ISSUE TITLE
Charts doesn't work when running redis_exporter under docker

### ISSUE THREAD

**Issue by arnoldasb** [oliver006/redis_exporter#230]
I needed to run docker container with local network so exporter is able to see redis running on default localhost:6379

docker run -d --name redis_exporter **--network host** oliver006/redis_exporter

**Comment by oliver006** [comment]
Thanks, that's good to know, I'll add this to the documentation when I have a moment.

**Comment by oliver006** [comment]
Added via https://github.com/oliver006/redis_exporter/commit/2e64b0f9a32cdf9cb3ae5a0e5260952ee24ef53b
