### ISSUE TITLE
IPv6 address in redis output breaks parsing

### ISSUE THREAD

**Issue by jobec** [oliver006/redis_exporter#242]
When there's an IPv6 address in the output of Redis, the line is skipped, resulting in missing metrics.

For example:
```
slave0:ip=2a00:1450:400e:808::200e,port=6379,state=online,offset=9694740951,lag=1
```
This line will never be handled.

Line of code causing this:
https://github.com/oliver006/redis_exporter/blob/e3f43cfe305f8d20d931de6eb84e32c664b7edd1/exporter/redis.go#L627-L630

**Comment by oliver006** [comment]
Nice catch, an IP6 address indeed would break how the line is currently split.
