### ISSUE TITLE
Request for precompiled binary

### ISSUE THREAD

**Issue by kormotodor** [oliver006/redis_exporter#244]
Would you place the precompiled binary in assests section for the [latest](https://github.com/oliver006/redis_exporter/releases/tag/v0.31.0) release? Like in other previous releases, it will very usefull, thank you.

**Comment by oliver006** [comment]
Sorry about that, trying to fix this right now. I broke this as part of #238 when switching the CI/CD to drone.

**Comment by oliver006** [comment]
Binaries are back, see https://github.com/oliver006/redis_exporter/releases/tag/v0.32.0

cc: @jobec
