### ISSUE TITLE
Can't get the metrics of redis queue length 

### ISSUE THREAD

**Issue by devils-ey3** [oliver006/redis_exporter#248]
I need to scrape how many queue in my redis, but can't find anything. 
Is **redis_db_keys** metrics provide the queue length of redis ?

**Comment by oliver006** [comment]
Hey there. I understand you right that you want to monitor the depth/number of items in a queue?
What redis structure are you using for the queue? Are you using a list? In that case, you should be able to use the name of the list in redis as a check-key argument and the exporter should gather and export the number of items in that list.

**Comment by devils-ey3** [comment]
@oliver006 I saw [this](https://github.com/oliver006/redis_exporter/issues/51#issue-205665671) sample code for enable check-key flag, but i haven't got anything special, can you give me any example code ? I am using redis_exporter with docker

**Comment by devils-ey3** [comment]
@oliver006 I figure out redis_db_keys is the queue, I was confused because my application redis structure queue is fixed, I test other application and it give true result. Thanks for your help.

**Comment by balathati** [comment]
@oliver006 I didn't see a queue length ex: when I perform scan 0
1) "1"
2)  1) "A-default"
    2) "_kombu.binding.A1"
    3) "A2"
    4) "A3"
    5) "A4"
    6) "A5"
    7) "A6"

now I need to know how many messages on A2 or A6 
maybe A2 when I put 3 messages I should get A2=3 but A2 one celery worker processed 1 message now A2 should get A2=2, is anything like that will I get from current exporter?
Thanks.
