### ISSUE TITLE
'redis.password-file' relies on the separator.

### ISSUE THREAD

**Issue by kubiak95** [oliver006/redis_exporter#258]
Let's say my password file looks like this:

/etc/secure_password:
> VeryS3curePassword

when I run:

**redis-exporter -redis.password-file /etc/secure_password -debug**

One of the messages I get back is:
**DialURL() failed, err: ERR invalid password**

Once I change my password to include the default separator "," :

/etc/secure_password:
> VeryS3curePassword,

redis-exporter authenticates successfully and works as intended. I don't think **redis.password-file** should rely on the separator, it should be a 'one for all' type of file. In an environment where multiple applications refer to the same password file, this is rather inconvenient. If one wants to set per-node passwords, **redis.file** already serves that purpose.

**Comment by oliver006** [comment]
I agree, this shouldn't happen and definitely looks like a bug.
However, looking at the code, this shouldn't happen (see line 19 of discovery.go - it simply splits it and if password doesn't include separator it should simply return password).
Is it possible your possible your password file includes/ends with "\r\n" or similar?

**Comment by kubiak95** [comment]
I checked with **cat -A** to show all characters, and there are no extra characters other than **$** at the end which is a line ending symbol used in Linux.

**Comment by oliver006** [comment]
What does `hexdump` show?

**Comment by kubiak95** [comment]
The file ends with a linefeed value, here's an excerpt:

00000010  73 34 64 **0a**

**Comment by oliver006** [comment]
I guess you found the culprit.

**Comment by kubiak95** [comment]
Actually this is another reason to think it's a bug. Single **0a** at the end is the expected result, every standard ASCII text file ends this way and there is nothing wrong with that. Redis, and anything else I can throw at my password file parses it correctly.

**Comment by oliver006** [comment]
I see. This looks like a bug.
I think a `strings.TrimSpace()` should solve the problem, let me open a PR to get this addressed.

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v0.34.1
