### ISSUE TITLE
keys-checks with ':'

### ISSUE THREAD

**Issue by mfouilleul** [oliver006/redis_exporter#26]
Hello,

It seams that the key-check feature doesn't work with keys with ':' in the name, example "cntr:flood". 

Max.

**Comment by oliver006** [comment]
Ah yes, it uses `:` to separate `db##:keyName`.

Here's an idea, the exporter will expect the key to urlencoded so in your case it would be `cntr%3aflood` and `:` will continue to be the separator.
Would that work?

**Comment by oliver006** [comment]
See PR #27
