### ISSUE TITLE
What classes need to be modified to support Codis monitoring?（Acquisition method：dashboard restful api）

### ISSUE THREAD

**Issue by SenLinLeo** [oliver006/redis_exporter#267]
The following metrics are available in the metrics interface.However, as not shown in Grafana, the forecast is that Prometheus is stored without scheduled polling.Don't know how to change?

Part of the code:
`
buildCodis := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "codis_exporter_build_info",
		Help: "codis exporter build_info",
}, []string{"addr", "alias"})
buildCodis.WithLabelValues("192.32.61.178:19000", "").Set(result.Sessions.Total)
``

interface `data(http://192.32.61.178:9121/metrics):
`
_# HELP codis_exporter_build_info codis exporter build_info
_# TYPE codis_exporter_build_info gauge_
codis_exporter_build_info{addr="192.32.61.178:19000",alias=""} 655
codis_exporter_build_info{addr="192.32.61.179:19000",alias=""} 655
`

**Comment by oliver006** [comment]
I'm not sure what Codis or the codis_exporter is that you talk about.

However, it looks like your code is using `addr` and `alias1 labels which were all made obsolete by PR #256 so if you use redis_exporter 1.0.0 and an older version of your exporter then mixing the metrics will not work and your Grafana dashboard will be broken.
