### ISSUE TITLE
In release build missing Cluster data

### ISSUE THREAD

**Issue by michalss** [oliver006/redis_exporter#273]
Dear dev,

I just found out that in your latest release build missing all cluster data information. I dont want to build it from source can you please include this data in main release batch ?

Thx

**Comment by oliver006** [comment]
What exactly is it that you're missing? Clustering information should still be available, that didn't change with the release of v1.0.0

**Comment by michalss** [comment]
Nope i when i take your older builds all is there but with this version from 1.0.0 missing lots of metrics..

**Comment by oliver006** [comment]
That's not good :-/

What's an example for a metric that's missing?

**Comment by michalss** [comment]
With your older versions im getting this :

`# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.2592e-05
go_gc_duration_seconds{quantile="0.25"} 1.973e-05
go_gc_duration_seconds{quantile="0.5"} 2.4642e-05
go_gc_duration_seconds{quantile="0.75"} 4.7404e-05
go_gc_duration_seconds{quantile="1"} 0.000631716
go_gc_duration_seconds_sum 0.004480192
go_gc_duration_seconds_count 82
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 7
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.12.5"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.668976e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.04043128e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 732276
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 1.293892e+06
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 1.4943080246530325e-06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 739328
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.668976e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 4.34176e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.424256e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 15879
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 4.17792e+06
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.766016e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.560349590986833e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 1.309771e+06
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 3472
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 18832
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 32768
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.300488e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 622592
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 622592
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.1209852e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 9
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1.28
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 7.589888e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.56033891946e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 8.21870592e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 198
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP redis_allocator_active_bytes allocator_active_bytesmetric
# TYPE redis_allocator_active_bytes gauge
redis_allocator_active_bytes{addr="redis://localhost:6379",alias=""} 4.672065536e+09
# HELP redis_allocator_allocated_bytes allocator_allocated_bytesmetric
# TYPE redis_allocator_allocated_bytes gauge
redis_allocator_allocated_bytes{addr="redis://localhost:6379",alias=""} 4.28874308e+09
# HELP redis_allocator_resident_bytes allocator_resident_bytesmetric
# TYPE redis_allocator_resident_bytes gauge
redis_allocator_resident_bytes{addr="redis://localhost:6379",alias=""} 4.7440896e+09
# HELP redis_aof_current_rewrite_duration_sec aof_current_rewrite_duration_secmetric
# TYPE redis_aof_current_rewrite_duration_sec gauge
redis_aof_current_rewrite_duration_sec{addr="redis://localhost:6379",alias=""} -1
# HELP redis_aof_enabled aof_enabledmetric
# TYPE redis_aof_enabled gauge
redis_aof_enabled{addr="redis://localhost:6379",alias=""} 0
# HELP redis_aof_last_bgrewrite_status aof_last_bgrewrite_statusmetric
# TYPE redis_aof_last_bgrewrite_status gauge
redis_aof_last_bgrewrite_status{addr="redis://localhost:6379",alias=""} 1
# HELP redis_aof_last_cow_size_bytes aof_last_cow_size_bytesmetric
# TYPE redis_aof_last_cow_size_bytes gauge
redis_aof_last_cow_size_bytes{addr="redis://localhost:6379",alias=""} 0
# HELP redis_aof_last_rewrite_duration_sec aof_last_rewrite_duration_secmetric
# TYPE redis_aof_last_rewrite_duration_sec gauge
redis_aof_last_rewrite_duration_sec{addr="redis://localhost:6379",alias=""} -1
# HELP redis_aof_last_write_status aof_last_write_statusmetric
# TYPE redis_aof_last_write_status gauge
redis_aof_last_write_status{addr="redis://localhost:6379",alias=""} 1
# HELP redis_aof_rewrite_in_progress aof_rewrite_in_progressmetric
# TYPE redis_aof_rewrite_in_progress gauge
redis_aof_rewrite_in_progress{addr="redis://localhost:6379",alias=""} 0
# HELP redis_aof_rewrite_scheduled aof_rewrite_scheduledmetric
# TYPE redis_aof_rewrite_scheduled gauge
redis_aof_rewrite_scheduled{addr="redis://localhost:6379",alias=""} 0
# HELP redis_blocked_clients blocked_clientsmetric
# TYPE redis_blocked_clients gauge
redis_blocked_clients{addr="redis://localhost:6379",alias=""} 0
# HELP redis_cluster_current_epoch cluster_current_epochmetric
# TYPE redis_cluster_current_epoch gauge
redis_cluster_current_epoch{addr="redis://localhost:6379",alias=""} 6
# HELP redis_cluster_enabled cluster_enabledmetric
# TYPE redis_cluster_enabled gauge
redis_cluster_enabled{addr="redis://localhost:6379",alias=""} 1
# HELP redis_cluster_known_nodes cluster_known_nodesmetric
# TYPE redis_cluster_known_nodes gauge
redis_cluster_known_nodes{addr="redis://localhost:6379",alias=""} 6
# HELP redis_cluster_messages_received_total cluster_messages_received_totalmetric
# TYPE redis_cluster_messages_received_total gauge
redis_cluster_messages_received_total{addr="redis://localhost:6379",alias=""} 2.138125e+06
# HELP redis_cluster_messages_sent_total cluster_messages_sent_totalmetric
# TYPE redis_cluster_messages_sent_total gauge
redis_cluster_messages_sent_total{addr="redis://localhost:6379",alias=""} 2.138127e+06
# HELP redis_cluster_my_epoch cluster_my_epochmetric
# TYPE redis_cluster_my_epoch gauge
redis_cluster_my_epoch{addr="redis://localhost:6379",alias=""} 2
# HELP redis_cluster_size cluster_sizemetric
# TYPE redis_cluster_size gauge
redis_cluster_size{addr="redis://localhost:6379",alias=""} 3
# HELP redis_cluster_slots_assigned cluster_slots_assignedmetric
# TYPE redis_cluster_slots_assigned gauge
redis_cluster_slots_assigned{addr="redis://localhost:6379",alias=""} 16384
# HELP redis_cluster_slots_fail cluster_slots_failmetric
# TYPE redis_cluster_slots_fail gauge
redis_cluster_slots_fail{addr="redis://localhost:6379",alias=""} 0
# HELP redis_cluster_slots_ok cluster_slots_okmetric
# TYPE redis_cluster_slots_ok gauge
redis_cluster_slots_ok{addr="redis://localhost:6379",alias=""} 16384
# HELP redis_cluster_slots_pfail cluster_slots_pfailmetric
# TYPE redis_cluster_slots_pfail gauge
redis_cluster_slots_pfail{addr="redis://localhost:6379",alias=""} 0
# HELP redis_cluster_state cluster_statemetric
# TYPE redis_cluster_state gauge
redis_cluster_state{addr="redis://localhost:6379",alias=""} 1
# HELP redis_cluster_stats_messages_ping_received cluster_stats_messages_ping_receivedmetric
# TYPE redis_cluster_stats_messages_ping_received gauge
redis_cluster_stats_messages_ping_received{addr="redis://localhost:6379",alias=""} 1.052618e+06
# HELP redis_cluster_stats_messages_ping_sent cluster_stats_messages_ping_sentmetric
# TYPE redis_cluster_stats_messages_ping_sent gauge
redis_cluster_stats_messages_ping_sent{addr="redis://localhost:6379",alias=""} 1.085509e+06
# HELP redis_cluster_stats_messages_pong_received cluster_stats_messages_pong_receivedmetric
# TYPE redis_cluster_stats_messages_pong_received gauge
redis_cluster_stats_messages_pong_received{addr="redis://localhost:6379",alias=""} 1.085507e+06
# HELP redis_cluster_stats_messages_pong_sent cluster_stats_messages_pong_sentmetric
# TYPE redis_cluster_stats_messages_pong_sent gauge
redis_cluster_stats_messages_pong_sent{addr="redis://localhost:6379",alias=""} 1.052618e+06
# HELP redis_commands_duration_seconds_total Total amount of time in seconds spent per command
# TYPE redis_commands_duration_seconds_total gauge
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="client"} 0.000314
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="cluster"} 0.033608
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="config"} 0.01815
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="del"} 501.15886
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="echo"} 5e-05
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="get"} 550.851177
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="hmset"} 0.043165
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="info"} 1.709648
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="latency"} 0.000832
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="ping"} 0.076053
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="readonly"} 4.3e-05
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="select"} 2.5e-05
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="set"} 16.339844
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="setex"} 413.16023
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="slowlog"} 0.002168
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="subscribe"} 0.00017
redis_commands_duration_seconds_total{addr="redis://localhost:6379",alias="",cmd="unlink"} 60.189522
# HELP redis_commands_processed_total commands_processed_totalmetric
# TYPE redis_commands_processed_total gauge
redis_commands_processed_total{addr="redis://localhost:6379",alias=""} 1.93065528e+08
# HELP redis_commands_total Total number of calls per command
# TYPE redis_commands_total gauge
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="client"} 93
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="cluster"} 260
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="config"} 385
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="del"} 2.3356927e+07
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="echo"} 93
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="get"} 1.34944828e+08
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="hmset"} 264
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="info"} 55780
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="latency"} 198
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="ping"} 81267
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="readonly"} 65
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="select"} 1
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="set"} 948062
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="setex"} 3.0271817e+07
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="slowlog"} 396
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="subscribe"} 31
redis_commands_total{addr="redis://localhost:6379",alias="",cmd="unlink"} 3.405061e+06
# HELP redis_config_maxclients config_maxclientsmetric
# TYPE redis_config_maxclients gauge
redis_config_maxclients{addr="redis://localhost:6379",alias=""} 10000
# HELP redis_config_maxmemory config_maxmemorymetric
# TYPE redis_config_maxmemory gauge
redis_config_maxmemory{addr="redis://localhost:6379",alias=""} 0
# HELP redis_connected_clients connected_clientsmetric
# TYPE redis_connected_clients gauge
redis_connected_clients{addr="redis://localhost:6379",alias=""} 44
# HELP redis_connected_slaves connected_slavesmetric
# TYPE redis_connected_slaves gauge
redis_connected_slaves{addr="redis://localhost:6379",alias=""} 0
# HELP redis_connections_received_total connections_received_totalmetric
# TYPE redis_connections_received_total gauge
redis_connections_received_total{addr="redis://localhost:6379",alias=""} 292
# HELP redis_db_avg_ttl_seconds Avg TTL in seconds
# TYPE redis_db_avg_ttl_seconds gauge
redis_db_avg_ttl_seconds{addr="redis://localhost:6379",alias="",db="db0"} 0
# HELP redis_db_keys Total number of keys by DB
# TYPE redis_db_keys gauge
redis_db_keys{addr="redis://localhost:6379",alias="",db="db0"} 3.979713e+06
# HELP redis_db_keys_expiring Total number of expiring keys by DB
# TYPE redis_db_keys_expiring gauge
redis_db_keys_expiring{addr="redis://localhost:6379",alias="",db="db0"} 3.633401e+06
# HELP redis_evicted_keys_total evicted_keys_totalmetric
# TYPE redis_evicted_keys_total gauge
redis_evicted_keys_total{addr="redis://localhost:6379",alias=""} 0
# HELP redis_expired_keys_total expired_keys_totalmetric
# TYPE redis_expired_keys_total gauge
redis_expired_keys_total{addr="redis://localhost:6379",alias=""} 0
# HELP redis_exporter_build_info redis exporter build_info
# TYPE redis_exporter_build_info gauge
redis_exporter_build_info{build_date="2019-05-09-15:42:21",commit_sha="1c168d07eff09e64efb18600a35664d6666926e6",golang_version="go1.12.5",version="v0.34.1"} 1
# HELP redis_exporter_last_scrape_duration_seconds The last scrape duration.
# TYPE redis_exporter_last_scrape_duration_seconds gauge
redis_exporter_last_scrape_duration_seconds 0.002949779
# HELP redis_exporter_last_scrape_error The last scrape error status.
# TYPE redis_exporter_last_scrape_error gauge
redis_exporter_last_scrape_error 0
# HELP redis_exporter_scrapes_total Current total redis scrapes.
# TYPE redis_exporter_scrapes_total counter
redis_exporter_scrapes_total 199
# HELP redis_instance_info Information about the Redis instance
# TYPE redis_instance_info gauge
redis_instance_info{addr="redis://localhost:6379",alias="",os="Linux 3.10.0-862.11.6.el7.x86_64 x86_64",redis_build_id="619d60bfb0a92c36",redis_mode="cluster",redis_version="5.0.5",role="slave"} 1
# HELP redis_instantaneous_input_kbps instantaneous_input_kbpsmetric
# TYPE redis_instantaneous_input_kbps gauge
redis_instantaneous_input_kbps{addr="redis://localhost:6379",alias=""} 256.27
# HELP redis_instantaneous_ops_per_sec instantaneous_ops_per_secmetric
# TYPE redis_instantaneous_ops_per_sec gauge
redis_instantaneous_ops_per_sec{addr="redis://localhost:6379",alias=""} 2092
# HELP redis_instantaneous_output_kbps instantaneous_output_kbpsmetric
# TYPE redis_instantaneous_output_kbps gauge
redis_instantaneous_output_kbps{addr="redis://localhost:6379",alias=""} 1778.33
# HELP redis_keyspace_hits_total keyspace_hits_totalmetric
# TYPE redis_keyspace_hits_total gauge
redis_keyspace_hits_total{addr="redis://localhost:6379",alias=""} 1.03701886e+08
# HELP redis_keyspace_misses_total keyspace_misses_totalmetric
# TYPE redis_keyspace_misses_total gauge
redis_keyspace_misses_total{addr="redis://localhost:6379",alias=""} 3.1242942e+07
# HELP redis_last_slow_execution_duration_seconds The amount of time needed for last slow execution, in seconds
# TYPE redis_last_slow_execution_duration_seconds gauge
redis_last_slow_execution_duration_seconds{addr="redis://localhost:6379",alias=""} 0.013707
# HELP redis_latency_spike_last When the latency spike last occurred
# TYPE redis_latency_spike_last gauge
redis_latency_spike_last{addr="redis://localhost:6379",alias="",event_name="fork"} 1.560349517e+09
# HELP redis_latency_spike_milliseconds Length of the last latency spike in milliseconds
# TYPE redis_latency_spike_milliseconds gauge
redis_latency_spike_milliseconds{addr="redis://localhost:6379",alias="",event_name="fork"} 111
# HELP redis_latest_fork_usec latest_fork_usecmetric
# TYPE redis_latest_fork_usec gauge
redis_latest_fork_usec{addr="redis://localhost:6379",alias=""} 92621
# HELP redis_loading_dump_file loading_dump_filemetric
# TYPE redis_loading_dump_file gauge
redis_loading_dump_file{addr="redis://localhost:6379",alias=""} 0
# HELP redis_master_last_io_seconds master_last_io_secondsmetric
# TYPE redis_master_last_io_seconds gauge
redis_master_last_io_seconds{addr="redis://localhost:6379",alias=""} 0
# HELP redis_master_link_up Master link status on Redis slave
# TYPE redis_master_link_up gauge
redis_master_link_up{addr="redis://localhost:6379",alias=""} 1
# HELP redis_master_repl_offset master_repl_offsetmetric
# TYPE redis_master_repl_offset gauge
redis_master_repl_offset{addr="redis://localhost:6379",alias=""} 2.5701063279e+10
# HELP redis_memory_max_bytes memory_max_bytesmetric
# TYPE redis_memory_max_bytes gauge
redis_memory_max_bytes{addr="redis://localhost:6379",alias=""} 0
# HELP redis_memory_used_bytes memory_used_bytesmetric
# TYPE redis_memory_used_bytes gauge
redis_memory_used_bytes{addr="redis://localhost:6379",alias=""} 4.288629024e+09
# HELP redis_memory_used_lua_bytes memory_used_lua_bytesmetric
# TYPE redis_memory_used_lua_bytes gauge
redis_memory_used_lua_bytes{addr="redis://localhost:6379",alias=""} 37888
# HELP redis_memory_used_peak_bytes memory_used_peak_bytesmetric
# TYPE redis_memory_used_peak_bytes gauge
redis_memory_used_peak_bytes{addr="redis://localhost:6379",alias=""} 4.608622216e+09
# HELP redis_memory_used_rss_bytes memory_used_rss_bytesmetric
# TYPE redis_memory_used_rss_bytes gauge
redis_memory_used_rss_bytes{addr="redis://localhost:6379",alias=""} 4.7414272e+09
# HELP redis_net_input_bytes_total net_input_bytes_totalmetric
# TYPE redis_net_input_bytes_total gauge
redis_net_input_bytes_total{addr="redis://localhost:6379",alias=""} 3.2846562664e+10
# HELP redis_net_output_bytes_total net_output_bytes_totalmetric
# TYPE redis_net_output_bytes_total gauge
redis_net_output_bytes_total{addr="redis://localhost:6379",alias=""} 1.56158752671e+11
# HELP redis_process_id process_idmetric
# TYPE redis_process_id gauge
redis_process_id{addr="redis://localhost:6379",alias=""} 13692
# HELP redis_pubsub_channels pubsub_channelsmetric
# TYPE redis_pubsub_channels gauge
redis_pubsub_channels{addr="redis://localhost:6379",alias=""} 1
# HELP redis_pubsub_patterns pubsub_patternsmetric
# TYPE redis_pubsub_patterns gauge
redis_pubsub_patterns{addr="redis://localhost:6379",alias=""} 0
# HELP redis_rdb_bgsave_in_progress rdb_bgsave_in_progressmetric
# TYPE redis_rdb_bgsave_in_progress gauge
redis_rdb_bgsave_in_progress{addr="redis://localhost:6379",alias=""} 0
# HELP redis_rdb_changes_since_last_save rdb_changes_since_last_savemetric
# TYPE redis_rdb_changes_since_last_save gauge
redis_rdb_changes_since_last_save{addr="redis://localhost:6379",alias=""} 43909
# HELP redis_rdb_current_bgsave_duration_sec rdb_current_bgsave_duration_secmetric
# TYPE redis_rdb_current_bgsave_duration_sec gauge
redis_rdb_current_bgsave_duration_sec{addr="redis://localhost:6379",alias=""} -1
# HELP redis_rdb_last_bgsave_duration_sec rdb_last_bgsave_duration_secmetric
# TYPE redis_rdb_last_bgsave_duration_sec gauge
redis_rdb_last_bgsave_duration_sec{addr="redis://localhost:6379",alias=""} 32
# HELP redis_rdb_last_bgsave_status rdb_last_bgsave_statusmetric
# TYPE redis_rdb_last_bgsave_status gauge
redis_rdb_last_bgsave_status{addr="redis://localhost:6379",alias=""} 1
# HELP redis_rdb_last_cow_size_bytes rdb_last_cow_size_bytesmetric
# TYPE redis_rdb_last_cow_size_bytes gauge
redis_rdb_last_cow_size_bytes{addr="redis://localhost:6379",alias=""} 3.44539136e+08
# HELP redis_rdb_last_save_timestamp_seconds rdb_last_save_timestamp_secondsmetric
# TYPE redis_rdb_last_save_timestamp_seconds gauge
redis_rdb_last_save_timestamp_seconds{addr="redis://localhost:6379",alias=""} 1.560349642e+09
# HELP redis_rejected_connections_total rejected_connections_totalmetric
# TYPE redis_rejected_connections_total gauge
redis_rejected_connections_total{addr="redis://localhost:6379",alias=""} 0
# HELP redis_replication_backlog_bytes replication_backlog_bytesmetric
# TYPE redis_replication_backlog_bytes gauge
redis_replication_backlog_bytes{addr="redis://localhost:6379",alias=""} 1.048576e+06
# HELP redis_slave_info Information about the Redis slave
# TYPE redis_slave_info gauge
redis_slave_info{addr="redis://localhost:6379",alias="",master_host="192.168.1.121",master_port="6379",read_only="1"} 1
# HELP redis_slowlog_last_id Last id of slowlog
# TYPE redis_slowlog_last_id gauge
redis_slowlog_last_id{addr="redis://localhost:6379",alias=""} 230
# HELP redis_slowlog_length Total slowlog
# TYPE redis_slowlog_length gauge
redis_slowlog_length{addr="redis://localhost:6379",alias=""} 128
# HELP redis_start_time_seconds Start time of the Redis instance since unix epoch in seconds.
# TYPE redis_start_time_seconds gauge
redis_start_time_seconds{addr="redis://localhost:6379",alias=""} 1.559813891e+09
# HELP redis_total_system_memory_bytes total_system_memory_bytesmetric
# TYPE redis_total_system_memory_bytes gauge
redis_total_system_memory_bytes{addr="redis://localhost:6379",alias=""} 1.6639901696e+10
# HELP redis_up upmetric
# TYPE redis_up gauge
redis_up{addr="redis://localhost:6379",alias=""} 1
# HELP redis_uptime_in_seconds uptime_in_secondsmetric
# TYPE redis_uptime_in_seconds gauge
redis_uptime_in_seconds{addr="redis://localhost:6379",alias=""} 535808
# HELP redis_used_cpu_sys used_cpu_sysmetric
# TYPE redis_used_cpu_sys gauge
redis_used_cpu_sys{addr="redis://localhost:6379",alias=""} 3217.675053
# HELP redis_used_cpu_sys_children used_cpu_sys_childrenmetric
# TYPE redis_used_cpu_sys_children gauge
redis_used_cpu_sys_children{addr="redis://localhost:6379",alias=""} 3995.292786
# HELP redis_used_cpu_user used_cpu_usermetric
# TYPE redis_used_cpu_user gauge
redis_used_cpu_user{addr="redis://localhost:6379",alias=""} 2684.219589
# HELP redis_used_cpu_user_children used_cpu_user_childrenmetric
# TYPE redis_used_cpu_user_children gauge
redis_used_cpu_user_children{addr="redis://localhost:6379",alias=""} 31080.82922`

But with a latest one only first 50% of the metrics

**Comment by oliver006** [comment]
I just tried the latest version with the cluster that's part of the docker-compose file and I got the metrics as expected.
(pull the latest version of hte repo, just pushed a minor fix to the docker-compose file. then run `docker-compose -f contrib/docker-compose-for-tests.yml up -d` and point the exporter to either `redis://localhost:7000` for a master node or port 7005 for a slave node)

What's the output of `redis_up` in the metrics you get? Is the scrape successful?

**Comment by michalss** [comment]
well im not using docker-compose.

**Comment by oliver006** [comment]
Ok - 🤷‍♀. Without more information I can't help you figuring out what's going wrong.

Closing. Feel free to re-open when you have more information to help diagnose the problem.

**Comment by michalss** [comment]
not a problem im using older versions works like charm... thx

**Comment by DanRoscigno** [comment]
@oliver006 I am happy to debug this with you.  I am having the same issue.  I wrote a blog post about using your exporter with Metricbeat from Elastic.  When I wrote the blog I was using instantaneous ops per sec in my example.  Today I went to update a screenshot and was not able to see that metric.  I backed down from :latest to :v0.17.2 and instantaneous ops per sec was back.  Here is the blog if you are interested in seeing your work: https://www.elastic.co/blog/elasticsearch-observability-embracing-prometheus-and-openmetrics-standards-for-metrics

**Comment by oliver006** [comment]
@DanRoscigno - looks like `instantaneous_ops_per_sec` was removed a while back. It's a derived metric, calculated by redis and you should be able to get the same number by using `rate(redis_commands_total[1m])` and have prometheus calculate it.

**Comment by oliver006** [comment]
And that's a nice blog post!

**Comment by DanRoscigno** [comment]
Thanks for the info!  And thanks to you for the exporter, I could not have written the post without your work.

I will take a look at the metricbeat code and see if we are calculating that one.  For the time being I just updated the example to use an older version of your exporter.

**Comment by oliver006** [comment]
👍
