### ISSUE TITLE
Maybe... REDIS_ADDR not set default value

### ISSUE THREAD

**Issue by pwpo1999** [oliver006/redis_exporter#274]
My environment is Redis Cluster running on Kubernetes.
And using Redis Exporter sidecar with not set REDIS_ADDR.

until 0.34.1 version looks good.
but after upgrade to 1.0.1 version, can not scrape metrics.
so add -debug argument.
and show log redisAddr empty

so add REDIS_ADDR environment variable with value redis://localhost:6379
after do that, looks good.

with README.md
redis.addr | REDIS_ADDR | Address of the Redis instance, defaults to redis://localhost:6379.
-- | -- | --

but maybe... not set Default Value.
Please Confirm.

**Comment by oliver006** [comment]
Thanks for the bug report!

You're right, not defaulting to `redis://localhost:6379` is indeed a mistake, I'll get that fixed.
