### ISSUE TITLE
Error using -redis.password-file

### ISSUE THREAD

**Issue by focabr** [oliver006/redis_exporter#277]
```
#./redis_exporter  -version
INFO[0000] Redis Metrics Exporter v1.0.2    build date: 2019-06-13-01:55:42    sha1: 4f808dc9c774ed56a55600630440a1993224acf8    Go: go1.12.6 
```

Error using:
```

#./redis_exporter -redis.password-file /opt/exporter/conf/redis.pwd
flag provided but not defined: -redis.password-file
```

It worked in version 0.28 normally.

**Comment by oliver006** [comment]
Please see https://github.com/oliver006/redis_exporter#upgrading-from-0x-to-1x

**Comment by ntelisil** [comment]
Any plans to reintroduce the support of reading the password from a file (defined as env variable or as cmd line parameter) ?

**Comment by ntelisil** [comment]
For the time being there are two options:
1. stick with a working version of 0.x
2. or use the latest versions and override the entry point like below (I am using docker compose to build)
_entrypoint: ["sh", "-c", "/redis_exporter -redis.password `cat /run/secrets/redis_password`"]_

**Comment by oliver006** [comment]
No plans to bring back the `-redis.password-file` flag, your suggested option (2) would be way to go.
