### ISSUE TITLE
QUESTION Is posible to add custom metrics prefix or custom label?

### ISSUE THREAD

**Issue by castocolina** [oliver006/redis_exporter#279]
My dev-ops team manage the central prometheus and use configuration that requires we provide custom match prefix for my components metrics. My dev team need to set custom prefix for all our products components. Is possible do this for this exporter or set custom label?

**Comment by oliver006** [comment]
the exporter allows you to set a custom namespace for the metrics but you should be able to use Prometheus metric and label rewriting for that, see the official docs for more information about that.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by castocolina** [comment]
Thanks @oliver006

**Comment by jsmilani** [comment]
I request this to be reopened. This is one of the most frustrating issues with prometheus exporters. It is way easier to have host specific custom labels added at the exporter level than the prometheus configuration because it requires custom configuration for each host.

**Comment by krinklesaurus** [comment]
@oliver006 can we reopen this pls? 

I have multiple Redis running in different environments and regions and my workaround right now is to set the name space to like this
> `my_cache_dev_us_1_commands_total`

Would be neat to have 

> `my_cache_commands_total{environment="dev",region"us",node="1"}` 

instead. I cannot use Prometheus' label rewriting for various reeasons
