### ISSUE TITLE
multi instance failure.

### ISSUE THREAD

**Issue by LanceYuan** [oliver006/redis_exporter#280]
**Describe the problem**
multi instance failure.
./redis_exporter --redis.addr="127.0.0.1:6379,127.0.0.1:6380"

ERROR:
redis_exporter_last_scrape_error{err="dial tcp: address 127.0.0.1:6379,127.0.0.1:6380: too many colons in address"} 1

**What version of redis_exporter are you running?**
redis_exporter-v1.0.3 and redis_exporter-v1.0.2

![image](https://user-images.githubusercontent.com/16434627/60378986-86759680-9a5d-11e9-9602-a6fce89ab8cf.png)

![image](https://user-images.githubusercontent.com/16434627/60378988-90979500-9a5d-11e9-97dd-50e2fcff6b72.png)

![image](https://user-images.githubusercontent.com/16434627/60378994-a442fb80-9a5d-11e9-8f08-09a453833aa7.png)

![image](https://user-images.githubusercontent.com/16434627/60378999-b15fea80-9a5d-11e9-8cc2-af61a1afa2d5.png)

**Comment by oliver006** [comment]
Have a look here: [how to configure the exporter when scraping multiple instances.](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)
