### ISSUE TITLE
1.x Dashboard: instance dropdown as hostnames

### ISSUE THREAD

**Issue by naseemkullah** [oliver006/redis_exporter#288]
The use of `addr` (i.e. `label_values(redis_up, addr)`) gives a us a hostname rather than the use of `instance` which gives us IPs. Is there some advantage to using `instance` over `addr` that outweighs seeing a hostname over an ip?

cc @oliver006  @brian-brazil

**Comment by brian-brazil** [comment]
Where's this addr label coming from? There should only be instance.

**Comment by naseemkullah** [comment]
Sorry I meant `addr` is used in the older version of the dashboard. But we would replace `instance` by `addr` in the new dashboard and get hostnames rather than IPs in the drop down.

**Comment by naseemkullah** [comment]
Sorry I'm still using the `0.3.x` version of the exporter and looking at the `1.x.x` version of the dashboard.

**Comment by naseemkullah** [comment]
Just read your blog posts https://www.robustperception.io/controlling-the-instance-label has and https://www.robustperception.io/target-labels-are-for-life-not-just-for-christmas @brian-brazil, they shed a lot of light on the matter.

>The instance label generally uniquely identifies a target, so there's no need to add additional host or alias labels on top of that to provide a prettier name - instead take advantage of the existing instance label and give it the better name.

Basically to not have a drop down with IPs,  but rather a dropdown with hostnames, one should relabel instance if I understand correctly?

**Comment by naseemkullah** [comment]
I'm using `job: kubernetes-service-endpoints` via adding the prometheus annotations (`prometheus.io/scrape: "true"`) to the redis-exporter services. Is it recommended to reconfigure `instance` for the `job: kubernetes-service-endpoints` ?

The [official prometheus chart does not seem to relabel instance](https://github.com/helm/charts/blob/399c74aca0c4a8c6c2ba097df45d36d2a9d5234d/stable/prometheus/values.yaml#L1141-L1171), but having it relabelled with the value of `[__meta_kubernetes_service_name]` would be good right?

**Comment by naseemkullah** [comment]
https://github.com/helm/charts/issues/15323 created, Would love to get your input on this @brian-brazil

**Comment by naseemkullah** [comment]
Are you using the 1.x dashboard, is your drop down of instances IPs or hostnames? if the latter how do you achieve this? If not let's just add back `addr` it was really convenient

**Comment by oliver006** [comment]
Using redis_exporter 1.0 and scraping multiple redis instances, I see `instance` being the hostname of the redis instance (and not an IP).

**Comment by naseemkullah** [comment]
Good to know. I must be doing something wrong then.

**Comment by oliver006** [comment]
fwiw, I _think_ Prometheus sets the `instance` label to whatever you configure the scrape target to be. So if you use a host name then `instance` will be that host name.

What do you have in your configs? Are they static configurations or using a SD? When using Kubernetes it was all IPs but not sure what other service discoveries surface.

**Comment by naseemkullah** [comment]
That makes sense.
I have an explicitly set scrape config for nodes, that have a node exporter running on them and they show up as hostnames as I define them as such under `targets`.

```
- job_name: node
[...]
  static_configs:
  - targets:
    - redis.default.svc:9100
    - nfs-server.default.svc:9100
```

However with regards to the redis exporters, I do indeed use the `kubernetes-service-endpoints` SD as the exporters' services are annotated with `prometheus.io/scrape: 'true'` . 

I would like to keep the convenience of the SD+annotation but have a drop down of hostnames rather than IPs (wether it be Prometheus configuring what `instance` is or by some other means e.g. `addr`). I guess I can't have my cake and eat it too! :)

**Comment by oliver006** [comment]
Ah, there you go, good ol' Kubernetes SD.

One thing you can try is see if there are other labels available as part of the k8s SD (`__meta_kubernetes__ ...`)  and then add them via the relabel_config section.

**Comment by naseemkullah** [comment]
Thanks for the suggestion.

So the job when enabling scraping of service such as here:
https://github.com/helm/charts/blob/793f25b7ce30d645d75e2fe030853b0f9066dd29/stable/prometheus-redis-exporter/values.yaml#L30-L33

or

https://github.com/helm/charts/blob/793f25b7ce30d645d75e2fe030853b0f9066dd29/stable/redis/values.yaml#L459-L461

is `kubernetes-service-endpoints`

Here's the available meta labels: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#endpoints

When adding a relabel config to this sd configuration like so:
```
          - source_labels: [__meta_kubernetes_endpoints_name]
            target_label: instance
```

We get great results for the redis exported instances.

However there is a problem. This job `kubernetes-service-endpoints` is also used by prometheus node exporters on kubernetes hosts:

https://github.com/helm/charts/blob/793f25b7ce30d645d75e2fe030853b0f9066dd29/stable/prometheus/values.yaml#L501-L502

This relabels all the nodes from their IPs (not ideal, node name would be ideal, but at least they are unique) all to `prometheus-node-exporter`

So still trying to figure this one out!

**Comment by naseemkullah** [comment]
Is adding `addr` back (perhaps renaming as `hostname`) not desirable? 
It was pretty great when using the k8s service endpoints SD which assigns IPs to the instance labels.

**Comment by oliver006** [comment]
Closing, we're not bringing `addr` back.

**Comment by naseemkullah** [comment]
Ah shucks
