### ISSUE TITLE
redis exporter can not report system related metrics on version 1.0.1

### ISSUE THREAD

**Issue by ardenxu** [oliver006/redis_exporter#289]
**Describe the problem**

we deploy redis exporter to collector redis server info, production env has case that redis hit Out of memory problem, so use  redis exporter metrics to setup alert for memory usage.  But we can get redis memory usage now, but can not get redis_total_system_memory_bytes on version 1.0.1, though the help menu indicate this should be reported by default.

**What version of redis_exporter are you running?**
INFO[0000] Redis Metrics Exporter v1.0.1    
build date: 2019-06-07-16:06:50    
sha1: acbc52515af1bf5d6384f09438af792cb643524f    
Go: go1.12.5

**Running the exporter**
./redis_exporter -redis.addr=10.18.210.89

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 

1. per help menu, exporter should report redis_total_system_memory_bytes, see menu below.

./redis_exporter --help
Usage of ./redis_exporter:
  -include-system-metrics
    	Whether to include system metrics like e.g. redis_total_system_memory_bytes (default true)

2.  there is no redis_total_system_memory_bytes in output, we also tried run exporter with following command, get same result.

./redis_exporter -redis.addr=10.18.210.89 -include-system-metrics="true"

3 full metrics are attached below.

**Screenshots**
exporter_scrape_duration_seconds{quantile="0.5"} NaN
exporter_scrape_duration_seconds{quantile="0.9"} NaN
exporter_scrape_duration_seconds{quantile="0.99"} NaN
exporter_scrape_duration_seconds_sum 0
exporter_scrape_duration_seconds_count 0
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
go_goroutines 6
go_info{version="go1.12.5"} 1
go_memstats_alloc_bytes 919640
go_memstats_alloc_bytes_total 919640
go_memstats_buck_hash_sys_bytes 1.442947e+06
go_memstats_frees_total 186
go_memstats_gc_cpu_fraction 0
go_memstats_gc_sys_bytes 2.240512e+06
go_memstats_heap_alloc_bytes 919640
go_memstats_heap_idle_bytes 6.4749568e+07
go_memstats_heap_inuse_bytes 2.031616e+06
go_memstats_heap_objects 2771
go_memstats_heap_released_bytes 0
go_memstats_heap_sys_bytes 6.6781184e+07
go_memstats_last_gc_time_seconds 0
go_memstats_lookups_total 0
go_memstats_mallocs_total 2957
go_memstats_mcache_inuse_bytes 55552
go_memstats_mcache_sys_bytes 65536
go_memstats_mspan_inuse_bytes 23904
go_memstats_mspan_sys_bytes 32768
go_memstats_next_gc_bytes 4.473924e+06
go_memstats_other_sys_bytes 1.002613e+06
go_memstats_stack_inuse_bytes 327680
go_memstats_stack_sys_bytes 327680
go_memstats_sys_bytes 7.189324e+07
go_threads 5
process_cpu_seconds_total 0
process_max_fds 655360
process_open_fds 8
process_resident_memory_bytes 4.251648e+06
process_start_time_seconds 1.56274677454e+09
process_virtual_memory_bytes 1.14434048e+08
process_virtual_memory_max_bytes -1
promhttp_metric_handler_requests_in_flight 1
promhttp_metric_handler_requests_total{code="200"} 0
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
redis_aof_current_rewrite_duration_sec -1
redis_aof_enabled 0
redis_aof_last_bgrewrite_status 1
redis_aof_last_rewrite_duration_sec -1
redis_aof_last_write_status 1
redis_aof_rewrite_in_progress 0
redis_aof_rewrite_scheduled 0
redis_blocked_clients 0
redis_client_biggest_input_buf 0
redis_client_longest_output_list 0
redis_commands_duration_seconds_total{cmd="auth"} 0.582284
redis_commands_duration_seconds_total{cmd="command"} 0.015574
redis_commands_duration_seconds_total{cmd="config"} 72.989331
redis_commands_duration_seconds_total{cmd="del"} 0.013972
redis_commands_duration_seconds_total{cmd="expire"} 2.2e-05
redis_commands_duration_seconds_total{cmd="get"} 0.017621
redis_commands_duration_seconds_total{cmd="hgetall"} 0.00017
redis_commands_duration_seconds_total{cmd="hlen"} 1.2e-05
redis_commands_duration_seconds_total{cmd="hmset"} 0.000695
redis_commands_duration_seconds_total{cmd="incr"} 0.025615
redis_commands_duration_seconds_total{cmd="info"} 545.417557
redis_commands_duration_seconds_total{cmd="keys"} 8.1e-05
redis_commands_duration_seconds_total{cmd="latency"} 0.651393
redis_commands_duration_seconds_total{cmd="lpop"} 0.017435
redis_commands_duration_seconds_total{cmd="lpush"} 0.053372
redis_commands_duration_seconds_total{cmd="lrange"} 0.204581
redis_commands_duration_seconds_total{cmd="monitor"} 2.9e-05
redis_commands_duration_seconds_total{cmd="ping"} 1.705904
redis_commands_duration_seconds_total{cmd="restore"} 4.4e-05
redis_commands_duration_seconds_total{cmd="sadd"} 0.01812
redis_commands_duration_seconds_total{cmd="select"} 21.976845
redis_commands_duration_seconds_total{cmd="set"} 4.20666
redis_commands_duration_seconds_total{cmd="slowlog"} 3.797642
redis_commands_duration_seconds_total{cmd="spop"} 0.004359
redis_commands_duration_seconds_total{cmd="srem"} 0.015297
redis_commands_processed_total 2.092875e+06
redis_commands_total{cmd="auth"} 106100
redis_commands_total{cmd="command"} 1
redis_commands_total{cmd="config"} 82431
redis_commands_total{cmd="del"} 2
redis_commands_total{cmd="expire"} 1
redis_commands_total{cmd="get"} 10004
redis_commands_total{cmd="hgetall"} 4
redis_commands_total{cmd="hlen"} 1
redis_commands_total{cmd="hmset"} 2
redis_commands_total{cmd="incr"} 10100
redis_commands_total{cmd="info"} 82391
redis_commands_total{cmd="keys"} 2
redis_commands_total{cmd="latency"} 82294
redis_commands_total{cmd="lpop"} 10000
redis_commands_total{cmd="lpush"} 20000
redis_commands_total{cmd="lrange"} 12271
redis_commands_total{cmd="monitor"} 4
redis_commands_total{cmd="ping"} 204557
redis_commands_total{cmd="restore"} 10
redis_commands_total{cmd="sadd"} 10000
redis_commands_total{cmd="select"} 503
redis_commands_total{cmd="set"} 1.287607e+06
redis_commands_total{cmd="slowlog"} 164590
redis_commands_total{cmd="spop"} 3651
redis_commands_total{cmd="srem"} 6349
redis_config_maxclients 10000
redis_config_maxmemory 0
redis_connected_clients 2
redis_connected_slaves 0
redis_connections_received_total 190722
redis_cpu_sys_children_seconds_total 0.14
redis_cpu_sys_seconds_total 3779.8
redis_cpu_user_children_seconds_total 1.12
redis_cpu_user_seconds_total 1332.18
redis_db_avg_ttl_seconds{db="db0"} 0
redis_db_keys{db="db0"} 729668
redis_db_keys{db="db1"} 0
redis_db_keys{db="db10"} 0
redis_db_keys{db="db11"} 0
redis_db_keys{db="db12"} 0
redis_db_keys{db="db13"} 0
redis_db_keys{db="db14"} 0
redis_db_keys{db="db15"} 0
redis_db_keys{db="db2"} 0
redis_db_keys{db="db3"} 0
redis_db_keys{db="db4"} 0
redis_db_keys{db="db5"} 0
redis_db_keys{db="db6"} 0
redis_db_keys{db="db7"} 0
redis_db_keys{db="db8"} 0
redis_db_keys{db="db9"} 0
redis_db_keys_expiring{db="db0"} 0
redis_db_keys_expiring{db="db1"} 0
redis_db_keys_expiring{db="db10"} 0
redis_db_keys_expiring{db="db11"} 0
redis_db_keys_expiring{db="db12"} 0
redis_db_keys_expiring{db="db13"} 0
redis_db_keys_expiring{db="db14"} 0
redis_db_keys_expiring{db="db15"} 0
redis_db_keys_expiring{db="db2"} 0
redis_db_keys_expiring{db="db3"} 0
redis_db_keys_expiring{db="db4"} 0
redis_db_keys_expiring{db="db5"} 0
redis_db_keys_expiring{db="db6"} 0
redis_db_keys_expiring{db="db7"} 0
redis_db_keys_expiring{db="db8"} 0
redis_db_keys_expiring{db="db9"} 0
redis_evicted_keys_total 0
redis_expired_keys_total 1
redis_exporter_build_info{build_date="2019-06-07-16:06:50",commit_sha="acbc52515af1bf5d6384f09438af792cb643524f",golang_version="go1.12.5",version="v1.0.1"} 1
redis_exporter_last_scrape_duration_seconds 0.003872511
redis_exporter_last_scrape_error{err=""} 0
redis_exporter_scrapes_total 1
redis_instance_info{os="Linux 3.10.0-327.el7.x86_64 x86_64",redis_build_id="35fc9cedb27bce13",redis_mode="standalone",redis_version="2.8.21",role="master"} 1
redis_keyspace_hits_total 18635
redis_keyspace_misses_total 3646
redis_last_slow_execution_duration_seconds 0.230493
redis_latest_fork_seconds 0.002282
redis_loading_dump_file 0
redis_master_repl_offset 0
redis_memory_used_bytes 7.9730224e+07
redis_memory_used_lua_bytes 36864
redis_memory_used_peak_bytes 8.270272e+07
redis_memory_used_rss_bytes 4.571136e+07
redis_net_input_bytes_total 9.2556749e+07
redis_net_output_bytes_total 4.79058487e+08
redis_process_id 243
redis_pubsub_channels 0
redis_pubsub_patterns 0
redis_rdb_bgsave_in_progress 0
redis_rdb_changes_since_last_save 0
redis_rdb_current_bgsave_duration_sec -1
redis_rdb_last_bgsave_duration_sec 0
redis_rdb_last_bgsave_status 1
redis_rdb_last_save_timestamp_seconds 1.562038517e+09
redis_rejected_connections_total 0
redis_replication_backlog_bytes 1.048576e+06
redis_slowlog_last_id 130
redis_slowlog_length 128
redis_start_time_seconds 1.557025784e+09
redis_target_scrape_request_errors_total 0
redis_up 1
redis_uptime_in_seconds 5.721002e+06

**Additional context**
 i noticed there is change back to Jan that merge the redis_total_system_memory_bytes, metrics back to redis exporter,  but  not sure why it does not work on 1.0.1. 

thanks for support!!

**Comment by ardenxu** [comment]
please ignore this issue, its due redis server version, i scrape an old redis on 2.8, it has no system memory info at all, so close this.

# Memory
used_memory:79730184
used_memory_human:76.04M
used_memory_rss:43237376
used_memory_peak:82702720
used_memory_peak_human:78.87M
used_memory_lua:36864
mem_fragmentation_ratio:0.54
mem_allocator:jemalloc-3.6.0

**Comment by oliver006** [comment]
👍
