### ISSUE TITLE
Can't get the Redis each queue length

### ISSUE THREAD

**Issue by balathati** [oliver006/redis_exporter#291]
@oliver006 I am looking for some equivalent metrics from Redis exporter

We have Robbitmq exporter for RMQ which will export the metrics below.
1. rabbitmq_queue_messages_ready will give us how many messages are ready on each queue if there are any messages it will return the number of messages otherwise, it will return 0.
2.  rabbitmq_queue_consumers will give us is any consumer consuming from the queue if any consumers it will return number consumer count otherwise, it will return 0.

Example: scan 0
1. "1"
    * "A-default"
    * "A1"
    * "_kombu.binding.A1"
    * "A2"
    * "A3"
    * "A4"
    * "A5"
    * "_kombu.binding.A2"
The Queue names are A1,A2,A3...A5, now I need to know how many messages are ready on each queue, how can I get that info from metrics?

Also, how can I get a particular queue that has consumer/consumers or not?

Thanks.

**Comment by oliver006** [comment]
I don't use redis for queues so not sure what you'd be looking for with the exporter, sorry!

Leaving this open in case someone else is more familiar with queues.

**Comment by oliver006** [comment]
Closing
