### ISSUE TITLE
Additional metric to redis_connected_clients

### ISSUE THREAD

**Issue by justinasfour04** [oliver006/redis_exporter#292]
I need to group the number of redis connected clients by the name of the clients. How would you suggest I go about adding this new contribution?

Would my best bet be writing a lua script to do this? If so how would anyone of you suggest I go about writing this script

**Comment by oliver006** [comment]
Thanks for raising the issue.
I think it's entirely possible to do this without a lua script but by extending the exporter. I'd start with calling `CLIENT LIST` and then parse the output and generate a gauge, set to 1, for each client with labels as the client attributes. That'd be one way to do it. You can then have a PromQL query that sums the clients by client name.
Redis instances can have thousands of clients so it's probably prudent to put that behind a cmd line flag, turned off by default to not blow up the metrics/label space. 

I'm not sure how much time I have over the next couple of weeks to add this myself so if you're familiar with Go (or want to learn) then go ahead and open a PR and I'll review it.

**Comment by justinasfour04** [comment]
I'm down to learn, can you just point me in the right direction to get started of where you think would best to place this

**Comment by oliver006** [comment]
Sure thing. 

I'd model it after the Tile38 switch. Add another function to gather client metrics, and call it here:
https://github.com/oliver006/redis_exporter/blob/master/exporter.go#L1070

You can then have an extractClientList() function that calls `CLIENT LIST` and parses the results and extract the label values.

```
127.0.0.1:6379> CLIENT LIST
id=4 addr=172.20.0.1:43592 fd=9 name= age=2 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client
127.0.0.1:6379>
```

Each line is one client, looks like they're space separated values but the docs probably have more information.

And then you need to add the metric via `registerConstMetric()` and also add a description, more info here: https://github.com/oliver006/redis_exporter/blob/master/exporter.go#L501-L508

**Comment by justinasfour04** [comment]
ERRO[0004] extractConnectedClientMetrics() err: %sredigo: unexpected type for Strings, got type []uint8 

Which redis function should I use to convert the utf8 array

```golang
func (e *Exporter) extractConnectedClientMetrics(ch chan<- prometheus.Metric, c redis.Conn) {
	reply, err := redis.Strings(doRedisCmd(c, "CLIENT", "LIST"))
	if err != nil {
		log.Error("extractConnectedClientMetrics() err: %s", err)
	}
	
	fmt.Printf("%T\n", reply)
}

**Comment by oliver006** [comment]
Interesting, i would have expected that to return an array of strings but doesn't look like it.
Can you try redis.StringMap() or redis.Int64s ? I'm really just guessing here...

**Comment by justinasfour04** [comment]
I can use redis.String() because it returns a string. I can then split the string on \n and then collect the names

**Comment by oliver006** [comment]
👍

**Comment by justinasfour04** [comment]
how do i registerConstMetric(). I keep getting a panic

**Comment by justinasfour04** [comment]
#293 Please let me know what you think

**Comment by justinasfour04** [comment]
@oliver006 closing the issue

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.0.4

**Comment by justinasfour04** [comment]
@oliver006 It was greater working together on this and I got to learn how to use Golang a bit. Thank you

**Comment by oliver006** [comment]
Yeah, this was a fun learning exercise, I'm happy with how this turned out and thanks again for your contribution.

**Comment by justinasfour04** [comment]
one thing we should consider adding to is the ability to collect clients by age greater than certain values or idle above certain values. Not sure if we can do that now because age and idle are labels and aka strings

**Comment by oliver006** [comment]
You're right, the string labels make it hard to filter for a particular threshold.
You might be able to hack something together by only matching 2 or 3 digit long labels using a regex in the PromQL query and be able to filter for `age > 99` or `idle > 999` but that's all a bit hacky and sounds like a terrible thing to do.

I think the better way to do this would be to collect a separate, new metric for _age and for _idle for each client (with the same labels like host and port and id as you have already) and use age or idle as the value or the gauge.
Then you can do the filtering on the prometheus server or grafana side.

**Comment by justinasfour04** [comment]
I'll make a PR I guess
