### ISSUE TITLE
consul and redis_exporter not work

### ISSUE THREAD

**Issue by kong62** [oliver006/redis_exporter#294]
1. prometheus -> consul -> redis_exporter    [not ok]
2. prometheus -> redis_exporter     [ok]

consul for redis_exporter:
[root@Sit-Test-02 consul.d]# cat redis_exporter.json 
{"service": {"name": "redis_exporter", "tags": ["exporter"], "port": 9121}}

prometheus for consul:
- job_name: consul_reids_exporter
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
    - server: '10.64.57.43:8500'
      datacenter: dc1
      scheme: http
      services:
        - reids_exporter

![image](https://user-images.githubusercontent.com/10241723/62523029-83907180-b865-11e9-82fb-b2d0722b221d.png)

**Comment by oliver006** [comment]
I think you misspelled `reids_exporter` in your consul_sd_configs section in the Prometheus configs.

**Comment by kong62** [comment]
@oliver006 Thanks。
