### ISSUE TITLE
Some metrics not being exported

### ISSUE THREAD

**Issue by wpirraglia** [oliver006/redis_exporter#296]
I have some exported metrics differences between my environments, where the only configuration difference between them is that one is a single node, and the other one is a master with two slaves, using sentinel (shouldn't be an issue though, just mentioning). The specific metrics I don't get on the three-nodes environment are **redis_command_call_duration_seconds_count** and **redis_config_maxmemory**. The metrics are not displayed in neither of the three-nodes instances, but are shown at the single node environment. Some idea of what could be happening?
Versions are:
redis: 5.0.3 (both environments)
redis_exporter: v1.0.3

**Comment by oliver006** [comment]
`redis_command_call_duration_seconds_count` has been deprecated/removed a long time ago (sometime mid-2018?) so looks like you're running different exporters in your environments.

`redis_config_maxmemory` should be there, it's still being extracted here: https://github.com/oliver006/redis_exporter/blob/master/exporter.go#L523-L532

Unless `maxmemory` isn't set in your Redis instance in which case the ParseFloat will fail (and the metric won't get recorded).
