### ISSUE TITLE
Counters with same name

### ISSUE THREAD

**Issue by binayakumar09** [oliver006/redis_exporter#297]
I have the below counters in Keys in the Redis Server DBs.
DB2 ->
     KEY1
        test1 - 1
        test2 - 0.5
        test3 - 2

     KEY2
        test1 - 5
        test2 - 5
        test4 - 4

I am using an LUA script to export the data. However, I can see the Counter value test1 is exported once. The latest value over-writes the previous one. It would be good to have a way to uniquely identify the counters along with Keys, so that they are exported separately.

![image](https://user-images.githubusercontent.com/53930372/62758631-9b056f80-ba9c-11e9-817a-ef6ede095836.png)

**Comment by oliver006** [comment]
I'm not sure I follow. Why not use different keys in the return value of your lua script for key1 and key2 ?
What output would you rather have?

**Comment by binayakumar09** [comment]
Thanks. I am trying to integrate SONiC system with Prometheus which uses Redis Server as its DB. Its Counter DB has 1200 KEYS for ports with each key having the same 32 counters. Its not manageable to have KEYs as command line arguments. More so because KEY names are dynamically generated. I am using an LUA script to export all keys - 

```
local result = {}

-- Add all keys and values from some hash in db 5
redis.call("SELECT", 2)
local list = redis.call("KEYS", "*")
for _,i in ipairs(list) do
  local r = redis.call("HGETALL", i)
  if r ~= nil then
      for _,v in ipairs(r) do
          table.insert(result, v) -- alternating keys and values
      end
  end
end
return result
```

The problem is in Prometheus scraped data, I see only the counters from the last Key available.
Is there a way to handle such a situation with exporter or I need to fix something in the LUA script.

I hope, I was a little more clearer on the issue.

Regards

**Comment by oliver006** [comment]
Hmm, I'm not really familiar with Lua but it looks like your script is not doing the right thing, the last `table.insert()` will overwrite what's there already.

Not sure how to do it in Lua but what you could try to do is to prefix/namespace all your key values in `v` before adding them to `result` with `i`, in that way the keys are unique to the key returned from `KEYS`.

**Comment by binayakumar09** [comment]
Thanks.
Kind of understood that while composing my last mail. It helps actually.
I am also totally new to Go Lang as well as LUA. But somehow figured out the correct script with help from LUA documentation.

Below is the LUA script that worked - 

```
-- Example collect script for -script option
-- This returns a Lua table with alternating keys and values.
-- Suitable for Redis Database with huge number of Keys/Counters
-- Avoid Over-writing of counters in DB if they have same name.
-- Both keys and values must be strings, similar to a HGETALL result.
-- More info about Redis Lua scripting: https://redis.io/commands/eval

local result = {}
local list = {}

-- Add all keys and values from some hash in db 5
redis.call("SELECT", 2)
local list = redis.call("KEYS", "*")

    for _,i in ipairs(list) do
        local r = redis.call("HGETALL", i)
        if r ~= nil then
            for _,v in ipairs(r) do
                if tonumber(v) == nil then
                    table.insert(result, i .. "-" .. v) -- alternating keys and values
                else
                    table.insert(result, v) -- alternating keys and values
                end
            end
        end
    end

return result
```

Not sure, if this is the most efficiently written snippet but I can live with that. If needed can be added to contribution directory to help others. 

Thank you very much.
Binaya

![image](https://user-images.githubusercontent.com/53930372/62852546-4fa2c980-bd07-11e9-8746-337a2ea491d3.png)

**Comment by oliver006** [comment]
Thanks for posting the working script! I don't think we need to add it to the contrib folder but we can leave it here so people can find it in the future.
