### ISSUE TITLE
/scrape does not respect `-script` parameter

### ISSUE THREAD

**Issue by mdsummers** [oliver006/redis_exporter#298]
I'm attempting to use a lua script to export custom metrics, as well as the `/scrape` endpoint with ~10 redis targets. However, the script is never invoked.

**Version details**
v1.0.4 - 863ddc928bac938d3da5bbe32a59b479ca53837b

**Running the exporter**
```
./redis_exporter -debug -script /path/to/script
```

**Expected behavior**
Script is invoked, or if it cannot be, a parse error is shown. This is the case when querying `/metrics`. Against `/scrape` this behaviour is not matched.

**Example**
Invoke exporter
```
$ ./redis_exporter -debug -script /path/to/script
```
Curling the /scrape endpoint
```
$ curl localhost:9121/scrape?target=redis%3A%2F%2F127.0.0.1%3A6379
# No logging about the script is seen
```
Curling the /metrics endpoint
```
$ curl localhost:9121/metrics
...
# script logging is seen
DEBU[0059] Evaluating e.LuaScript
DEBU[0059] c.Do() - running command: EVAL
...
```

**Comment by oliver006** [comment]
This is the same issue as #282 - let me see that I can get that fixed int he next couple of days.

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter/pull/299 should fix this.

**Comment by oliver006** [comment]
Closed by https://github.com/oliver006/redis_exporter/releases/tag/v1.1.0
