### ISSUE TITLE
add gauge `redis_used_memory_percent`?

### ISSUE THREAD

**Issue by iwinux** [oliver006/redis_exporter#3]
With `used_memory` in `INFO memory`, plus `CONFIG GET maxmemory`.

**Comment by oliver006** [comment]
Interesting, let me look into that.

**Comment by oliver006** [comment]
@iwinux I pushed up commit https://github.com/oliver006/redis_exporter/commit/e4cf9c925c03214ff727cc4a42559fabf33970d8 that adds a gauge for `redis_config_maxmemory` so you can create a metric that uses used_memory and maxmemory to calculate usage percentage.
Let me know if that works for you.

**Comment by iwinux** [comment]
Thanks :)

I will try this out later and reply back soon.

**Comment by iwinux** [comment]
Hi,

Sorry for the late reply.

`CONFIG GET maxmemory` would not work as expected, because command `CONFIG` of our Redis instances are renamed with secret prefixes (to prevent mis-operation).

**Comment by Cas-pian** [comment]
Seems the `maxmemory` metric is missing from the newest version? The [commit](https://github.com/oliver006/redis_exporter/commit/e4cf9c925c03214ff727cc4a42559fabf33970d8) is not included?

**Comment by oliver006** [comment]
Ah, interesting. Looks like this got removed in April 2017 via https://github.com/oliver006/redis_exporter/pull/64
and now the metric is available via `redis_memory_max_bytes` (but only Redis versions that expose that info via `CONFIG`).
There's an open issue for this here: https://github.com/oliver006/redis_exporter/issues/82

Let me see if I can find some time over the next few days/weeks to bring back support for the `config_` metrics but in the meantime, PRs are welcome.

**Comment by Cas-pian** [comment]
En, seems AWS INFO GET doesnot have maxmemory , but for common redis it works. Seems it's better to retrive the data in different way?
