### ISSUE TITLE
Could you please provide ARM64 binary package?

### ISSUE THREAD

**Issue by communityexplorer** [oliver006/redis_exporter#301]
**Describe the problem**
Now many computer is ARM architecture， could you please provide ARM binary package?

**Comment by oliver006** [comment]
Sure thing, shouldn't be hard to add ARM binaries to the list of targets to compile during a release, will do!

**Comment by oliver006** [comment]
Included in #299 in commit https://github.com/oliver006/redis_exporter/pull/299/commits/97a344f70df6dc3e1141dc4524ff50517d390ed7

**Comment by communityexplorer** [comment]
thank you for support very much, when will  be released?

**Comment by oliver006** [comment]
I hope to have time today or tomorrow to get this released.

**Comment by oliver006** [comment]
Closed by https://github.com/oliver006/redis_exporter/releases/tag/v1.1.0
