### ISSUE TITLE
latency metrics on grafana

### ISSUE THREAD

**Issue by metapraveen** [oliver006/redis_exporter#302]
Thank you for creating this exporter. 
I might be missing something basic, but could not figure out which metrics I should use to get latency spike metrics on grafana. 
Am I missing something from the documentation?

**Comment by oliver006** [comment]
There are two latency related metrics, `[redis_]latency_spike_last` and `[redis_]latency_spike_timestamp_seconds`, you can see how they're collected here:
https://github.com/oliver006/redis_exporter/blob/master/exporter.go#L826-L839
