### ISSUE TITLE
Not able to genrate metrices for multiple redis instance 

### ISSUE THREAD

**Issue by vivek779** [oliver006/redis_exporter#305]
HI I am trying to run redis_exporter for multiple instances  using the following command 

nohup ./redis_exporter -redis.addr localhost:6379 ,localhost:6380 &

but it shows metrics of only single instance nor multiple instances 

Also in nohup, it does not show how much instances it is providing metrics 

Kindly give feedback and also mention it on the main page so that this thread won't rise again

**Comment by vivek779** [comment]
Hi oliver006  

Could you please share me workaround for that

**Comment by woodpenker** [comment]
> Hi oliver006
> 
> Could you please share me workaround for that

You should follow the readme

**Comment by vivek779** [comment]
Hi woodpenker

I followed the following one and it work 
 
nohup ./redis_exporter -redis.addr localhost:6380 -web.listen-address :9122 &

It works thanks

**Comment by oliver006** [comment]
The README has detailed instructions here how to configure Prometheus when scraping multiple instances:

https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
