### ISSUE TITLE
why only listen ipv6 address ?

### ISSUE THREAD

**Issue by cevin** [oliver006/redis_exporter#306]
`./redis_exporter -redis.addr 333 -web.listen-address "0.0.0.0:9121" -debug`
` netstat -anop`got `listen :::9121` only so http://ipv4:9121 not work...

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
```

ipv6 is disabled

**Comment by oliver006** [comment]
Hmm, not really familiar with Core OS but there's nothing that special the exporter is doing regarding ipv4/ipv6 addresses, not sure why it wouldn't work.

**Comment by oliver006** [comment]
Out of curiosity, what was the problem?

**Comment by cevin** [comment]
@oliver006 Need to manually specify whether it is IPV4 or IPV6
