### ISSUE TITLE
targets example in readme not correct

### ISSUE THREAD

**Issue by woodpenker** [oliver006/redis_exporter#307]
**Describe the problem**

The example for define a Redis JSON config file is not correct here if you use IP as host:

```
The targets-redis-instances.json should look something like this:

[
  {
    "targets": [ "redis-host-01:6379", "redis-host-02:6379"],
    "labels": { }
  }
]
```
It should be 
```
[
  {
    "targets": [ "tcp://redis-host-01:6379", "tcp://redis-host-02:6379"],
// or "targets": [ "redis://redis-host-01:6379", "redis://redis-host-02:6379"],
    "labels": { }
  }
]
```

Without leading string `tcp://` or `redis://` may lead to scraping fail like:

```
Invalid 'target' parameter, parse err: &{%!c(string=parse) %!c(string=xx.xx.xx.xx:xxxx) %!c(*errors.errorString=&{first path segment in URL cannot contain colon})}k 
```
This error is caused by line 78 in exporter.go file.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[x] 1.1.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
redis_exporter --redis.password="xxx"

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

**Screenshots**

**Additional context**

**Comment by oliver006** [comment]
Hmm, this should work either way, with our without the `redis://` prefix but let me confirm and update the README if needed.

**Comment by oliver006** [comment]
Interesting, I managed to reproduce this and it happens only if the hostname is an IP, not a name like `localhost`.

I'll amend the README and see if I can fix the address parsing to catch this case.

Thanks for reporting this!
