### ISSUE TITLE
Use ConstMetrics

### ISSUE THREAD

**Issue by brian-brazil** [oliver006/redis_exporter#31]
This exporter is currently using direct instrumentation, which is strong discouraged for custom collectors. It should be switched to use ConstMetrics, and all the mutexes can then be removed.

**Comment by oliver006** [comment]
Not sure what you mean by this, do you have any relevant links to code or docs?

**Comment by brian-brazil** [comment]
https://github.com/prometheus/memcached_exporter/blob/master/main.go has some examples.

**Comment by oliver006** [comment]
Cool, thanks!
