### ISSUE TITLE
Breakdown of items in each list key

### ISSUE THREAD

**Issue by jungopro** [oliver006/redis_exporter#310]
**Describe the problem**
I'm looking for a way to export the names of all the keys of type list with the number of items in each key. for example:
mylist ["hello", "world"]

I'm running the exporter as a side car container in a K8s Pod.
I reviewed https://github.com/oliver006/redis_exporter/issues/248 and tried modifying the command of the docker using -check-keys but I don't get the output I expect, the metric *redis_db_keys* gives me the number of keys, not the number of items in each key

Is there a way to get a "breakdown" of all the lists and number of items in each list?

**What version of redis_exporter are you running?**
0.16.0

**Running the exporter**
redis-exporter -redis.addr=127.0.0.1:6379 -check-keys=mylist

**Expected**

see the nubmer 3 in _redis_db_keys_ metric, got 2

**Actual**

```shell
# redis container:

$ redis-cli
KEYS *
1) "lastSample"
LPUSH mylist "hello"
LPUSH mylist "world"
LPUSH mylist "now"
KEYS *
1) "mylist"
2) "lastSample"

# redis exporter sidecar container:
$ wget localhost:9121/metrcis -O - | grep redis_db_keys
redis_db_keys{addr="127.0.0.1:6379",alias="",db="db0"} 2
```

**Comment by jungopro** [comment]
Hello, I figured it out
I got a new metric for each list with the data
redis_key_size

it works perfectly, thank you

**Comment by oliver006** [comment]
👍
