### ISSUE TITLE
HTTPS connection to redis_exporter

### ISSUE THREAD

**Issue by srikang85** [oliver006/redis_exporter#316]
**Description**
I dont see any flag to run the redis_exporter on TLS/HTTPS protocol

**What version of redis_exporter are you running?**
redis_exporter-v1.1.1.linux-amd64.tar.gz

**Expected behavior**
redis_exporter should expose /metrics on HTTPS port. I understand redis_exporter can connect to redis server on HTTPS port. 

**Additional context**
How would you secure redis_exporter end points?

**Comment by oliver006** [comment]
`redis_exporter` does not support TLS itself. Use a reverse proxy like nginx if you require it as part of your setup. See the docs here: https://prometheus.io/docs/guides/tls-encryption/
