### ISSUE TITLE
Scraping big keys size make the exporter unresponsive

### ISSUE THREAD

**Issue by mazzy89** [oliver006/redis_exporter#319]
**Describe the problem**

Using the `--check-keys` and glob-pattern against big keys, break the exporter.

I've set the flag `--check-keys=key:*` and the exporter does not return any more metrics

A log from the the exporter which is stuck at this line and does not report anything else:
```
prometheus-redis-exporter-6c69956fcc-cfs7w prometheus-redis-exporter time="2019-10-05T12:35:26Z" level=debug msg="e.keys: []main.dbKeyPair{main.dbKeyPair{db:\"0\", key:\"key*\"}}"
```

The target in the Prometheus UI should be healthy but it is unhealthy.

**What version of redis_exporter are you running?**

1.1.0

**Running the exporter**

I'm running the exporter from the Helm chart under `stable` repo and added the `--check-keys` flag.

**Expected behavior**

I'd expect to have metrics exported but if I try to retrieve metrics from `/metrics` it hangs.

Prometheus should have the target healthy in the UI.

**Screenshots**

**Additional context**

Using `--debug` flag I can't see any error. Just that the exporter hangs somewhere and can't get to the end the scrape cycle

**Comment by oliver006** [comment]
Thanks for you question. `--check-keys` makes the exporter collect metrics for each key that's matched, in your case every single key in db0 of your Redis instance, is that intended? How many keys does the DB have? If it's a lot then it'd make sense that the exporter times out / hangs forever.

**Comment by mazzy89** [comment]
The database is pretty big around over 1M of keys. 

I've passed to `--check-keys` a specific pattern to match against it and I believe that this pattern matches with a lot of keys but definitely not all the database. 

So, in this case, the exporter does not support retrieving many keys. probably it worths to write down a disclaimer in the documentation to not use `--check-keys` to retrieve a lot of keys.

**Comment by oliver006** [comment]
Do you really want to export a million metrics to Prometheus every 15 or so senconds? A better way to do this might be through an offline task that dumps them every so often and have node_exporter import them from a file and expose to Prometheus.

That said, I agree, I disclaimer in the docs would help to manage expectations around what's feasible with this feature.

**Comment by mazzy89** [comment]
Likely the keys I would like to retrieve are not of that order of magnitude but less. Nevertheless I got your point and it's not the best approach. Speaking about your idea, I like your approach and it worths to give a try.

If I might help around this topic, just let me know.

**Comment by oliver006** [comment]
Cool. I added a warning via https://github.com/oliver006/redis_exporter/commit/2d7b6448bd5c175a62a2ec158ec3b5ea08383967 - closing this ticket.
