### ISSUE TITLE
Good Practice

### ISSUE THREAD

**Issue by akshatgit** [oliver006/redis_exporter#320]
I am new to prometheus monitoring, and I wanted to know what is the good practice for using redis_exporter. 
Consider I have 10 AWS instances, with multiple redis instances running on them. Should I run redis exporter in each EC2 to expose redis metrics for all instances running on them or should I just run 1 redis exporter for the entire infra?

**Comment by oliver006** [comment]
There are several ways how to tackle this issue but it all depends on your architecture and general setup. Do you run multiple redis instances per AWS instance or is it 1:1? What do you use for service discovery/orchestration?

The general Prometheus recommendation is to run one exporter per exported service instance so in your case, one exporter for each Redis instance which might or might not be practical.
Do you already have node_exporters run on each of your EC2 instances? If yes, how do you set up your prometheus configs to discover & scrape those? Maybe that's a way to then also have one redis_exporter per EC2 instance that you use for Redis and discover/configure them the same way.

You can also try to monitor all Redis instances with one exporter (see [docs here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)) but there are limitations around password protected instances. And you still need a way to configure/discover your redis instances.

The [Prometheus docs](https://prometheus.io/docs/) have a lot more information round these topics.

Hope this helps to get you started.

**Comment by akshatgit** [comment]
We have multiple redis instances on each ec2 instance. Redis is provisioned and configured by puppet. Right now we use Nagios to monitor redis. 
You mentioned '_exported service instance_' what does this mean? Can you point me to the doc where all these topics are mentioned? 
BTW great work with redis exporter. I would like to contribute to this project, assign me if you are implementing any feature.

**Comment by akshatgit** [comment]
Thanks for clearing it up.
