### ISSUE TITLE
redis cluster with error "Couldn't connect to redis instance"

### ISSUE THREAD

**Issue by superfenv** [oliver006/redis_exporter#325]
I want to use the redis_exporter to monitor redis-cluster. At startup - -redis.addr=xxx:6379,xxx:6380,xxx:6381 (the password does not exist in the cluster), the error message "Couldn't connect to redis instance". but if Just one instance address is normal (- -redis.addr=xxx:6379).

redis version: 3.0.6
redis_exproter: v1.3.1
command: ./redis_exporter --redis.addr redis://xxx:7001,redis://xxx:7002,reids://xxx:7003 &

![image](https://user-images.githubusercontent.com/30689249/68101517-ee0a8980-ff08-11e9-9d0f-cce2062c15f9.png)

**Comment by oliver006** [comment]
Please have a look at the [documentation](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) for how to scrape multiple redis instances with redis_exporter 1.x.
