### ISSUE TITLE
Redis password is exposed in the process

### ISSUE THREAD

**Issue by superfenv** [oliver006/redis_exporter#328]
Redis password is exposed in the process
redis_exporter version: 1.x.x
command:  /opt/redis_exporter/redis_exporter --redis.addr=xxx.xxx.xxx.xxx:6379 -web.listen-address=:9121 -redis.password="$redis_pass" &

Is there any way to hide the password?

**Comment by oliver006** [comment]
You can set the `REDIS_PASSWORD` environment variable and the exporter will pick it up and use it.

**Comment by superfenv** [comment]
I understand this:
export REDIS_POSSWORD="xxx"
/opt/redis_exporter/redis_exporter --redis.addr=xxx.xxx.xxx.xxx:7008 -web.listen-address=:9121 -redis.password="$REDIS_POSSWORD"
But the password is still displayed.

**Comment by oliver006** [comment]
`REDIS_PASSWORD`, not `REDIS_POSSWORD`

And when that env variable is set you don't need to pass the command line flag, the exporter will get the password directly from the variable.

```
export REDIS_PASSWORD="password123"
/opt/redis_exporter/redis_exporter --redis.addr=xxx.xxx.xxx.xxx:7008 -web.listen-address=:9121 
```

**Comment by superfenv** [comment]
Wish you all the best!
    Thank you very much for your quick response, according to your way, the
test is successful! I have another question.
    I haven't figured out the redis-cluster monitoring. Do I need to start
an exporter on each master? Or is it that my entire cluster only starts the
exporter on one master?

Oliver <notifications@github.com> 于2019年11月13日周三 上午11:05写道：

**Comment by oliver006** [comment]
Good to hear it's working!

As for cluster monitoring, the recommended way is to use one exporter per redis instance.

**Comment by superfenv** [comment]
Thank you for your advice, very useful for me.

Oliver <notifications@github.com> 于2019年11月13日周三 上午11:25写道：

**Comment by superfenv** [comment]
> `REDIS_PASSWORD`, not `REDIS_POSSWORD`
> 
> And when that env variable is set you don't need to pass the command line flag, the exporter will get the password directly from the variable.
> 
> ```
> export REDIS_PASSWORD="password123"
> /opt/redis_exporter/redis_exporter --redis.addr=xxx.xxx.xxx.xxx:7008 -web.listen-address=:9121 
> ```

Hello, I'm sorry to bother you again, I encountered this problem again. I wrote a for loop outside REDIS_PASSWORD = "xx", and started exporter to report an error Couldn't set client name, err: NOAUTH Authentication required. I hope to get your advice.

start () {
    second_port = `expr $port + 622` #The second redis instance port
    for i in $ port $ second_port
    do
      a = $ {i: 1} #string interception
      exporter_port = `expr $ a + 9000` #exporter port definition
      epid = `ss -ntlpu state listening sport =: $ exporter_port | grep users | awk -F ',' '{print $ 2}' | awk -F '=' 'NR == 1 {print $ 2}'` #exporter port Is listening
      if [-z "$ {epid}"]; then
         REDIS_PASSWORD = `cat $ redis_dir / conf / redis_ $ i.conf | grep -v '#' | sed '/ ^ $ / d' | grep requirepass | awk '{print $ 2}'` #Get redis cluster password
$ base_dir / redis_exporter / redis_exporter -web.listen-address = "$ ip_address: $ exporter_port" -redis.addr = "$ ip_address: $ i" & #Start redis_exporter
         sleep 3
         curl -X PUT -d '{"id":' \ "$ {id} _ $ {exporter_port} \" ', "name":' \ "$ name \" ', "address":' \ "$ ip_address \ "'," port ":' $ exporter_port '," tags ": [' $ tags ']," checks ": [{" http ":" http: //' "$ ip_address" ':' "$ exporter_port "'/ metrics", "interval": "15s"}]}' '$ consul / register #redis_exporter
      else
         echo "redis_exporter already running with $ exporter_port."
      fi
    done
}

start

**Comment by code871** [comment]
if you want to use systemd to manage exporter:

[root@manager-23 ~]# cat /usr/lib/systemd/system/redis_exporter.service 
[Unit]
Description=redis_exporter
After=network.target
[Service]
Environment='REDIS_PASSWORD=YourRedisPassword'
Restart=on-failure
ExecStart=/data/monitor/redis_exporter/redis_exporter 
[Install]
WantedBy=multi-user.target
