### ISSUE TITLE
Add /health endpoint returning 200 OK

### ISSUE THREAD

**Issue by analytically** [oliver006/redis_exporter#329]
It'd be handy for schedulers like Nomad and K8s to have a /health endpoint indicating service availability.

**Comment by oliver006** [comment]
You could use `/` to check for availability of the exporter?

**Comment by analytically** [comment]
It's better to be explicit IMHO and have a simple OK response instead of this:

![image](https://user-images.githubusercontent.com/254434/68818593-54468900-063a-11ea-8d6f-6319d281e18f.png)

**Comment by oliver006** [comment]
Oh, yeah, that's a little ugly.

**Comment by oliver006** [comment]
There's also a spurious `v` in the `<title>` :-/

**Comment by analytically** [comment]
There is :-)

**Comment by oliver006** [comment]
Let me fix that and add a `/health` endpoint while I'm at it.

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.3.3
