### ISSUE TITLE
docker/Dockerfile.arm64 has GO_ARCH="amd64" defined.

### ISSUE THREAD

**Issue by jaredquinn** [oliver006/redis_exporter#331]
**Describe the problem**
Build container uses wrong architecture in GO_ARCH

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[x] master branch build
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
Build issue.

**Expected behavior**
The correct architecture is built

**Screenshots**

**Additional context**

**Comment by oliver006** [comment]
Good catch, thanks for opening the issue.

I'll get that fixed but I think current builds are still ok as `GOARCH` is set here 
https://github.com/oliver006/redis_exporter/blob/master/.drone.yml#L114
and the value in the Dockerfile is only used if no override value is provided.

**Comment by oliver006** [comment]
Fixed via https://github.com/oliver006/redis_exporter/commit/97389d281a46298fef324bd42d30a8a26e1ae130
