### ISSUE TITLE
it seems that redis 5.0.5 replaces "client_longest_output_list" &"client_biggest_input_buf" by "client_recent_max_output_buffer" &"client_recent_max_input_buffer"

### ISSUE THREAD

**Issue by callmebymyname-caiji** [oliver006/redis_exporter#333]
version:latest
as described in title，exporter cant get that 2 metrics now

**Comment by oliver006** [comment]
Ah yes, looks like that happened in https://github.com/antirez/redis/commit/be88c0b16a53f5763d8fc1ae683f99ee39b0d68e 
and it looks like the docs didn't get updated, https://redis.io/commands/info still lists the old fields.

Let me see how I can add them to the exporter, shouldn't be too hard.

**Comment by oliver006** [comment]
fyi, i just tried with an older redis version (2.8) and the exporter doesn't export which, when looking at the code now, makes sense, the older metrics aren't included in the list of exported ones.
