### ISSUE TITLE
Passing the password in a file instead of in the command line

### ISSUE THREAD

**Issue by daviddetorres** [oliver006/redis_exporter#335]
Passing the password to the exporter in the command line can be insecure. Would it be better to use a password-file option?

Also, this way the password-file can be passed to the exporter through a config-map in a Kubernetes deployment.

**Comment by oliver006** [comment]
You can set the `REDIS_PASSWORD` environment variable which will be picked up by the exporter, no cmd line parameter needed.

**Comment by daviddetorres** [comment]
Thanks for the answer. You are right, using the environment variable is both secure and can be passed via a config-map, so no password-file is needed :+1: 

I'll close the issue.

**Comment by superfenv** [comment]
> Thanks for the answer. You are right, using the environment variable is both secure and can be passed via a config-map, so no password-file is needed 👍
> 
> I'll close the issue.



> Thanks for the answer. You are right, using the environment variable is both secure and can be passed via a config-map, so no password-file is needed 👍
> 
> I'll close the issue.

hi,oliver006
      I encountered a very strange problem. I specified REDIS_PASSWORD, but still appeared "couldn't connect to redis instance."
![image](https://user-images.githubusercontent.com/30689249/102586553-53d5c700-4145-11eb-912a-2d004c570c38.png)
