### ISSUE TITLE
redis exporter is working but "Couldn't connect to redis instance" thrown

### ISSUE THREAD

**Issue by arnaudlemaignen** [oliver006/redis_exporter#336]
**Describe the problem**
Not sure I have an issue. I just updated from 1.0.2 to 1.3.4, all data are well scraped but the exporter logs is throwing continuously "Couldn't connect to redis instance"

time="2019-11-20T13:35:52Z" level=info msg="Redis Metrics Exporter v1.3.4    build date: 2019-11-15-19:32:19    sha1: e15c7d22b9151c3681c60b5df5cd552584bef10d    Go: go1.13.4    GOOS: linux    GOARCH: amd64"
time="2019-11-20T13:35:52Z" level=info msg="Providing metrics at :9121/metrics"
time="2019-11-20T13:36:01Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:36:31Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:37:01Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:37:31Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:38:01Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:38:31Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T13:39:01Z" level=error msg="Couldn't connect to redis instance"

**What version of redis_exporter are you running?**
1.3.4 release

**Running the exporter**
the default command from docker file

**Expected behavior**
No error logs

**Screenshots**
data are scraped without issues apparently
![image](https://user-images.githubusercontent.com/22667740/69250344-cb869a80-0baf-11ea-9f50-de1b1ef3f2b8.png)

**Additional context**
my prom config is
```
- job_name: redis-exporter-targets
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /scrape
  scheme: http
  static_configs:
  - targets:
    - redis://redis-1:6379
    - redis://redis-2:6379
    - redis://redis-3:6379
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: redis-exporter:9121
    action: replace
  metric_relabel_configs:
  - source_labels: [instance]
    separator: ;
    regex: redis://redis-([0-9]*):6379
    target_label: alias
    replacement: redis-${1}
    action: replace
```

**Comment by oliver006** [comment]
Interesting - could you post the full command line that you use when starting the exporter and could you maybe run this with the `--debug` flag to see if there's more log output that could help to track this down?

**Comment by arnaudlemaignen** [comment]
basically
./redis_exporter


I will try --debug flag

**Comment by arnaudlemaignen** [comment]
here it is
actually look like is getting data from redis1/2/3 but it is also trying on localhost as well which is failing
should I had something to the configuration to avoid localhost scraping?

time="2019-11-20T16:38:42Z" level=info msg="Redis Metrics Exporter v1.3.4    build date: 2019-11-15-19:32:19    sha1: e15c7d22b9151c3681c60b5df5cd552584bef10d    Go: go1.13.4    GOOS: linux    GOARCH: amd64"
time="2019-11-20T16:38:42Z" level=debug msg="Enabling debug output"
time="2019-11-20T16:38:42Z" level=debug msg="keys: []main.dbKeyPair(nil)"
time="2019-11-20T16:38:42Z" level=debug msg="singleKeys: []main.dbKeyPair(nil)"
time="2019-11-20T16:38:42Z" level=info msg="Providing metrics at :9121/metrics"
time="2019-11-20T16:38:42Z" level=debug msg="Configured redis addr: \"redis://localhost:6379\""
time="2019-11-20T16:38:47Z" level=debug msg="keys: []main.dbKeyPair(nil)"
time="2019-11-20T16:38:47Z" level=debug msg="singleKeys: []main.dbKeyPair(nil)"
time="2019-11-20T16:38:47Z" level=debug msg="Trying DialURL(): redis://redis-3:6379"
time="2019-11-20T16:38:47Z" level=debug msg="connected to: redis://redis-3:6379"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - running command: CLIENT [SETNAME redis_exporter]"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - running command: CONFIG [GET *]"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - running command: INFO [ALL]"
time="2019-11-20T16:38:47Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:38:47Z" level=debug msg="info: # Server"
time="2019-11-20T16:38:47Z" level=debug msg="info: redis_version:4.0.14"
time="2019-11-20T16:38:47Z" level=debug msg="info: redis_git_sha1:00000000"
time="2019-11-20T16:38:47Z" level=debug msg="info: redis_git_dirty:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: redis_build_id:d5cb9d9a74410bd0"
time="2019-11-20T16:38:47Z" level=debug msg="info: redis_mode:standalone"
time="2019-11-20T16:38:47Z" level=debug msg="info: os:Linux 3.10.0-957.1.3.el7.x86_64 x86_64"
time="2019-11-20T16:38:47Z" level=debug msg="info: arch_bits:64"
time="2019-11-20T16:38:47Z" level=debug msg="info: multiplexing_api:epoll"
time="2019-11-20T16:38:47Z" level=debug msg="info: atomicvar_api:atomic-builtin"
time="2019-11-20T16:38:47Z" level=debug msg="info: gcc_version:8.3.0"
time="2019-11-20T16:38:47Z" level=debug msg="info: process_id:33"
time="2019-11-20T16:38:47Z" level=debug msg="info: run_id:78c22cfea0db02a63c34eb38b488baf752139ac0"
time="2019-11-20T16:38:47Z" level=debug msg="info: tcp_port:6379"
time="2019-11-20T16:38:47Z" level=debug msg="info: uptime_in_seconds:1093889"
time="2019-11-20T16:38:47Z" level=debug msg="info: uptime_in_days:12"
time="2019-11-20T16:38:47Z" level=debug msg="info: hz:10"
time="2019-11-20T16:38:47Z" level=debug msg="info: lru_clock:13986839"
time="2019-11-20T16:38:47Z" level=debug msg="info: executable:/data/redis-server"
time="2019-11-20T16:38:47Z" level=debug msg="info: config_file:/opt/blabla/conf/redis.conf"
time="2019-11-20T16:38:47Z" level=debug msg="info: "
time="2019-11-20T16:38:47Z" level=debug msg="info: # Clients"
time="2019-11-20T16:38:47Z" level=debug msg="info: connected_clients:152"
time="2019-11-20T16:38:47Z" level=debug msg="info: client_longest_output_list:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: client_biggest_input_buf:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: blocked_clients:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: "
time="2019-11-20T16:38:47Z" level=debug msg="info: # Memory"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory:5675112"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_human:5.41M"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_rss:7225344"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_rss_human:6.89M"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_peak:9273952"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_peak_human:8.84M"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_peak_perc:61.19%"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_overhead:4678132"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_startup:786608"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_dataset:996980"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_dataset_perc:20.39%"
time="2019-11-20T16:38:47Z" level=debug msg="info: total_system_memory:64215793664"
time="2019-11-20T16:38:47Z" level=debug msg="info: total_system_memory_human:59.81G"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_lua:45056"
time="2019-11-20T16:38:47Z" level=debug msg="info: used_memory_lua_human:44.00K"
time="2019-11-20T16:38:47Z" level=debug msg="info: maxmemory:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: maxmemory_human:0B"
time="2019-11-20T16:38:47Z" level=debug msg="info: maxmemory_policy:noeviction"
time="2019-11-20T16:38:47Z" level=debug msg="info: mem_fragmentation_ratio:1.27"
time="2019-11-20T16:38:47Z" level=debug msg="info: mem_allocator:jemalloc-4.0.3"
time="2019-11-20T16:38:47Z" level=debug msg="info: active_defrag_running:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: lazyfree_pending_objects:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: "
time="2019-11-20T16:38:47Z" level=debug msg="info: # Persistence"
time="2019-11-20T16:38:47Z" level=debug msg="info: loading:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_changes_since_last_save:273"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_bgsave_in_progress:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_last_save_time:1574267877"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_last_bgsave_status:ok"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_last_bgsave_time_sec:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_current_bgsave_time_sec:-1"
time="2019-11-20T16:38:47Z" level=debug msg="info: rdb_last_cow_size:716800"
time="2019-11-20T16:38:47Z" level=debug msg="info: aof_enabled:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: aof_rewrite_in_progress:0"
time="2019-11-20T16:38:47Z" level=debug msg="info: aof_rewrite_scheduled:0"
time="2019-11-20T16:39:01Z" level=debug msg="Trying DialURL(): redis://localhost:6379"
time="2019-11-20T16:39:01Z" level=debug msg="DialURL() failed, err: dial tcp [::1]:6379: connect: connection refused"
**time="2019-11-20T16:39:01Z" level=debug msg="Trying: Dial(): redis localhost:6379"
time="2019-11-20T16:39:01Z" level=error msg="Couldn't connect to redis instance"
time="2019-11-20T16:39:01Z" level=debug msg="connectToRedis( redis://localhost:6379 ) err: dial redis: unknown network redis"**
time="2019-11-20T16:39:07Z" level=debug msg="keys: []main.dbKeyPair(nil)"
time="2019-11-20T16:39:07Z" level=debug msg="singleKeys: []main.dbKeyPair(nil)"
time="2019-11-20T16:39:07Z" level=debug msg="Trying DialURL(): redis://redis-2:6379"
time="2019-11-20T16:39:07Z" level=debug msg="connected to: redis://redis-2:6379"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - running command: CLIENT [SETNAME redis_exporter]"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - running command: CONFIG [GET *]"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - running command: INFO [ALL]"
time="2019-11-20T16:39:07Z" level=debug msg="c.Do() - done"
time="2019-11-20T16:39:07Z" level=debug msg="info: # Server"
time="2019-11-20T16:39:07Z" level=debug msg="info: redis_version:4.0.14"
time="2019-11-20T16:39:07Z" level=debug msg="info: redis_git_sha1:00000000"
time="2019-11-20T16:39:07Z" level=debug msg="info: redis_git_dirty:0"
time="2019-11-20T16:39:07Z" level=debug msg="info: redis_build_id:d5cb9d9a74410bd0"
time="2019-11-20T16:39:07Z" level=debug msg="info: redis_mode:standalone"
time="2019-11-20T16:39:07Z" level=debug msg="info: os:Linux 3.10.0-957.1.3.el7.x86_64 x86_64"
time="2019-11-20T16:39:07Z" level=debug msg="info: arch_bits:64"
time="2019-11-20T16:39:07Z" level=debug msg="info: multiplexing_api:epoll"
time="2019-11-20T16:39:07Z" level=debug msg="info: atomicvar_api:atomic-builtin"
time="2019-11-20T16:39:07Z" level=debug msg="info: gcc_version:8.3.0"
time="2019-11-20T16:39:07Z" level=debug msg="info: process_id:33"
time="2019-11-20T16:39:07Z" level=debug msg="info: run_id:bde747dcc6272699006c6e4f375eef2938fed802"
time="2019-11-20T16:39:07Z" level=debug msg="info: tcp_port:6379"
time="2019-11-20T16:39:07Z" level=debug msg="info: uptime_in_seconds:1081296"
time="2019-11-20T16:39:07Z" level=debug msg="info: uptime_in_days:12"
time="2019-11-20T16:39:07Z" level=debug msg="info: hz:10"
time="2019-11-20T16:39:07Z" level=debug msg="info: lru_clock:13986859"
time="2019-11-20T16:39:07Z" level=debug msg="info: executable:/data/redis-server"
time="2019-11-20T16:39:07Z" level=debug msg="info: config_file:/opt/blabla/conf/redis.conf"
time="2019-11-20T16:39:07Z" level=debug msg="info: "
time="2019-11-20T16:39:07Z" level=debug msg="info: # Clients"
time="2019-11-20T16:39:07Z" level=debug msg="info: connected_clients:8"
time="2019-11-20T16:39:07Z" level=debug msg="info: client_longest_output_list:0"
time="2019-11-20T16:39:07Z" level=debug msg="info: client_biggest_input_buf:0"
time="2019-11-20T16:39:07Z" level=debug msg="info: blocked_clients:0"
time="2019-11-20T16:39:07Z" level=debug msg="info: "
time="2019-11-20T16:39:07Z" level=debug msg="info: # Memory"
time="2019-11-20T16:39:07Z" level=debug msg="info: used_memory:2447664"
time="2019-11-20T16:39:07Z" level=debug msg="info: used_memory_human:2.33M"
time="2019-11-20T16:39:07Z" level=debug msg="info: used_memory_rss:5701632"
time="2019-11-20T16:39:07Z" level=debug msg="info: used_memory_rss_human:5.44M"
time="2019-11-20T16:39:07Z" level=debug msg="info: used_memory_peak:2726240"
...

**Comment by oliver006** [comment]
Are you by any chance scraping the exporter itself? I don't see it in the prometheus.yml config but that might explain it.
[The docs here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
) say to set `--redis.addr=` - try doing that, I don't think you do right now.

**Comment by arnaudlemaignen** [comment]
thanks it works !
you can close the ticket

**Comment by oliver006** [comment]
Woooohoooooooooo!

**Comment by Joshua-Igoni** [comment]
Hi i am having the same issue, but i am using grafana agent, i have also set up the agent config using the redis_addr attribute but still getting same error. here is my agent config below;

```
server:
    log_level: info

metrics:
  wal_directory: /tmp/agent
  global:
    scrape_interval: 15s
    remote_write:
    - url: https://prometheus-us-central1.grafana.net/api/prom/push
      basic_auth:
        username: user-id
        password: api-token

integrations:
   redis_exporter:
      enabled: true
      redis_addr: "redis:6379"
```

is there something am missing?
