### ISSUE TITLE
LLEN Key

### ISSUE THREAD

**Issue by Idriel** [oliver006/redis_exporter#337]
Hi, 

Is it possible to get "LLEN Key" through env variable as metric?
Something that will do the same as: redis-cli llen key

Thanks.

**Comment by oliver006** [comment]
Have you looked at the `--check-keys` command line parameter? 

https://github.com/oliver006/redis_exporter#flags

That might be what you want to use.

**Comment by Idriel** [comment]
it'll return mi 0 or 1 if list exist's. When list exists I want to get list length. I am trying success and error methods. For now, all error methods. :D

**Comment by oliver006** [comment]
Can you run the exporter with `--debug` to get more verbnose output so I can see which command the exporter is actually trying to use to get the length of the key? 

What type is the key exactly (run `TYPE <<key name>>` ?

**Comment by Idriel** [comment]
```
time="2019-12-06T08:49:44Z" level=debug msg="keys: []main.dbKeyPair(nil)"
time="2019-12-06T08:49:44Z" level=debug msg="e.singleKeys: []main.dbKeyPair{main.dbKeyPair{db:\"0\", key:\"TYPE collector\"}}"
time="2019-12-06T08:49:44Z" level=debug msg="e.keys: []main.dbKeyPair(nil)"
time="2019-12-06T08:49:44Z" level=debug msg="allKeys: []main.dbKeyPair{main.dbKeyPair{db:\"0\", key:\"TYPE collector\"}}"
time="2019-12-06T08:49:44Z" level=debug msg="c.Do() - running command: SELECT [0]"
time="2019-12-06T08:49:44Z" level=debug msg="c.Do() - done"
time="2019-12-06T08:49:44Z" level=debug msg="c.Do() - running command: TYPE [TYPE collector]"
time="2019-12-06T08:49:44Z" level=debug msg="c.Do() - done"
time="2019-12-06T08:49:44Z" level=debug msg="Key 'TYPE collector' not found when trying to get type and size."

```

**Comment by oliver006** [comment]
`key:\"TYPE collector\"`

do you have the cmd line options set to `"TYPE collector"` ? Should that be `collector` only?

**Comment by oliver006** [comment]
Closing, please re-open if you have more questions.
