### ISSUE TITLE
REDIS_EXPORTER_INCL_SYSTEM_METRICS="true" doesn't export redis_total_system_memory_bytes

### ISSUE THREAD

**Issue by analytically** [oliver006/redis_exporter#338]
Running latest, setting REDIS_EXPORTER_INCL_SYSTEM_METRICS to "true" doesn't export redis_total_system_memory_bytes

**Comment by oliver006** [comment]
Just tried and it works for me with the latest master:

```
REDIS_EXPORTER_INCL_SYSTEM_METRICS=true go run .`
```

and 

```
curl -s "localhost:9121/metrics" | grep system_memory
# HELP redis_total_system_memory_bytes total_system_memory_bytes metric
# TYPE redis_total_system_memory_bytes gauge
redis_total_system_memory_bytes 5.189890048e+09
```

**Comment by analytically** [comment]
Hmm I've set REDIS_EXPORTER_INCL_SYSTEM_METRICS=true but it's not exporting the metric. Could it be due to using Elasticache's Redis?

**Comment by oliver006** [comment]
Could be.

When you connect to your Elasticache instance and run `INFO ALL`, do you see a line with `total_system_memory` ?

**Comment by oliver006** [comment]
Closing.
