### ISSUE TITLE
Multiple Instance

### ISSUE THREAD

**Issue by Mutantt** [oliver006/redis_exporter#340]
i want to the exporter use info from two instances in two separate namespaces in my k8s cluster.when i use latest image the exporter log says "couldnt connect to redis instance" but it works fine with image version 0.23.0 .
i tested two different method for addressing instances
i use configmap with this data section:

for REDIS_ADDR:

REDIS_ADDR: |-
    redis-svc.namespace1:6379
    redis-svc.namespace2:6379
for REDIS_FILE:

redis-nodes.txt: |-
    redis-svc.namespace1:6379
    redis-svc.namespace2:6379
REDIS_FILE: /root/redis-nodes.txt

also when i use v0.23.0 i cant see separate instance on grafana.these two graph s overlap on the same graph.would you please advise?

**Comment by oliver006** [comment]
See https://github.com/oliver006/redis_exporter#upgrading-from-0x-to-1x

redis_exporter 1.x only supports configuring one instance via the command line but you can have a look here https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts to see how you can scrape multiple redis instances.

**Comment by oliver006** [comment]
Closing
