### ISSUE TITLE
memory_max_bytes value is 0

### ISSUE THREAD

**Issue by ermisus** [oliver006/redis_exporter#341]
**Describe the problem**
codis_memory_max_bytes value is returning 0

**What version of redis_exporter are you running?**
INFO[0000] Redis Metrics Exporter v1.3.5    build date: 2019-12-16-18:43:41    sha1: 14dda66e724e45935782db610aca803594107ff0    Go: go1.13.5    GOOS: linux    GOARCH: amd64 

**Running the exporter**
ARGS="--log-format=txt \
--namespace=codis \
--web.listen-address=:9100 \
--redis.addr=redis://localIP:localPort \
--web.telemetry-path=/metrics"

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
memory_max_bytes value is returning 0, so Memory Usage cannot be calculated.

**Example output metric**
\# HELP codis_memory_max_bytes memory_max_bytes metric
\# TYPE codis_memory_max_bytes gauge
codis_memory_max_bytes 0
\# HELP codis_memory_used_bytes memory_used_bytes metric
\# TYPE codis_memory_used_bytes gauge
codis_memory_used_bytes 2.3862341296e+10

**Additional context**
I'm using redis exporter on codis servers and metrics all almost perfect. Here is my setup:

- OS: CentOS release 6.9 (Final)
- Kernel: Linux hostname 2.6.32-696.23.1.el6.x86_64 # 1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Codis version: Redis server v=3.2.11 sha=4803cffb:0 malloc=jemalloc-4.0.3 bits=64 build=adbbb2397aba6f7a

**Comment by oliver006** [comment]
Thanks for the detailed bug report!

`codis_memory_max_bytes` is zero if no max memory is set for your redis instance.

If you connect to your redis instance by using the `redis-cli` and run `INFO`, what value o you see for  `maxmemory` in the `# Memory` section ?

**Comment by ermisus** [comment]
You are welcome! Here is the `INFO` output:

`# Memory`
`used_memory:23972802752`
`used_memory_human:22.33G`
`used_memory_rss:39470387200`
`used_memory_rss_human:36.76G`
`used_memory_peak:39867899024`
`used_memory_peak_human:37.13G`
`total_system_memory:101163560960`
`total_system_memory_human:94.22G`
`used_memory_lua:37888`
`used_memory_lua_human:37.00K`
`maxmemory:0`
`maxmemory_human:0B`
`maxmemory_policy:noeviction`
`mem_fragmentation_ratio:1.65`
`mem_allocator:jemalloc-4.0.3`

**Comment by oliver006** [comment]
Ok, great, there you go: `maxmemory:0`

If you want to get use the  total_system_memory value to calculate usage of memory then you need to run the exporter with the `-include-system-metrics=true` command line parameter and then you can use the `redis_total_system_memory_bytes` metric.

**Comment by ermisus** [comment]
Thank you for your reply @oliver006.

**Comment by harrow1ng** [comment]
thanks @oliver006
