### ISSUE TITLE
How to get end-to-end redis latency

### ISSUE THREAD

**Issue by TarekAS** [oliver006/redis_exporter#342]
My aim is to get the total latency for a PING command, including network latency. Basically I want to simulate this command: ```redis-cli -h my_cluster --latency```

The closest I got was through this query, it's probably not correct:

```rate(redis_commands_duration_seconds_total{cmd="ping"}[5m])/ rate(redis_commands_total{cmd="ping"}[5m]) * 1000 * 1000```

What is the best way to achieve this?

**Comment by oliver006** [comment]
Ah interesting, I don't think there currently is a way to measure and record this with the redis_exporter.

I believe your query only measures the time the redis instance itself spent on the PING command.

I think the way to do this would be to measure the time for just before the [connect() here](https://github.com/oliver006/redis_exporter/blob/14dda66e724e45935782db610aca803594107ff0/exporter.go#L1132) and then send a PING and record that as the metric for a a full command network round trip.

I think it could even be helpful to break this into two metrics, one for "time it takes to open a connection" and the second one for "time it takes to send a PING and get a PONG back".

This should be easy thing to add and be quite useful, esp when monitoring hosted redis instances. 

Let me know if you want to give this a shot, I'd be happy to review a PR. If not then I'll try to find some time the next couple of days.

**Comment by oliver006** [comment]
PR #343 added metrics around connect and ping time. Let me know if this addressed your issue.
