### ISSUE TITLE
Question about cluster mode with slaves

### ISSUE THREAD

**Issue by JuniorCtba** [oliver006/redis_exporter#346]
**Describe the problem**
Will be good to have an environment config to set that we are using cluster mode, in my case is 3 master and 3 slaves and with this configuration was possible to get the information about my entire cluster.

**What version of redis_exporter are you running?**
Redis Metrics Exporter v1.3.5    build date: 2019-12-16-18:41:58

I am using in an openshift environment

**Comment by oliver006** [comment]
You should monitor each master and slave instance with a separate redis_exporter process or use a setup where you scrape multiple redis instances as explained here: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

**Comment by JuniorCtba** [comment]
Will be good if we can have this kind of monitoring with one process redis_exporter in my case using container and if it is set as cluster create more internal threads to get the other nodes to scrape the information.

**Comment by oliver006** [comment]
Sure, you can do that. In that case, look at the part of the docs that I linked above, it outlines how to scrape multiple redis instances with one exporter.

**Comment by oliver006** [comment]
Closing - please re-open if you have more questions.
