### ISSUE TITLE
Can I bring back the exporter package?

### ISSUE THREAD

**Issue by tcolgate** [oliver006/redis_exporter#347]
**Describe the problem**

I was using the exporter as a package, pre-1.0. Specifically, we used it to instantiate multiple exporters, for all redis instances from a project using Google Cloud Memorystore. The memorystore exporter isn't currently released, since it was a quick and dirty hack, but it's something I did want to make public at some point.

If I put together a PR to move the exporter back to the exporter/ subdir, would you accept it?

**Comment by oliver006** [comment]
Thanks for asking and sorry for the late reply.
I'm a little torn about bringing back the exporter package. I'd rather not cause it makes development a little more easy but let hear more about your use case. 

If you're using the exporter to monitor multiple instances, could you use the /scrape endpoint instead [as documented here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) ?

**Comment by tcolgate** [comment]
It is for multiple instances, I would effectively need to turn my existing discovery into a prometheus scrape discovery, which is doable, but obviously not quite as convenient. Or proxy /metrics from my discover on to redis_exporter, and add a label on the way back. That's a little more convenient. I can explore that a bit.

**Comment by oliver006** [comment]
`my existing discovery` - what do you currently use for discovery?

**Comment by tcolgate** [comment]
It's a go client that talk to the Google cloud memorystore API. I keep an exporter per discovered target,.

**Comment by oliver006** [comment]
`It's a go client that talk to the Google cloud memorystore API` - Hmm, if you have that client output a piece of json to disk instead and have your Prometheus server pick that up via file SD and use the `/scrape` endpoint like [described here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) then you're pretty much there.

**Comment by tcolgate** [comment]
Yes, that's what I meant by turning it into a prom scrape. I have that option, but a scrape config + exporter  is more hassle than a single pod exporter. 
  If re-exposing the exporter makes life harder, that's cool, I have a bunch of other options. This was just my preference.

**Comment by oliver006** [comment]
👍

**Comment by oliver006** [comment]
@tcolgate - see current PR #435
