### ISSUE TITLE
Question Regarding Default Dashboard

### ISSUE THREAD

**Issue by WilliamCassanova** [oliver006/redis_exporter#348]
Regarding the dashboard there are 2 graphs that are a little confusing.
The first is Commands Executed/Sec which is rate(redis_commands_processed_total) which maps to the REDIS-INFO output parameter `total_commands_processed`

The second is Command Calls/Sec which maps to what I think is an internally maintained counter?
topk(5, irate(redis_commands_total{pod=~"$instance"} [1m]))

Is there some way of describing the intent of the second?

I don't seem to have a way of labeling this specifically as a question as opposed to a bug...But that is my intent.

**Comment by oliver006** [comment]
The second graph breaks down the commands executed by command. The metrics for thast one are also coming from REDIS INFO:

```
# Commandstats
cmdstat_get:calls=2,usec=34,usec_per_call=17.00
cmdstat_command:calls=1,usec=802,usec_per_call=802.00
cmdstat_info:calls=2,usec=299,usec_per_call=149.50
```

**Comment by WilliamCassanova** [comment]
Thank you.
