### ISSUE TITLE
Dashboard question: Viewing overall sentinel cluster metrics?

### ISSUE THREAD

**Issue by naseemkullah** [oliver006/redis_exporter#352]
Hi @oliver006 ,

Currently we have a few redis sentinels deployed where each redis runs alongside an exporter. In the dashboard today it is not possible to see all cluster members at the same time in the dashboard

Is having the drop down as a `multi` a possibility? 
👎 This does make the process of switching redises more more cumbersome (uncheck, check, uncheck, check)
 👍But allows us to see a cluster (check all members of cluster).

If not, would you have a suggested approach? Perhaps there is an exporter config/metrics I am unaware of that allows us to see performance of the cluster as whole in the dashboard.

**Comment by oliver006** [comment]
I would want to keep the included sample dashboard to be exactly that, a sample dashboard that solves 80-99% of the needs of users that set up redis_exporter, Prometheus and Grafana for the first time.
It should serve as a starting point and any customization that is particular to a users needs can be done on their end without having to be contributed back into the repo.

I think rop-down as multi would be useful for everyone but I wouldn't want to include sentinel specific settings/changes.

Just be aware, making the dashboard work with multiple redis instances will pose some problems. For instance, you'll have to decide on a per-panel basis if you want to aggregate stats or label them each with the instance they belong to.
Also, the single stat panels at the top like uptime won't make much sense in a multi-instance context.

**Comment by naseemkullah** [comment]
Totally agree. To be clear, you *don't* mind changing the drop down to `multi-value` and then, as you mention, decide on a per-panel basis what to do?

**Comment by oliver006** [comment]
Nope, I don't mind changing it to multi-mode.

**Comment by naseemkullah** [comment]
Great, will get started on that soon!

**Comment by vijayakumar1** [comment]
Iam trying to create exporter for 6 redis services   it's give very late response. Prometheus is unable to read metrics.
upto 4 redis services it's working fine .

**Comment by oliver006** [comment]
@vijayakumar1 - this seems unrelated to this issue, can you open a separate one and please provider more information about what your setup looks like? What version exporter you run, what you scrape (and how), what's slow, etc etc
