### ISSUE TITLE
About  Redis's Password

### ISSUE THREAD

**Issue by yiyiqian** [oliver006/redis_exporter#356]
if  Redis's password includes "!",  I found,  In grafana platform,  no data was shows there. Then I check the file "nohup.out" , it doesn't record any error .

**Comment by oliver006** [comment]
How do you run the exporter (cmd line parameters, how do you pass config values, etc)? 
What's the output if you curl the exporter metrics endpoint ?

My suspicion is that you pass the password via the command line and your shell escapes or swallows the `!`.

**Comment by oliver006** [comment]
Closing.
