### ISSUE TITLE
failed to scrape metrics if ssl is enabled

### ISSUE THREAD

**Issue by cfbytes** [oliver006/redis_exporter#362]
My redis cluster is setup with ssl enabled, I can use my cert and key to collect to redis server from cli. 
But when starting with redis_exporter, it failed scrape metrics.

Starting log:
./redis_exporter -tls-client-cert-file=/opt/xxxx.com.cert.pem -tls-client-key-file=/opt/xxx.key -redis-only-metrics=true -redis.addr=xxxx:6379 -debug=true -skip-tls-verification=false
INFO[0000] Redis Metrics Exporter v1.3.5    build date: 2019-12-16-18:43:41    sha1: 14dda66e724e45935782db610aca803594107ff0    Go: go1.13.5    GOOS: linux    GOARCH: amd64
DEBU[0000] Enabling debug output
DEBU[0000] keys: []main.dbKeyPair(nil)
DEBU[0000] singleKeys: []main.dbKeyPair(nil)
INFO[0000] Providing metrics at :9121/metrics
DEBU[0000] Configured redis addr: "xxxx:6379"
DEBU[0044] Trying DialURL(): redis://xxxx:6379
DEBU[0044] connected to: xxxx:6379

Then try to curl the metrics endpoint with: curl http://127.0.0.1:9121/metrics, get below error log

DEBU[0044] c.Do() - running command: CLIENT [SETNAME redis_exporter]
DEBU[0044] c.Do() - err: read tcp xxxx:53061->xxxx:6379: read: connection reset by peer
DEBU[0044] c.Do() - done
ERRO[0044] Couldn't set client name, err: read tcp xxxx:53061->xxxx:6379: read: connection reset by peer
DEBU[0044] c.Do() - running command: CONFIG [GET *]
DEBU[0044] c.Do() - err: write tcp xxxx:53061->xxxx:6379: use of closed network connection
DEBU[0044] c.Do() - done
DEBU[0044] Redis CONFIG err: write tcp xxxx:53061->xxxxx:6379: use of closed network connection
DEBU[0044] c.Do() - running command: INFO [ALL]
DEBU[0044] c.Do() - err: write tcp xxxxx:53061->xxxxx:6379: use of closed network connection
DEBU[0044] c.Do() - done
DEBU[0044] c.Do() - running command: INFO []
DEBU[0044] c.Do() - err: write tcp xxxxx:53061->xxxx:6379: use of closed network connection
DEBU[0044] c.Do() - done
ERRO[0044] Redis INFO err: write tcp xxxxx:53061->xxxxx:6379: use of closed network connection

From redis-cli, i can run commant "CLIENT SETNAME redis_exporter"

**Comment by oliver006** [comment]
Could try adding `rediss://` to the address? (note the double `s`)

**Comment by cfbytes** [comment]
It works! Thanks a lot.
