### ISSUE TITLE
Whether I can configure the password in Prometheus

### ISSUE THREAD

**Issue by for-mat** [oliver006/redis_exporter#367]
**Describe the problem**
There are many redis and their passwords are different,If I have to start many redis_exporters, I want to be able to deploy in bulk and configure the password in Prometheus.Then I don't need to start with parameters -redis.password.
I try this way  redis://h:paswd@host:6379   ,but there is no effective

**What version of redis_exporter are you running?**
v1.3.5

**prometheus config
  - job_name: 'tssss'
    static_configs:
      - targets:
        - 'redis://10.228.129.158:6379'
        - 'redis://10.228.129.158:6380'
        - 'redis://h:xxxxx@10.228.137.114:6379'
    metrics_path: /scrape 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.228.137.114:9121

**Comment by oliver006** [comment]
Passing the password like this is currently not supported, see e.g. #364 for more details.
