### ISSUE TITLE
老师，能不能给个redis_exporter v 1.3.1 的docker镜像或镜像名称。

### ISSUE THREAD

**Issue by zbaolong** [oliver006/redis_exporter#370]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by ylmcr7** [comment]
# go build .

好长时间  没有动静
