### ISSUE TITLE
Why can't I see cmdstat metrics?

### ISSUE THREAD

**Issue by zivori** [oliver006/redis_exporter#373]
**Describe the problem**

I'm running Redis 5.0.8 (using docker image redis:5.0.8-buster) and seeing Commandstats in Redis itself 
`# Commandstats
cmdstat_ping:calls=1,usec=0,usec_per_call=0.00
cmdstat_monitor:calls=1,usec=2,usec_per_call=2.00
cmdstat_command:calls=11,usec=15593,usec_per_call=1417.55
cmdstat_latency:calls=26530,usec=57896,usec_per_call=2.18
cmdstat_client:calls=25286,usec=55196,usec_per_call=2.18
cmdstat_psync:calls=1,usec=513,usec_per_call=513.00
cmdstat_replconf:calls=1343921,usec=1866803,usec_per_call=1.39
cmdstat_info:calls=26544,usec=2576999,usec_per_call=97.08
cmdstat_cluster:calls=26542,usec=1833206,usec_per_call=69.07
cmdstat_config:calls=26530,usec=2086274,usec_per_call=78.64
cmdstat_slowlog:calls=53060,usec=125366,usec_per_call=2.36
cmdstat_auth:calls=26886,usec=61298,usec_per_call=2.28`

But not in redis-exporter 1.5.2  (Using Docker image: oliver006/redis_exporter:v1.5.2-alpine , for example)
and with the following run command

ENTRYPOINT [ \
                "/redis_exporter", \
                "-namespace=default", \
                "-redis.password=...", \
                "-redis.addr=" \
           ]

I do see other metrics in redis-exporter
`
...
default_exporter_build_info{build_date="2020-03-16-20:51:44",commit_sha="18080da36b0a97595d308cfb4bdf92eb1e396c44",golang_version="go1.14",version="v1.5.2"} 1
...
default_exporter_scrapes_total 41
...
go_memstats_last_gc_time_seconds 1.5868496821038551e+09
...
process_cpu_seconds_total 8.23
...
process_resident_memory_bytes 1.6662528e+07
...
`

What am I missing?

**Comment by kotchaosu** [comment]
@zivori Could you please tell me, what was the reason? I'm encountering similar issue with exporter v1.5.3. I assume from the code that failing `INFO ALL` fallbacks silently to `INFO` which misses the **Commandstats** section.
