### ISSUE TITLE
How to scrape multiple instance?

### ISSUE THREAD

**Issue by ygqygq2** [oliver006/redis_exporter#375]
`-e REDIS_ADDR='10.25.231.107:6379,10.25.231.107:6380'`
`-e REDIS_ADDR='redis://10.25.231.107:6379,redis://10.25.231.107:6380'`
the same errors:

```
redis_exporter_last_scrape_error{err="dial tcp: address redis://10.25.231.107:6379,redis://10.25.231.107:6380: too many colons in address"} 1
```

```
redis_exporter_last_scrape_error{err="dial tcp: address 10.25.231.107:6379,10.25.231.107:6380: too many colons in address"} 1
```

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#upgrading-from-0x-to-1x
and
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
