### ISSUE TITLE
No data points from data query

### ISSUE THREAD

**Issue by Tiffanyxq** [oliver006/redis_exporter#376]
Hi, I have some questions in grafana dashboard.
I use the Redis-5.0.7, and I want to show its metrics by using Prometheus and grafana. I find my prometheus is working and the redis metrics are right, but Grafana doesn't have data points. I'm so confused.
![image](https://user-images.githubusercontent.com/28520733/80485835-b3038300-898c-11ea-97fd-f065625b39fc.png)

The redis_up is 1. But the Grafana has no data points.
![image](https://user-images.githubusercontent.com/28520733/80485744-8ea7a680-898c-11ea-843c-2267280b4edd.png)

Thanks soooooo much!

**Comment by oliver006** [comment]
Not sure what's going wrong - did you try to take one of the queries in grafana and run them in prometheus directly to see if data is available?

**Comment by Tiffanyxq** [comment]
Hi, oliver!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;I tried it and updated the edition of the Grafana to the newest one,&nbsp; it works well now!&nbsp; I think the reason is the edition of Grafana I used yesterday is too old. Thanks for helping~
Best wishes
Tiffany



---Original---

**Comment by oliver006** [comment]
Great to hear!
