### ISSUE TITLE
Correct the Dockerfile.arm on the

### ISSUE THREAD

**Issue by digas** [oliver006/redis_exporter#378]
Please correct the arch type on this file 

Where you have on line 9 :
` ARG GOARCH="amd64"`
should be:
` ARG GOARCH="arm"`

On line 17 too 
`RUN [ $GOARCH = "amd64" ]  && /redis_exporter -version || ls -la /redis_exporter`

**Comment by oliver006** [comment]
Thanks, that's a good catch, I'll get this fixed asap.

Line 17 is as intended, it's only running the `/redis_exporter --version` command when the `ARCH == amd64` because the build host being an amd64 image and otherwise there's an error cause the executable not matching the platform.

**Comment by digas** [comment]
Nice thank you for your work , keep on

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.6.0
