### ISSUE TITLE
How to config COUNT in the "check-keys" command line flag,just like the option in SCAN(SCAN cursor [MATCH pattern] [COUNT count])

### ISSUE THREAD

**Issue by fengyinqiao** [oliver006/redis_exporter#381]
**Describe the problem**
I have known the exporter support key patterns in the "check-keys" command line flag,but there is no way to config COUNT,just like the option in SCAN(SCAN cursor [MATCH pattern] [COUNT count]).How can I do it ?

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by fengyinqiao** [comment]
Looking forward to your reply.Thank you!

**Comment by oliver006** [comment]
Sorry, there is currently no way to do this.
However, this shouldn't be hard to add. If you submit a PR I'll be happy to review and merge it.
