### ISSUE TITLE
Cannot connect to redis using ssl because there is no option to pass ca cert

### ISSUE THREAD

**Issue by SarjakShirishShah** [oliver006/redis_exporter#387]
**Describe the problem**
Cannot connect to redis using ssl because there is no option to pass ca cert

**What version of redis_exporter are you running?**
 Redis Metrics Exporter v0.31.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Provided these environment variables in helm chart
REDIS_ADDR = rediss://localhost:6385
REDIS_PASSWORD = <password>
REDIS_EXPORTER_TLS_CLIENT_KEY_FILE = /path/to/client.key
REDIS_EXPORTER_TLS_CLIENT_CERT_FILE = /path/to/client.cert

**Additional context**
I think redis needs CA cert as well, and I don't see a paramter to pass that in redis-exporter

Logs on redis, when redis-exporter tries to connect:
May 2020 22:39:56.416 # Error accepting a client connection: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate

**Comment by oliver006** [comment]
Hey there. I can't find the discussion in a past issue/PR but I _think_ this is a known issue and could use some help by someone that want's to submit a PR.

Implementation should be very similar to https://github.com/oliver006/redis_exporter/pull/264
