### ISSUE TITLE
Redis Server in Windows environment requires authentication

### ISSUE THREAD

**Issue by xuuechen** [oliver006/redis_exporter#388]
version: 1.6.1
redis_exporter:  redis_exporter-v1.6.1.windows-amd64
description:  Our redis server requires password to login in, when i use this to gain some metrics, redis_exporter.exe displays "NOAUTH Authentication Required".   In Linux environment,we can use "-redis.password xxxxx" ,but In Windows environment, this is a ".exe"  program, How can I do?
Thanks

**Comment by xuuechen** [comment]
sorry, I has found solution.  I didn't read “readme.md” carefully. Thanks!!

**Comment by oliver006** [comment]
🎉
