### ISSUE TITLE
How we can use this redis_exporter to push aws redis cache metrics to Prometheus?

### ISSUE THREAD

**Issue by chandu484** [oliver006/redis_exporter#389]
Hi ,

I have used your redis_exporter image to push local redis instance metrics to prometheus.That was really easy and wonderful. I love the metrics coming to prometheus and grafana at the end. But I'm not sure how we can use this for aws redis cluster as they open only port 6379 and we can't see any metrics from that port! I see you have something for azure redis cluster in the readme. 
Could you let me know how we can use it for AWS redis cluster #REDIS #AWS #HELP

**Comment by oliver006** [comment]
How did you try to run the exporter? What's the log output?

You should be able to pass the address of your AWS cluster to the redis_exporter using `--addr=<<address here>>` and it should be able to scrape the instance just fine.

**Comment by aravind** [comment]
Using redis.addr works for a single server. We typically run a cluster of redis servers in AWS - Prior to https://github.com/oliver006/redis_exporter/pull/256 we would stick all of these instances in a config file and let the exporter scrape them. With the above PR - the idea is to configure the prometheus server to tell the exporter to scrape all of these servers instead. This presents some issues in our environment:

1. Prometheus typically doesn't know anything about the redis clusters/servers meant for an application - the application configs typically contain this information and it isn't visible to the prometheus server.

**Comment by oliver006** [comment]
Closing - please re-open as needed.
