### ISSUE TITLE
Add redis_up gauge

### ISSUE THREAD

**Issue by filippog** [oliver006/redis_exporter#39]
Hi!
thanks for redis_exporter!
In line with other exporters (e.g. memcached) it'd be nice to provide a gauge `redis_up` 0/1 whenever redis scraping fails or succeeds.

thanks!

**Comment by oliver006** [comment]
There is `exporter_last_scrape_error`, see code here: https://github.com/oliver006/redis_exporter/blob/master/exporter/redis.go#L168

I think that provides what you're looking for?

**Comment by filippog** [comment]
Sort of, it is the other way around wrt to what it means though. I think it'd be nice to have the `up` gauge for consistency with other exporters if anything, would also help counting how many redis instances can be scraped, alerting, etc.

**Comment by oliver006** [comment]
Hmm, ok, I see. I'll see that I add an `up` gauge but in the meantime you can use the existing gauge to pretty much the same effect.

**Comment by eagafonov** [comment]
Oops, I've implemented it accidentally... Wait for a MR soon
