### ISSUE TITLE
redis exporter is up in targets but prom doesn't scrape

### ISSUE THREAD

**Issue by jividijuvent** [oliver006/redis_exporter#391]
Hi, I had several redis exporters working, after a prom server reset, exporters are up in targets page on prometheus, but when running "up" query, returns 0 and prom doesn't see exporters, on the same server, I have node_exporter that works fine, also prom server sees the /metrics URL.
anybody has any idea?

**Comment by oliver006** [comment]
Any indication on the Promerheus server side why the scrapes fail? What does it say on the Targets page? Anything in the logs?
