### ISSUE TITLE
Precompiled Binary for SmartOS/Illumos?

### ISSUE THREAD

**Issue by neuroserve** [oliver006/redis_exporter#401]
Currently there is no precompiled binary of the redis_exporter for Illumos based operating systems (like SmartOS, Omnios, etc.).
What would be neccessary in order to get one (e. g. for SmartOS)?
I just checked. Compiling on SmartOS (base-64-lts 19.4.0) with go113-1.13.5 works OK.

**Comment by oliver006** [comment]
It looks like it would be a matter of adding another build step [here](https://github.com/oliver006/redis_exporter/blob/master/build-github-binaries.sh#L26 ) and using GOOS=illumos (plus the architectures that it's available for, amd64? anything else?)
Not sure if you'd also want Docker images, that would require a new Dockerfile and a new step in the drone file.

Happy to review & merge a PR if you submit one!

**Comment by neuroserve** [comment]
I didn't know, that a builder for illumos/amd64 exists. That is great news!
Docker images would not be neccessary at the moment - Illumos runs Linux Docker images in lx-branded zones and there is no Docker implementation on Illumos.
Then I guess, I'd have to find out how to create a PR :-)

**Comment by oliver006** [comment]
I added binaries for Illumos in #415 - [the latest release has a binary](https://github.com/oliver006/redis_exporter/releases/tag/v1.11.0) for it, can you give it a spin and see if they work for you?

**Comment by oliver006** [comment]
Closing this. Please re-open if there's an issue with the provided binary.

**Comment by neuroserve** [comment]
Sorry for being late (vacation) - a short test on my minimal-64-lts@19.4.0 SmartOS Zone worked as expected. Thank you for your support!
