### ISSUE TITLE
New metric "maxmemory_policy"?

### ISSUE THREAD

**Issue by frenkye** [oliver006/redis_exporter#403]
Hi,

great exporter, I was wondering if it would be possible add metric for used maxmemory_policy which is available under `info memory`

With some metric like:
redis_maxmemory_policy{policy="noeviction|allkeys-lru|...."} 1 

We have multiple instances with all kind of diffrent policies and this info in alert with maxmemory used would safe some calls in the night.

**Comment by oliver006** [comment]
Thanks for raising this issue!
I think this could be useful and shouldn't be hard to implement. I'm currently a little low on time but would gladly accept a PR.
