### ISSUE TITLE
New metrics for memory reservation

### ISSUE THREAD

**Issue by jon-walton** [oliver006/redis_exporter#404]
Thanks for the exporter!

We're using Azure's managed redis, I would like to view metrics for memory reservations, namely `maxfragmentationmemory_reservation` and `maxmemory_reservation`

However, I'm not sure if these are standard metrics? (not listed at https://redis.io/commands/info , documented at https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-configure#memory-policies)

Would you be open to a pull request to add these? if so, how would you like them added?

```promql
redis_memory_max_reservation_bytes{}
redis_memory_max_fragmentation_reservation_bytes{}
```

as an example

**Comment by oliver006** [comment]
Hey there, a PR is definitely welcome!

As for the name or how to implement this, is this a value that can be retrieved from `CONFIG GET` via the cli? 
If yes then you could leverage this code here and see if the metric gets added if you add the correct redis config field to this map: https://github.com/oliver006/redis_exporter/blob/3e15a27ef8657e77100a55f10895e1a4fee70f79/exporter.go#L652-L655

**Comment by jon-walton** [comment]
Unfortunately it looks like `config get` is blocked on azure redis, probably to stop people using `config set`. It also looks like these are azure specific metrics 😢

```
ERR unknown command `config`, with args beginning with: `get`, `*`,
```

azure redis `info memory` gives us

```
maxmemory
maxmemory_reservation
maxfragmentationmemory_reservation
maxmemory_desired_reservation
maxfragmentationmemory_desired_reservation
```

vanilla redis `info memory` or `config get *memory*` doesn't have them. I'm not sure you'll want to add provider specific metrics? (what does [insert favorite cloud provider here] expose? etc), or perhaps with an `azure_` prefix?

**Comment by oliver006** [comment]
Interesting. Sounds like extracting the data from the "INFO" command is the way to go.
I'd say use `redis_memory_max_fragmentation_reservation_bytes` and wouldn't include an `azure_` prefix.
