### ISSUE TITLE
redis_exporter basic auth

### ISSUE THREAD

**Issue by gongjiang2** [oliver006/redis_exporter#407]
does redis_exporter support Basic Auth like node-exporter？
If I want to get the monitoring data of redis, I should enter the username and password.

**Comment by oliver006** [comment]
> does redis_exporter support Basic Auth like node-exporter？

redis_exporter does not support basic auth natively, you'll have to use e,g, nginx as a reverse proxy if you want auth on the http metrics endpoint.

> If I want to get the monitoring data of redis, I should enter the username and password.

Check the README, it has several examples on how to provide the exporter with Redis username and password.

**Comment by gongjiang2** [comment]
oh，thanks
