### ISSUE TITLE
Not connecting to Auzre Redis on SSL port

### ISSUE THREAD

**Issue by gambrose** [oliver006/redis_exporter#41]
I am trying to get this exported working against an Azure Redis Cache instance.
By default it uses SSL on port 6380.

I can get it working if I disable 'Allow access only via SSL' and connect to port 6379.
Is SSL support something you could add to the exporter or should I be running something else to handle the SSL connection?

**Comment by oliver006** [comment]
Interesting, I haven't tried connecting via SSL yet but let me look into what's needed to enable SSL/TLS.

**Comment by gambrose** [comment]
If it helps I can create an Azure Redis instance for you to test against.
Let me know if this would be helpful and I will create a dedicated instance on my account and email you the connection details.

**Comment by oliver006** [comment]
Ah yes, that'd definitely be helpful!
You can send me the details to oliver@21zoo.com - shouldn't take more than a couple of days.
Thx!

**Comment by oliver006** [comment]
See #44

**Comment by oliver006** [comment]
And thanks for providing me with the Azure instance to test this!

**Comment by gambrose** [comment]
Testing the new build I getting and error `unknown network rediss`

Here is the output with debug logging, password redacted
```
redis_exporter.exe -redis.addr rediss://redis-exporter.redis.cache.windows.net:6380 -redis.password xxxxxxxxxxxxxxx -debug
time="2016-11-24T16:40:07Z" level=info msg="Redis Metrics Exporter v0.10.0    build date: 2016-11-24-16:14:03    sha1: 556b39d117f692295a9ad59b5623c28a0fd94a4b\n"
time="2016-11-24T16:40:07Z" level=debug msg="Enabling debug output"
time="2016-11-24T16:40:07Z" level=info msg="Providing metrics at :9121/metrics"
time="2016-11-24T16:40:07Z" level=info msg="Connecting to redis hosts: []string{\"rediss://redis-exporter.redis.cache.windows.net:6380\"}"
time="2016-11-24T16:40:10Z" level=debug msg="Trying DialURL(): rediss://redis-exporter.redis.cache.windows.net:6380"
time="2016-11-24T16:40:10Z" level=debug msg="Trying: Dial(): rediss redis-exporter.redis.cache.windows.net:6380"
time="2016-11-24T16:40:10Z" level=info msg="redis err: dial rediss: unknown network rediss"
```

**Comment by oliver006** [comment]
Weird, looks like the circle build is using an outdated version of the redis library. Let me see that I force updating the dependencies on every build.

**Comment by oliver006** [comment]
I cut a new release: https://github.com/oliver006/redis_exporter/releases/tag/v0.10.2

I tried the OSX build and it works but can you try the windows version?

**Comment by gambrose** [comment]
Just tested It works a treat. 
Thanks so much for you time and perseverance getting this working @oliver006.

**Comment by oliver006** [comment]
No problem, glad to hear it's working!
