### ISSUE TITLE
Disable default localhost scrape

### ISSUE THREAD

**Issue by cuotos** [oliver006/redis_exporter#410]
version 1.8.0
GKE (k8s 1.16)

Is it possible to disable the default scrape of "localhost"?

We are using prometheus to scrape via the `/scrape` api, so would like the exporter to sit there silently unless asked to do something.

currently it is just logging that it could not connected to localhost repeatedly.

**Comment by cuotos** [comment]
have since spotted

`Run the exporter with the command line flag --redis.addr= so it won't try to access the local instance every time the /metrics endpoint is scraped.`

**Comment by tiaoxixiaoji** [comment]
> 
> 
> have since spotted
> 
> `Run the exporter with the command line flag --redis.addr= so it won't try to access the local instance every time the /metrics endpoint is scraped.`

Run the exporter with the command line flag --redis.addr=, but it doesn't work. Can you help me , thanks!

docker run -d --name redis-exporter -p 9121:9121 oliver006/redis_exporter:v1.15.0 --redis.addr=

time="2020-12-31T02:00:34Z" level=info msg="Redis Metrics Exporter v1.15.0    build date: 2020-12-27-18:57:29    sha1: 43ec65f7a22041e64ec557291c36500d04c6f6b0    Go: go1.15.6    GOOS: linux    GOARCH: amd64"
time="2020-12-31T02:00:34Z" level=info msg="Providing metrics at :9121/metrics"
time="2020-12-31T02:00:36Z" level=error msg="Couldn't set client name, err: NOAUTH Authentication required."
time="2020-12-31T02:00:36Z" level=error msg="Redis INFO err: NOAUTH Authentication required."
time="2020-12-31T02:00:37Z" level=error msg="Couldn't set client name, err: NOAUTH Authentication required."
time="2020-12-31T02:00:37Z" level=error msg="Redis INFO err: NOAUTH Authentication required."
