### ISSUE TITLE
remove the "v" in tar name?

### ISSUE THREAD

**Issue by nkn1111** [oliver006/redis_exporter#413]
**Describe the problem**
Most of the tar.gz bundle of prometheus exporters ends like  `<exporter_name>-<exporter_version>.<arch>.tar.gz` but the redis exporter have a extra "v" before the version `<exporter_name>-v<exporter_version>.<arch>.tar.gz`. 

In a CI pipeline, I can use a template url like 
`https://github.com/<repo_name>/<exporter>/releases/download/v<version>/<exporter>-<version>.<arch>.tar.gz`
to download almost all the commonly used exporters but not the redis exporter just because there is a "v" and it breaks the redis installation.

I know its a bit silly but it would be great help if the redis_exporter also follows the pattern as the other commonly used exporter to make life easier for the people who use CI to install and config prometheus and its exporters. 

**What version of redis_exporter are you running?**
latest

**Running the exporter**
Change this 
`https://github.com/oliver006/redis_exporter/releases/download/v1.10.0/redis_exporter-`v1.10.0`.darwin-amd64.tar.gz` --> `https://github.com/oliver006/redis_exporter/releases/download/v1.10.0/redis_exporter-`1.10.0`.darwin-amd64.tar.gz`

**Comment by sayf-eddine-scality** [comment]
Same here, breaking my packaging buildchain :D but again not urgent

**Comment by oliver006** [comment]
Closing this. I'll consider revisiting this if I release a 2.x version with breaking changes.
