### ISSUE TITLE
Exporter not able to connect to Redis instance in Openshift 

### ISSUE THREAD

**Issue by anushreemjoshi** [oliver006/redis_exporter#416]
I am using Openshift 4.3 and have deployed the exporter in a namespace. I have provided the credentials of the Redis instance as environment variable in the deployment
After the deployment, the pod for the exporter has started, however it is not able to connect to the instance and throws this error:

The configuration in deployment yaml file is as follows:
 spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter
          ports:
            - containerPort: 9121
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: <redis_url>
            - name: REDIS_USER
              value: admin
            - name: REDIS_PASSWORD
              value: <redis_password>

As i am giving the image name as 'oliver006/redis_exporter', i suppose, it downloads latest version of redis exporter.
Please let me know how to fix this issue.
Thanks.

**Comment by oliver006** [comment]
Hey there, please post the logs of the exporter, that should help with diagnosing the problem.

**Comment by anushreemjoshi** [comment]
Hello,
The logs are as follows:

time="2020-08-26T14:14:18Z" level=info msg="Redis Metrics Exporter v1.11.0    build date: 2020-08-26-00:55:27    sha1: 12519bf3ff70d4c4e4ca0fa06a3ae64347b39bbe    Go: go1.15    GOOS: linux    GOARCH: amd64"
time="2020-08-26T14:14:18Z" level=info msg="Providing metrics at :9121/metrics"
time="2020-08-26T14:14:29Z" level=error msg="Couldn't connect to redis instance"
time="2020-08-26T14:14:33Z" level=error msg="Couldn't connect to redis instance"
time="2020-08-26T14:14:36Z" level=error msg="Couldn't connect to redis instance"

**Comment by oliver006** [comment]
Thanks. Looks like there's an issue with the exporter connecting to the redis instance. 
See if connectivity is possible and try running the exporter with the --debug flag to get more detailed output.

**Comment by anushreemjoshi** [comment]
I am able to connect to the redis instance now. There was a problem in the URL that i ad specified. 
Thanks.

**Comment by pmmalinov01** [comment]
@anushreemjoshi I am facing same issue, what should be the format of the URL? are you using sidecar pattern or redis-exporter is outside the redis cluster deployment?
