### ISSUE TITLE
I want to know what is the difference between these two methods?

### ISSUE THREAD

**Issue by fengzhigu2000** [oliver006/redis_exporter#417]
The first:

scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
        - redis://second-redis-host:6380
        - redis://second-redis-host:6381
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
The secoconfigs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
        - redis://second-redis-host:6380
        - redis://second-redis-host:6381
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121

The second:

  ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - <<REDIS-EXPORTER-HOSTNAME>>:9121
      
       
     I want to know what is the difference between these two methods? I found that in the first way, no matter how I choose targets, the result is the redis information on the host where REDIS-EXPORTER-HOSTNAME is located. Can you tell me what the metrics collected in the first way are for different targets Is it different? Can you tell me how prometheus pulls information? It would be better if you could draw a picture.

**Comment by fengzhigu2000** [comment]
I use sentinel mode

**Comment by fengzhigu2000** [comment]
Which form should the sentinel mode take

**Comment by oliver006** [comment]
One let's you scrape multiple Redis instances with one exporter (using target), the other one is having one exporter per redis instance (and you scrape multiple exporters).
