### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by rayl15** [oliver006/redis_exporter#419]
Hello,

I was looking for an option to run the exporter on ipv6. How this can be done what changes I need to make?

**Comment by rayl15** [comment]
I see that it's listening on ipv6 interface.
![Screenshot 2020-09-02 at 3 00 36 PM](https://user-images.githubusercontent.com/10575622/91964780-35ca8f00-ed2d-11ea-844b-bc6c83e4183c.png)

**Comment by oliver006** [comment]
The exporter should work with IPv6 - what exactly is the problem you're seeing?
