### ISSUE TITLE
Use sentinel to find redis instances to monitor

### ISSUE THREAD

**Issue by postelrich** [oliver006/redis_exporter#422]
**Describe the problem**
I would like the exporter to monitor all redis instances monitored by sentinel. All I would do is pass in a sentinel address and the exporter would do the rest.

**What version of redis_exporter are you running?**
v1.11.1

**Comment by oliver006** [comment]
Please whatever orchestration system you use to surface all the redis instances and set up redis exporter (one or multiple instances), the exporter itself doesn't do any service discovery.

If it's a fairy static setup you could look into using the file based SD: https://prometheus.io/docs/guides/file-sd/
