### ISSUE TITLE
How do I get `maxclients` and `maxmemory` metrics from AWS Elasticache?

### ISSUE THREAD

**Issue by wangbaocongnb** [oliver006/redis_exporter#424]
**Describe the problem**

Hi, oliver006

I use redis_exporter to monitor AWS Elasticache, but there is no way to get the `maxclients` and `maxmemory` in Prometheus

Is there a way to get `maxclients` and `maxmemory` from AWS Elasticache

If so, please let me know. Thank you very much

If not, would you consider adding this feature?

**What version of redis_exporter are you running?**
```shell
$ ./redis_exporter --version
INFO[0000] Redis Metrics Exporter v1.11.1    build date: 2020-08-28-17:20:15    sha1: 3d94cd439e70d3ab478bfa65c1f131ab978a60ad    Go: go1.15    GOOS: linux    GOARCH: amd64
```

**Running the exporter**
```shell
/data/redis_exporter-v1.11.1/redis_exporter -redis.addr x.x.x.x:6381 -web.listen-address :40006
```

**Comment by wangbaocongnb** [comment]
I found the monitor item that gets the `maxmemory` metric: `redis_memory_max_bytes`

**Comment by wangbaocongnb** [comment]
`instantaneous_input_kbps` and `instantaneous_output_kbps` what is the name of redis_exporter?

**Comment by oliver006** [comment]
`instantaneous_[input|output]_kbps` are not exported.

maxclients/maxmemory depend on what "CONFIG GET *"  returns. Not sure if AWS Elasticache supports those commands and returns all the info needed.

**Comment by wangbaocongnb** [comment]
I add some code, recompile the implementation can export `instantaneous_[input|output]_kbps`

```go
...
                metricMapCounters: map[string]string{
                        "total_connections_received": "connections_received_total",
                        "total_commands_processed":   "commands_processed_total",

                        "rejected_connections":   "rejected_connections_total",
                        "total_net_input_bytes":  "net_input_bytes_total",
                        "total_net_output_bytes": "net_output_bytes_total",
+                       "instantaneous_input_kbps": "instantaneous_input_kbps",
+                       "instantaneous_output_kbps": "instantaneous_output_kbps",
...
```

**Comment by wangbaocongnb** [comment]
Thank you for your help @oliver006
