### ISSUE TITLE
How to plot command latency spikes?

### ISSUE THREAD

**Issue by axsuul** [oliver006/redis_exporter#426]
I'm on v1.11.1 and finding it challenging to plot command latency spikes by time since `redis_latency_spike_duration_seconds` only gives the last spiked value and stays at that value until another spike happens. Instead, is there a way to generate a Prometheus query so that this type of plot can be achieved?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/187961/94833639-39047980-03c4-11eb-880d-fd16917a2a7b.png">

P.S. Thanks for the exporter!

**Comment by oliver006** [comment]
Unfortunately I don't know (I don't use/plot the latency spike metrics), sorry about that.

**Comment by axsuul** [comment]
Thanks for chiming in! I found a workaround by setting the latency threshold in redis to the lowest possible value (1 ms) which delivers a lot more data points.
