### ISSUE TITLE
Unable to use count-keys functionality

### ISSUE THREAD

**Issue by laubstein** [oliver006/redis_exporter#445]
**Describe the problem**
While trying to use the count-keys functionality, I get `flag provided but not defined: -count-keys` 

**What version of redis_exporter are you running?**
v1.12.1

**Running the exporter**
`./redis_exporter -count-keys "db0=xpto::*" -redis-only-metrics`

**Expected behavior**
I was expecting to see `redis_keys_count{db="db0",key="xpto::*"} X`

**Comment by laubstein** [comment]
PR #444 fixes the problem

**Comment by oliver006** [comment]
Thank you for reporting and fixing this!
