### ISSUE TITLE
Multiple Nodes for Scraping 

### ISSUE THREAD

**Issue by alexgaganashvili** [oliver006/redis_exporter#453]
I need to provide multiple endpoints to scrape in K8s manifest. I have tried doing it as follows:

```
        env:
        - name: REDIS_ADDR
          value: "redis://localhost:26379,redis://localhost:6379"
```

However, it is not working for me. I am using the image redis_exporter:v1.12.1.
Also, I saw this when I queried http://127.0.0.1:9121/metrics while troubleshooting the issue:

`redis_exporter_last_scrape_error{err="dial tcp: address redis://localhost:26379,redis://localhost:6379: too many colons in address"} 1`

Please advise.

Thanks.

**Comment by oliver006** [comment]
Have a look at the [documentation here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) - in particular the section that explains how to scrape multiple Redis instances with one exporter.

**Comment by alexgaganashvili** [comment]
I had read the doc before opening the issues. However, it does not explain how to specify multiple redis endpoints when using redis_exporter as a sidecar.

Thanks.

**Comment by oliver006** [comment]
You must be looking at outdated documentation, with the release of 1.0.0 the support for multiple redis addresses via `redis.addr` is no longer supported.

You might be mixing up two things.

If you use redis_exporter as a side car then you should have one exporter per redis instance and can scrape all those exporters.

If you want to have one redis_exporter run in your cluster and scrape all redis instances then look at the Prometheus server yaml config at the link above, it shows you how to use `metrics_path`, `relabel_configs`, and then e.g. `static_configs` to scrape multiple redis instances via the same exporter.
