### ISSUE TITLE
It is likely to not support rediss ?

### ISSUE THREAD

**Issue by Robin-up** [oliver006/redis_exporter#458]
DEBU[0000] keys: []exporter.dbKeyPair(nil)              
DEBU[0000] singleKeys: []exporter.dbKeyPair(nil)        
DEBU[0000] streams: []exporter.dbKeyPair(nil)           
DEBU[0000] singleStreams: []exporter.dbKeyPair(nil)     
DEBU[0000] countKeys: []exporter.dbKeyPair(nil)         
INFO[0000] Providing metrics at :9121/metrics           
DEBU[0000] Configured redis addr: "rediss://XXXX:xxxxxxxx@xxxxxx.yyyyyyyy.cloud:32044/0" 
DEBU[0004] Trying DialURL(): rediss://XXXX:xxxxxxxx@xxxxxx.yyyyyyyy.cloud:32044/0 
DEBU[0004] DialURL() failed, err: ERR wrong number of arguments for 'auth' command 
DEBU[0004] Trying: Dial(): rediss rediss://XXXX:xxxxxxxx@xxxxxx.yyyyyyyy.cloud:32044/0 
ERRO[0004] Couldn't connect to redis instance           
DEBU[0004] connectToRedis( rediss://rediss://XXXX:xxxxxxxx@xxxxxx.yyyyyyyy.cloud:32044/0 ) err: dial rediss: unknown network rediss 
DEBU[0004] scrapeRedisHost() done

**Comment by oliver006** [comment]
`rediss` is supported but you might want to try the `--redis.user` and `--redis.password` parameters in conjunction with the `--redis.addr` parameter instead of putting it all in the addr parameter, that might help (I haven't personally tried the redis6 style auth with username and password)

**Comment by oliver006** [comment]
I just noticed, in your debug logs it says:
`connectToRedis( rediss://rediss://XXXX:xxxxxxxx@xxxxxx.yyyyyyyy.cloud:32044/0 )`

`rediss://rediss://` - one too many.
