### ISSUE TITLE
Redis 6 ACL : Specific redis user "Prometheus Redis Metrics Exporter" - No "default" user

### ISSUE THREAD

**Issue by cha9qaf** [oliver006/redis_exporter#460]
**Question**
How to have the good rights on the redis user used for Prometheus Redis Metrics Exporter ?

**What version of redis_exporter are you running?**
1.13.1

**Comments**
Did you work on the redis 6 ACL for a specific redis user (not use default user with all redis commands ) ?

This is an example of ACL
user username +client +ping +info +config|get +cluster|info +slowlog +latency +memory +select +get +scan +xinfo +type +pfcount +strlen +llen +scard +zcard +hlen +xlen on >userpassword

**Comment by oliver006** [comment]
Not 1oo% sure what you mean. Are you asking what ACLs to set for the user that the redis_exporter is using?

I _think_ the list of commands you listed is pretty exhaustive and looks good.

You can check all calls to [doRedisCmd()](https://github.com/oliver006/redis_exporter/blob/fe6c83f4ca18f1ce78a2d97f1474765793394dad/exporter/exporter.go#L1309) in the exporter.go file - that should give you a good idea what commands are being used.

**Comment by cha9qaf** [comment]
It was my question. To produce the list, i red your Go source. I will try this ACL list and i come back to you to validate or not this list because i understand that you never tried without using the default user (it's not secure). Best Regards.

**Comment by oliver006** [comment]
If you figure out the full list of commands for the ACL it'd be awesome if you could open a PR to get them added to the README, I'm sure it would be useful information for others.
