### ISSUE TITLE
How should I configure the redis cluster running on k8s

### ISSUE THREAD

**Issue by ktpktr0** [oliver006/redis_exporter#461]
redis: 3.2
redis-exporter: 1.x.x

My redis cluster runs on k8s (3 masters and 3 slaves); redis exporter runs on k8s; Prometheus runs on k8s.
I don't know how to configure a redis cluster running on k8s. I try the following configuration
![image](https://user-images.githubusercontent.com/41657218/101466679-61889100-397c-11eb-8faa-aee7e72c8fdf.png)

I created the servicemonitor manually
![image](https://user-images.githubusercontent.com/41657218/101466735-6fd6ad00-397c-11eb-87af-f42145aef266.png)
![image](https://user-images.githubusercontent.com/41657218/101466759-75cc8e00-397c-11eb-9525-c9f7bf8365ae.png)

However, my query expression found that all values were redis exporter, not six redis nodes
![B761CFCE-D69B-4f50-878D-99BB7AF42F85](https://user-images.githubusercontent.com/41657218/101467303-1753df80-397d-11eb-9483-e9d8e2ba0baf.png)

**Comment by oliver006** [comment]
I think a better way how to handle this would be to do have the Prometheus server do the discovery, using dns_sd_config.

You can then either

1) run a redis_exporter as a side car next to the redis instance, and scrape port 9121 of each redis_instance that was discovered (it'll scrape the redis exporter which will connect to the local redis instance)

or 

2) run one redis_exporter and have the Prometheus use the `/scrape` endpoint, see [here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) for more information.

**Comment by ktpktr0** [comment]
Using DNS_ Sd_ Config is similar to the method I use now. For the first method, it should be feasible. For the second method, it seems that it is only for redis clusters running in containers (k8s applications are accessed uniformly through service).

**Comment by oliver006** [comment]
I think the method you use is flawed cause it relies on the exporter expanding the DNS record. It will scrape a different exporter each time it resolves the address and scrape the exporters in an unpredictable order and frequency.

The second method is not just for clustering but can be used any time you don't want to run multiple exporters (one per redis instance)

**Comment by ktpktr0** [comment]
OK, I also expected this result. Therefore, I finally determined the following two methods to obtain the redis cluster running on k8s

1. Each redis pod runs a redis exporter (not recommended method, takes more resources)
+++++++redis.yaml++++++++++++
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
  - name: redis
    port: 6379
  - name: prom
    port: 9121
    targetPort: 9121
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis-cluster
  annotations:
    prometheus.io/scrape: 'true'
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        appCluster: redis-cluster
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - redis
              topologyKey: kubernetes.io/hostname
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - "--protected-mode"
          - "no"
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        - containerPort: 16379
          name: cluster
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /etc/redis
        - name: data
          mountPath: /var/lib/redis
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121
      volumes:
      - name: conf
        configMap:
          name: redis-conf
          items:
          - key: redis.conf
            path: redis.conf
  volumeClaimTemplates:
  - metadata:
      name: data
      namespace: redis-cluster
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
++++++++++++++++++++++++++++++++++++++++
+++++prometheus-additional.yaml+++++++++++
- job_name: 'redis_exporter'
  static_configs:
    - targets:
      - redis-0.redis.redis-cluster.svc.cluster.local:9121
      - redis-1.redis.redis-cluster.svc.cluster.local:9121
      - redis-2.redis.redis-cluster.svc.cluster.local:9121
      - redis-3.redis.redis-cluster.svc.cluster.local:9121
      - redis-4.redis.redis-cluster.svc.cluster.local:9121
      - redis-5.redis.redis-cluster.svc.cluster.local:9121
  relabel_configs:
    - source_labels: [__address__]
      action: replace
      target_label: instance
      regex: (.*redis.*)

![image](https://user-images.githubusercontent.com/41657218/101710043-b4249300-3acb-11eb-88e7-a2429e2326be.png)

2. Use the absolute service of each redis instance for access.
redis.yaml No change required

++++++++++++redis-exporter.yaml+++++++++++
redis.addr Configure one to get all redis instances. Of course, you can also configure all redis addresses, separated by commas
args: ["--redis.addr", "redis-0.redis.redis-cluster.svc.cluster.local:6379", "redis-1.redis.redis-cluster.svc.cluster.local:6379", "redis-2.redis.redis-cluster.svc.cluster.local:6379"]

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: monitoring
  labels:
    k8s-app: redis-exporter
spec:
  selector:
    matchLabels:
      k8s-app: redis-exporter
  template:
    metadata:
      labels:
        k8s-app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        args: ["--redis.addr", "redis-0.redis.redis-cluster.svc.cluster.local:6379"]
        ports:
        - containerPort: 9121
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9121
    targetPort: http
  selector:
    k8s-app: redis-exporter

+++++prometheus-additional.yaml+++++++++++
- job_name: 'redis_exporter_targets'
  static_configs:
    - targets:
      - redis://redis-0.redis.redis-cluster.svc.cluster.local:6379
      - redis://redis-1.redis.redis-cluster.svc.cluster.local:6379
      - redis://redis-2.redis.redis-cluster.svc.cluster.local:6379
      - redis://redis-3.redis.redis-cluster.svc.cluster.local:6379
      - redis://redis-4.redis.redis-cluster.svc.cluster.local:6379
      - redis://redis-5.redis.redis-cluster.svc.cluster.local:6379
  metrics_path: /scrape
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: redis-exporter:9121

  ## config for scraping the exporter itself
- job_name: 'redis_exporter'
  static_configs:
    - targets:
      - redis-exporter:9121

**Comment by oliver006** [comment]
Correct, those are the two options.

Though I think approach 1) is the more Prometheus-y way of doing this as per past conversations with the Prometheus folks.

One last improvement would be to use DNS or Kubernetes for SD to dynamically retrieve the list of Redis instances instead of using the static_configs for 'redis_exporter_targets' so you don't hardcode the six Redis URIs.

**Comment by ktpktr0** [comment]
3. Improvement on method one
stay redis.yaml On exposure, allowing Prometheus to collect

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  name: redis
  namespace: redis-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
  - name: redis
    port: 6379
  - name: prom
    port: 9121
    targetPort: 9121
  clusterIP: None
+++++++++++++++++++++++++++++++

Using kuberneters_ Sd_ Config to automatically discover:

- job_name: 'kubernetes-redis-cluster'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    regex: (redis.*)
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: keep
    regex: (.*redis.*)
    target_label: kubernetes_pod_name

**Comment by ktpktr0** [comment]
3. Improvement on method one
stay redis.yaml On exposure, allowing Prometheus to collect
+++++++++++++redis.yaml++++++++++++++++
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
  name: redis
  namespace: redis-cluster
  labels:
    app: redis
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
  - name: redis
    port: 6379
  - name: prom
    port: 9121
    targetPort: 9121
  clusterIP: None
+++++++++++++++++++++++++++++++++++++

Using kuberneters_ Sd_ Config to automatically discover:
++++++++++++prometheus-sd-config.yaml+++++++++++
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    regex: (redis.*)
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: keep
    regex: (.*redis.*)
    target_label: kubernetes_pod_name
++++++++++++++++++++++++++++++++++++

**Comment by oliver006** [comment]
👍

**Comment by oldthreefeng** [comment]
@oliver006  @ktpktr0  thanks for your work.  

> 3. Improvement on method one

For me. grafana is shown with `ip:port` .  is there any ways to  show by pod name.  I am not very familiar with the monitoring configuration of promethues

![image](https://user-images.githubusercontent.com/38313565/109122687-e61ccb80-7783-11eb-9729-583628b33d9f.png)

I hava serveral redis instance.  It is difficult to know what redis is from ip:port.

**Comment by ktpktr0** [comment]
The default configuration for k8s service discovery is pod name

**Comment by oldthreefeng** [comment]
@ktpktr0  thanks for your reply
we have four environment.  then we have four namespace for redis . the sts for redis cluster is the same.  Use pod name may misleading for us . 
And I found there is no namespace tag for redis_exporter?  
![image](https://user-images.githubusercontent.com/38313565/109129754-f33db880-778b-11eb-8f8e-e237ec17a895.png)
i want to use namespcae  Variables to seprate the redis resource. 
![image](https://user-images.githubusercontent.com/38313565/109129868-110b1d80-778c-11eb-8976-77325548f58f.png)
