### ISSUE TITLE
Couldn't connect to redis instance

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [oliver006/redis_exporter#463]
I'm using Ubuntu 18.04.5 LTS and have redis exporter running as a docker container; When I start this container it's running fine and I'm getting the metrics I need but after sometime it shows **Couldn't connect to redis instance** error;
Please let me know how to fix this issue.
Thanks.

**Version of redis_exporter**
Redis Metrics Exporter v1.13.1
`INFO[0000] Redis Metrics Exporter v1.13.1    build date: 2020-11-02-14:44:38    sha1: f3d90ddcf7f772ee67332d0172e87c07bdab67a2    Go: go1.15.3    GOOS: linux    GOARCH: amd64`

**Command used for running the exporter**
`docker run -itd --name redis_production_exporter --restart unless-stopped oliver006/redis_exporter -redis.addr <redis_instance> -redis.password <redis_instance_pwd>`

**Screenshots**
![image](https://user-images.githubusercontent.com/63767821/102036681-72585d00-3de9-11eb-94cf-69c59ab8e175.png)

**Comment by oliver006** [comment]
Did you try running with the `--debug` flag to see if there's more information?

And can you confirm that you can connect to the redis container from the exporter container using e.g. telnet or similar?
