### ISSUE TITLE
A URI including a password not work, Error: NOAUTH Authentication required

### ISSUE THREAD

**Issue by Ansen** [oliver006/redis_exporter#464]
**Describe the problem**

> redis server version 4.0.x

A URI including a password not work, I do not know why.

json formart

```json
[
  {
    "targets": ["redis://h:123456@192.168.8.73:6379"],
    "labels": {
      "alias": "test-redis-6379",
      "channel": "test",
      "type": "db",
      "isTest": "false"
    }
  }
]
```

![图片](https://user-images.githubusercontent.com/676412/102216694-7d5cdb80-3f16-11eb-8fe5-e07dc8c7edc0.png)

**What version of redis_exporter are you running?**

- Redis Metrics Exporter v1.14.0
- build date: 2020-12-10-01:08:38
- sha1: fcb9a8fdf63125ee43a40cf6a6dae2e37414c2b0
- Go: go1.15.6
- GOOS: linux 
- GOARCH: amd64"

**Running the exporter**
![图片](https://user-images.githubusercontent.com/676412/102216064-91540d80-3f15-11eb-8d7a-b85e939a6493.png)

Prometheus config

![图片](https://user-images.githubusercontent.com/676412/102216157-b47ebd00-3f15-11eb-92d6-8abec5d8c3bf.png)

**Screenshots**
![图片](https://user-images.githubusercontent.com/676412/102216233-cd876e00-3f15-11eb-9cef-2f18de659a64.png)

**Comment by oliver006** [comment]
Passing a password via the target parameter to /scrape is not supported, [see the README here](https://github.com/oliver006/redis_exporter#authenticating-with-redis).

**Comment by Ansen** [comment]
> 
> 
> Passing a password via the target parameter to /scrape is not supported, [see the README here](https://github.com/oliver006/redis_exporter#authenticating-with-redis).

In this case, should I deploy an exporter for each redis instance?

**Comment by oliver006** [comment]
Yeah, that's the preferred way to do it.
