### ISSUE TITLE
Improved documentation (Readme file) : Add specific redis user (Redis 6 only) for Prometheus Redis Exporter 

### ISSUE THREAD

**Issue by cha9qaf** [oliver006/redis_exporter#468]
After testing on v1.13.1 exporter successfully, if you don't want use the 'default' user, this is the user to declare on redis server for Prometheus Redis Metrics Exporter 

ACL SETUSER [username] +client +ping +info +config|get +cluster|info +slowlog +latency +memory +select +get +scan +xinfo +type +pfcount +strlen +llen +scard +zcard +hlen +xlen +eval allkeys on >[userpassword] 

You could add in your Readme file. 

Thanks a lot. No Pull Request only for a detail in Readme file as you asked previously.

**Comment by oliver006** [comment]
Thanks, I'll get this added to the README in the next couple of days.

**Comment by oliver006** [comment]
Added in e61c18eeaed87b140b82c512b4ef0ff73ef8c1cc 
Thanks for finding out the exact command to add the user!
