### ISSUE TITLE
Old version of last release

### ISSUE THREAD

**Issue by jsedy7** [oliver006/redis_exporter#47]
I tried to install new release of exporter to my server, but in metrics is a value with older version.
In your changelog is adding metric "up" to new release, but I haven't this value in my redis exporter.  
Is that a [new release](https://github.com/oliver006/redis_exporter/releases/tag/v0.10.4) of exporter? 

> redis_exporter_build_info{build_date="2016-12-02-21:09:17",commit_sha="a410b50d53985b76f117a6d9ee81ab052c8c1c91",golang_version="go1.7.3",version="v0.10.3"} 1

Thank you :)

**Comment by jsedy7** [comment]
I'm sorry. I found problem in my exporter. All of this git works correctly. I'm sorry.
Actual version: 
> redis_exporter_build_info{build_date="2016-12-19-17:31:10",commit_sha="45ed897e72098fbaf87bb15e0c844c23a1db3f0b",golang_version="go1.7.3",version="v0.10.4"} 1

**Comment by oliver006** [comment]
np, good to hear you figured it out.
