### ISSUE TITLE
Is there a large key monitoring and Slowest Calls?

### ISSUE THREAD

**Issue by heheliu321** [oliver006/redis_exporter#471]
Such as：
Slowest Calls
========================================
3490.75     "SMEMBERS" "friendlist:zzz:1:2"
2362.0      "SMEMBERS" "friendlist:xzz:1:3"
2061.0      "SMEMBERS" "friendlist:zpz:1:2"
1961.0      "SMEMBERS" "friendlist:yzz:1:2"
1947.5      "SMEMBERS" "friendlist:zpz:1:2"
1459.0      "SISMEMBER" "friendlist:hzz:1:2" "zzz"
1416.25     "SMEMBERS" "friendlist:zhz:1:2"
1389.75     "SISMEMBER" "friendlist:zzx:1:2" "zzz"

**Comment by oliver006** [comment]
Not sure what exactly you're trying to do but maybe using a custom Lua script could solve your problem.

**Comment by oliver006** [comment]
There's SLOWLOG metrics support (see relevant code [here](https://github.com/oliver006/redis_exporter/blob/master/exporter/exporter.go#L1204-L1225)).
If the snippet above is from a log then you should look into collecting and evaluating your redis logs.
