### ISSUE TITLE
Scraping multiple Redis instances

### ISSUE THREAD

**Issue by akatch** [oliver006/redis_exporter#473]
Is it (or could it be) possible to scrape multiple Redis instances with redis_exporter? For example, I have a Redis instance running on port 6379 and another on 16379. I would like to collect metrics from both instances, but would rather not have to run multiple exporters. Can this be achieved?

**What version of redis_exporter are you running?**
[x] 1.15.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.
```
redis_exporter --web.listen-address=:3994 --redis.addr=redis://x.x.x.x:6379 --export-client-list=true --redis-only-metrics
```

**Comment by oliver006** [comment]
It's possible, see the [documentation here](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts).
