### ISSUE TITLE
redis exporter with ssl `rediss://` does not work

### ISSUE THREAD

**Issue by sangeethdba** [oliver006/redis_exporter#478]
**Describe the problem**
redis exporter with ssl `rediss://` does not work

 /opt/isv/redis/redis_exporter/redis_exporter-v1.14.0.linux-amd64/redis_exporter \ 
-redis.addr rediss://xx.xx.xx.xx:9002 -web.listen-address 0.0.0.0:9132 \ -tls-server-key-file /opt/isv/redis/certfiles/newqpssc_certs/private.key \
 -tls-server-cert-file /opt/isv/redis/certfiles/newqpssc_certs/com-redis-cluster-qpssc.cer \
 -tls-ca-cert-file /opt/isv/redis/certfiles/newqpssc_certs/rootca.crt \
 -debug

INFO[0000] Redis Metrics Exporter v1.14.0    build date: 2020-12-10-01:08:14    sha1: fcb9a8fdf63125ee43a40cf6a6dae2e37414c2b0    Go: go1.15.6    GOOS: linux    GOARCH: amd64
INFO[0000] Providing metrics at 0.0.0.0:9132/metrics
ERRO[0003] Couldn't connect to redis instance

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

**Screenshots**
INFO[0000] Redis Metrics Exporter v1.14.0    build date: 2020-12-10-01:08:14    sha1: fcb9a8fdf63125ee43a40cf6a6dae2e37414c2b0    Go: go1.15.6    GOOS: linux    GOARCH: amd64
INFO[0000] Providing metrics at 0.0.0.0:9132/metrics
ERRO[0003] Couldn't connect to redis instance

**Additional context**

**Comment by oliver006** [comment]
Can you please run the exporter with the --debug flag to get more verbose output and post it here?
(Make sure to first remove any sensitive data like passwords or private URIs from the logs)

**Comment by sangeethdba** [comment]
Tried adding -debug and —debug.

It is not giving any additional details

**Comment by oliver006** [comment]
Hmm, that's odd, there should definitely be more verbose output when running with the debug flag.

**Comment by sangeethdba** [comment]
DEBU[0068] Trying: Dial(): rediss cmqsrd00.sds.com:9002
ERRO[0068] Couldn't connect to redis instance
DEBU[0068] connectToRedis( rediss://cmqsrd00.sds.com:9002 ) err: dial rediss: unknown network rediss
DEBU[0068] scrapeRedisHost() done
DEBU[0078] Trying DialURL(): rediss://cmqsrd00.sds.com:9002
DEBU[0078] DialURL() failed, err: x509: certificate signed by unknown authority
DEBU[0078] Trying: Dial(): rediss cmqsrd00.sds.com:9002
ERRO[0078] Couldn't connect to redis instance
DEBU[0078] connectToRedis( rediss://cmqsrd00.sds.com:9002 ) err: dial rediss: unknown network rediss
DEBU[0078] scrapeRedisHost() done

**Comment by sangeethdba** [comment]
@oliver006

**Comment by sangeethdba** [comment]
using the same certs im able to connect to cluster via redis-cli ,but some how exporter throwing DEBU[0078] DialURL() failed, err: x509: certificate signed by unknown authority

**Comment by sangeethdba** [comment]
@oliver006 i figured out the issue .

/opt/isv/redis/redis_exporter/redis_exporter-v1.14.0.linux-amd64/redis_exporter -debug -redis.addr rediss://cmqsrd01.sds:9002 -web.listen-address 0.0.0.0:9132 -skip-tls-verification   -tls-ca-cert-file "/opt/isv/redis/certfiles/newqpssc_certs/rootca.crt"  -tls-client-cert-file "/opt/isv/redis/certfiles/newqpssc_certs/com-redis-cluster-qpssc.sds.com.cer" -tls-client-key-file "/opt/isv/redis/certfiles/newqpssc_certs/private.key"     using these parameters in this order resolved the issue.
