### ISSUE TITLE
Add metric: "expired_stale_perc"

### ISSUE THREAD

**Issue by frenkye** [oliver006/redis_exporter#482]
**Describe the problem**
Missing metric from INFO STATS "expired_stale_perc". Which should represent: "expired_stale_perc: The percentage of keys probably expired". (source: https://redis.io/commands/info )

**What version of redis_exporter are you running?**
INFO[0000] Redis Metrics Exporter v1.16.0    build date: 2021-01-29-01:51:41    sha1: 1e42f5ab827ee51a093d6d3b91cc207634b86dd2    Go: go1.15.7    GOOS: linux    GOARCH: amd64

**Running the exporter**
/opt/prometheus/bin/redis_exporter --redis.addr="redis://127.0.0.1:6379"

**Screenshots**
![Screenshot 2021-02-02 at 14 38 30](https://user-images.githubusercontent.com/13994937/106608478-bc95c900-6564-11eb-90a5-968d889f56b5.png)

**Comment by oliver006** [comment]
This should be as simple as adding a line here:
https://github.com/oliver006/redis_exporter/blob/master/exporter/exporter.go#L257

I'm currently short of time but will review and merge a PR if you submit one.
