### ISSUE TITLE
DEBUG mode logs password, is that correct? 

### ISSUE THREAD

**Issue by blommish** [oliver006/redis_exporter#486]
**Describe the problem**
When running debug mode, the password is logged, is that wanted?
`{"level":"debug","msg":"NewRedisExporter options: exporter.Options{User:\"\", Password:\"`

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
  image: oliver006/redis_exporter:v1.16.0
[x] 1.16.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.
```
    - name: REDIS_EXPORTER_LOG_FORMAT
      value: json
    - name: REDIS_EXPORTER_DEBUG
      value: "true"
```

**Comment by oliver006** [comment]
Yes, that's a side effect of running in debug mode. Don't run the exporter in debug mode if you don't want to log sensitive information.
