### ISSUE TITLE
The redis-exporter must be runned with --debug to work

### ISSUE THREAD

**Issue by daquinoaldo** [oliver006/redis_exporter#493]
**Describe the problem**
The exporter requires `--debug` to work.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[x] 0.3x.x
[ ] 1.x.x

**Running the exporter**
`docker run --name redis-exporter --env-file /path/to/.env --publish 9121:9121 redis-exporter --web.listen-address :9121 --debug`

`/path/to/.env` contains only the following row:
```sh
REDIS_ADDR=redis://:password@hostname:port
```
The username is missing because our Redis database doesn't want it in the URI. This URI works both with the python application and the `redis-exporter` when using `--debug`, but doesn't work without `--debug`.

**Expected behavior**
It should work by removing `--debug`, but it doesn't.

**Screenshots**
Not relevant.

**Additional context**
No other relevant context.

**Comment by oliver006** [comment]
The only difference that `--debug` makes is setting the log level so I think it's highly improbable that this will affect the exporter's ability to connect.
Can you check the logs (with and without --debug) to see if there's more information about what's going on?

**Comment by daquinoaldo** [comment]
You are right. The `--debug` flag delays the startup just a little bit. Meanwhile, the service the exporter was depending on finishes writing a file need by the exporter. Sorry I have bothered you, the issue is solved.

**Comment by oliver006** [comment]
Good to hear you figured it out!
