### ISSUE TITLE
v1.17.1 fails with REDIS_PASSWORD

### ISSUE THREAD

**Issue by Kyrremann** [oliver006/redis_exporter#499]
**Describe the problem**
Using the latest version (v1.17.1-alpine) the exporter won't connect to my Redis instace that has a password. It work with the previous version (v1.17.0-alpine)

**What version of redis_exporter are you running?**
v1.17.1-alpine

**Running the exporter**
Running as a pod in Kubernetes, using the provided Docker image.

**Expected behavior**
Expected the exporter to be able to connect to the Redis isntance

**Comment by oliver006** [comment]
Do you have any log output to help diagnosing what the issue might be?

**Comment by Kyrremann** [comment]
Forgot to add the logs, it's pretty basic output.
```
$ k logs kyrre-redisexporter-765c5c7d59-t2xq4 kyrre-redisexporter
{"level":"info","msg":"Redis Metrics Exporter v1.17.1    build date: 2021-02-20-13:14:47    sha1: 39f8ddd5c6bd6e8a14f37779e4899aa884d8a201    Go: go1.16    GOOS: linux    GOARCH: amd64","time":"2021-03-09T06:48:17Z"}
{"level":"info","msg":"Providing metrics at :9121/metrics","time":"2021-03-09T06:48:17Z"}
{"level":"error","msg":"Couldn't connect to redis instance","time":"2021-03-09T06:48:20Z"}
{"level":"error","msg":"Couldn't connect to redis instance","time":"2021-03-09T06:48:35Z"}
```

I'm going to do some more tests, to see if Istio is doing something.

**Comment by Kyrremann** [comment]
We can close this. Turns out it's Istio (service mesh) that causes the problem. Sorry for the interruption.
