### ISSUE TITLE
prometheus get nodata from redis_exporter

### ISSUE THREAD

**Issue by itnikita** [oliver006/redis_exporter#502]
/usr/local/bin/redis-server -v
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=c0f4b44041a38bb8

redis-cli -v                  
redis-cli 3.0.6

/usr/local/redis_exporter/redis_exporter -redis.addr 192.168.5.46:6379 -redis.password mypasswdhere &
curl 192.168.5.46:9121/metrics|grep redis_memory|grep -v ^#
output like that

```
redis_memory_used_bytes 4.41542548e+09
redis_memory_used_lua_bytes 46080
redis_memory_used_peak_bytes 4.697117176e+09
redis_memory_used_rss_bytes 4.98440192e+09
```
but when I exxcute this on prometheus like IP:9090/graph/  via chrome
redis_memory_max_bytes{instance=~"192.168.5.46:9121"} 
or
100 * (redis_memory_used_bytes{instance=~"192.168.5.46:9121"} / redis_memory_max_bytes{instance=~"192.168.5.46:9121"} )
the element shows no data

some version is here.
prometheus-2.13.1
redis_exporter-v1.16.0

prometheus.yml is like bellow,
static_configs:
    - targets: ['localhost:9090']
  - job_name: 'redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.18.167:9121']
  - job_name: 'redis-5-46'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.5.46:9121']

the same version on the other node redis
that is 192.168.18.167
prometheus can get data on graph page
and curl is like this

redis_memory_max_bytes 9.65e+08
redis_memory_used_bytes 895280
redis_memory_used_dataset_bytes 315664
redis_memory_used_lua_bytes 37888
redis_memory_used_overhead_bytes 579616
redis_memory_used_peak_bytes 7.975832e+06
redis_memory_used_rss_bytes 2.3740416e+07
redis_memory_used_scripts_bytes 0
redis_memory_used_startup_bytes 512928

redis version is 5.x on node 192.168.18.167

**Comment by itnikita** [comment]
check
```
curl 192.168.5.46:9121/metrics|grep redis_config_maxmemory|grep -v ^#
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Curr
                                 Dload  Upload   Total   Spent    Left  Spee
100 22919    0 22919    0     0  4500k      0 --:--:-- --:--:-- --:--:-- 746
redis_config_maxmemory 1.073741824e+10
```

```
192.168.5.46:6379> config get maxmemory
1) "maxmemory"
2) "10737418240"
```

**Comment by itnikita** [comment]
more info
```
cat /etc/redis/redis_6379.conf|grep maxmemory|grep -v ^#
maxmemory 10737418240
```

**Comment by oliver006** [comment]
I'm not sure I understand what the issue is, can you try to clarify your question?

**Comment by itnikita** [comment]
redis version 3.0.6  can not get data redis_memory_max_bytes metric
it is not my config cause the issue.
I guess redis_exporter do not support the redis 3.0.6 version
maybe I hava to upgrade the redis version.

**Comment by oliver006** [comment]
Yeah, an upgrade might help. I'm not 1oo% sure when the maxmemory INFO line was introduced but e.g. for Redis 2.8 it wasn't there.
