### ISSUE TITLE
How to get the connection number, concurrency number and delay per Redis client ?

### ISSUE THREAD

**Issue by heheliu321** [oliver006/redis_exporter#506]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
You can query the `redis_connected_clients_details` metrics (make sure have set --export-client-list=true) and then you could sum by host or client name or whatever you desire.
