### ISSUE TITLE
question for redis_connected_clients_details 

### ISSUE THREAD

**Issue by heheliu321** [oliver006/redis_exporter#509]
redis_connected_clients_details{age="10", cmd="NULL", db="0", flags="N", host="10.173.94.161", idle="10", instance="redis://100.94.2.224:7002", job="redis_exporter_dev_targets", port="39788"}

cmd is NULL is why?

my client is lettuce 5.3.4,

public class RedisController {

    @Autowired
    private StringRedisTemplate redisTemplate;

    @RequestMapping(produces = {"application/json"}, method = RequestMethod.GET)
    public void kafkaTest() {
        for (int i = 0; i < 150; i++) {
            redisTemplate.opsForValue().set("acs-redis-key-" + i, "acs-redis-value");
            redisTemplate.opsForValue().get("acs-redis-key" + i);
        }
    }
}

total statistics is: 
it does  not match
![image](https://user-images.githubusercontent.com/16066077/112415696-3a08d900-8d5f-11eb-993a-7fcd1d073835.png)

**Comment by oliver006** [comment]
Not sure why cmd would be NULL. I tried to reproduce but no luck. Is this a vanilla redis instance or a cloud-hosted version?

**Comment by heheliu321** [comment]
Is  a vanilla redis instance

**Comment by oliver006** [comment]
What version ?

**Comment by houstonheat** [comment]
If the client connects to Redis, and has NOT executed any command, then there's no `LAST COMMAND`, and its last command is `NULL`. You can check this behavior by executing `CLIENTS LIST` directly from `redis-cli`. There is no issue with exporter itself.

More info about clients handling: https://redis.io/topics/clients

**Comment by oliver006** [comment]
Thanks @houstonheat - that's really helpful!
