### ISSUE TITLE
Hash sum mismatch

### ISSUE THREAD

**Issue by Ramshield** [oliver006/redis_exporter#510]
Hi,

```
$ sha256sum redis_exporter-v1.12.0.linux-amd64.tar.gz
f1015b6288c4481b19708c79c3bd762bb7d6be358bb68159b09fb6307973787a  redis_exporter-v1.12.0.linux-amd64.tar.gz
```
The hash sum doesn't match the given in the `sha256sum` with `dc270f87394afdc0ffb4f33129b0214bc583b947a3859e0506030f369d558459`.

I downloaded from the following exact URL:  https://github.com/oliver006/redis_exporter/releases/download/v1.12.0/redis_exporter-v1.12.0.linux-amd64.tar.gz

Would someone mind confirming this?

**Comment by oliver006** [comment]
Not sure where you got the `dc270...` hash from. The [sha256sums.txt from the 1.12.0 release](https://github.com/oliver006/redis_exporter/releases/download/v1.12.0/sha256sums.txt) has `f101...` and I can confirm, that's what I get when checking the hash:

```
➜  ~ shasum -a 256 redis_exporter-v1.12.0.linux-amd64.tar.gz
f1015b6288c4481b19708c79c3bd762bb7d6be358bb68159b09fb6307973787a  redis_exporter-v1.12.0.linux-amd64.tar.gz
➜  ~
```

**Comment by Ramshield** [comment]
I get what I did wrong, I mixed `v1.20.0` and `v1.12.0`. My sincere apologies!

**Comment by oliver006** [comment]
No problem, glad you figured it out.
