### ISSUE TITLE
could it work in redis-cluster ？

### ISSUE THREAD

**Issue by zzliliang199053** [oliver006/redis_exporter#512]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.

 ./redis_exporter  --version
INFO[0000] Redis Metrics Exporter v1.20.0    build date: 2021-03-22-13:25:02    sha1: f367ed48b4d1571b57f59e435418f402d4329265    Go: go1.16.2    GOOS: linux    GOARCH: amd64 

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

nohup ./redis_exporter -redis.addr 127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382 -redis.password "mypass" 

**Screenshots**
If applicable, add screenshots to help explain your question.

I can't get valid data from the  http://localhost:9121/metrics
![image](https://user-images.githubusercontent.com/55841728/113157367-68aa1680-926d-11eb-9ce1-6e901feae52c.png)

**Additional context**
Add any other context about the question here.

How should I use redis-exporter to get the monitoring data of redis cluster
Are there other wikis or tutorials

**Comment by oliver006** [comment]
Please see the [documentation here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts)how to set up redis exporter for how to scrape multiple redis intances.
