### ISSUE TITLE
Use GOMAXPROCS

### ISSUE THREAD

**Issue by mmesbah** [oliver006/redis_exporter#513]
https://github.com/uber-go/automaxprocs

Is it possible to use this go package in your exporter? This will cause its CPU throttling to decrease so much.

Thanks

**Comment by oliver006** [comment]
Interesting. Do you currently experience an issue with redis_exporter CPU usage when running it in a container?

**Comment by mmesbah** [comment]
Yes, oliver. With the exporter container memory set to 200Mi (which should be sufficient I think), we experience a mean CPU throttling of 5%. Albeit, after setting RAM to 500Mi, the CPU throttling problem solved, but I think this is a memory waste for such a minimal microservice.

**Comment by oliver006** [comment]
Yeah, 100Mi of memory should be plenty for the exporter. But I don't understand why that affects setting the CPU limits. E.g. Kubernetes lets you set those independently. And the exporter should need so little CPU that you probably won't need more than half a core, possibly even less.

**Comment by mmesbah** [comment]
You're right, RAM an CPU resources are set independently, but as I said before, we have a special case that we are setting them relative to each other. I would have better not involved you in this story. :)

Anyway, It would be appreciated if you use `automaxprocs` package in your exporter so that we will be able to check if it influences the CPU throttling metrics.

**Comment by oliver006** [comment]
> I would have better not involved you in this story. :)

:-)


> Anyway, It would be appreciated if you use `automaxprocs` package in your exporter so that we will be able to check if it influences the CPU throttling metrics.

I prefer to test this before pulling in a new dependency.
Best way to test would be for you to build a version of redis_exporter and test it in your environment if it addresses the issue, then you can open a PR and we can get it merged.

**Comment by oliver006** [comment]
@mmesbah - any update here?

**Comment by mmesbah** [comment]
Sorry @oliver006 , I refused to work more on this issue, because I was too busy to do so.

**Comment by oliver006** [comment]
No worries. I'll close the issue and you can open a new one if this comes up again.
