### ISSUE TITLE
missing Tile38 metrics

### ISSUE THREAD

**Issue by mmesbah** [oliver006/redis_exporter#514]
We are using the redis_exporter container for both redis and tile38 instances.
But it seems there are some important metrics missing in tile38 in contrast to redis.
For example:
```
redis_commands_total
redis_keyspace_hits_total
redis_keyspace_misses_total
redis_db_keys (Not empty, but equal to 0)
redis_net_input_bytes_total
redis_net_output_bytes_total
...
```

Is there any problem in your exporter when using tile38? I am not sure if it's a bug, or just a lacking feature.

Thanks for your attention

**Comment by oliver006** [comment]
Hmm, good question, not sure why those metrics don't show up but I think they should (if the right output is present in `INFO ALL`).
Did you try running the exporter with `--debug` and see if there's anything useful in the logs?
What version of Tile38 are you running?

**Comment by oliver006** [comment]
I had a brief look at the INFO ALL output of a Tile38 isntance version 1.22.5 and there's a lot of output missing, compared to a real Redis server so makes sense that you're missing a lot of metrics.

**Comment by mmesbah** [comment]
Yes, you're right.
So it seems the exporter cannot do anything special.
Thanks for your response.

**Comment by oliver006** [comment]
That's right, it can only export what's available.
