### ISSUE TITLE
use systemctl startup redis_exporter  service missing -check-single-keys value

### ISSUE THREAD

**Issue by wiljay** [oliver006/redis_exporter#515]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
v1.20.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

two running method 

one is throughs systemctl start command 
two is direct run command 

/usr/local/path/redis/redis_exporter -redis.addr 127.0.0.1:5379 -web.listen-address=0.0.0.0:61927 -check-single-keys='db0=testkey1'  
 

**Screenshots**
If applicable, add screenshots to help explain your question.

direct run command can find testkey1
![image](https://user-images.githubusercontent.com/42308868/114490912-3ffc2680-9c48-11eb-918a-cab123004672.png)

Via systemctl start the service cannot  find testkey1
![image](https://user-images.githubusercontent.com/42308868/114490956-5a360480-9c48-11eb-8aa0-aa7141c6c9e6.png)

**Additional context**
Add any other context about the question here.
![image](https://user-images.githubusercontent.com/42308868/114491369-1db6d880-9c49-11eb-89cd-1bb8368a856b.png)
this is my systemctl file

**Comment by oliver006** [comment]
This might be some quote escaping issue when you use systemctl.
When you run via systemctl, can you run `ps faux | grep redis_exporter` to see what's actually being executed?
You can also add the `--debug` flag to get extra log output to tell you what the value is for `-check-single-keys`.

**Comment by wiljay** [comment]
systemd cannot put '', just remove '' in -check-single-keys=db0=testkey1 and restart can work.
