### ISSUE TITLE
redis_slowlog_last_id 

### ISSUE THREAD

**Issue by zzliliang199053** [oliver006/redis_exporter#516]
**Describe the problem**

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.

INFO[0000] Redis Metrics Exporter v1.20.0    build date: 2021-03-22-13:25:02    sha1: f367ed48b4d1571b57f59e435418f402d4329265    Go: go1.16.2    GOOS: linux    GOARCH: amd64 

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
 
/usr/bin/redis_exporter -web.listen-address 0.0.0.0:9121 -redis.password mypass -redis.addr addr -ping-on-connect=true

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

In my redis-cluster, The value of redis_slowlog_last_id for all instances is the same as the instance used to start the exporter

**Screenshots**

![image](https://user-images.githubusercontent.com/55841728/114729488-9c5b6500-9d72-11eb-9a67-1353aaa49120.png)

**Additional context**

**Comment by zzliliang199053** [comment]
I found that there are other metrics that are the same
It seems that the information obtained from the info command is the same
mabye my configuration is wrong ?

**Comment by oliver006** [comment]
`information obtained from the info command is the same` - that's the info that the exporter exposes so looks like it's working fine? 
How did you set up slowlog?

**Comment by zzliliang199053** [comment]
All of redis instance config is the same,
slowlog-max-len 128
slowlog-log-slower-than 1000

other metric  , eg redis_process_id..

**Comment by oliver006** [comment]
What's the problem with `redis_process_id` ?

**Comment by zzliliang199053** [comment]
The redis_process_id of all redis instances is the same

**Comment by oliver006** [comment]
And I assume yo checked on the box and they all have different PIDs, correct? You're not running this in a container, correct? 

Can you post your exact PromQL query and the result when you query for PIDs?

**Comment by zzliliang199053** [comment]
![image](https://user-images.githubusercontent.com/55841728/116089715-b3d11100-a6d5-11eb-87fb-16e397dedee0.png)

i'm sure that the pid of each redis instance is different, not container

**Comment by zzliliang199053** [comment]
![image](https://user-images.githubusercontent.com/55841728/116090511-89cc1e80-a6d6-11eb-9e7d-5557d7ee95af.png)

**Comment by zzliliang199053** [comment]
![image](https://user-images.githubusercontent.com/55841728/116096615-04e40380-a6dc-11eb-9a79-f75353c5d524.png)

**Comment by oliver006** [comment]
Thanks. Can you also post the results as queried by using PromQL in the Prometheus server ui? 

The query you're using is `sum by (instance, job) redis_procesS_id` ? Why sum?

**Comment by zzliliang199053** [comment]
The result will not change, using sum is just a personal habit.
![image](https://user-images.githubusercontent.com/55841728/116176735-3c3aca80-a745-11eb-81af-15a2625002c9.png)

**Comment by zzliliang199053** [comment]
@oliver006

**Comment by oliver006** [comment]
Don't know what else it could be. Did you check the `/metrics` endpoints of all the redis_exporters? This could give you an indication if the ID (or PID) was correct when the exporter scraped it.

Or are you using federation / recording of rules and maybe your aggregation is wrong?
