### ISSUE TITLE
prometheus is't aware of a target is down

### ISSUE THREAD

**Issue by yangshenrui** [oliver006/redis_exporter#522]
**Describe the problem**
Prometheus Configuration to Scrape Multiple Redis Hosts
/scrape?target=redis:6989 returns a 200 even if the scraped redis instance(redis:6989) is down.
so the state of endpoint in target page of prometheus always up
Is there any way to make it show down？

**What version of redis_exporter are you running?**
v1.23.1.linux-amd64

**Running the exporter**
redis_exporter-v1.23.1.linux-amd64/redis_exporter --web.listen-address=:10006 --redis.addr=

**Additional context**
prometheus
>  \- job_name: 'redis'
    static_configs:
    - targets: ['localhost:10006']
      labels:
        exporter: redis
  \- job_name: 'redis_target'
    static_configs:
      - targets: ['redis:6989']
        labels:
          model_name: factory
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:10006

**Comment by oliver006** [comment]
The `up` metric will be 0 if the host is down - can you use that to detect hosts that are not responding?

**Comment by yangshenrui** [comment]
> The `up` metric will be 0 if the host is down - can you use that to detect hosts that are not responding?

 `up` metric is 1
![image](https://user-images.githubusercontent.com/35597353/118343595-910b7d00-b55c-11eb-832c-11b2abdad2fb.png)
![image](https://user-images.githubusercontent.com/35597353/118343661-cfa13780-b55c-11eb-863d-9c5e8fa39a09.png)

**Comment by yangshenrui** [comment]
I tried to reduce `scrape_timeout` to avoid this problem temporarily,it works
but is there a better solution？

**Comment by oliver006** [comment]
Oh, my bad, you need to query for `redis_up` - thats the metric generated by the exporter, the `up` metric is generated by the Prometheus server and you're right, that one shows as up.

**Comment by yangshenrui** [comment]
tks
