### ISSUE TITLE
Support TLS certificate hot-reload 

### ISSUE THREAD

**Issue by bjosv** [oliver006/redis_exporter#525]
**Describe the problem**
When TLS certificates are renewed there is a need to trigger `redis_exporter` to use the new certs.
The current procedure is to restart the process.

The proposal is to enable hot-reload of the certs, either by lazy-loading the configured files during the accept or connect,
or by using something like `fsnotify` to trigger a reload when changes occur.

This would be applicable for both the metrics endpoint server and the connection to Redis.

**What version of redis_exporter are you running?**
v1.23.1 / master

**Comment by oliver006** [comment]
Interesting, I didn't know that/s possible but looks like [this SO article](https://stackoverflow.com/questions/37473201/is-there-a-way-to-update-the-tls-certificates-in-a-net-http-server-without-any-d) outlines a way to do it.

I don't have a need for it and frankly doubt it's necessary (couple of seconds (max) downtime to bounce the exporter shouldn't cause any trouble) but I'd accept a PR if you (or anyone else) submits one.

**Comment by bjosv** [comment]
Sounds good, I will prepare a PR.

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.24.0

**Comment by bjosv** [comment]
> Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.24.0

Great! Many thanks for all your time and effort put into this great project.
