### ISSUE TITLE
Incorrect value of maxmemory_policy shown for redis_instance_info metric for KeyDB

### ISSUE THREAD

**Issue by Drugoy** [oliver006/redis_exporter#529]
**Describe the problem**
I see incorrect value of `maxmemory_policy` label shown for `redis_instance_info` metric for scraped KeyDB instance.
I've configured KeyDB with `maxmemory_policy: volatile-lfu`, but redis-exporter returns this:
```
# HELP redis_instance_info Information about the Redis instance
# TYPE redis_instance_info gauge
redis_instance_info{maxmemory_policy="noeviction",os...} 1
```

**What version of redis_exporter are you running?**
1.24.0

**Running the exporter**
`/usr/local/bin/redis_exporter --web.lister-address :9121`

**Comment by oliver006** [comment]
Hmmm, the value of the maxmemory_policy label is taken verbatim from the output of the `INFO` - can you post the output of the `INFO` command when run it on your instance (redact anything that's sensitive) ?

**Comment by Drugoy** [comment]
It returned correct value for that setting under `# Memory` block: `maxmemory_policy:volatile-lfu`.
`CONFIG GET maxmemory-policy` returns
```
1) "maxmemory-policy"
2) "volatile-lfu"
```
Note the dash vs underscore in the setting name between these two.
And in config file (/etc/keydb/keydb.conf) it is set as `maxmemory-policy folatile-lfu` (note the lack of colon between the key and the value).

**Comment by Drugoy** [comment]
Sorry, looks like I got mixed in terminals or something, there is no bug, I had 1 server where I didn't apply the config somehow.
Sorry for bothering.

**Comment by oliver006** [comment]
No worries, that happens.
