### ISSUE TITLE
trying to connect to redis database on Azure through the redis exporter service but failing

### ISSUE THREAD

**Issue by mach6307** [oliver006/redis_exporter#530]
I am running into an issue.

I am trying to connect to redis database through the redis exporter service but I am errors like below:

redis_exporter[22654]: time="2021-06-29T16:31:47Z" level=debug msg="Trying: Dial(): redis metrics.redis.cache.windows.net:6379"
redis_exporter[22654]: time="2021-06-29T16:31:47Z" level=error msg="Couldn't connect to redis instance"
redis_exporter[22654]: time="2021-06-29T16:31:47Z" level=debug msg="connectToRedis( redis://metrics.redis.cache.windows.net:6379 ) err: dial redis: unknown network redis"
redis_exporter[22654]: time="2021-06-29T16:31:47Z" level=debug msg="scrapeRedisHost() done"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=debug msg="Trying DialURL(): redis://metrics.redis.cache.windows.net:6379"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=debug msg="DialURL() failed, err: ERR invalid password"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=debug msg="Trying: Dial(): redis metrics.redis.cache.windows.net:6379"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=error msg="Couldn't connect to redis instance"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=debug msg="connectToRedis( redis://metrics.redis.cache.windows.net:6379 ) err: dial redis: unknown network redis"
redis_exporter[22654]: time="2021-06-29T16:32:02Z" level=debug msg="scrapeRedisHost() done"

About Environment:

1. Redis is hosted on Azure. We do not have access to server.
2. Installed redis exporter on Prometheus server it self. 
3. The password to connect to redis has an "=" in it. (ex: dfgfgfjhgfgHhh9HH=)
4. Created the service like below:
[Unit]
Description=Redis Exporter
Wants=network-online.target
After=network-online.target
[Service]
User=root
Group=root
Type=simple
Environment=ARG1=dfgfgfjhgfgHhh9HH=
ExecStart=/usr/local/bin/redis_exporter \
    -web.listen-address ":9121" \
    -redis.addr "redis://metrics.redis.cache.windows.net:6379" \
    -redis.password $ARG1 \
    -debug
--log.level=debug

[Install]
WantedBy=multi-user.target

If you see above I used as a variable. 
I tried to give directly instaed of variable but that "=" is not taking it.
5. Redis exporter version:
INFO[0000] Redis Metrics Exporter v1.24.0    GOOS: linux    GOARCH: amd64
6. I could able to ping the redis server from prometheus server.

So what could be possibly wrong here? Please help.

Regards
Kishore

**Comment by oliver006** [comment]
Hmm, you should look into how to use quotes or escape the `=` in the password. Not sure what the right way to do this but that might be it. Did you try with a password that does not have a `=` in it?

**Comment by houstonheat** [comment]
Also, you can try to start `redis-exporter` manually from any host with direct access to the target network and pass password through ENV/flag/URI to check if all work correctly without systemd-unit.
