### ISSUE TITLE
Multiplatform Docker Images

### ISSUE THREAD

**Issue by bartenew** [oliver006/redis_exporter#533]
**Describe the problem**
Today the images for amd64 and arm64 are in separate tags. There is a way to unite them under the same tag using docker manifest or docker buildx utility. My use case is that I have multiple Kubernetes nodes where some of them are ARM64 and some are AMD64. Having a docker manifest will allow using the same tag for all platforms

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[x] 1.x.x

**Comment by oliver006** [comment]
Thanks for raising this issue - do you have a link with more information? If there's a better way to organize/set up the Docker files then I'd be interested to see how.

**Comment by garrygerber** [comment]
Would love to see this supported too!

you will find all the information you need in: https://docs.docker.com/buildx/working-with-buildx/
but basically, you need your Dockerfile to know to differentiate between the architectures and install appropriate files to each arch, and then use the following command to build and push it:
`docker buildx build --platform linux/amd64,linux/arm64 --push -t latest .`

hope this helps

**Comment by oliver006** [comment]
Thanks Garry, that's helpful.
I'd need to look into how to make `buildx` work with the drone plugin and then rework the Dockerfile accordingly but I'm a little short of time right now.
If anyone is interested in picking this up and submitting a PR that'd be great!

**Comment by oliver006** [comment]
Fixed by #548 - thanks @garrygerber !

**Comment by riconnon** [comment]
@oliver006 I think the changes you've made are a huge step in the right direction, but I think there's still a little left to be desired.
At the moment, from what I can tell, only the `alpine` tag is a multi-platform manifest, and the other tags, (eg. `latest`, `v1.31.0` or `v1.31.0-alpine`) are still single platform

**Comment by oliver006** [comment]
Thanks for double-checking our work @riconnon !

I pushed a change and released v1.31.1 and I now see this on [Docker Hub](https://hub.docker.com/r/oliver006/redis_exporter/tags):
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1222339/141215422-c1951907-e488-4dad-be0c-0d372522c98f.png">
 
Does that look correct to you?

**Comment by garrygerber** [comment]
there is a small issue with the ARM tags, they are built for arm64/v8:
repo:
`docker run oliver006/redis_exporter:v1.31.1-arm64  (master)redis_exporter
Unable to find image 'oliver006/redis_exporter:v1.31.1-arm64' locally
v1.31.1-arm64: Pulling from oliver006/redis_exporter
Digest: sha256:7b3d9f9772bf859eefb2cb2c735ca10107440f6ebff6ba169b38bc2f94a59248
Status: Downloaded newer image for oliver006/redis_exporter:v1.31.1-arm64
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
time="2021-11-11T11:29:33Z" level=info msg="Redis Metrics Exporter v1.31.1    build date: 2021-11-11-00:26:53    sha1: 39d8a4f5e178e4e75ae481fbd9028ff044843c2d    Go: go1.17.3    GOOS: linux    GOARCH: amd64"
time="2021-11-11T11:29:33Z" level=info msg="Providing metrics at :9121/metrics"                                                                                                               
`
local fix:
`docker run redis_exporter-arm64                    (master)redis_exporter
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
time="2021-11-11T11:30:09Z" level=info msg="Redis Metrics Exporter test    build date: 2021-11-11-11:22:02    sha1:     Go: go1.17.3    GOOS: linux    GOARCH: arm64"
time="2021-11-11T11:30:09Z" level=info msg="Providing metrics at :9121/metrics"`
I will PR a fix now

**Comment by garrygerber** [comment]
@oliver006 the fix #581

**Comment by oliver006** [comment]
#581 caused a new issue. You always have to use linux/amd64 for the builder container as we run on linux/amd64 and cross-compile to arm.
I'm going to revert that part of #581

**Comment by garrygerber** [comment]
@oliver006 created a fix for the ARM images, as the cross-compile didn't work properly with Drone.io CI
#582 contains the fix

**Comment by oliver006** [comment]
This should be fixed now, thanks @garrygerber !
