### ISSUE TITLE
What number of keys is considered 'very large' for check-keys

### ISSUE THREAD

**Issue by kerossin** [oliver006/redis_exporter#536]
Hey! 

The description for the 'check-keys' command line options says 'Warning: using --check-keys to match a very large number of keys can slow down the exporter to the point where it doesn't finish scraping the redis instance.'

What number is roughly considered to be very large in this situation?

We have about 175 keys in our Redis database and we tried using --check-keys=* but the Redis exporter endpoint would very rarely return the metrics. Sometimes it would get stuck seemingly indefinitely or take about 20 seconds.

I'm trying to figure out if it's the exporter being unable to handle all of the keys or maybe it's the Redis server itself.

Running the exporter without check-keys makes it return metrics instantly. Tried with check-single-keys and various number of keys to see how much it would handle, about 75 was where it would still return metrics well enough.

Redis exporter runs together with Redis on the same physical machine, it has plenty of free resources.

Anybody has thoughts on this? I'm not really experienced with Redis itself.

**Comment by kerossin** [comment]
Running KEYS * returns all of them instantly, a lot of our keys are sets, there's a few hashes, lists and strings.

Running in debug mode I saw a few errors:

1) Basically every GET command is failing
It only seems to work on string type
```
running command: GET [my-key]
err: WRONGTYPE Operation against a key holding the wrong kind of value
```
Perhaps adding a check to see if the type of the key is string before running GET would be faster than running it on every key?
https://github.com/oliver006/redis_exporter/blob/f9b000fed91e74677cec57eb747437f03dd4ed8d/exporter/keys.go#L110-L113
2) PFCOUNT ran on strings is also failing
```
running command: PFCOUNT [my-key2]
err: WRONGTYPE Key is not a valid HyperLogLog string value.
```

I don't know how often people use HyperLogLog strings but if they're rarer than regular strings then maybe switching places of PFCOUNT and STRLEN to always run STRLEN first would provide a bit of an optimization? https://github.com/oliver006/redis_exporter/blob/f9b000fed91e74677cec57eb747437f03dd4ed8d/exporter/keys.go#L36-L41



Also, our Prometheus instance was using it's global values of scrape_interval: 15s; scrape_timeout: 10s to scrape this Redis exporter, I'm testing it now with a 1m scrape interval and a 30s timeout. Every 15s might have been a bit too frequent with the number of keys we have.

**Comment by oliver006** [comment]
Thanks for pointing out these issues, they could definitely use some improving.
I'm pretty busy right now but could make time to review a PR if you want to submit one. Otherwise I'll try to get when my schedule frees up a bit.

Question for when you ran in debug mode:
Where was the bulk of the time spent? Simply on the sheer number of commands that were run or did anything hang and take disproportionately/unreasonably longer?

**Comment by kerossin** [comment]
I just ran it with debug mode to see again what's happening and it doesn't get stuck anywhere, it just keeps going and going through all the keys one by one.

This sequential execution doesn't scale well, running these commands concurrently would probably be better.

I'll see if I can come up with something for a PR.

**Comment by kerossin** [comment]
I've submitted a PR https://github.com/oliver006/redis_exporter/pull/538 for the small change to not run GET on every key, tests passed and GET seems to work when it's needed. Looks like it shaved off a few seconds from our scrape time so it's something.

As for concurrency, I was not able to implement it. I tried a really naive way of putting the for loop that gets all the info about keys from extractCheckKeyMetrics to it's own function and calling it with `go getKeyMetrics(....)` but of course it's not that simple.

I'm a total noob in Go and programming in general but I'll try to learn more about concurrency and see if it's possible.

**Comment by oliver006** [comment]
Thanks for the PR, I'll hopefully have time later today have a look. Something is off with the drone run, not sure why it's failing but I'll have a look.

As for the cncurrency, not sure that's a good approach, it might overwhelm the connection to the redis instance and/or the Redis instance itself. Maybe pipelining commands could help to reduce roundtrips but it would need some more research.
