### ISSUE TITLE
quay.io mirror along with dockerhub

### ISSUE THREAD

**Issue by ssandanshi** [oliver006/redis_exporter#537]
**Describe the problem**
The docker image currently gets published to dockerhub. Since docker introduced rater limiting a few months ago, Its preferable to have a mirror in Quay that is not affected from said rate limits.

**Expected behavior**
the docker images are pushed to a quay.io mirror.

**Comment by oliver006** [comment]
That's a great suggestion, Docker's rate limits have been extremely annoying. I'll look into getting this set up when I can find some time, hopefully in the next few days/weeks.

**Comment by oliver006** [comment]
redis_exporter is now available on quay as well, you can find the quay repo here:

https://quay.io/repository/oliver006/redis_exporter?tab=tags
