### ISSUE TITLE
https://github.com/prometheus-community

### ISSUE THREAD

**Issue by tamalsaha** [oliver006/redis_exporter#542]
**Describe the problem**
Thanks for building and maintaining the redis Prometheus exporter. It seems that various prometheus community contributed operators has been moved into https://github.com/prometheus-community . Have you considered / or interested in doing the same for this exporter? I am not associated with https://github.com/prometheus-community just a user of redis_exporter.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
Thats a good question! My understanding is that prometheus-community is for exporters that are no longer actively maintained by their original owners so they get moved to find a new home and maintainer.
I still enjoy maintaining and owning the repo so no need to move it right now but it's definitely an option in the future if that changes.
