### ISSUE TITLE
how to write sample-pwd-file.json!

### ISSUE THREAD

**Issue by luciferhs** [oliver006/redis_exporter#545]
**when i configure like this ! run error **
```
it can  run well

cat sample-pwd-file.json 
{
"reids://192.168.112.157:6879": "123456"
}


redis_exporter -redis.addr redis://192.168.112.157:6879 -redis.password-file /root/redis_exporter-v1.27.0.linux-amd64/sample-pwd-file.json -debug
INFO[0000] Redis Metrics Exporter v1.27.0    build date: 2021-08-30-23:37:23    sha1: ef05f8642cd71d632ca14d728c9c7534835d3674    Go: go1.17    GOOS: linux    GOARCH: amd64

but when get the metrics  trun like this

ERRO[0004] Redis INFO err: NOAUTH Authentication required. 
DEBU[0004] scrapeRedisHost() done      

and redis instance is not up
```

how ti config sample-pwd-file.json.  the example 
![image](https://user-images.githubusercontent.com/22001115/132329615-ba6fc6d6-bd66-47e1-ab9c-6c7fc77af608.png)
is not run well.

**Comment by houstonheat** [comment]
Is there any **debug log** entries like `"start load password file"` or `"Error loading redis passwords from file"`? If not, then the syntax is not the cause. So... If you provided an exact example, then I clearly see a typo in your parameters:
`sample-pwd-file.json`: **reids**://192.168.112.157:6879
`redis_exporter`: **redis**://192.168.112.157:6879

Judging by the code, I think it's worth adding a message with the loaded `PasswordMap` keys (no values, just URLs). FYI @oliver006

**Comment by oliver006** [comment]
I think that's a sensible suggestion @houstonheat . Listing the number of key-value pairs as an Errorf and then dump the keys with Debugf could be a useful addition to the logs.
