### ISSUE TITLE
latency metrics on 1.21.1 version

### ISSUE THREAD

**Issue by jelmokri** [oliver006/redis_exporter#551]
Hello,
I'm using the 1.21.1 version of the exporter.
I'm using the exporter on docker and deploy it via docker-compose and have added the ping-on-connect=true on command line of the exporter but dont see any metrics about latency or connect time and ping time.

    command:
      - --ping-on-connect=true

What's the name of the suppose metrics ? 

thanks for your help.

**Comment by oliver006** [comment]
```
curl -s localhost:9121/metrics | grep exporter_last_scrape_ping_time_seconds
# HELP redis_exporter_last_scrape_ping_time_seconds exporter_last_scrape_ping_time_seconds metric
# TYPE redis_exporter_last_scrape_ping_time_seconds gauge
redis_exporter_last_scrape_ping_time_seconds 0.014046175
```

**Comment by jelmokri** [comment]
Thanks for your quick answer.
I found this issue https://github.com/oliver006/redis_exporter/pull/349
where we talked about redis_latency_spike_* metrics exporter by the redis_exporter.
How should I proceed to have this kind of metrics ?
