### ISSUE TITLE
Wny redis_exporter redis_memory_max_bytes  0 

### ISSUE THREAD

**Issue by Hallow-zw** [oliver006/redis_exporter#574]
redis_exporter-v1.29.0.linux-amd64 

get ip:9121/metrics 
back data 
# HELP redis_memory_max_bytes memory_max_bytes metric
# TYPE redis_memory_max_bytes gauge
redis_memory_max_bytes 0
# HELP redis_memory_used_bytes memory_used_bytes metric
# TYPE redis_memory_used_bytes gauge
redis_memory_used_bytes 2.658576e+06

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#the-redis_memory_max_bytes-metric
