### ISSUE TITLE
Expose metric for `io-threads` config param.

### ISSUE THREAD

**Issue by shamil** [oliver006/redis_exporter#576]
**Describe the problem**

Redis 6+ added support for multi threaded IO. This is configurable via `io-threads` option.

```
127.0.0.1:6379> CONFIG GET io-threads
1) "io-threads"
2) "1"
```

It will be useful to have this eposed via the exporter as well

I can PR this , if it will be an acceptable change
Thanks

**Comment by oliver006** [comment]
Thanks for raising this issue @shamil - I think that would be a very valuable metric to have and I'd definitely review and merge a PR.
