### ISSUE TITLE
Multiple Targets but no metrics appearing

### ISSUE THREAD

**Issue by BenHesketh21** [oliver006/redis_exporter#578]
**Describe the problem**
I have the exporter set up to scrape multiple targets, it manages to connect to the server but none of the metrics are being collected, the only ones appearing on Grafana are:

redis_exporter_build_info
redis_exporter_scrape_duration_seconds_count
redis_exporter_scrape_duration_seconds_sum
redis_exporter_scrapes_total
redis_target_scrape_request_errors_total

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[X ] 1.x.x

INFO[0000] Redis Metrics Exporter v1.29.0    build date: 2021-10-20-13:27:32    sha1: df6f98b7c70db9d5598b5f001676da4b08dc7726    Go: go1.17.2    GOOS: linux    GOARCH: amd64 

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

./redis_exporter -debug -redis.addr= -script hlen.lua

**Comment by oliver006** [comment]
Can you please also post your prometheus config pertaining to the redis_exporter?
Especially the section where you configure the multiple targets (plz redact any sensitive information)

**Comment by BenHesketh21** [comment]
Thanks for getting back to me and I checked the prometheus config and I used the one in the docs for the exporter but the problem was grafana expects certain labels with our current set up, as soon as I added the labels everything worked great.
