### ISSUE TITLE
Elasticache "Cluster refresh failed"

### ISSUE THREAD

**Issue by AlexeiBarabash** [oliver006/redis_exporter#579]
**Describe the problem**
Hello , I try to monitor my AWS Elasticache but I encounter some strange issue with 
"Running refresh on cluster object"
and its returning
```
time="2021-11-07T20:14:41Z" level=debug msg="Running refresh on cluster object" (after 2 minutes)
time="2021-11-07T20:16:41Z" level=error msg="Cluster refresh failed: redisc: all nodes failed\nread tcp 10.5.3.11:32174->10.2.1.54:6379: i/o timeout"
```

but I see its connected and returned some information from `cluster info` command

**What version of redis_exporter are you running?**
1.30.0

**Running the exporter**
I deploy via Helm chart with this environment variables
```
env:
- name: REDIS_EXPORTER_DEBUG
  value: "true"
- name: REDIS_EXPORTER_IS_CLUSTER
  value: "true"
- name : REDIS_EXPORTER_CONNECTION_TIMEOUT
  value: 2m
- name : REDIS_EXPORTER_PING_ON_CONNECT
  value: "true"
```

**Screenshots**
looks like it works with cluster info
![image](https://user-images.githubusercontent.com/33050457/140660687-77ed04a7-1c00-4abe-ab9c-7c8fef5deb0a.png)

did anyone encounter same issue ? thank you

**Comment by oliver006** [comment]
From looking at the code, when doing a "cluster refresh" the exporter runs 
```
CLUSTER SLOTS
```
and that's about it? Can you try running that when connected to one node?
Also, can the exporter connect to all the private IPs? As in, are your security groups set up accordingly, etc ?
