### ISSUE TITLE
Could you provide statically linked binaries?

### ISSUE THREAD

**Issue by cmur2** [oliver006/redis_exporter#58]
I want to create a docker image for redis_exporter based on vanilla alpine:3.5 that by default lacks the libraries required to run dynamically linked binaries such as the one you provide on the Releases tab. E.g. the https://github.com/prometheus/blackbox_exporter/ project does this and it would be very nice if you could, too :) That would allow creating docker images without having to locally compile the go program again.

Maybe http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/ helps.

**Comment by oliver006** [comment]
Interesting, I didn't know there a static and totally static builds.

Let me add those addtl build flags.
