### ISSUE TITLE
Queue Custom metrics using Lua acript

### ISSUE THREAD

**Issue by OjerDev** [oliver006/redis_exporter#583]
First of all Thanks to this amazing exporter. Using this exporter I can get all "INFO" command metrics and also I can visualize it in Grafana. 

The question is,

As you mentioned, using the LUA script we can get the custom metrics. Is it possible to get the Custom metrics like "queue-related metrics" using LUA Script?

I need the following Redis_queue_metrics

- Redis_queue_length? (Each)
- Queue worker name?
- Total number of Queues?
- queue_request_processing_seconds?
- queue Jobs?
- Queue Status?

**Comment by oliver006** [comment]
That should be possible.
You might need to plan a little what your lua script result looks like so you can capture the metrics, esp things like worker name (make them a label value?) but in general that's possible.
[See the sample lua script here ](https://github.com/oliver006/redis_exporter/blob/master/contrib/sample_collect_script.lua)to get an idea how to do this.

**Comment by OjerDev** [comment]
Thank you @oliver006 

I have seen that sample script. I will start working on that. By the way, are you planning to add these features in the near future? 
If yes it would be helpful!!

**Comment by oliver006** [comment]
There are no plans to add these but if you like to add them in a PR I'd be happy to help with reviewing it.

**Comment by bmgante** [comment]
Hi @oliver006 @OjerDev , i am also really interested having redis queue metrics using this exporter. Were you able to achieve that? if yes, can you share please?
