### ISSUE TITLE
sample_redis_hosts_file.txt is left in `contrib` folder after `-redis.file` option was removed

### ISSUE THREAD

**Issue by nantiferov** [oliver006/redis_exporter#584]
**Describe the problem**

Hi, 
I think that `sample_redis_hosts_file.txt` file is left in `contrib` folder, while `-redis.file` option was removed.
I was checking Lua scripts in that folder and run into this file.

**What version of redis_exporter are you running?**

N/A

**Running the exporter**

N/A

**Expected behavior**

File `contrib/sample_redis_hosts_file.txt` is removed

**Screenshots**

N/A

**Additional context**

File mentioned here https://github.com/oliver006/redis_exporter/issues/198

**Comment by oliver006** [comment]
Thanks, removed in [d77b73d](https://github.com/oliver006/redis_exporter/commit/d77b73dc1f7fcf5c36eb0eba0fac214d18d3ec52).
