### ISSUE TITLE
Redis Stream item ids

### ISSUE THREAD

**Issue by Lupunita** [oliver006/redis_exporter#585]
**Describe the problem** 
The exporter does not provide information on Redis Stream item ids:
 
- [last-generated-id ](https://redis.io/commands/xinfo-stream) for stream
- [last-delivered-id ](https://redis.io/commands/xinfo-groups)  for stream consumer group

These two metrics can estimate how much are services keeping up with the traffic. And for instance, it would be possible to build a scaling logic based on that. 

The ID consists of a timestamp and a number of items added/delivered under some timestamp. I propose to parse just the timestamp as a unique ID.  `1538385846314-2` -> `1538385846314`

The custom ID would be ignored and metrics wouldn't return anything. 

Is it possible to add this? I have it prepared locally for PR if that would be ok? 

Thanks!

**Comment by oliver006** [comment]
Thanks for raising this issue.
Would you export these as metrics (a gauge) or as label values? 
For label values this could be problematic as this would generate a very high cardinality for the labels, something that Prometheus doesn't handle well.

**Comment by Lupunita** [comment]
No, definitively metrics. I am currently exporting these as `stream_last_generated_id` and `stream_group_last_delivered_id` metrics.

**Comment by oliver006** [comment]
Sounds good - I'd be happy to review and merge that PR.

**Comment by Lupunita** [comment]
Could you please give me access rights? 
Thanks!

**Comment by oliver006** [comment]
Fork the repo, create a branch in your repo, open a PR.

**Comment by oliver006** [comment]
Closed by #588 - thanks @Lupunita !
