### ISSUE TITLE
DialURL() failed, err: WRONGPASS invalid username-password pair"

### ISSUE THREAD

**Issue by scosma** [oliver006/redis_exporter#586]
Version of redis exporter: 

> INFO[0000] Redis Metrics Exporter v1.31.4    build date: 2021-11-17-12:31:49    sha1: f6e78de9161444a51c8c33fccf223d8d0ae11d4a    Go: go1.17.3    GOOS: linux    GOARCH: amd64 

If I launch the command on the server, I am able to connect to my Redis cluster in AWS with no issues, but when I execute the redis_exporter service which contains the same command it gives me this error:

> Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=info msg="Redis Metrics Exporter v1.31.4    build date: 2021-11-17-12:31:49    sha1: f6e78de9161444a51c8c33fccf22>
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="Enabling debug output"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="NewRedisExporter options: exporter.Options{User:\"default\", Password:\"xxxxxxxx\", Namespac>
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="keys: []exporter.dbKeyPair(nil)"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="singleKeys: []exporter.dbKeyPair(nil)"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="streams: []exporter.dbKeyPair(nil)"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="singleStreams: []exporter.dbKeyPair(nil)"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="parseKeyArg(): Got empty key arguments, parsing skipped"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="countKeys: []exporter.dbKeyPair(nil)"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=info msg="Providing metrics at :9121/metrics"
Nov 25 09:02:58 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:02:58Z" level=debug msg="Configured redis addr: \"rediss://master.swp-eu-redis-cluster-605.gysu5q.euw1.cache.amazonaws.com:6379>
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=debug msg="Trying DialURL(): rediss://master.swp-eu-redis-cluster-605.gysu5q.euw1.cache.amazonaws.com:6379"
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=debug msg="DialURL() failed, err: WRONGPASS invalid username-password pair"
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=debug msg="Trying: Dial(): rediss master.swp-eu-redis-cluster-605.gysu5q.euw1.cache.amazonaws.com:6379"
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=error msg="Couldn't connect to redis instance"
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=debug msg="connectToRedis( rediss://master.swp-eu-redis-cluster-605.gysu5q.euw1.cache.amazonaws.com:6379 ) err: d>
Nov 25 09:05:33 bastion-host-eu redis_exporter[50872]: time="2021-11-25T09:05:33Z" level=debug msg="scrapeRedisHost() done"

Here is the service configuration:
`[Unit]
Description=Prometheus Redis Exporter
After=network.target

[Service]
User=redis_exporter
Group=redis_exporter
Type=simple
Restart=always
ExecStart=/usr/local/bin/redis_exporter --debug  --web.listen-address=":9121" --redis.addr="rediss://master.swp-eu-redis-cluster-605.gysu5q.euw1.cache.amazonaws.com:6379" --skip-tls-verification  --redis.user="default"  --redis.password="xxxxxxxxxxx"

[Install]
WantedBy=multi-user.target`

Any ideea why this behaviour?
Thanks.

**Comment by oliver006** [comment]
Can you make sure the username password is set and escaped correctly in the startup script?
