### ISSUE TITLE
ssl protocol issue

### ISSUE THREAD

**Issue by skaravad** [oliver006/redis_exporter#587]
**Describe the problem**
ssl protocol errors, when connecting to redis cluster

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
```Redis Metrics Exporter v1.31.4```

**Running the exporter**
```
  REDIS_ADDR: rediss://localhost:6379
  REDIS_EXPORTER_DEBUG: "true"
  REDIS_EXPORTER_IS_CLUSTER: "true"
  REDIS_EXPORTER_NAMESPACE: redis
  REDIS_EXPORTER_PING_ON_CONNECT: "true"
  REDIS_EXPORTER_REDIS_ONLY_METRICS: "true"
  REDIS_EXPORTER_SET_CLIENT_NAME: "true"
  REDIS_EXPORTER_TLS_CA_CERT_FILE: /etc/server_trust_ca.crt
  REDIS_EXPORTER_TLS_CLIENT_CERT_FILE: /etc/certs/client.crt
  REDIS_EXPORTER_TLS_CLIENT_KEY_FILE: /etc/certs/client.key
  REDIS_EXPORTER_WEB_LISTEN_ADDRESS: 0.0.0.0:9113
```
**Expected behavior**
When scraping the metrics for redis cluster, we see errors in both redis and redis-exporter logs for a specific call, all metrics are being scraped, just that the logs in redis and exporter are kind of worrying.
```
redis_exporter error
time="2021-11-26T07:38:56Z" level=debug msg="Creating cluster object"
time="2021-11-26T07:38:56Z" level=debug msg="Running refresh on cluster object"
time="2021-11-26T07:38:56Z" level=error msg="Cluster refresh failed: redisc: all nodes failed\nread tcp 127.0.0.1:42196->127.0.0.1:6379: read: connection reset by peer"

redis error
36:S 26 Nov 2021 07:39:56.142 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
36:S 26 Nov 2021 07:40:35.392 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=21)
36:S 26 Nov 2021 07:40:56.151 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Screenshots**

**Additional context**

**Comment by skaravad** [comment]
from what I see, irrespective of the `REDIS_EXPORTER_IS_CLUSTER` flag, the cluster metrics are being scraped, not entirely sure how what metrics will not be available when this is set to false.
When I set this to false, the error goes away.

**Comment by oliver006** [comment]
Sorry for the late reply.
Not sure why this is happening but a quick google search for `routines:ssl3_get_record:wrong version number` yields a bunch of results that make it look like this means you're trying to talk non-SSL to a SSL connection. I wonder if there's an issue with the redis cluster refresh when using SSL.

**Comment by skaravad** [comment]
@oliver006 thank you, not sure why this specific call would try to bypass the TLS, for now we have disabled the cluster mode.
