### ISSUE TITLE
Add sentinel support

### ISSUE THREAD

**Issue by jmastr** [oliver006/redis_exporter#59]
Especially the master discovery part.

**Comment by oliver006** [comment]
Yeah, that'd be useful.

Alas, I don't have access to a Redis sentinel installation right now so help would be appreciated.

**Comment by jmastr** [comment]
I'll look into it

**Comment by renannprado** [comment]
We are using Kubernetes and this is our setup: 3 redis, 3 sentinels.
Each redis has its own exporter and so the sentinels (even though the support for sentinel info is not optimal). 
That being said: @jmastr and @oliver006 I don't think that the exporter should query the sentinel to find who the master is. But instead each of the nodes should get its own exporter. But I might be wrong or maybe I misunderstood what @jmastr said.

**Comment by oliver006** [comment]
Yes, preferably each redis instance should get its own exporter (in Kubernetes that's particularly easy by combining the two container to a pod).

I don't use redis_exporter with sentinel so not familiar with the shortcomings  but if you have suggestions what can be improved/added I'd love to hear 'em.

**Comment by siavashs** [comment]
We are also interested in knowings which node is **master/slave**(we need this in Grafana dashboard templating to automatically query the metrics from master's `resque_exporter`, etc.).

I've added this metric:
```
redis_replication{master_host="10.91.64.152",master_port="6379",role="slave"} 1
```

If you think this is useful, I can submit a PR.

**Comment by toredash** [comment]
@siavashs I wouldn't mind getting my hands on that

**Comment by siavashs** [comment]
@toredash check #105

**Comment by oliver006** [comment]
Closing, each redis instance should have its own redis_exporter and SD should be done in the Prometheus server (via e.g. Kubernetes)
