### ISSUE TITLE
scrape multiple redis nodes

### ISSUE THREAD

**Issue by skaravad** [oliver006/redis_exporter#590]
**Describe the problem**
We are running redis cluster in kubernets, right now each pod runs a sidecar of the exporter, is there a way if a single standalone scraper can scrape all redis pods , if yes, how the redis URL should be set in the command line or env-var, I tried few options but could not get the metrics for all pods.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
`Redis Metrics Exporter v1.31.4`

**Comment by oliver006** [comment]
Have a look at the documentation here: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
