### ISSUE TITLE
Key group script runs on every scrape, which feels like an overkill

### ISSUE THREAD

**Issue by avinash-getmega** [oliver006/redis_exporter#591]
**Describe the problem**
I feel running key group script on every scrape is an overkill. I feel so because I think here the real time metrics would not actually matter since we just want to understand the distribution of how keys are spread. This isn't to say the current approach is wrong.
I feel If we could somehow provide users with an option of specifying the interval at which this script should run, then that should do the job for both who want real time metrics and for those as well who can do with some stale metrics as well.

I was facing a small issue with the current approach, my redis has around ~10mil entries and ~5GB mem, and since the scrape runs the script in sync, I guess every scrape would also take a longer duration to complete just because of the key group extension.

Moreover, the main issue I faced was that even after waiting for ~5 hours, I didn't get any data from the exporter. I was able to get data from exporter as soon as I disabled the key group extension.
Also, I tried to access the http endpoint exposing metrics on redis-exporter and it wasn't replying anything, I guess I needed to wait for some minutes before the script completed to get the response.

**Comment by avinash-getmega** [comment]
#592 
Here, I'm running the key group metric collection in parallel and the collection runs at an interval which by default is set to 1hr but can be changed using environment variable. Please let me know if this is helpful, I would be happy to discuss and help.

**Comment by oliver006** [comment]
Please see my comment in #592 - I don't think using async is the way to go here. You have options to address this via your Prometheus server setup by using a scrape config with larger intervals.
