### ISSUE TITLE
Errors when getting streams info on redis cluster slaves

### ISSUE THREAD

**Issue by artem198315** [oliver006/redis_exporter#594]
**Describe the problem**
I have Redis cluster installation.
When running redis_exporter with check-streams option enabled  redis_exporters on Redis Slaves throw errors when trying fetching stream info.

**What version of redis_exporter are you running?**
v1.32.0

**Running the exporter**
redis_exporter -log-format txt -redis.addr redis://localhost:6379 -redis.password *** -namespace redis -web.listen-address 0.0.0.0:9121 -web.telemetry-path /metrics -check-streams platform:ManagedRedisStreamsDatabase:stream:* -is-cluster

**Expected behavior**
At least errors must not be produced.

**Comment by oliver006** [comment]
What error do you see?
