### ISSUE TITLE
Get redis statistics by username

### ISSUE THREAD

**Issue by jelmokri** [oliver006/redis_exporter#595]
Hello everyone,

do you know if it's possible to have redis statistics & metrics by username ?
Since REDIS 6 and the possibility to have diff rents users than the default one, it could be useful to have statistics by username.

I have search on internet but didn't find any useful in formations.

Thanks for your help !!

**Comment by oliver006** [comment]
That's a very good question (and agreed, it would be a useful metric) but I'm not sure that's possible right now. It depends on if the INFO command provides detailed stats on a per-user basis.

**Comment by oliver006** [comment]
Doesn't look like this is possible.
