### ISSUE TITLE
The KeyDB Multi-Master with Active-Active Mode Support or Not?

### ISSUE THREAD

**Issue by j13tw** [oliver006/redis_exporter#598]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
Place the redis-export same of the KeyDB Pod (like same host)
and use prometheus record the metrics

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Dose the redis-exporter have metric record the KeyDB special feature?
may likes the button items
- All master host List
- Master to Master Ping
- Cluster Status

**Comment by oliver006** [comment]
```
    All master host List
    Master to Master Ping
    Cluster Status
```

I don't think these are exported (yet).
If `CONFIG` cmd provides them then adding these metrics should be trivial.
