### ISSUE TITLE
Detect cluster nodes automatically

### ISSUE THREAD

**Issue by madhur** [oliver006/redis_exporter#599]
**Describe the problem**
We have setup the redis exporter successfully in cluster configuration. Ours is a enterprise hosted model by Redis labs where they just provide us with a single endpoint in form of (hostname:port). Behind the scenes the redis nodes are scaled up/down depending upon the iops configuration  in https://app.redislabs.com/#/login

Currently, we have setup the monitoring for each node by figuring out the IP Address of each node and specifying them in prometheus configuration. However, it would be great if exporter could do that automatically. This will be especially useful when nodes scale up/down elastically. We won't have to alter the prometheus configuration everytime.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ x] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

```
/opt/redis_exporter/bin/redis_exporter -log-format txt -redis.addr -namespace redis -web.listen-address 0.0.0.0:9121 -web.telemetry-path /metrics
```

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
Node/service discovery belongs in the Prometheus server, not the exporter.

In your case you could use File SD, have a process (cronjob & script or similar) that keeps track of what the cluster nodes are and writes them to a json file. In this way only the json file changes and the Prometheus server will automatically pick up any changes and scrape the new targets.

See https://prometheus.io/docs/guides/file-sd/ for more information.
