### ISSUE TITLE
Build version missing

### ISSUE THREAD

**Issue by michnovka** [oliver006/redis_exporter#601]
**Describe the problem**
I am building from source with Go 1.17.6 (and any prev version I tested) and some variables are not filled in by build:

The build script I use is just from the README.md
```

git clone https://github.com/oliver006/redis_exporter.git
cd redis_exporter
go build .
./redis_exporter --version
```
And still the version is not filled in

```
[root@hv-api3 redis_exporter]# ./redis_exporter --version
INFO[0000] Redis Metrics Exporter <<< filled in by build >>>    build date: <<< filled in by build >>>    sha1: <<< filled in by build >>>    Go: go1.17.6    GOOS: linux    GOARCH: amd64 

```

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[X ] 1.x.x

**Comment by oliver006** [comment]
Check the Makefile, they're being filled in by the "go build" command.

**Comment by michnovka** [comment]
Yea, but the README.md uses plain `go build .` which is problematic because the proper values are not inserted. I created a PR https://github.com/oliver006/redis_exporter/pull/602 to address this. Please check

**Comment by michnovka** [comment]
Actually that pull request still doesnt fix it, as you use `DRONE_TAG` and `DRONE_COMMIT_SHA` to insert the values, which are not present for local go build of the repo. So what do you suggest?

**Comment by oliver006** [comment]
You could add a `build` target to the Makefile that runs the build and then set the env variables yourself.
I didn't have a need for this because those variables are only of informational value for the releases and not of much/any use when building/running locally.
