### ISSUE TITLE
Prometheus.yml not used

### ISSUE THREAD

**Issue by Stobbe9** [oliver006/redis_exporter#610]
Hello,

I am trying to export two Redis instances and I have created a prometheus.yml,

start with:

./redis_exporter --redis.addr=

Prometheus.yml:

scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'DEFAULT'
    static_configs:
    - targets:
      - redis://localhost:6379
      - redis://localhost:6380
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
   ## config for scraping the exporter itself
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - <<REDIS-EXPORTER-HOSTNAME>>:9121
This is not picked up at start:

DEBU[0000] Configured redis addr: ""

What am I doing wrong )-;

Go: go1.13.8    GOOS: linux    GOARCH: amd64

KR Henk Stobbe

**Comment by oliver006** [comment]
The yaml is a bit malformed / misformatted so it's hard to say what exactly is going wrong but have a look at this section here:
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts

For instance, make sure `REDIS-EXPORTER-HOSTNAME` is filled in correctly.
