### ISSUE TITLE
[CR] Dynamic Stream Options

### ISSUE THREAD

**Issue by BubbaJoe** [oliver006/redis_exporter#614]
**Describe the problem**

Hello,

I have a few streams in Redis and I add new streams frequently, so this means updating the list (REDIS_EXPORTER_CHECK_STREAMS) every time I need to add a new feature, it's also not very pretty to have really long environment variable names.

I tried using `*`, `.*` and `(.*)` as the `REDIS_EXPORTER_CHECK_STREAMS`, but this did not have select all streams in redis for me. It would be nice if there was a dynamic stream selector option to allow this, so that it automatically add  multiple stream metrics without having to specify all of them. For my use-case, I would like to monitor all streams, but maybe this isn't the case for all users, so regex might also be a good idea.

A list of streams can be fetched for a specific database via `SCAN 0 TYPE stream` periodically. Maybe this can be called for each database also? Let me know what you think?

**Comment by BubbaJoe** [comment]
@oliver006 Do you foresee any issues with this feature?

i.e. Needs large refactor? ? Already exists?

**Comment by oliver006** [comment]
Sorry, took me a few days to get to this.

I think this is already supported by the `--check-streams` parameter which supports patterns (and `*` should work but I have not tried it myself).
The patterns are checked with `SCAN` [here](https://github.com/oliver006/redis_exporter/blob/master/exporter/streams.go#L141) - if it's broken then it needs a bit of investigating.

**Comment by BubbaJoe** [comment]
Hello @oliver006; Thanks you your reply,

I dont think this will work because it will get all keys right? Not just the stream keys. Let me test this.

**Comment by oliver006** [comment]
Any luck with this @BubbaJoe ?

**Comment by BubbaJoe** [comment]
Hey I tried it and it worked. My streams have a specific pattern, "prefix-*".

**Comment by oliver006** [comment]
🚀
