### ISSUE TITLE
[Feature]  Azure MSI support

### ISSUE THREAD

**Issue by NissesSenap** [oliver006/redis_exporter#615]
**Describe the problem**

Would you be willing to add support for cloud specific auth solution. For example Azure MSI support?

This would help me to be able to spin up the application inside kubernetes and I could reach my redis servers inside Azure without having to provide username and password. 

**Thoughts**

It's not very hard to implement but all cloud providers have their own solution for this.
It can easily become something that other cloud users would like to have. Both AWS and GCP have similar functionality.

**Additional context**

- https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

**Comment by oliver006** [comment]
I'm not sure I follow what components need to auth. 
Are you running the Prometheus inside the cluster? And exporter as well? Maybe a little diagram would help with making this more clear.

**Comment by NissesSenap** [comment]
Hi @oliver006 , for sure.

I'm running both redis-expoter inside kubernetes and prometheus inside kubernetes.
I use Azure redis which is outside of the cluster.

![image](https://user-images.githubusercontent.com/14774899/154720661-eb85f05a-99da-46fc-a245-a8d6a2457c5f.png)

So to setup a connection to redis without defining a password I could use MSI and use a "service account" that I provide with read access to redis. This way I don't have to handle passwords.

Currently I use a password file that looks something like this:

```.json
    {
      "rediss://my-random-redis.redis.cache.windows.net:6380": "superSecretPassword"
    }
```

and my simplified kubernetes yaml looks like this (I plan to create a PR with my example setup):

```.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-instance-redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
      app.kubernetes.io/instance: my-redis-instance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-exporter
        app.kubernetes.io/instance: my-redis-instance
    spec:
      containers:
        - name: redis-exporter
          env:
            - name: REDIS_ADDR
              value: rediss://my-random-redis.redis.cache.windows.net:6380
            - name: REDIS_PASSWORD_FILE
              value: "/mnt/secret/redis-exporter-productcatalog"
          image: "oliver006/redis_exporter:v1.35.1"
          ports:
            - name: metrics
              containerPort: 9121
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mnt/secret
              readOnly: true
      volumes:
      - name: config
        secret:
          secretName: mysecret
---
# Source: redis-exporter/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-redis-instance-redis-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-exporter
      app.kubernetes.io/instance: my-redis-instance
  endpoints:
    - port: metrics
      path: /metrics
      relabelings:
        - targetLabel: instance
          replacement: my-redis-instance
```

If i can do this in any better way I would love feedback. I the docs there is some talk about sending password through prometheus that way.

My understanding is that even if you would do that I can only connect to a single redis instance from my redis-expoter so I have to have one redis-expoter per redis instance. Is this correct?

**Comment by oliver006** [comment]
Sorry, just getting back to this, I was OOO for a few days.
Thanks for explaining MSI and your setup. I'm still not sure how MSI would work from an auth perspective or how the Golang redis library would handle auth when connecting. 
For instance, I see that GCP Redis Memorystore can do authentication using an AUTH string so you could use that and pass that as the password.

As for the `connect to a single redis instance from my redis-exporter` - you can monitor multiple Redis instances with one exporter, [see here in the README](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) for how to set this up ([and this section](https://github.com/oliver006/redis_exporter#authenticating-with-redis) if you're scraping password protected Redis instances).

**Comment by NissesSenap** [comment]
The reason to use MSI would be to not having to pass the password at all. But since this is a more general redis exporter it's probably not worth to fuzz to add a azure specific feature to get rid of the passwords.

I might give it a try in the future but for now I will close the issue.
Thanks for your feedback @oliver006

**Comment by oliver006** [comment]
I understand why MSI is of interest, it's just not clear to me how it would actually work with the current Redis library. Do you have an example for that? (could be of any redis client)
