### ISSUE TITLE
redis_memory_max_bytes is 0

### ISSUE THREAD

**Issue by chenaichenet** [oliver006/redis_exporter#617]
Hello, in the process of using redis exporter, I wanted to obtain the utilization rate of redis, so I used "redis_memory_used_bytes/redis_memory_max_bytes", but now, "redis_memory_max_bytes"The data of bytes is always 0, which leads to the exception of my data. Excuse me, about "redis_memory_max_bytes", is there a corresponding switch or indicator item that needs to be opened manually? Or is there another solution?

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#the-redis_memory_max_bytes-metric
