### ISSUE TITLE
-redis.password-file is not working as expected, it doesn't recongized multi character

### ISSUE THREAD

**Issue by michael-liumh** [oliver006/redis_exporter#624]
**Describe the problem**

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[x] 0.3x.x
[x] 1.x.x
![image](https://user-images.githubusercontent.com/40595864/161186006-b56ad3da-5913-476a-8123-34ac62a49a03.png)

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/40595864/161186090-573fa768-93c3-4b40-9e05-b3fde519c260.png)
Is it a bug?
![image](https://user-images.githubusercontent.com/40595864/161186841-2b617483-032d-4358-b0ba-647460c09147.png)
This is my password, this instance is only for test, so that password is not sensitive

**Additional context**

**Comment by oliver006** [comment]
Hey there,

Looks like this is a case of insufficient documentation, the [auth section here](https://github.com/oliver006/redis_exporter#authenticating-with-redis) isn't as clear as it should be.
The password file is expected to be a json map of "addr" --> "pwd" mappings, have a look at 
https://github.com/oliver006/redis_exporter/blob/master/contrib/sample-pwd-file.json
for an example.

I'll add to the documentation to make this more clear.
