### ISSUE TITLE
Is there a way to monitor Multiple redis instances with a single redis-exporter

### ISSUE THREAD

**Issue by Thara-123** [oliver006/redis_exporter#625]
Our application has two redis endpoints is there a way to monitor both the redis instances using same exporter

redis exporter version used is v.1.37.0 

There is a variable called "REDIS_ADDR" where we  pass the redis endpoint details, Is there any way to point multiple instances here

Thanks in advance

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
