### ISSUE TITLE
Invalid password included in redis URL

### ISSUE THREAD

**Issue by dong9205** [oliver006/redis_exporter#626]
**Describe the problem**
redis_export log: Couldn't set client name, err: NOAUTH Authentication required

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
Exporter：v1.37.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

start: docker run -d --name redis_exporter -p 9121:9121 oliver006/redis_exporter

**Screenshots**

**Additional context**
***commond***
curl 127.0.0.1:9121/scrape?target=redis://password@127.0.0.1:6379

***log***
time="2022-04-08T02:56:36Z" level=error msg="Couldn't set client name, err: NOAUTH Authentication required."
time="2022-04-08T02:56:36Z" level=error msg="Redis INFO err: NOAUTH Authentication required."

**Comment by oliver006** [comment]
Looks like you need a password to connect to the Redis instance?
