### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by feixia5712** [oliver006/redis_exporter#627]
[root@localhost redis_exporter]# ./redis_exporter -version
INFO[0000] Redis Metrics Exporter v1.37.0    build date: 2022-03-18-01:20:01    sha1: a1c28b775760f2f00fce07a24db7fd4e83c26b9f    Go: go1.17.8    GOOS: linux    GOARCH: amd64
//
![image](https://user-images.githubusercontent.com/12670758/162397759-7954fcb3-e3ab-480b-8383-5fccd4a9a704.png)
![image](https://user-images.githubusercontent.com/12670758/162397799-dba30858-7dcf-46df-b9d7-50b8462af6b7.png)

**Comment by feixia5712** [comment]
redis version 5.x

**Comment by oliver006** [comment]
Looks like you need to provide a password to connect to this Redis instance? 

I think there's a mistake in your command line, it should be `--redis.password-file` - you're missing the two dashes.

**Comment by feixia5712** [comment]
to do 
![image](https://user-images.githubusercontent.com/12670758/162864786-125efc31-ead3-45fc-a543-c8276fd59479.png)

**Comment by feixia5712** [comment]
it working !!!!!
/opt/redis_exporter/redis_exporter -redis.addr=10.10.157.73:6379 -redis.password-file=/opt/redis_exporter/file.json
BUT，，， There are some mistakes
`level=error msg="Loaded 1 entries from /opt/redis_exporter/file.json"`
=========
However, the monitoring data can still be obtained
curl 10.10.157.73:9121/metrics
