### ISSUE TITLE
Expose p99/p99 redis latency metrics

### ISSUE THREAD

**Issue by g0a019a** [oliver006/redis_exporter#631]
Hi Team,
I am using redis open source for my application and would like to know when redis exporter will start supporting to expose metrics which is related to p99/p95 latency metrics. 
As we saw in latest version for redis 7 supports latency histogram stats.Any plans from redis exporter to support these metrics ?

Thank you

**Comment by g0a019a** [comment]
any updates @oliver006

**Comment by oliver006** [comment]
Apologies for the delayed response, the last few weeks were busy.
Yes, adding these metrics would be great. If they're available via "INFO ALL" then it should be easy to get them exported.

**Comment by filipecosta90** [comment]
@oliver006 will gladly open a PR for it. Parsing all the exposed percentiles via:
```
redis-cli info all
```

``(...)
# Latencystats
latency_percentiles_usec_rpop:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_zadd:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_hset:p50=0.001,p99=1.003,p99.9=3.007
latency_percentiles_usec_set:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_lpop:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_lpush:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_lrange:p50=17.023,p99=21.119,p99.9=27.007
latency_percentiles_usec_get:p50=0.001,p99=1.003,p99.9=3.007
latency_percentiles_usec_mset:p50=1.003,p99=1.003,p99.9=1.003
latency_percentiles_usec_spop:p50=0.001,p99=1.003,p99.9=1.003
latency_percentiles_usec_incr:p50=0.001,p99=1.003,p99.9=3.007
latency_percentiles_usec_rpush:p50=0.001,p99=1.003,p99.9=4.015
latency_percentiles_usec_zpopmin:p50=0.001,p99=1.003,p99.9=3.007
latency_percentiles_usec_config|resetstat:p50=280.575,p99=280.575,p99.9=280.575
latency_percentiles_usec_config|get:p50=8.031,p99=27.007,p99.9=27.007
latency_percentiles_usec_ping:p50=0.001,p99=1.003,p99.9=1.003
latency_percentiles_usec_sadd:p50=0.001,p99=1.003,p99.9=3.007
```

**Comment by oliver006** [comment]
Released as v1.38.0

**Comment by philandrewatfamilyzone** [comment]
How to access these metrics?

**Comment by filipecosta90** [comment]
> How to access these metrics?

@philandrewatfamilyzone this info is available in Redis via `INFO LATENCYSTATS` since redis 7.0.
