### ISSUE TITLE
Support for cluster auto configure

### ISSUE THREAD

**Issue by katepangLiu** [oliver006/redis_exporter#632]
**Describe the problem**
Giving any node of cluster, we can query the nodes list of the cluster. 
Why not just add a node as target, if it's cluster mod, then exporter fetch all metrics from nodes of the cluster.

**Comment by katepangLiu** [comment]
If it is ok, I will try to add this feature.

**Comment by oliver006** [comment]
The "prometheus-esque" way to do this is to handle SD outside the exporter and have e.g. an exporter per Redis instance and let the Prometheus server handle the rest.
