### ISSUE TITLE
Exporter unable to connect to the Redis instance

### ISSUE THREAD

**Issue by anjalin1001** [oliver006/redis_exporter#642]
Hi I am using redis exporter to get the metrics from Memorystore for Redis.
It was initially working and all of  a sudden , after some days, I was getting this connection issue .
I tried to add multiple redis instances to the redis exporter, that was one of the changes I tried to do, but reverted back.
I checked if its the Redis instance problem, but I was able to ping the instance from VM and Kubernetes pods.
Could you please help. 

  name: redis-exporter
  namespace: monitoring
  resourceVersion: "184731251"
  uid: 0d2e9e2d-8b4a-4d34-9e42-5bc3b193cc12
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: redis-exporter
    spec:
      containers:
      - env:
        - name: REDIS_1
          value: redis://<redis_instance_ip>:6379
        image: oliver006/redis_exporter:latest
        imagePullPolicy: Always
        name: redis-exporter
        ports:
        - containerPort: 9121
          protocol: TCP
        resources:
          limits:
            cpu: 256m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

**Comment by oliver006** [comment]
Please provide more information like logs when running the exporter in debug mode, commands you run to test this, etc etc.

**Comment by anjalin1001** [comment]
I am using GKE.
I am directly deploying the yaml in kubernetes and the redis url was mentioned as specified earlier comment. 
From a particular day onwards, the exporter stopped working and the error message I could see in the Cloud logging was "unable to connect  to Redis instance"

**Comment by oliver006** [comment]
Try running it with the `--debug` flag, that should give addtl log output that can help with diagnosing the issue.
