### ISSUE TITLE
Update dashboard on grafana.com

### ISSUE THREAD

**Issue by dataviruset** [oliver006/redis_exporter#645]
**Describe the problem**
The dashboard in the [repository](https://github.com/oliver006/redis_exporter/tree/master/contrib/grafana_prometheus_redis_dashboard.json) is newer than the one on [Grafana.com](https://grafana.com/grafana/dashboards/763). Would be great if you could update the one on Grafana.com so it can be referenced for automatic download by the Grafana chart.

https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#import-dashboards

There's a workaround right now, to use the `url` directive pointing to this GitHub repository instead of `gnetId`, but it would be good if I could standardize to use Grafana.com for all my dashboards.

Thanks for creating this great project :)

**Comment by oliver006** [comment]
Good call-out, thanks!
I updated the grafana.com repo with the latest version.

**Comment by hinricht** [comment]
Please update again, thanks !

**Comment by oliver006** [comment]
Done!
