### ISSUE TITLE
KeyDB get information about keys per DB

### ISSUE THREAD

**Issue by vitalvas** [oliver006/redis_exporter#650]
**Describe the problem**
The `redis_db_keys` and `redis_db_keys_expiring` always zero.

**What version of redis_exporter are you running?**
```
INFO[0000] Redis Metrics Exporter v1.37.0    build date: 2022-03-18-01:20:01    sha1: a1c28b775760f2f00fce07a24db7fd4e83c26b9f    Go: go1.17.8    GOOS: linux    GOARCH: amd64
```

**Running the exporter**
No any args and env variables.

**Screenshots**
```
172.31.130.70:6379> INFO Keyspace
# Keyspace
db0:keys=12867,expires=12833,avg_ttl=3465683577997863,cached_keys=12867
```

**Additional context**
KeyDB server:

```
KeyDB server v=6.3.0 sha=cbc7a895:1
```

**Comment by oliver006** [comment]
I think #656 will fix this.
