### ISSUE TITLE
After starting Docker, I cannot enter the container

### ISSUE THREAD

**Issue by oubodan** [oliver006/redis_exporter#655]
I pulled the container from the official website, but I could not enter the container. May I ask what operating system is used at the bottom of this Docker

**Comment by oliver006** [comment]
`but I could not enter the container` - what does that mean?

**Comment by oubodan** [comment]
docker exec -ti  oliver006/redis_exporter:v1.13.1   /bin/bash
 
An error：OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bi/bash\": stat /bi/bash: no such file or directory": unknown

**Comment by oliver006** [comment]
Same as #657 ?
