### ISSUE TITLE
Redis exporter hangs on dead redis target

### ISSUE THREAD

**Issue by andel7** [oliver006/redis_exporter#66]
If provided with multiple redis hosts and one of them is inactive/dead  via -redis.addr parameter - the exporter hangs even if other redis hosts are up and running.

**Way to reproduce:**
$./redis_exporter -redis.addr working_server1_IP:6379, working_server2_IP:6379,dead_server1_IP:6379 

$wget http://localhost:9121/metrics

**Comment by oliver006** [comment]
Interesting, thanks for reporting, let me have a look how to fix that.

**Comment by andel7** [comment]
Thank you

**Comment by oliver006** [comment]
Just tagged and released it as v0.11.1
