### ISSUE TITLE
Use and visualize tracked keys or key groups

### ISSUE THREAD

**Issue by rhymes** [oliver006/redis_exporter#668]
**Describe the problem**

I read the documentation but it's not clear to me how to visualize tracked keys in Grafana

**What version of redis_exporter are you running?**

[x] 1.43.0

**Running the exporter**

I'm deploying it on Render.com with a `Dockerfile` that only imports the base image from Docker Hub:

```Dockerfile
FROM oliver006/redis_exporter:v1.43.0
```

I can see the basic Redis graphs but I can't find how to visualize `check-keys`, `check-single-keys` and `check-key-groups` in graphs. 

This is how env vars are configured:

```shell
REDIS_EXPORTER_CHECK_KEY_GROUPS=namespace1:namespaceA:*,namespace1:namespaceB:*,namespace1:namespaceC:*
REDIS_EXPORTER_MAX_DISTINCT_KEY_GROUPS=10
REDIS_EXPORTER_CHECK_SINGLE_KEYS=a-single-key
REDIS_EXPORTER_DEBUG=true
REDIS_EXPORTER_INCL_SYSTEM_METRICS=true
REDIS_EXPORTER_PING_ON_CONNECT=true
```

In the logs of the server I see 

```
Jun 23 11:40:57 AM  time="2022-06-23T09:40:57Z" level=debug msg="NewRedisExporter options: exporter.Options{User:\"\", Password:\"\", Namespace:\"redis\", PasswordMap:map[string]string{}, ConfigCommandName:\"CONFIG\", CheckKeys:\"\", CheckSingleKeys:\"a-single-key\", CheckStreams:\"\", CheckSingleStreams:\"\", CheckKeysBatchSize:1000, CheckKeyGroups:\"namespace1:namespaceA:*,namespace1:namespaceB:*,namespace1:namespaceC:*\", MaxDistinctKeyGroups:10, CountKeys:\"\", ...
```

Is it configured correctly? How do I visualize these groups in Grafana?

Thank you!

**Comment by oliver006** [comment]
I'm no Grafana expert, sorry. I looked in the past if it's possible to extract label values as a metrics but didn't find anything.

**Comment by rhymes** [comment]
Thank you! In the meantime I think I at least I extracted the metrics from the endpoint. Also I looked at the Go tests and used better regular expressions with capturing groups. I'm going to close this. 

Thanks for the precious tool!
