### ISSUE TITLE
redis slow log metrics

### ISSUE THREAD

**Issue by Colstuwjx** [oliver006/redis_exporter#67]
As redis has [slow log metrics](https://redis.io/commands/slowlog
) to show the slowest CMD, we should export these to prom. Thus, grafana could show the topK slow CMD, and makes redis ops feel happy.

**Comment by oliver006** [comment]
@Colstuwjx - what do you think would be useful to export for the slow log?

I could see the number of slow log entries being useful (e.g. export `SLOWLOG LEN`) but the slow log contents itself seems not really suitable for exporting.

Thoughts?

**Comment by Colstuwjx** [comment]
Yes, I agree that. Instead collecting the detail slow log CMD as "metrics" into prometheus, I'd like to scrape them into Elastic.

Thanks a lot for your reply.

**Comment by mazzy89** [comment]
i'd need a slow queries view in Grafana maybe showing the last 10 slow query. My idea would be to have a metric that would look like this:

```
redis_slowlog_info{command='', id='', time='', exeution=''}
```

where the values are the result of the `SLOWLOG` query properly parsed.

wouldn't be hard to add this to the exporter. What do you think @oliver006 ?

**Comment by oliver006** [comment]
I think that's something for log collection, not for metrics and therefor out of scope for the exporter.

**Comment by siwyd** [comment]
FYI, you can use Filebeat to export slow logs: https://www.elastic.co/blog/brewing-in-beats-read-redis-slow-logs-with-filebeat

**Comment by madhur** [comment]
I think slow queries logs are really needed to be exported for prometheus. Atleast the top 10
