### ISSUE TITLE
What's up with the Ukranian flag on top of the README?

### ISSUE THREAD

**Issue by popovpa** [oliver006/redis_exporter#670]
Describe the problem
Whats doing ukranian flag at readme???
Leave it please for evening dinner with your parents, friends and other.
Delete it

What version of redis_exporter are you running?
Please run redis_exporter --version if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

Running the exporter
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

Screenshots
If applicable, add screenshots to help explain your question.

Additional context
Add any other context about the question here.

**Comment by oliver006** [comment]
Thanks for opening this issue, Pavel.

Unfortunately, I'm not kidding. Having a Russian autocrat/dictator starting a war in the middle of Europe is not a fun matter.

> `Leave it please for evening dinner with your parents, friends and other.`
>> **`friends and other.`**

That's exactly why I added the bit to the README of my Github repo. To make friends and others aware of the issue and link to resources where they can find more information and ways to help.

**Comment by oliver006** [comment]
fwiw, this issue prompted me to update the section, [this repo has good sample banners](https://github.com/vshymanskyy/StandWithUkraine) and I took a new one from there.

**Comment by anytron** [comment]
Ukranian is NAZI
