### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by nanom1t** [oliver006/redis_exporter#674]
**Describe the problem**
The Grafana dashboard does not work. There are metrics in Prometheus for redis, but Grafana shows errors:
```
Templating
Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found

Templating [instance]
Error updating options: Datasource ${DS_PROMETHEUS} was not found
```

**What version of redis_exporter are you running?**
v1.43.0

**Running the exporter**
redis_exporter --web.listen-address=127.0.0.1:9121 --redis.addr=redis://127.0.0.1:6379 --redis.password=123

![Screenshot from 2022-07-08 15-37-25](https://user-images.githubusercontent.com/6481192/177993794-d3f0eb81-a36b-4c59-9c98-43e4cc094125.png)
![Screenshot from 2022-07-08 14-51-22](https://user-images.githubusercontent.com/6481192/177993796-cb3b32cd-f2ae-40bc-8ca7-b2dd9a35bd6b.png)

**Comment by nanom1t** [comment]
@oliver006 Could you please help with this issue? Thanks

**Comment by oliver006** [comment]
I Just tried the [dashboard for 1.x (contrib/grafana_prometheus_redis_dashboard.json) ](https://github.com/oliver006/redis_exporter/blob/master/contrib/grafana_prometheus_redis_dashboard.json) and it works just fine.
