### ISSUE TITLE
redis-exporter failing with tls enabled

### ISSUE THREAD

**Issue by ayasha05** [oliver006/redis_exporter#676]
I have used the certs files for tls and mentioned same in the redis exporter configuration, it is showing the metrics but the redis_mode is coming as the standalone even though it is cluster mode and some of the metrics is not visible, rest of things like redis-cli commands is working fine.

**Comment by oliver006** [comment]
Thanks for reporting this.
Does the same happen (wrong redis_mode) when not using TLS? Can you isolate a minimal test case to reproduce?

**Comment by oliver006** [comment]
Clsoing - please re-open when you can provide more information to track this down.
