### ISSUE TITLE
how to start redis_exporter when the key file path 'cipher-dir' is configured in the redis.conf?

### ISSUE THREAD

**Issue by hiuwan** [oliver006/redis_exporter#683]
**Describe the problem**
The key file path 'cipher-dir' is configured in the redis.conf, and connect to redis instance should specify the 'cipherdir', now i should how to start redis_exporter? I don't know how to pass this 'cipherdir' parameter.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 1.43.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.
./redis_exporter -redis.user xxx -redis.password xxx -redis.addr 127.0.0.1:26520

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
I can't find any conclusive documetnation aroudn this. In fact, a google search for `redis "cipherdir"` leads to an old issue in this repo (https://github.com/oliver006/redis_exporter/issues/200).
I guess the answer is, it's not supported right now.
