### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by mjtrangoni** [oliver006/redis_exporter#69]
Hi @oliver006,
I would like make a kind of feature request. Could it be possible having a Makefile here, as well as Build Information handle correctly like the most of Prometheus-Exporters? If you are interested about it, I would be making a PR soon. Thanks!

**Comment by oliver006** [comment]
Yeah, a PR would be greatly appreciated. Thanks!

**Comment by mjtrangoni** [comment]
Perfect! I am working on it. Expect a PR at weekend. Thanks!

**Comment by oliver006** [comment]
👍

**Comment by kpachhai** [comment]
Is this being worked on? I would love to work on this as my first contribution to an open source project!! @mjtrangoni Let me know.

**Comment by mjtrangoni** [comment]
HI @kpachhai,
You can fork my PR #73 and coordinate it with @oliver006. I am currently a bit busy, sorry!
