### ISSUE TITLE
Impossible to use multiple Lua scripts with exporter

### ISSUE THREAD

**Issue by nantiferov** [oliver006/redis_exporter#699]
**Describe the problem**
Hello, as I can see from the code and experimentally, there is no way to define couple of Lua scripts to evaluate by exporter. Only one is working in the end. I 

If there is no critical requirement, is it possible improve exporter to handle multiple scripts?
Or add information to Readme about this limitations.

**What version of redis_exporter are you running?**
`Redis Metrics Exporter v1.37.0    build date: 2022-03-18-01:20:01    sha1: a1c28b775760f2f00fce07a24db7fd4e83c26b9f    Go: go1.17.8    GOOS: linux    GOARCH: arm64`
* [ ] 0.3x.x
* [x] 1.x.x

**Running the exporter**
```sh
redis_exporter -redis.addr redis://localhost:6379 -script script1.lua -script script2.lua
```
Only last script is working.

**Screenshots**
None

**Additional context**
None

**Comment by oliver006** [comment]
Ah yes, you're right, only one lua script is supported. I think it'd be easy to add support for multiple if you're interested in opening a PR.

**Comment by nantiferov** [comment]
Sure, thanks, will try to create a PR around next week.

I'm thinking of add new option like `-script-folder` to pass whole folder with Lua scripts.
And maybe allow multiple definition of current `-script` like [here](https://go.dev/play/p/Ig5sm7jA14), but it will probably break env variable `REDIS_EXPORTER_SCRIPT` support.

Also, as an option, we can just split what's passed to `-script` or env var by `,` for example, which allow to pass multiple scripts separated by `,`.

What do you think?

**Comment by oliver006** [comment]
Sorry, I as away over the weekend.
I like the suggestion of extending the currently available flags and env var instead of adding new cmd line options.
Maybe both suggested options are possible, parse and split the env using `,` as a separator and also support passing the `--script` flag multiple times.

**Comment by nantiferov** [comment]
@oliver006  one more thing I noticed - I forgot to update docs on how to use it in mine PR https://github.com/oliver006/redis_exporter/pull/704

I can create it, but my question is should I open new GH issue or just mention this one in new PR?

**Comment by nantiferov** [comment]
Nevermind, created PR https://github.com/oliver006/redis_exporter/pull/804
