### ISSUE TITLE
[BUG] Bad message length or signature received from Cluster bus & quorum reached

### ISSUE THREAD

**Issue by n1vgabay** [oliver006/redis_exporter#703]
**Describe the problem**
Increased resources for redis-cluster & redis-exporter.
Uninstall & install bitnami/redis-cluster helm chart again. Didn't help.

```
1:M 29 Sep 2022 14:52:25.003 # Bad message length or signature received from Cluster bus.
1:M 29 Sep 2022 14:52:25.003 # Bad message length or signature received from Cluster bus.
1:M 29 Sep 2022 14:52:25.003 # Bad message length or signature received from Cluster bus.
1:M 29 Sep 2022 14:52:25.003 # Bad message length or signature received from Cluster bus.
```

**What version of redis_exporter are you running?**
1.23.1-debian-10-r24

**Expected behavior**
redis-exporter looks like being the cause for redis not to function properly. Expected behaviour is NOT to get messages above.

When I disable metrics and redis exporter from the redis-cluster, there is not issues appears.

**Comment by oliver006** [comment]
Hey there and sorry about the delay.
I see you also [raised the issue in the redis repo](https://github.com/redis/redis/issues/11339).
Frankly, I have no idea what could trigger this but I also don;t use Redis Cluster so not familiar with its workings on what the guy means by "sending messages to the cluster bus" - maybe the ports need to be configured differently? No idea, just guessing, sorry.

**Comment by madolson** [comment]
I can provide a little context about Redis cluster. There are two ports for Redis during cluster mode, the main port for accepting incoming commands and a separate port that is used by the cluster to send messages to each other. My guess is that somehow the exporter is being configured to send messages to this incorrect port.

**Comment by DGRFL** [comment]
My redis cluster has 3 masters & 3 slaves (1 m+s per VM).
1 such master listens on ports 7000 and 17000. (7000 specified in redis.conf).

When using  - redis://git-kfkrds01:7000
in prometheus.yml, I get : 

```
3490883:S 27 Oct 2022 15:05:39.339 - Accepted 10.244.226.93:34326
3490883:S 27 Oct 2022 15:05:39.339 # Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (conn: fd=19)

```
When using  - redis://git-kfkrds01:17000
in prometheus.yml, I get : 

```
Accepting cluster node connection from 10.244.226.93:48150
3490883:S 27 Oct 2022 15:04:05.207 - Error accepting cluster node connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

```
So port 7000 is for the client connection, 17000 for the cluster-to-cluster config. @madolson, this confirms your explanation.

But the error message remains the same.
Should redis-exporter connect to the client connection, or is this over a third port on which it currently does not listen?

**Comment by DGRFL** [comment]
I found the same error on another redis related issue list.
https://github.com/bitnami/charts/issues/3045
it is talking about allowing -tls-replication

**Comment by madolson** [comment]
Redis exporter should be configured to talk to the client configuration, it's just acting like a regular old client to pull data out of Redis.
