### ISSUE TITLE
Can it be like mysqld_ Export Set Account Password to Ensure Security？

### ISSUE THREAD

**Issue by 1240106808** [oliver006/redis_exporter#707]
**Describe the problem**
A clear and concise description of what the question is.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by 1240106808** [comment]
like  ./mysqld_exporter --web.config.file=./config.yml ，the config.yml centent is

**Comment by 1240106808** [comment]
basic_auth_users:
  admin: xxxxxxxxxxxxxxxxxxx

**Comment by oliver006** [comment]
`--redis.password-file` might be what you're looking for.
