### ISSUE TITLE
Exporter Blacklist and Whitelist Option

### ISSUE THREAD

**Issue by aeg12345** [oliver006/redis_exporter#709]
**Describe the problem**
A clear and concise description of what the question is.
Is there any way to restrict the metrics exposed by the exporter like a blacklist and whitelist options?
There are some configs to increase the metrics available and make way for custom metrics but I could not find any way to decrease the metrics exposed by the exporter?
**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[X] 1.x.x
1.44

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
Check the command line flags for what you can control.

And if there are certain metrics you absolutely don't want to collect then you can configure your Prometheus server to drop them.
