### ISSUE TITLE
How to config multi instance with password

### ISSUE THREAD

**Issue by lbzss** [oliver006/redis_exporter#715]
**Describe the problem**
A clear and concise description of what the question is.
Can someone tell me how to config multi instance with password? I tried to use redis.password-file and it can effect only when the redis.addr=redis://server:port, but still don't know how to add multi instance. If I add multi instances in redis.addr,which seems not be seperated.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[* ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by dartagnanli** [comment]
I noticed that you close this issue after 5 days,please, if you find some solution? and i also need this featue.

**Comment by lbzss** [comment]
Need to config a file to store the password with json format, you can check the file contrib/sample-pwd-file.json as a sample.
Then start the exporter with -redis.password-file=
Now you can config the scrape target as usual in prometheus.yml

**Comment by dartagnanli** [comment]
oh,I got it  ,but I find something maybe is a bug ,
My start command is `./redis_exporter -redis.password-file=redis-pwd-file.json`,and i think i don not need to set a param `-redis.addr` at this case. but some unexpected occured. the of the app continuous output `Couldn't connect to redis instance (redis://localhost:6379)`.
Are you meet it?if so, how you do with it?
