### ISSUE TITLE
Monitor Multiple Redis

### ISSUE THREAD

**Issue by matthewsc05** [oliver006/redis_exporter#722]
**Describe the problem**
Trying to monitor multiple endpoints on my machine with systemd, only pulling metrics for the last port.
command run is the below.
ExecStart=/usr/local/bin/redis_exporter --redis.addr="localhost:xxxx" --redis.addr="localhost:xxxx" --redis.addr="localhost:xxxx"

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ 1.45.0] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.
ExecStart=/usr/local/bin/redis_exporter --redis.addr="localhost:xxxx" --redis.addr="localhost:xxxx" --redis.addr="localhost:xxxx"

**Screenshots**
If applicable, add screenshots to help explain your question.
N/A

**Additional context**
Add any other context about the question here.

Machines have three different redis instances running, but I can only monitor one of them. Only option for me to get all metrics would be to have 3 different exporters running on each port which is not feasible/efficient. Am I doing something wrong or is this not supported?

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
