### ISSUE TITLE
Add support for -redis.password-file=sample-pwd-file.json hot-reload 

### ISSUE THREAD

**Issue by leesirc** [oliver006/redis_exporter#727]

**Comment by leesirc** [comment]
When sample-pwd-file.json changes, redis_exporter must restart to load the new passwords

**Comment by oliver006** [comment]
Agree, this would be helpful to have. Alas, I'm short of time right now but can help with reviewing and merging a PR.

**Comment by leesirc** [comment]
I'm sorry,  I don't have the ability to solve this problem

**Comment by oliver006** [comment]
Note to self: [this package](https://github.com/fsnotify/fsnotify) could be useful for implementing this.

**Comment by oliver006** [comment]
Ability to reload the config was added in [1.50.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.50.0)
