### ISSUE TITLE
I can't capture redis via redis_exporter

### ISSUE THREAD

**Issue by shuncon** [oliver006/redis_exporter#731]
I can't capture redis via redis_exporter, my json configuration is：
redis-passwd:123456
vim /data/prometheus/redis_exporter/targets-redispwd-instances.json 
{
  "redis://172.17.0.9:6379":"123456"
}
prome：
 job_name: 'redis_exporter__password_targets'
    file_sd_configs:
      - files:
        - /data/redis_exporter/targets-redispwd-instances.json
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.145.143:9121

redis_expoter:
time="2022-12-20T02:57:24Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"
time="2022-12-20T02:57:27Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"
time="2022-12-20T02:57:28Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"
time="2022-12-20T02:57:28Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"
time="2022-12-20T02:57:28Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"
time="2022-12-20T02:57:28Z" level=error msg="Couldn't connect to redis instance (redis://172.17.0.9:6379:123456)"

redis can collect data without password

**Comment by shuncon** [comment]
{
  "redis://default:123456@172.17.0.10:6379"
}

{
  "redis://172.17.0.10:6379":"default":"123456"
}
{
  "redis://172.17.0.10:6379":"123456"
}
Neither can

**Comment by shuncon** [comment]
oot@shun:/data/redis_exporter# docker run -d  --restart=always \
>  -p 9121:9121 --name redis_exporter \
>  -v /data/redis_exporter/redis_passwd.json:/etc/ \
>  oliver006/redis_exporter -redis.password-file=/etc/redis_passwd.json
98bdf20bb55d0561e078f4f72db4c0ee5513a29abf8cd6dbb1cd785339dc9d9f
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/redis_exporter/redis_passwd.json" to rootfs at "/etc": mount /data/redis_exporter/redis_passwd.json:/etc (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.

**Comment by oliver006** [comment]
See here for a sample password file: https://github.com/oliver006/redis_exporter/blob/master/contrib/sample-pwd-file.json

There's also an entire section about the topic in the README: https://github.com/oliver006/redis_exporter#authenticating-with-redis

**Comment by shuncon** [comment]
I have solved, I hope the author can fix the docker image, the image can not support mounting json files.
I looked at the link for a few hours before it was solved

**Comment by oliver006** [comment]
Thanks for the update and good to hear you got it to work!

Could you let me know what the problem was and how you fixed so I can fix the issue and address the problem in the README?
