### ISSUE TITLE
The script collect_lists_length_growing.lua gives error

### ISSUE THREAD

**Issue by rmalenko** [oliver006/redis_exporter#734]
I'm trying to collect memory usage using this script collect_lists_length_growing.lua 

It gives error message: `Script attempted to access nonexistent global variable 'DB_NO' `

I use this command line flag `--check-key-groups="db0:laravel:*,db1:queues:*,db2:laravel:*,db3:laravel_horizon:*"`

Dds I correctly write command line flag?

Thanks in advance for your help.

**Comment by oliver006** [comment]
I've not used the script and don't have much time to look into this right now, maybe @jango89 can help as he committed it.

**Comment by jango89** [comment]
@rmalenko hey yes, the script either needs a GLOBAL variable being set before executing the script (https://redis.io/docs/manual/programmability/lua-api/) or replace the DB_NO manually before executing (https://github.com/oliver006/redis_exporter/blob/master/contrib/sample_collect_script.lua#L8)
