### ISSUE TITLE
SSL Medium Strength Cipher Suites Supported (SWEET32)

### ISSUE THREAD

**Issue by krushnakantb** [oliver006/redis_exporter#736]
Hi Team,

We are using redis exporter version 1.43 and Version 1.45 for the export redis data we are getting SSL Medium Strength Cipher Suites Supported (SWEET32) vulnerability for the same. We have mentioned TLS 1.2 in Redis exporter conf but we are not able to find any specific parameter to mention Ciphers so we can not able to resolve the same. 

Below is the description for vulnerability SSL Medium Strength Cipher Suites Supported (SWEET32)

Medium Strength Ciphers (> 64-bit and < 112-bit key, or 3DES)

    Name                          Code             KEX           Auth     Encryption             MAC
    ----------------------        ----------       ---           ----     ---------------------  ---
    ECDHE-RSA-DES-CBC3-SHA        0xC0, 0x12       ECDH          RSA      3DES-CBC(168)          SHA1
    DES-CBC3-SHA                  0x00, 0x0A       RSA           RSA      3DES-CBC(168)          SHA1

Please Guide us if any solution is there for the above vulnerability or please provide a fix for the same.

**Comment by oliver006** [comment]
A quick google search suggests [there is a way](https://stackoverflow.com/questions/31226131/how-to-set-tls-cipher-for-go-server) to specify what ciphers to allow.
There currently is no support for it but I'd be happy to review and merge a PR if you submit on.

**Comment by krushnakantb** [comment]
By mentioning TLS1.3 our issue has been resolved so we are good currently. Thanks for reply @oliver006
