### ISSUE TITLE
"Unknown command LATENCY" on managed Redis Enterprise (6.2.6)

### ISSUE THREAD

**Issue by rh2048** [oliver006/redis_exporter#739]
**Describe the problem**

When using newer versions of Redis Exporter against Redis Enterprise (managed fixed plan, v6.2.6), it returns the following error:

```
time="2023-01-01T18:41:44Z" level=info msg="Redis Metrics Exporter v1.45.0    build date:     sha1: ec7ec0fa0d32dccf950d36701fc92f17c4f2d395    Go: go1.19.2    GOOS: linux    GOARCH: amd64"
time="2023-01-01T18:41:44Z" level=info msg="Providing metrics at :9121/metrics"
time="2023-01-01T18:42:23Z" level=error msg="WARNING, LOGGED ONCE ONLY: cmd LATENCY LATEST, err: ERR unknown command 'LATENCY'"
```

~~I believe this started happening in v1.38.~~ I revered back to v1.33 which still works. Didn't take the time to narrow down exactly which version it broke in.

**What version of redis_exporter are you running?**

1.45.0

**Running the exporter**

```
docker run oliver006/redis_exporter:v1.45.0 --redis.addr=xxxx --redis.user=xxxx --redis.password=xxxx
```

**Expected behavior**

Should scrape hosts but instead seems to return no data.

**Screenshots**

**Additional context**

**Comment by oliver006** [comment]
Odd. If LATENCY is not available it should still record the other metrics.

**Comment by rh2048** [comment]
The latency issue may not be the root cause, but I assumed such because the newer versions of redis_exporter were not working and that was the only error logged. I'll double check I'm not missing anything on my end.

**Comment by oliver006** [comment]
You could try running the exporter with the `--debug` flag for additional log output (just be careful to not paste any logs here with sensitive information like passwords or IPs).
Keep me posted!
