### ISSUE TITLE
Is it too long to scrape every 15 seconds ?

### ISSUE THREAD

**Issue by baiwfg2** [oliver006/redis_exporter#74]
Hi, oliver006.  Something puzzled me. I find redis_exporter do the scraping every 15 seconds(default). Is it too long ? I mean, there're probably many metrics changes within 15 seconds, we may miss the most part of them. Unless these redis metrics obtained by INFO command only go up(never go down), 15 seconds is workable. 

However, as far as I know, there are some metrics that could either go up or go down, so you may not capture the major changes if setting the interval too long.

**Comment by oliver006** [comment]
redis_exporter scrapes your Redis instance as often as you configure the Prometheus server to do the scraping (15 seconds by default).

You're right, gauges can fluctuate wildly in between scrapes and Prometheus would never catch that but counters would be fine.

If you feel like you'd need more data samples then configure Prometheus to scrape the exporter e.g. every 5 seconds.
