### ISSUE TITLE
Need to change os parse to optional in info

### ISSUE THREAD

**Issue by baronwangr** [oliver006/redis_exporter#741]
**Describe the problem**
Most redis and redis-like system are managed in proxy mode and proxies could be deployed via a batch of machines that could have its own operating system. In most case it's the real deployment online.

Proxies are chosen by a DNS name, or probably a L4 distributor(load balancer) so lead in quite a confusion in return different OS time to time. It caused many customers can't run exporter without proper configuration and versions.

In redis, the #Server field is suggest to give debugging hint, however in commercial product it's usually faked or masked.

**What version of redis_exporter are you running?**
current version

**Running the exporter**
suggest to make "os" and "redis_build_id" an OPTIONAL field instead of a MUST
https://github.com/oliver006/redis_exporter/blob/master/exporter/info.go#L169
https://github.com/oliver006/redis_exporter/blob/master/exporter/info.go#L167

suggest to make "redis_version" a transient acceptable,
https://github.com/oliver006/redis_exporter/blob/master/exporter/info.go#L166
that's because some of the clusters can upgrade its redis node one by one so versions are not irrelevant at that upgrade time.

**Expected behavior**
entitled.

**Screenshots**
entitled.

**Additional context**
redis_exporter are becoming more and more popular in our customers according to our recent observation, we appreciate your great job and hope our feedback could be accepted.

Thanks!

**Comment by oliver006** [comment]
Interesting problem, I see how this can result in inconsistent labels.
What do you suggest? 
`it caused many customers can't run exporter` - is there harm if the OS label changes every so often? Is this something that can be addressed by educating the customer?

**Comment by baronwangr** [comment]
My mistake to make you confused, sorry for this. there are two issues.
1. Some proxy don't return the "os" field, for example, our proxy before version 6.8 or early version of codis proxy, etc. Cloud vendors can release a proper version to deal with it so it's ok. Some on-premise deployment or private usage are not feasible to reach and exporter can't start without this field. that's the reason why exporter are in limit usage, people hope to use redis_exporter to adapt to their own deployment so I turn to here for help
2. "info command" is very likely to sent to proxies randomly or evenly. If the result bounce time to time, people are still puzzled about it. we've hardcode the "os" to "Linux" very brief to mask all differences but in monitor systems it still looked strange since it's a metric that is relative static

**Comment by oliver006** [comment]
Ok, thanks.
So let me ask again, is there harm in including the "os" label?
And what's your suggestion? What would be better behaviour? Make inclusion of the "os" label optional and configurable?
