### ISSUE TITLE
Wrong sha256 checksum

### ISSUE THREAD

**Issue by JulianNeuhaus27** [oliver006/redis_exporter#744]
**Describe the problem**
The current version checksum for 1.45.0 linux amd should be this (at least this is what the file says)
```
0890f4a75c41a953b608a3c025ef735296a473e0119ed31864c8510efe7a8393  redis_exporter-v1.45.0.linux-amd64.tar.gz
```

But the file has:

```
# sha256sum redis_exporter-v1.45.0.linux-amd64.tar.gz
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  redis_exporter-v1.45.0.linux-amd64.tar.gz
```

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ x] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 
Did you upgrade from 0.3x.x to 1.0 and are scraping multiple hosts? [Have a look here ](https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts) how the configuration changed.

**Screenshots**

**Additional context**

**Comment by JulianNeuhaus27** [comment]
File was empty...sorry 🙈

**Comment by oliver006** [comment]
No worries, happens.
