### ISSUE TITLE
Dead link to Grafana dashboard

### ISSUE THREAD

**Issue by SaskiaKeil** [oliver006/redis_exporter#745]
**Describe the problem**
The link to the grafana dashboard in the README is leading to a 404 page:
https://github.com/oliver006/redis_exporter/blob/master/README.md?plain=1#L278
https://grafana.com/dashboards/763

**Screenshots**
<img width="1254" alt="screenshot_256" src="https://user-images.githubusercontent.com/4289850/211673365-f24c5881-5a3e-478a-ab01-b3327db0c533.png">

**Additional context**
I would have created a PR myself, but I wasn't sure which of the uploaded version on grafana is "yours", maybe this one?
https://grafana.com/grafana/dashboards/11835-redis-dashboard-for-prometheus-redis-exporter-helm-stable-redis-ha/

**Comment by oliver006** [comment]
Thanks for raising the issue. I have no idea what's going on, looks like an issue on the Grafana side as I can log in to my account and see & update the settings for the dashboard (but I can't see the dashboard page itself).
Odd. But no idea how to fix it, sorry!
