### ISSUE TITLE
Is this applicable for redis Enterprise version too?

### ISSUE THREAD

**Issue by pndims** [oliver006/redis_exporter#755]
**Describe the problem**
I am trying to collect the metrics from our redis Enterprise cluster hosted in openshift

**What version of redis_exporter are you running?**
[ ] v1.45.0

**Running the exporter**
./redis_exporter --debug  -redis.addr redis://redis-dev2:9443 -web.listen-address 0.0.0.0:8443 -redis.password redis-pass 

**ERROR**
ERRO[0156] Couldn't connect to redis instance (redis://redis-dev2:9443) 
DEBU[0156] connectToRedis( redis://redis-dev2:9443 ) err: dial redis: unknown network redis 
DEBU[0156] scrapeRedisHost() done  

Is it due to trying to connect to Enterprise redis?

**Comment by banker** [comment]
Redis Enterprise has its own built-in Prometheus, exporter. See here: https://docs.redis.com/latest/rs/clusters/monitoring/prometheus-integration/
