### ISSUE TITLE
How do I connect redis exporter to a Redis enterprise cluster running on Kubernetes on SSL?

### ISSUE THREAD

**Issue by dnarasim** [oliver006/redis_exporter#757]
**Describe the problem**
How do I connect redis exporter to a Redis enterprise cluster running on Kubernetes on SSL?

**What version of redis_exporter are you running?**
1.45.0

**Running the exporter**
./redis_exporter --debug -redis.addr redis://<name of redis service>:8070 -web.listen-address 0.0.0.0:8443 -redis.password redis-pass

**Comment by dnarasim** [comment]
Really need help

**Comment by oliver006** [comment]
Do you have more information with regards to what is not working?
