### ISSUE TITLE
redis connection alerts

### ISSUE THREAD

**Issue by thomas-vt** [oliver006/redis_exporter#758]
We have created few new alerts for redis as described in https://nexclipper.io/redis-exporter-review/

We are seeing too many alerts for RedisTooManyConnections (expr: redis_connected_clients > 100)

labels have the following details
redis_connected_clients container:metrics endpoint:http-metrics

It seems that the connection from redis-exporter to redis are not being released. 
I cannot confirm that this is the issue, but would appreciate any help to find the reason as to why there are so many connections to the metrics endpoints (eg: 100 to 1000 connections)

Is there an idle connection timeout we can specify for redis-exporter? 
I do see REDIS_EXPORTER_CONNECTION_TIMEOUT but this seems for connection to redis and not for idle connection timeout

REDIS_EXPORTER_CONNECTION_TIMEOUT - Timeout for connection to Redis instance, defaults to "15s"

**Comment by oliver006** [comment]
The redis_exporter disconnects after every scrape and does not re-use connections or keeps them open.

Have you connected to the Redis instance and check what those connections are? Try [CLIENT LIST](https://redis.io/commands/client-list/) and see if you can get more information about those idle connections

**Comment by thomas-vt** [comment]
Thanks Oliver. I ran the command on one of the node showing high number of connections. Some lines from the end pasted below

`id=12779252 addr=10.244.21.138:44864 laddr=10.244.13.132:6379 fd=936 name= age=53 idle=22 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=12779253 addr=10.244.19.190:59298 laddr=10.244.13.132:6379 fd=1048 name= age=53 idle=22 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=12779254 addr=10.244.21.138:44880 laddr=10.244.13.132:6379 fd=1093 name= age=53 idle=22 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=12779255 addr=10.244.19.190:59304 laddr=10.244.13.132:6379 fd=1100 name= age=53 idle=22 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=12779885 addr=10.244.19.190:37786 laddr=10.244.13.132:6379 fd=84 name= age=18 idle=18 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=4 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20488 events=r cmd=NULL user=default redir=-1
id=12779886 addr=10.244.19.190:37792 laddr=10.244.13.132:6379 fd=85 name= age=18 idle=18 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=4 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20488 events=r cmd=NULL user=default redir=-1
id=12779887 addr=10.244.19.190:37802 laddr=10.244.13.132:6379 fd=87 name= age=18 idle=18 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=4 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20488 events=r cmd=NULL user=default redir=-1
id=12779888 addr=10.244.21.138:39850 laddr=10.244.13.132:6379 fd=97 name= age=18 idle=18 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=4 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20488 events=r cmd=NULL user=default `redir=-1``

**Comment by oliver006** [comment]
This helps a little.
You have incoming connections from two IP addresses, 10.244.21.138 and 10.244.21.190 - can you find out what those IPs are? How many redis exporters are you running? 
Also, none of the clients has the name set and redis_exporter sets the client name by default. Not sure but maybe this indicates that something else is connecting?

**Comment by thomas-vt** [comment]
most of these connections (approx 1000) are from haproxy-redis pods... and they seem to present immediately after a pod restart too.

We have 3 replicas running for redis and each has a container for redis-exporter

**Comment by oliver006** [comment]
Sounds like your haproxy is the problem. 
Fwiw, you should run the redis_exporter as a sidecar to the  redis instance and directly connect to the instance, and not go through the proxy.

**Comment by oliver006** [comment]
Sounds like your haproxy is the problem. 
Fwiw, you should run the redis_exporter as a sidecar to the  redis instance and directly connect to the instance, and not go through the proxy.

**Comment by thomas-vt** [comment]
redis_exporter is running as a sidecar container in the pod. The connections could be from prometheus trying to scrape the metrics endpoint

**Comment by oliver006** [comment]
Right. And looks like the source IPs of those connections are not the redis_exporter, correct?
