### ISSUE TITLE
Support for the LATENCY HISTOGRAM Redis metrics

### ISSUE THREAD

**Issue by LarssonOliver** [oliver006/redis_exporter#765]
Hi!

What do you think about exporting the LATENCY HISTOGRAM metrics added in Redis 7.0.0 (https://redis.io/commands/latency-histogram/)? This would map nicely to a Prometheus histogram metric, perhaps `redis_latency_usec_bucket` or similar, and is something we could use! :)

**Comment by oliver006** [comment]
That's a neat idea.
Unfortunately I don't have time to implement this right now but I can review and merge a PR.
