### ISSUE TITLE
REDIS_EXPORTER_SKIP_TLS_VERIFICATION not working

### ISSUE THREAD

**Issue by duculete** [oliver006/redis_exporter#768]
tested with REDIS_EXPORTER_SKIP_TLS_VERIFICATION=true or REDIS_EXPORTER_SKIP_TLS_VERIFICATION="true" or with
-skip-tls-verification

every time when i am trying to get metrics i redis_exporter is giving an error:

2023/02/23 10:23:50 http: TLS handshake error from XXX:AAAA: tls: client didn't provide a certificate

**Comment by oliver006** [comment]
The `REDIS_EXPORTER_SKIP_TLS_VERIFICATION` flag is to control if the exporter will verify the TLS cert of the *redis instance*.

If you want the redis_exporter to provide metrics via https then look at the `REDIS_EXPORTER_TLS_SERVER_*` flags.

**Comment by oliver006** [comment]
Clarified README in https://github.com/oliver006/redis_exporter/commit/326cabcb84277585cda1b3d5c35e613d469b7c44
