### ISSUE TITLE
Docker Free Team subscription sunset

### ISSUE THREAD

**Issue by mouchar** [oliver006/redis_exporter#779]
**Describe the problem**

Hello, can you please confirm that your Docker Hub repository https://hub.docker.com/r/oliver006/redis_exporter will **NOT** be affected by the upcoming change in Docker's pricing policy and that your super-popular repo will not suddenly disappear from Docker Hub?
Many other projects and helm charts rely on your image and it would be a big surprise for many of us, happy redis exporter users.
In case your repo is affected, do you plan any proactive changes, like applying for [Docker-Sponsored Open Source Program](https://www.docker.com/community/open-source/application/), moving to another registry, etc.?

**Comment by oliver006** [comment]
The short answer is: I don't know if the docker hup repo will be affected by the upcoming Docker ToS changes but probably not? From what I read it only affects "Free Teams" accounts which I don't use, I just publish to my personal docker profile.

The longer answer is: thanks for linking the open source program application, I filled that out so we'll see what comes from it. Docker (the company) a while ago started to be an unreliable place with everchanging ToS and plans. If redis_exporter is critical to your company's success and your infra then you should probably publish it to your own registry in GCP or AWS or wherever you run your infra so you're in full control of your stack. There's also an image published to quay so you got that as an alternative. I could also start publishing to Github registry but that's a bit of extra work and I don't have bandwidth for that.

**Comment by mouchar** [comment]
Thank you, Oliver, for your response and explanation. As far as you don't use the Free Teams tier, you're not affected.
Of course, we mirror your image to our private registry and others should do the same.

There's no need to publish images to GHCR if you're already publishing both to DockerHub and quay.
