### ISSUE TITLE
with redis auth and --is-cluster "NOPERM this user has no permissions to run the 'cluster' command or its subcommand"

### ISSUE THREAD

**Issue by gzivdo** [oliver006/redis_exporter#785]
acl user rights:
+client +ping +info +config|get +cluster|info +slowlog +latency +memory +select +get +scan +xinfo +type +pfcount +strlen +llen +scard +zcard +hlen +xlen +eval allkeys 

I am able to run cluster info from redis-cli authorized with that user
In the log i see 
redis_exporter[11745]: time="2023-04-12T13:26:41+03:00" level=error msg="Cluster refresh failed: redisc: all nodes failed\nNOPERM this user has no permissions to run the 'cluster' command or its subcommand"
If I do "acl setuser +cluster", message dissapear, if do again "acl setuser -cluster +cluster|info" message appears again.
Without --is-cluster flag there is no such message in the log.

**Comment by gzivdo** [comment]
ACL LOG doesn't contain anything about this, also i see in the code if "CLUSTER", "INFO" is failed will be other log message.

**Comment by oliver006** [comment]
Ah, interesting.
How do you run the exporter? What's the full cmd line? (strip passwords or other sensitive information)

**Comment by gzivdo** [comment]
/etc/default/redis_exporter:
REDIS_EXPORTER_OPTS="--is-cluster --check-streams=somestream1,...
systemd service with
Environment=REDIS_USER=redis-exporter
Environment=REDIS_PASSWORD=somepw
EnvironmentFile=-/etc/default/redis_exporter
ExecStart=/usr/bin/redis_exporter $REDIS_EXPORTER_OPTS
