### ISSUE TITLE
Scrape multiple redis same host

### ISSUE THREAD

**Issue by bmgante** [oliver006/redis_exporter#792]
Can someone provide some detailed info on how to monitor multiple redis servers running in the same VM using only one redis exporter service installed on that same VM? I then gave Prometheus outside scrapping this redis Prometheus exporter.
Thanks

**Comment by oliver006** [comment]
Check the docs here on how to scrape multiple Redis instances with one exporter: https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
