### ISSUE TITLE
Support for entries-read and lag properties of XINFO GROUPS result in Redis 7

### ISSUE THREAD

**Issue by VladimirKhil** [oliver006/redis_exporter#799]
**Describe the problem**

In Redis 7 command XINFO GROUPS returns two new properties for each consumer group: entries-read and lag.

Are there any plans for supporting them as metric values?

Thank you!

https://redis.io/commands/xinfo-groups/

**What version of redis_exporter are you running?**
1.44.0

**Running the exporter**
-

**Screenshots**
-

**Additional context**
-

**Comment by oliver006** [comment]
Thanks for raising this issue! There are no immediate plans to add this but if you (or anyone else) submit a PR for this then I'll review and merge it as soon as possible.

**Comment by donovanvanheerden** [comment]
@oliver006 any ETA on when the next release will be, since then this issue can be closed after that?

**Comment by oliver006** [comment]
Releases as [v1.52.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.52.0)
