### ISSUE TITLE
Adapting the exporter to collect certain metrics only on replicas and not in master

### ISSUE THREAD

**Issue by dinesh-murugiah** [oliver006/redis_exporter#801]
Do we already have a feature for configuring the exporter to run certain metrics collection like 
https://github.com/oliver006/redis_exporter#memory-usage-aggregation-by-key-groups
only on replicas as it can reduce the performance impact on system due to scan

If not available can we add such feature ?

**Comment by oliver006** [comment]
You should run an exporter per instance (e.g. sidecar in k8s, etc)
Why not use different configs on primaries and replicas?

**Comment by dinesh-murugiah** [comment]
this should be a dynamic configuration based on current role of the redis
as the replica can failover to become a master
