### ISSUE TITLE
Sample config for Redis cluster?

### ISSUE THREAD

**Issue by piavgh** [oliver006/redis_exporter#811]
**Describe the problem**
A clear and concise description of what the question is.
Hi @oliver006 , is there a sample config for installing redis_exported to monitor a Redis cluster?

We have a Redis cluster installed on k8s (GKE) that has 6 nodes (3 masters and 3 replicas)

Thanks a lot

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 1.51.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
We currently have this part of the docs:
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
