### ISSUE TITLE
need redis 2.8 maxmemory support

### ISSUE THREAD

**Issue by itbdw** [oliver006/redis_exporter#82]
Hi, Im using old redis version 2.8 and there is no maxmemory in the INFO result.  What about use "CONFIG GET maxmemory" on old redis version?

**Comment by oliver006** [comment]
Yeah, seems like not all Redis versions have `maxmemory` in INFO (just tried on an older redis v3.0.6 and it's not there either)

**Comment by itbdw** [comment]
If we can not get `maxmemory` in INFO, then call `CONFIG GET maxmemory` once seems to be a good idea, regardless of version problems.

**Comment by oliver006** [comment]
This should be fixed by https://github.com/oliver006/redis_exporter/releases/tag/v0.14

You can now use the `redis_config_maxmemory` metric which should work for older Redis versions.
