### ISSUE TITLE
Does Redis Exporter really need allkeys permission?

### ISSUE THREAD

**Issue by kas-kad** [oliver006/redis_exporter#821]
Hello, reading the docs I have found one suspicious thing:

> ACL SETUSER <<<USERNAME>>> +client +ping +info +config|get +cluster|info +slowlog +latency +memory +select +get +scan +xinfo +type +pfcount +strlen +llen +scard +zcard +hlen +xlen +eval allkeys on > <<<PASSWORD>>>

Why does Redis Exporter need allkeys permission that allows accessing any possible key?

**Comment by oliver006** [comment]
You should always adjust the permissions as needed / appropriate for your use case.
If you want to export key values via metrics or use any of check-keys features then you'll need permissions accordingly.
