### ISSUE TITLE
KeyDB 6.3.3 CONFIG GET tls-allowlist unexpected type for String

### ISSUE THREAD

**Issue by Nefelim4ag** [oliver006/redis_exporter#822]
**Describe the problem**
Error logs, when connected to KeyDB 6.3.3
```
{"level":"error","msg":"invalid config value for key name tls-allowlist, err: redigo: unexpected type for String, got type []interface {}, skipped","time":"2023-08-03T14:36:49Z"}
{"level":"error","msg":"invalid config value for key name tls-allowlist, err: redigo: unexpected type for String, got type []interface {}, skipped","time":"2023-08-03T14:37:11Z"}
{"level":"error","msg":"invalid config value for key name tls-allowlist, err: redigo: unexpected type for String, got type []interface {}, skipped","time":"2023-08-03T14:37:19Z"}
```

Reason why:
`keydb-cli CONFIG GET '*'`
```
393) "active-replica"
394) "yes"
395) "tls-allowlist"
396) 1) "*.*"
....
393) "active-replica"
394) "yes"
395) "tls-allowlist"
396) (empty array)
```
**What version of redis_exporter are you running?**
1.52.0

**Comment by oliver006** [comment]
Thanks for bringing this up.
It logs as an error but it shouldn't affect scraping the instance (the code fails to parse the array for `tls-allowlist` and then simply continues).
I'll look int this a little more but I think it makes sense to make this a `Debug()` to reduce the noise.

**Comment by oliver006** [comment]
I pushed up commit https://github.com/oliver006/redis_exporter/commit/b49a8b89554f0055f32a596bf546f3357fdbf1bb that adjusts the logging a bit, I hope this helps.

I'll release this as a proper release in the soon but in the meantime you can go ahead and build and run it if you want to.
