### ISSUE TITLE
No binaries for v1.53.0

### ISSUE THREAD

**Issue by 0e39bf7b** [oliver006/redis_exporter#825]
redis_exporter [v1.52.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.52.0) and earlier releases have attached binaries. There are no binaries for [v1.53.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.53.0). Only source code is attached.

**Comment by oliver006** [comment]
Thanks for letting know, this is fixed now.
