### ISSUE TITLE
how to get latency related metrics by redis-exporter?

### ISSUE THREAD

**Issue by bling-star-hub** [oliver006/redis_exporter#827]
**Describe the problem**
Latency related metrics couldn't found in redis-exporter results, like "redis_latency_percentiles_usec". How can I get them? 

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
1.53.0.linux

**Running the exporter**
redis-expoter -redis.addr= --redis.password="xxx" -export-client-list -include-system-metrics -redis-only-metrics

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by bling-star-hub** [comment]
With -debug, one error was found: cmd LATENCY HISTOGRAM, err: ERR Unknown subcommand or wrong number of argument for 'HISTOGRAM'.

**Comment by bling-star-hub** [comment]
Well, maybe I found the reason: if the redis version too low to run the "LATENCY HISTOGRAM" command? 
Now the redis version is 5.0.14.

**Comment by oliver006** [comment]
Sounds like you figured it out.
