### ISSUE TITLE
REDIS_ADDR Multiple connection string

### ISSUE THREAD

**Issue by sksaranraj** [oliver006/redis_exporter#830]
Hi,

I need to monitor multiple redis instances, it there is any plan to add multiple connection string in REDIS_ADDR?. Also Can you please explain the metric **redis_stream_group_lag**,  This doesn't seems to be working

**Comment by oliver006** [comment]
See here for information on how to monitor multiple Redis hosts:

https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
