### ISSUE TITLE
Does it work with memoryDB ?

### ISSUE THREAD

**Issue by madhur** [oliver006/redis_exporter#831]
**Describe the problem**
AWS has launched MemoryDB which is based on elasticcache. Does it support MemoryDB?

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[x ] 0.3x.x
[x ] 1.x.x

**Comment by oliver006** [comment]
No idea. You could just try and see if it works?

**Comment by madhur** [comment]
Yes, it seems to work fine. Thanks for this flawless exporter.
