### ISSUE TITLE
I want to Add Basic authentication for accessing Exporter, Do you need this enhanced code?

### ISSUE THREAD

**Issue by AirTrioa** [oliver006/redis_exporter#833]
**Describe the problem**

- Due to special needs, our company needs to add basic auth for RedisExporter, but I found that the exporter itself does not support it, so I modified the source code based on the master branch.

- Now I want to submit these enhanced codes to the community. Do you need them ?
- If necessary, I can initiate a merge request ? [code address](https://github.com/AirTrioa/redis_exporter/tree/add-exporter-basic-auth)

**Comment by oliver006** [comment]
Thanks for opening this issue and asking about that feature.
I'd prefer to keep redis_exporter minimal - if e.g. basic auth is needed then a simple Nginx sidecar can serve that need.

**Comment by AirTrioa** [comment]
Okay, in many cases, the 'single responsibility principle' is indeed necessary, so I will close this issue later.
