### ISSUE TITLE
Redis exporter issue 1.54

### ISSUE THREAD

**Issue by jit22jan** [oliver006/redis_exporter#834]
**Getting below error while running redis exporter** 

DEBU[0051] Trying DialURL(): redis://x.x.x.x:6379
DEBU[0051] connected to: redis://x.x.x.x:6379
DEBU[0051] connecting took 0.000491 seconds
DEBU[0051] c.Do() - running command: CLIENT [SETNAME redis_exporter]
**DEBU[0066] c.Do() - err: read tcp x.x.x.x:38046->x.x.x.x:6379: i/o timeout**
DEBU[0066] c.Do() - done
**ERRO[0066] Couldn't set client name, err: read tcp x.x.x.x:38046->x.x.x.x:6379: i/o timeout**
DEBU[0066] c.Do() - running command: CONFIG [GET *]
**DEBU[0066] c.Do() - err: set tcp x.x.x.x:38046: use of closed network connection**
DEBU[0066] c.Do() - done
DEBU[0066] Redis CONFIG err: set tcp x.x.x.x:38046: use of closed network connection
DEBU[0066] c.Do() - running command: INFO [ALL]
DEBU[0066] c.Do() - err: set tcp x.x.x.x:38046: use of closed network connection
DEBU[0066] c.Do() - done
DEBU[0066] Redis INFO ALL err: set tcp x.x.x.x:38046: use of closed network connection
DEBU[0066] c.Do() - running command: INFO []
DEBU[0066] c.Do() - err: set tcp x.x.x.x:38046: use of closed network connection
DEBU[0066] c.Do() - done
**ERRO[0066] Redis INFO err: set tcp x.x.x.x:38046: use of closed network connection**
DEBU[0066] scrapeRedisHost() done

**version of redis_exporter**
1.54.0 linux amd64

**Running the exporter with below command**
./redis_exporter --redis.addr=redis://x.x.x.x:6379 --debug --connection-timeout=60s

**Prometheus Configuration**
- job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://x.x.x.x:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: x.x.x.x:9121

**Comment by jit22jan** [comment]
@oliver006  Kindly Help

**Comment by oliver006** [comment]
Can you confirm that the Redis instance is reachable from where the exporter is running? Using telnet or similar?

**Comment by jit22jan** [comment]
Yes  redis instance is reachable to redis exporter also sometimes redis
exporter able to collect metrics as well .

**Comment by oliver006** [comment]
Sounds like you're having intermittent issues with your network connection?
