### ISSUE TITLE
[QUESTION] Inquiry regarding redis exporter's support policy

### ISSUE THREAD

**Issue by ishaqkhattana** [oliver006/redis_exporter#842]
**Describe the problem**
Is there a fixed support policy that redis exporter follows (N-2 minors, latest minor etc)?

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**

**Comment by oliver006** [comment]
There's no official support policy, support is done on a best-effort basis while trying to allow for as many metrics as possible for Redis 2.8+, 5.x, 6.x, 7.x
