### ISSUE TITLE
[Feature Request] Changelog

### ISSUE THREAD

**Issue by GeiserX** [oliver006/redis_exporter#844]
Context: I'm using the Chart to deploy this software, and this time, the upgrade is 10 minor versions.
I wonder if it could be possible to add this in a file, instead of having to review every single version in the "tags" section.

**Comment by oliver006** [comment]
I understand that a Changelog would be a convenient place to capture all changes. You can find all that info in the notes of each release and in git (I squash PR commits so you should have 1 commit per PR).
Manually maintaining yet another record makes is additional work that I prefer to not do.
