### ISSUE TITLE
how to config multi-target  exporter in k8s prometheus servicemonitor?

### ISSUE THREAD

**Issue by aayasin0019** [oliver006/redis_exporter#848]
I use the version 1.55.0.
k8s version  1.21.8
I dont know how to config redis cluster with redis exporter in servicemonitor. 
servicemonitor cant config like this
    static_configs:
      - targets:

**Comment by oliver006** [comment]
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
