### ISSUE TITLE
Prometheus Server Label Rewriting: Missing ADDR Label in metrics

### ISSUE THREAD

**Issue by purti-rajpal** [oliver006/redis_exporter#849]
**Describe the problem**
ADDR label is missing from v1.38.0. I am running one redis exporter for each of redis instance of the cluster

**What version of redis_exporter are you running?**
v1.38.0

How can I get it back using prometheus server label rewriting. Sorry I am new to this. The current prometheus yaml file looks like below:

- labels:
    redis_cache: Test
  targets:
  - redis-host:9121/metrics
  - redis-host:9122/metrics

**Comment by oliver006** [comment]
See the docs here on how to monitor multiple Redis isntances:
https://github.com/oliver006/redis_exporter#prometheus-configuration-to-scrape-multiple-redis-hosts
