### ISSUE TITLE
Place configuration flags in a configuration file

### ISSUE THREAD

**Issue by ccs018** [oliver006/redis_exporter#85]
Rather than passing the configuration flags as command line options could you add reading these from a configuration file?  The primary concern is that when securing the RedisDB with a password, the password must then be passed as command line argument to the redis_exporter.  Anyone who gains access to the machine could then do a simple ps command and observe the password.  This violates various security requirements.

**Comment by oliver006** [comment]
You can always put the password or other secrets in an environment variable and use that when starting the process.
