### ISSUE TITLE
Add support for Latency monitor

### ISSUE THREAD

**Issue by kpachhai** [oliver006/redis_exporter#86]
Latency monitoring is a relatively new feature introduced in Redis 2.8.13 that helps you troubleshoot latency problems. This tool logs latency spikes on your server, and the events that cause them. You must enable latency monitoring before you can use it however but I guess it would be nice metrics to have. 
More details here: https://redis.io/topics/latency-monitor

Let me know if this is at all possible. I would love to work on it and see what we can come up with. Just getting my hands dirty to this whole open source thing, no big deal.

**Comment by oliver006** [comment]
That's an interesting feature, didn't know about it!

However, I'm not sure how to translate it into metrics. Maybe the timestamp of when the latest event occurred so you can alert on it? Would that be useful?
Other thoughts?

**Comment by kpachhai** [comment]
The LATENCY LATEST command reports the latest latency events logged. Each event has the following fields:
Event name.
Unix timestamp of the latest latency spike for the event.
Latest event latency in millisecond.
All time maximum latency for this event.

So, I think the best way to do it is to maybe expose couple of metrics based on this:
redis_latest_latency_spike{event="event_name"} Unix timestamp 
redis_latest_latency_time{event="event_name"} Latency in millisecond
redis_max_latency{event="event_name"} All time maximum latency

**Comment by oliver006** [comment]
That should work (though we might not need "max" - that's something that Prometheus can calculate for us).

I'll be away from my laptop for the next ~ 10 days - feel free to go ahead and give it a shot if you're interested.

**Comment by kpachhai** [comment]
Sounds good. I'm currently working on this. Thanks.

**Comment by kpachhai** [comment]
I created a PR for this change. Please look into it when you have time. https://github.com/oliver006/redis_exporter/pull/87

**Comment by davidpapx** [comment]
Installed oliver006/redis_exporter:v0.13 with Redis 3.2.11, and relevant metrics are not exposed (redis_latest_latency_spike). didn't find any issue in the exporter itself. what can be the reason?

**Comment by oliver006** [comment]
I've never used latency monitoring but from the docs (https://redis.io/topics/latency-monitor) it sounds like you need to enable it first and then a latency event needs to occur. Did you try with the instructions from the docs above? It worked for me using the latest exporter and Redis 3.2.8

**Comment by oliver006** [comment]
Closing this, please re-open if this is still an issue.
