### ISSUE TITLE
redis_exporter Support basic_auth?

### ISSUE THREAD

**Issue by 1310208262** [oliver006/redis_exporter#862]
redis_exporter Support basic_auth?

**Comment by 1310208262** [comment]
Security vulnerability scan failed

**Comment by oliver006** [comment]
You can use a reverse proxy like nginx if you need basic auth.

**Comment by andreymal** [comment]
The connection between nginx and redis_exporter is still not secure enough. Exporters should support basic auth to make sure that unauthorized processes can't connect to them

Note that official exporters (such as node_exporter) already support basic auth

(TLS can do this too, but it's just overkill)

**Comment by 0xFreeman-AI** [comment]
> The connection between nginx and redis_exporter is still not secure enough. Exporters should support basic auth to make sure that unauthorized processes can't connect to them
> 
> Note that official exporters (such as node_exporter) already support basic auth
> 
> (TLS can do this too, but it's just overkill)

Agree.
