### ISSUE TITLE
--export-client-list option doesn't work when IPv6 addresses are returned

### ISSUE THREAD

**Issue by edward-milkey** [oliver006/redis_exporter#863]
**Describe the problem**
First, thanks for the great work here!

When `--export-client-list` option is enabled, `redis_connected_clients_details` metrics are not provided by the exporter as expected when Redis `CLIENT INFO` returns IPv6 addresses. This is when using v6.0.14 of Redis.

I encounter IPv6 addresses returned from `CLIENT INFO` when using Azure Redis Cache service with private endpoints.

**What version of redis_exporter are you running?**
v1.55.0

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
`--redis.addr rediss://MY_REDIS:6380 --redis.password "REDACTED" --debug --export-client-list --export-client-port`

**Expected behavior**
What metrics are missing? What metrics are wrong? Is something missing that was present in an earlier version? 

The exporter returns other metrics, but the client list metrics (`redis_connected_clients_details`) are not present.

**Screenshots**

**Additional context**

**Comment by oliver006** [comment]
Released: https://github.com/oliver006/redis_exporter/releases/tag/v1.56.0
