### ISSUE TITLE
Exit Code: 2, Exit Message: "Docker container exited with non-zero exit code: 2"

### ISSUE THREAD

**Issue by wanghaowei0107** [oliver006/redis_exporter#868]
**Describe the problem**

Exit Code: 2, Exit Message: "Docker container exited with non-zero exit code: 2"

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[x ] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
`redis_exporter --redis.addr=127.0.0.1:6379`

**Expected behavior**
When redis exporter graceful shutdown, the exit code will be 0.

**Comment by oliver006** [comment]
Fixed by #867 - thanks for your PR!
