### ISSUE TITLE
Use sync.Map

### ISSUE THREAD

**Issue by oliver006** [oliver006/redis_exporter#88]
Once Go 1.9 is GA we should use sync.Map for e.metrics to simplify all the 
`lock -> set value -> unlock` sequences.

**Comment by Rucknar** [comment]
Advise i've had from the prometheus team before is to use `constmetric` and go's channels to avoid the locking. Can dig out some examples if it's something you are interested in.

**Comment by Rucknar** [comment]
... which if i'd read the other issues i'd see has been already brought up..
