### ISSUE TITLE
Grafana Dashboard Warnings

### ISSUE THREAD

**Issue by Pokom** [oliver006/redis_exporter#881]
**Describe the problem**
After running `redis_exporter` and collecting metrics into Prometheus, I setup the [community dashboard](https://grafana.com/grafana/dashboards/763-redis-dashboard-for-prometheus-redis-exporter-1-x/). All of the charts are working, but when inspecting some of the dashboards there's a warning:

```
Angular plugin

This plugin uses a deprecated, legacy platform based on AngularJS and will stop working in future releases of Grafana.
```

I've already gone through the process of updating all of the dashboards to use the [Time Series](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/time-series/) visualization and everything appears fine.

**Screenshots**
![image](https://github.com/oliver006/redis_exporter/assets/1080566/9be613fe-4e71-4a1b-9213-de568c9cb823)

**Additional context**
I can submit a PR with the changes applied if that helps. Otherwise it should be fairly straightforward to migrate the dashboards and update the json file.

**Comment by oliver006** [comment]
Ah, good one. I uploaded a new revision that doesn't use any more Angular widgets. Thanks for alerting me to this issue!

**Comment by oliver006** [comment]
Updating the dashboard in `contrib` via #883

**Comment by Pokom** [comment]
Thanks @oliver006! Really appreciate the fast turnaround 🙇🏻
