### ISSUE TITLE
Missing metric from exporter: connected_clients

### ISSUE THREAD

**Issue by macetw** [oliver006/redis_exporter#886]
**Describe the problem**
INFO CLIENTS shows very important information about how many clients are connected at a given time. Since Redis could block connections if the service is hitting a maximum, this metric should be reported with the redis-exporter.

Although I could create a lua-script to get this detail, I found that the kubernetes operator I am using (opstreelabs) does not support this approach of mounting a volume I would need to support using a lua-script on the exporter.

Here is that script, by the way:
```
    local result = {}
    local client_info = redis.call("info", "clients")
    local value = string.match(client_info, "connected_clients:(.-)\r\n")
    table.insert(result, 'connected_clients')
    table.insert(result, value)
    return result
```

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[ ] 1.x.x
[x] 1.58.0 (attempted with the very-latest version)

**Running the exporter**
Running the redis-exporter pod without any additional arguments. Environment variables:

```
      REDIS_ADDR:   redis://localhost:6379
      SERVER_MODE:  cluster
      SETUP_MODE:   cluster
```

**Expected behavior**

Missing a connected_client_count metric. Tested also on 1.44.0 and 1.58.0.

**Screenshots**
n/a

**Additional context**

**Comment by oliver006** [comment]
`redis_connected_clients` ?

**Comment by macetw** [comment]
Yes, that's the helpful metric that's needed. Thanks!
