### ISSUE TITLE
Future support of Redis or other BSD license alternatives?

### ISSUE THREAD

**Issue by thanh17** [oliver006/redis_exporter#898]
**Describe the problem**
With the recent changes in https://github.com/redis/redis/pull/13157, what will the future of redis_exporter support look like?

Will this come in the form of transitioning to other forked version of redis like [Valkey](https://github.com/valkey-io)?

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[X] 1.x.x

**Running the exporter**
N/A

**Screenshots**
N/A

**Additional context**
Rip Redis 🥲

**Comment by oliver006** [comment]
Thanks for opening this issue.

Not sure how `ioredis` relates to all of this (copy-paste mistake?) but the exporter works on the redis protocol and as long as Redis continues to maintain backwards-compatibility with with ValKey then we should be fine.

That said, I should add something to the README that the exporter works with ValKey.

IMO the exporter should continue to support a broad set of Redis-like systems (it already does, see support for KeyDB, Tile38, etc) so we'll try to cover as much as Redis and ValKey and other functionality as possible.

**Comment by thanh17** [comment]
Yes, meant to say redis_exporter...Will look at support for KeyDB as reference, thank you!
