### ISSUE TITLE
Docker image missing for v1.59.0

### ISSUE THREAD

**Issue by gmta** [oliver006/redis_exporter#901]
This morning, v1.59.0 was released:
https://github.com/oliver006/redis_exporter/releases/tag/v1.59.0

The Docker image for this version is still missing though:
https://hub.docker.com/r/oliver006/redis_exporter/tags

For most projects the publication of a new Docker tag coincides with (or at least, closely trails) the release notification. Would it be possible for this project to do the same? This way, using GitHub notifications to quickly update our containers when a release with security fixes comes out becomes a bit easier.

**Comment by oliver006** [comment]
Thanks for raising this issue!
The pipeline got stuck, should be fixed now.
