### ISSUE TITLE
Feature: Add option to exclude per consumer stream metrics

### ISSUE THREAD

**Issue by nantiferov** [oliver006/redis_exporter#902]
**Describe the problem**
Hi,

I noticed that with enabling existing **check-streams / check-single-streams** options exporter fetches quite a lot of metrics per each consumer. As a result, it creates additional load on TSDB and I'm not sure these metrics will be useful.

However, I find group/stream level metrics quite useful. What do you think about adding one more option to skip adding consumer level metrics for streams (default disabled to keep current behaviour)?

I can prepare PR with implementation.

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
* [ ] 0.3x.x
* [x] 1.x.x

**Running the exporter**
What's the full command you're using to run the exporter? (please remove passwords and other sensitive data)
Please include details about env variables, command line parameters, your orchestration setup, etc.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Additional context**
Add any other context about the question here.

**Comment by oliver006** [comment]
I think that's a great idea!
Happy to review a PR. Thanks!
