### ISSUE TITLE
Fetching extra config metrics fails on cloud managed Redis instances

### ISSUE THREAD

**Issue by ccorbacho** [oliver006/redis_exporter#905]
**Describe the problem**
Attempts to fetch the extra config metrics for a Redis instance fail on cloud managed Redis instances - on at least AWS Elasticache and GCP Memorystore.

```{"level":"debug","msg":"c.Do() - running command: CONFIG [GET *]","time":"2024-05-17T10:11:09Z"}
{"level":"debug","msg":"c.Do() - err: ERR unknown command 'CONFIG', with args beginning with: 'GET' '*' ","time":"2024-05-17T10:11:09Z"}
{"level":"debug","msg":"c.Do() - done","time":"2024-05-17T10:11:09Z"}
{"level":"debug","msg":"Redis CONFIG err: ERR unknown command 'CONFIG', with args beginning with: 'GET' '*' ","time":"2024-05-17T10:11:09Z"}
```

`CONFIG` is not an allowed command on most cloud managed Redis:
* https://cloud.google.com/memorystore/docs/redis/product-constraints
* https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/SupportedCommands.html

(This doesn't stop anything else, as the exporter continues onto the next ste of metrics).

**What version of redis_exporter are you running?**
1.59.0

**Running the exporter**
N/A (using the Docker image).

**Expected behavior**
Redis Exporter has a way to disable fetching the config metrics.

e.g. maybe a new environment variable to disable fetching these, so that we don't issue a command that will never succeed (and avoid these error messages when debug level logging is enabled).

**Screenshots**
N/A

**Additional context**

**Comment by oliver006** [comment]
I like the idea of adding a flag to skip calling the `CONFIG` command, I think that makes sense. Alas, I don't have the bandwidth right now to add the feature myself.
Feel free to open a PR, happy to review it.
