### ISSUE TITLE
Grafana dashboards compitable with the redis exporter

### ISSUE THREAD

**Issue by idan3** [oliver006/redis_exporter#907]
It's not clear from the docs which Grafana dashboards are compatible with this exporter.
Can someone help with what and where are those predefined dashboards?

**Comment by oliver006** [comment]
Grafana dashboards are [linked](https://grafana.com/grafana/dashboards/763-redis-dashboard-for-prometheus-redis-exporter-1-x/) from the README and you can always build your own.
