### ISSUE TITLE
Can not connect to redis_reporter

### ISSUE THREAD

**Issue by denglitong** [oliver006/redis_exporter#92]
[root@Redis-master redis_exporter]# pwd
/root/go/src/github.com/oliver006/redis_exporter
[root@Redis-master redis_exporter]# ll
total 7572
-rwxr-xr-x 1 root root    2540 Aug  8 05:42 build.sh
-rw-r----- 1 root root    2223 Aug  8 05:42 circle.yml
drwxr-x--- 2 root root    4096 Aug  8 05:42 contrib
-rw-r----- 1 root root     160 Aug  8 05:42 Dockerfile
drwxr-x--- 2 root root    4096 Aug  8 05:42 exporter
-rw-r----- 1 root root    1308 Aug  8 05:42 glide.lock
-rw-r----- 1 root root     366 Aug  8 05:42 glide.yaml
-rw-r----- 1 root root    1063 Aug  8 05:42 LICENSE
-rw-r----- 1 root root    5900 Aug  8 05:42 main.go
-rw-r----- 1 root root    4174 Aug  8 05:42 README.md
-rwxr-x--- 1 root root 7684197 Aug 11 10:14 redis_exporter
drwxr-x--- 3 root root    4096 Aug 11 10:11 src
[root@Redis-master redis_exporter]# ./redis_exporter -web.listen-address=10.21.20.241:9121 -redis.addr=redis://127.0.0.1:6379 -redis.password=password
INFO[0000] Redis Metrics Exporter <<< filled in by build >>>    build date: <<< filled in by build >>>    sha1: <<< filled in by build >>>    Go: go1.8.3
 
INFO[0000] Providing metrics at 10.21.20.241:9121/metrics 
INFO[0000] Connecting to redis hosts: []string{"redis://127.0.0.1:6379"} 
INFO[0000] Using alias: []string{""}                    

At the same machine: 

[root@Redis-master redis_exporter]# telnet 10.21.20.241 9121
Trying 10.21.20.241...
Connected to 10.21.20.241.
Escape character is '^]'.

HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad RequestConnection closed by foreign host.
[root@Redis-master redis_exporter]# 

At other machine:
[root@SZX1000347429 ~]# telnet 10.21.20.241 9121
Trying 10.21.20.241...
telnet: connect to address 10.21.20.241: No route to host

Is the way that I start the redis_exporter not correct? how should i do? thanks much!
And prometheus error message is:
Get http://10.21.20.241:9121/metrics: dial tcp 10.21.20.241:9121: getsockopt: no route to host

**Comment by denglitong** [comment]
is there anybody can help me, i am waiting here, having no metheods, sad..

**Comment by oliver006** [comment]
Try `curl -s 10.21.20.241:9121/metrics` ?

**Comment by denglitong** [comment]
Oh, I haved solved this problem, thank you all the same! Nice you are. Previously my linux machine can not access to github.com so I download the packages needed through windows chrome and then upload it to my linux machine. But then I find a way to add a proxy to let my linux machine can access to it and can download directly from github.com. At last I add accept the IP in firework, then it works!

**Comment by oliver006** [comment]
👍
