### ISSUE TITLE
Return String value of custom lua script

### ISSUE THREAD

**Issue by adibaulia** [oliver006/redis_exporter#920]
**Describe the problem**
I created a custom Lua script to extract information about my Redis cluster server. The script is structured as follows:
```lua
local result = {}
local nodes_info = redis.pcall('CLUSTER', 'NODES')

if type(nodes_info) == 'string' then
    for line in string.gmatch(nodes_info, '([^\n]+)') do
        if string.find(line, 'myself') then
            local parts = {}
            local idx = 1
            for part in string.gmatch(line, '([^%s]+)') do
                parts[idx] = part
                idx = idx + 1
            end

            table.insert(result, "node_id")
            table.insert(result, parts[1])

            table.insert(result, "address")
            table.insert(result, parts[2])

            table.insert(result, "flag")
            table.insert(result, parts[3])

            table.insert(result, "master_node_id")
            table.insert(result, parts[4])

            table.insert(result, "status")
            table.insert(result, parts[8])

            table.insert(result, "slots")
            table.insert(result, parts[9] or "")
            
            break
        end
    end
else
    table.insert(result, 'Error running CLUSTER NODES')
end

return result
```

When I executed the exporter, an error message indicated that the custom Lua script's return value (not the key) could not be parsed into float64. Delving into the code, I discovered the following section in the Go code snippets:
```go
// exporter/lua.go
for key, stringVal := range kv {
	val, err := strconv.ParseFloat(stringVal, 64)
	if err != nil {
		log.Errorf("Error parsing lua script results, err: %s", err)
		e.registerConstMetricGauge(ch, "script_result", 0, filename)
		return err
	}
	e.registerConstMetricGauge(ch, "script_values", val, key, filename)
}
```
I am curious about why only parsing to float is allowed, is there any reason? Are there any chance to support strings too? Or is there any support to export cluster-related metadata? Thank you!

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.
[ ] 0.3x.x
[v] 1.x.x

**Comment by oliver006** [comment]
The float that is returned from the lua script is used as the value that the gauge for the lua script is set to.
How would this work if you return a string?

**Comment by kunlun122** [comment]
I have made some modifications to the lua script based on yours, please refer to it.
`local result = {}
local nodes_info = redis.pcall('CLUSTER', 'NODES')

if type(nodes_info) == 'string' then
    for line in string.gmatch(nodes_info, '([^\n]+)') do
        if string.find(line, 'myself') then

            local parts = {}
            local idx = 1
            for part in string.gmatch(line, '([^%s]+)') do
                parts[idx] = part
                idx = idx + 1
            end

            table.insert(result, 'node_info_address='..parts[2])
            table.insert(result, "1")


            break
        end
    end
else
    table.insert(result, 'Error running CLUSTER NODES')
end


return result`

**metrics** 
`# HELP redis_script_result Result of the collect script evaluation
# TYPE redis_script_result gauge
redis_script_result{filename="/opt/server_info.lua"} 1
# HELP redis_script_values Values returned by the collect script
# TYPE redis_script_values gauge
redis_script_values{filename="/opt/server_info.lua",key="node_info_address=10.42.2.120:6379@16379"} 1`

**grafan**

use regular expression to split string
![image](https://github.com/user-attachments/assets/c96d1c33-a230-43a6-857e-987e5ef96160)
![image](https://github.com/user-attachments/assets/fc9532e7-54e4-4856-a898-5948117c4370)

**Comment by adibaulia** [comment]
> The float that is returned from the lua script is used as the value that the gauge for the lua script is set to. How would this work if you return a string?

oh i see, so i need to implement the code my self to get the cluster info or modify some lua script so i can extract the key only, the value remain as float




> I have made some modifications to the lua script based on yours, please refer to it.
> 
> ```lua
> local result = {}
> local nodes_info = redis.pcall('CLUSTER', 'NODES')
> 
> if type(nodes_info) == 'string' then
>     for line in string.gmatch(nodes_info, '([^\n]+)') do
>         if string.find(line, 'myself') then
> 
>             local parts = {}
>             local idx = 1
>             for part in string.gmatch(line, '([^%s]+)') do
>                 parts[idx] = part
>                 idx = idx + 1
>             end
> 
>             table.insert(result, 'node_info_address='..parts[2])
>             table.insert(result, "1")
> 
> 
>             break
>         end
>     end
> else
>     table.insert(result, 'Error running CLUSTER NODES')
> end
> 
> return result
> ```
> 
> **metrics**
> 
> ```
> # HELP redis_script_result Result of the collect script evaluation
> # TYPE redis_script_result gauge
> redis_script_result{filename="/opt/server_info.lua"} 1
> # HELP redis_script_values Values returned by the collect script
> # TYPE redis_script_values gauge
> redis_script_values{filename="/opt/server_info.lua",key="node_info_address=10.42.2.120:6379@16379"} 1
> ```
> 
> **grafan**
> 
> use regular expression to split string ![image](https://private-user-images.githubusercontent.com/16523425/348917813-fc9532e7-54e4-4856-a898-5948117c4370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDQ3NDAsIm5iZiI6MTcyMTEwNDQ0MCwicGF0aCI6Ii8xNjUyMzQyNS8zNDg5MTc4MTMtZmM5NTMyZTctNTRlNC00ODU2LWE4OTgtNTk0ODExN2M0MzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA0MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZGNmN2Q2MDBmNGE3MDU0MjU5NTFjZDM2OTYwZTQ1ZjBkZDZlMzAzMmZiNWVlYzhjNWZjYTRhNGEyOTY0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.67ytykv5uHEAW3o_4EOnzD-CBo_um5DBx5aLAljAs74)

thanks! this is what i looking for
