### ISSUE TITLE
Export `client-output-buffer-limits` as a metric

### ISSUE THREAD

**Issue by jdheyburn** [oliver006/redis_exporter#932]
**Describe the problem**

In redis-exporter [v1.60.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.60.0), a new metric is exported for tracking the total replication buffer size: `mem_total_replication_buffers`

Given that this metric increases up to the defined replication buffer limit in `client-output-buffer-limit`, I think it makes sense to export that into a metric too so that we can do some alerting on when `mem_total_replication_buffers` reaches a threshold of `client-output-buffer-limit`.

I tried out using `--include-config-metrics`, but that exports the config in an unusable format:

```
redis_config_key_value{key="client-output-buffer-limit",value="normal 0 0 0 slave 1610612736 1610612736 0 pubsub 33554432 8388608 60"} 1
```

This could be in some new metrics:

```
redis_config_client_output_buffer_limit{class="normal", limit="hard"} 0
redis_config_client_output_buffer_limit{class="slave", limit="hard"} 1610612736
redis_config_client_output_buffer_limit{class="pubsub", limit="hard"} 33554432
```

I'm not sure on the best way of presenting the soft limits, and the soft seconds. Keen to hear other opinions before raising a PR.

Config file docs: https://redis.io/docs/latest/operate/oss_and_stack/management/config-file/

After above is implemented, we could have an alert on below:

```
(mem_total_replication_buffers / redis_config_client_output_buffer_limit{class="slave", limit="hard"}) > 0.7
```

**What version of redis_exporter are you running?**
Please run `redis_exporter --version` if you're not sure what version you're running.

[x] 1.6.2

**Running the exporter**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by oliver006** [comment]
Thanks for raising this issue (and all the others!)

Your use case makes sense (alert on ratio driven directly by metrics) so let's figure this out.

I think your suggestion using the output_buffer_limit metric makes sense (should include suffix `_bytes` so `redis_config_client_output_buffer_limit_bytes`) 

You can do the same for the soft settings, no? Just add new metrics.
At this point you already have to parse the config setting into its pieces so might as well emit a bunch of new metrics.

**Comment by jdheyburn** [comment]
@oliver006  Thanks, I've given it a stab in the below. Would appreciate your feedback 👍🏻 
- #933
