### ISSUE TITLE
Redis 4

### ISSUE THREAD

**Issue by raypettersen** [oliver006/redis_exporter#95]
Redis 4 is stable, but this exporter only supports 2. 3. according to doc.

**Comment by oliver006** [comment]
I haven't had a chance yet to try it with Redis 4 yet, it might just work. Did you try?

**Comment by oliver006** [comment]
nvm, I just ran the tests with an instance of Redis 4.0.1 and they completed just fine so the exporter should be good to go for Redis 4.x

**Comment by raypettersen** [comment]
Superb. Thanks.
