### ISSUE TITLE
Where to specify flags?

### ISSUE THREAD

**Issue by albertoridolfi** [oliver006/redis_exporter#96]
The readme doesn't explain where flags should be specified. I'm using docker, how can I specify flags?

**Comment by oliver006** [comment]
You can pass them directly to `docker run`: 

`docker run -p 9122:9122 --name redis_exporter oliver006/redis_exporter  -web.listen-address=:9122`

will run the exporter with the flag `-web.listen-address=:9122`

**Comment by albertoridolfi** [comment]
That's great, thanks
