### ISSUE TITLE
Network Metrics missing

### ISSUE THREAD

**Issue by Rucknar** [oliver006/redis_exporter#99]
I'm running the latest version of the redis_exporter on an Elasticache instance in AWS. 
It's working well and i'm not seeing any errors, however i seem to be missing `redis_net_output_bytes_total` and the other similar metrics. 

Is this a known issue? I'm wondering if AWS simply don't expose this? It's something i'm desperate to get at after having real issues with the Cloudwatch metrics.

**Comment by oliver006** [comment]
Ah yes, Cloudwatch metrics can be a bit of a pain.

Can you run `CONFIG ALL` in `redis-cli` on your AWS Elasticache instance and see if it returns `total_net_output_bytes`? 

If not, then AWS is not exposing it...

**Comment by Rucknar** [comment]
`CONFIG` is restricted sadly. The output of `STATS` confirms however it's not exposed. I'll close the issue but hopefully can serve as reference should anyone else encounter the same issue.

**Comment by oliver006** [comment]
Thanks for the follow up and too bad it's not supported :-/
